### ISSUE TITLE
Docker upgrade fails because apache config stay at php 7.2

### ISSUE THREAD

**Issue by markusdd** [nextcloud/nextcloudpi#1002]
I'm now running the latest greatest docker image on mi RPi 3B and I was wondering why nextcloudpi started fine, but the web interfaces were not accessible.

After logging into the container using docker exec I discovered in the apache logs that it was missing the php fpm socket 7.2 .

After checking the container contents, php fpm was at 7.3 . I completely removed the container and image to make sure I did not do an accidential upgrade, but after a fresh pull and start, it remained the same error.

I helped myseld by copying the php fpm 7.2 conf to a 7.3 conf and linking it instead of the 7.2 . That fixed the issue and I have my nextcloudpi back.

Still, this is not supposed to happen. As the apache conf is part of the persistent storage, when running a newer container ncp has to take care to adapt the apache config if a newer php is used.

It took me half my Sunday to figure this out and still I do not know if the fix I did is even correct, as I just copied the config and replced 7.2. with 7.3 . Maybe the config is supposed to be different. Not a webserver expert and I have no idea about PHP, so this fix is quick and dirty.

Please let me know if you require more info, but I guess the problem statement is pretty straightforward.

**Comment by paschaef** [comment]
I encounterd the same issue.
