### ISSUE TITLE
Backup with choice the backuptime

### ISSUE THREAD

**Issue by daschmidt1994** [nextcloud/nextcloudpi#1007]
**Description**  

Good day

I use nextcloudpi on a Raspberry and am very satisfied with it. I like all the simplifications dur ncp. It’s easy to create backups, but I’m lacking a small amount of it and that the backup runs at certain times. I think of something like an extension in the selection where I can set the time. For example, I would like to create a backup daily at midnight.

With best regards
Schmidt

Guten Tag

Ich nutze nextcloudpi auf einen Raspberry und bin damit sehr zufrieden. Mir gefallen die ganzen vereinfachungen dur ncp. Es ist einfach backups zu erstellen, nur eine kleinichkeit fehlt mir und zwar, dass das backup zu bestimmten Zeiten ausgeführt wird. Ich denke an soetwas wie eine erweiterung bei der auswahl, wo ich die Zeit einstellen kann. Sprich ich möchte zumbeispiel täglich um Mitternacht ein backup erstellen.

Mit freundlichen Grüßen
Schmidt

**Example**  

I will backup my data but dont want this during the day. It's for "noobs" like me easyer to set 00:00 as backup time and every day in the night the backup will startet automaticly.

**Comment by nachoparker** [comment]
hi,

autobackups are done at night time already :)
