### ISSUE TITLE
Please enable OCC control (and config.php editing) from nextcloudpi Settings

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloudpi#1015]
I would like to see OCC control and maybe also direct config.php-editing beeing added to the nextcloudpi-settings. This would simplify the setup and configuration a lot.
Maybe if you have concerns you could simply add a big disclaimer, that the admin of this instance will use this feature on his/her own risk and should know what to do there.

**Comment by nachoparker** [comment]
Duplicate of #1016
