### ISSUE TITLE
Cannot start the docker container with bind-mount on windows

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloudpi#1018]
Hello, thank you for your great work! I love using nextcloudpi.

I am trying to start a docker container with the following command on Windows 10:

`docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v "C:\test":/data  --name nextcloudpi ownyourbits/nextcloudpi-x86`

Docker is correctly installed and the folder on the host "C:\test" gets correctly populated with the new files. But if I click on "activate" in the webpanel, it just says "NextCloudPi not yet initialized, trying again in a few seconds ..." for a view hours now. Using a docker volume works just fine but is not really an option because then incremental backups from the host system don't work. (I then had to backup the whole vhdx-volume each time which is not really an option).
So I think this is a bug and I would be really happy, if that could get fixed.
I tried other things but this error is ocurring every thime, that I try to use bind-mounts.

**Comment by szaimen** [comment]
In the logs I get this:
![image](https://user-images.githubusercontent.com/42591237/67636949-f42fb300-f8d5-11e9-95ba-9ea197af4ec4.png)

**Comment by nachoparker** [comment]
Sorry but we do not support docker on windows
