### ISSUE TITLE
integrate port mapper service?

### ISSUE THREAD

**Issue by bobblkabb** [nextcloud/nextcloudpi#102]
### What is the base image that you installed on the SD card? NextCloudPi_08-08-17

How do I integrate a portmapper service (ipv4 <-> ipv6) like feste-ip.net in nextcloudpi?!

client <--ipv4--> portmapper service (adress like mycloud.feste-ip.net <--ipv6--> modem/router <--ipv6--> nextcloudpi

**Comment by nachoparker** [comment]
The same way as you would do it on Raspbian. I haven't tried that myself, so I can't help.

This is a bit out of scope, so either somebody else around here helps you, or you can maybe try in the Raspberry Pi forums.
