### ISSUE TITLE
will ncp cover this security issue (ngix php-fpm) as well?

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/nextcloudpi#1020]
everyone got warned about a security issue here
https://help.nextcloud.com/t/urgent-security-issue-in-nginx-php-fpm/62665

so my question is: will ncp cover this security issue with an update? if not: this is my new FR ;-)

btw: i'm running ncp 1.19.0 now. still no dist-upgrade with me (will do later this year, need to since app passwords claims to have php 7.3 installed from january on)

**Comment by ovpc** [comment]
Ncp uses Apache2, not Nginx. So it it is not affected by this issue.

**Comment by JimmyKater** [comment]
oops. i thought that they at some point switched to ngix... so i then thought this might affect ncp as well... 
sorry if this isn't the case...
