### ISSUE TITLE
Cannot activate SSH with a passphrase containing a space character

### ISSUE THREAD

**Issue by mcorteel** [nextcloud/nextcloudpi#1022]
**System information**

NextCloudPi version | v1.18.0
-- | --
NextCloudPi image | NextCloudPi_07-21-19
distribution | Raspbian GNU/Linux 10 \n \l
automount | yes
USB devices | sda
datadir | /var/www/nextcloud/data
data in SD | yes
data filesystem | ext2/ext3
data disk usage | 2.0G/14G
rootfs usage | 2.0G/14G
swapfile | /var/swap
dbdir | /var/lib/mysql
Nextcloud check | ok
Nextcloud version | 16.0.3.0
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
Postfix service | up
internet check | ok
port check 80 | open
port check 443 | open
IP | 192.168.0.12
gateway | 192.168.0.1
interface | eth0
certificates | none
NAT loopback | no
uptime | 2:28

**Issue**
I wanted to activate SSH after a clean install with a passphrase containing a space character. It failed until I chose a password (without any space).

NOTE: I had to change the password again on first SSH login anyway, which is weird.

**Comment by nachoparker** [comment]
At this point we do not support spaces in input fields, for security reasons. Same reason we force a reset of the SSH password once you log in
