### ISSUE TITLE
NCP installer silently overwrites existing database "nextcloud" with no backup

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/nextcloudpi#1023]
A couple of days ago, I made the stupid move of running the installer script on my Raspi without having backed up the existing nextcloud database first. That was because I didn't read the fine print and assumed that it would download and install NCP as a docker appliance, rather than installing everything natively.

When I found out that I was mistaken, it was already too late, the installer was hanging and had already emptied the existing database "nextcloud", without asking for my consent. While a daily cronjob takes incremental backups of the nextcloud data directory, I forgot to ensure separate backups for the database. And I didn't think of taking a btrfs snapshot before running the installer. Stupid me. Happily, none of my valuable files was lost and the db didn't contain anything of value itself. So no real data loss occured, just a major nuissance (everything had to be re-synced, which took days), 

Anyway, when there is already a database "nextcloud", this should be a big red flag for the installer. It should choose a different name or at least ask for consent before overwriting it...

**Comment by nachoparker** [comment]
good suggestion, thanks. Applied
