### ISSUE TITLE
nc-rsync-auto.sh fails for restricted remote commands

### ISSUE THREAD

**Issue by fanaz** [nextcloud/nextcloudpi#1027]
I want use rsync.net as a target for the nc-rsync-auto but the configuration fails with error `SSH non-interactive not properly configured`.
nc-rsync works, so the ssh access is configured properly.

nc-rsync-auto.sh tries to run the : command remotely to check if ssh is properly configured. But rsync.net provides only a restricted set of Unix commands and : is not a supported command.

**Comment by nachoparker** [comment]
fixed in PR

**Comment by ttoopp** [comment]
Hi, I have now the same problem with a Storage-Box from Hetzner. 
nc-rsync works, but nc-rsync-auto give me a error "SSH non-interactive not properly configured"
