### ISSUE TITLE
Not able to start WebUI wizard with fresh ISO (should be updated with latest available version)

### ISSUE THREAD

**Issue by Fohlenrolle** [nextcloud/nextcloudpi#1033]
Just installed fresh ISO for RaspPi 3B (07/19 image) on an SDCard and although all ports were open, the only possibility to start wizard on WebUI was to enable it in nc-config. I was able to connect to my RaspPi IP (port 443) to be able to show the passwords, but when trying to access port 4443 it was not reachable. So enabled WebUI in nc-config (all passwords were reset to "ownyourbits"), but port 4443 now was accessible. When trying to update (nc-update) over admin panel on port 4443 there was a package conflict I only could solve with "sudo apt --fix-broken install" - this was because of packages preinstalled were too old and caused conflicts.

Updating NCP version before installing with WebUI wizard was not possible at all because there was some stack error stopping update at 48% (sorry for not saving exact messages).

**Comment by nachoparker** [comment]
it doesn't show you the password, you need to click "activate" in order to apply those random passwords and only then ncp-web becomes accessible
