### ISSUE TITLE
Directories ncdata in double (SDCARD and USBDRIVE) and code error in log

### ISSUE THREAD

**Issue by forum6691** [nextcloud/nextcloudpi#1040]
I use a SSD disk to store my nextcloupi. I have the last version of nextcloudrpi and nextcloud. This problem was also on the fromer versions.

I have permanently the 2 errors in log ( every seconds) :

```
Warning | no app in context | Temporary directory {"/media/USBdrive/ncdata/tmp":""} is not present or writable |  

Error | PHP | is_writable() expects parameter 1 to be a valid path, array given at /var/www/nextcloud/lib/private/TempManager.php#260
-- | -- | --

```
So I look inside the system and I note that I have to identical directories /media/ xxx /ncdata/ 
The xxx is myCloudDrive (sdcard) and USBdrive (disk SSD). All the file in these directories ncdata are the same, with same date !!

The tmp directory inside have the same rights (owner is www-data) in the 2 directories.
So I think there are 2 bugs:

- Firstly this copy in double of the data inside ncdata
- Secondly , the error log on access on the tmp directory because, directory is present and rights are ok ( drwxrwxr-x 1 www-data www-data         0 déc.  20 08:46 tmp )

**Comment by ovpc** [comment]
When automount is enabled and you want to add another drive:
Rather then using the symlink /media/USBdrive use /media/LABELofDrive 
see additional info at https://docs.nextcloudpi.com/en/configuration-reference/#nc-automount
Unless you are reporting a bug, please use help.nextcloud.com with ncp tag.
