### ISSUE TITLE
Error: Could not download app calendar

### ISSUE THREAD

**Issue by jdainen** [nextcloud/nextcloudpi#1043]
Error: Could not download app calendar.

Then Nextcloud will not run, but Nextcloudpi will run.

This is on a new install.  If I delete the ncdata folder and reinstall.  It still fails.

Is this a server issue?

**Comment by Godzgift206** [comment]
Same issue. I did have it installed working great, but when I installed “letsencrypt” docker things didn’t work as well.

**Comment by nachoparker** [comment]
Sometimes the hosting for some apps are shaky and while they are down they cause this failure

**Comment by WillPower3309** [comment]
This issue still exists as of April 16, 2020

**Comment by FackJox** [comment]
I get this same error, wipe ncdata, wipe volumes, wipe images, same compose file but no luck!
> Same issue. I did have it installed working great, but when I installed “letsencrypt” docker things didn’t work as well.
Funnily enough things went bad for me when messing round with the letsencrypt docker too ! It worked for a bit but I restarted the server and then nextcloud stopped working.
