### ISSUE TITLE
ncp-update

### ISSUE THREAD

**Issue by senecasphaedra** [nextcloud/nextcloudpi#105]
Will upgrading the nextcloudpi image (i.e., ncp-update) maintain all your nextcloud settings?  I would like to update but do not want to lose any of the nextcloud settings already configured.  Thanks for an excellent product.

**Comment by nachoparker** [comment]
Upgrading through `sudo ncp-update` or `nc-update` in web panel or in `nextcloudpi-config` only upgrades NextCloudPi stuff, meaning

- NextCloudPi additions:  remote updater system, custom MOTD... those things
- `nextcloudpi-config` launcher
- ncp-web: the web control panel

**It will not modify your Nextcloud instance in any way**

Somewhat related to question #92

So, go ahead! I release soon and then introduce little fixes and improvements almost everyday, like a rolling release. It is recommended to update often to get the latest stuff

;)

**Comment by senecasphaedra** [comment]
Awesome -- thank you kindly for the very quick response on this.  Much appreciated, and thanks again for the great work on this project.
