### ISSUE TITLE
Invalid parameters error if scan path contains a space

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/nextcloudpi#1050]
When I try to scan a path using the admin interface that contains a space , e.g. `username/files/dirname with space`, I get the following error: `invalid parameters`.

None of my below attempts worked:
`username/files/dirname with space`
`username/files/dirname\ with\ space`
`"username/files/dirname with space"`
`'username/files/dirname with space'`

Similar to issue #1036

**System information**
NextCloudPi  `1.20.1`
NextCloud `17.0.2.1`

**Comment by nachoparker** [comment]
spaces are not allowed for security reasons
