### ISSUE TITLE
RPI NextCloudPi

### ISSUE THREAD

**Issue by mancomx** [nextcloud/nextcloudpi#1051]
i received this error message during installation.
What can I do now?
Command:
wget https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh
sudo bash install.sh

Error: cURL error 28: Operation timed out after 30000 milliseconds with 852558 o                                                                                                                                                             ut of 1594265 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.h 

Thx
mancomx

**Comment by ovpc** [comment]
Please use [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for support.
