### ISSUE TITLE
Will Nextcloud 18.0.0 be available soon?

### ISSUE THREAD

**Issue by maschhoff** [nextcloud/nextcloudpi#1060]
Hey Guys,

thanks for building this awesome projekt!
Will Nextcloud 18.0.0 be available soon?

Regards
knex

**Comment by nachoparker** [comment]
hi,

you can install it yourself through ncp-update-nextcloud at your own risk. I have recieved reports that it works fine. We will release to autoupdate once we have tested it ourselves.

**Comment by nachoparker** [comment]
I tried out the upgrade just now and it works fine, but it disables a bunch of apps that need to be re-enabled in the apps menu because they are not marked as compatible yet with NC18 (but they work).

For this reason, we will wait a bit probably until NC18.0.1 to make sure that major bugs are fixed and apps are up to date before we roll out to all users that use nc-autoupdate-nc to upgrade automatically.

That being said anybody can upgrade manually at their own risk with nc-update-nextcloud

**Comment by maschhoff** [comment]
Thanks! I had to mannually enter 18.0.0 as version to make it.

**Comment by lenzls** [comment]
I heard in a recent announcement that starting from version 18 nextcloud gets rebranded to "nextcloud hub" and has the onlyoffice integration build in.

Did I got that right?

If yes, will that work on arm systems?

I find it hard to get this information from the official website.

**Comment by ovpc** [comment]
Updated my (test) rpi3 to NC 18.0.0 using nc-update-nextcloud without any issue, apart from some apps being disabled as mentioned by Nacho. Don't see any build in OnlyOffice functionality, it still needs OO server on a _64 system and the OO app on NC afaik.

**Comment by Larsene** [comment]
Right. Integrating OO in the NCP distribution could be a great thing. Plus, with a Raspberry Pi4 (more ram, 64bits) , this should be enough for small groups

**Comment by feutl** [comment]
The OnlyOffice integration has to optione, the one with docker and the new version which is called Documentserver (https://github.com/nextcloud/documentserver_community) which has been partly rewritten in PHP.

The docker OO implementation is also supporting ARM where the documentserver only supports x86 as stated on the gihub page.

> The community document server only supports running on x86-64 Linux servers.

**Comment by silas229** [comment]
The Nextcloud Hub is not available for me. 

Neither with ncp-config in the terminal
![image](https://user-images.githubusercontent.com/23215125/73300639-a9457480-4211-11ea-80ca-dcd0971587bf.png)
nor with the Web-Updater
![terminal](https://user-images.githubusercontent.com/23215125/73300565-80bd7a80-4211-11ea-8fd4-b14515689ce4.png)
Do I have to select a different update channel?

**Comment by lenzls** [comment]
@silas229 
> Do I have to select a different update channel?

As said in the second comment in this thread, it is not officially supported by ncp.
You have to update manually at your own risk via `ncp-update-nextcloud`

**Comment by maschhoff** [comment]
Will this be supported in the ncp docker container as well. Its not possible for me to update (data directory not empty) data is a volume mounted directory.

**Comment by maschhoff** [comment]
Everyone the Document Server is only running on x86-64

**Comment by feutl** [comment]
Any status update on an upcoming *official* 18.0.1 NCP release ?

**Comment by nachoparker** [comment]
18.0.1 was pushed a few days ago
