### ISSUE TITLE
ncp-update fails when a new distribution is available and the NextCloud user 'ncp' was removed.

### ISSUE THREAD

**Issue by volanin** [nextcloud/nextcloudpi#1072]
Near the end of **update.sh** there is this line to generate a notification if a new distribution is available:

`ncc notification:generate "ncp" "New distribution available" -l "${msg}"`

If the NextCloud user 'ncp' is removed, this command will fail and **ncp-update** will not complete. Since the availability of Debian Buster, my NextCloudPi wasn't updating properly.

**Comment by ovpc** [comment]
ncp is also a system user (UID<1000)  created for specific ncp related system tasks, it should not be removed.

**Comment by volanin** [comment]
Well, I was not talking about the Linux user 'ncp'. I have never deleted that one since, as you said, it's a system user.

I was talking about the NextCloud user 'ncp'. Since I created another admin user in the NextCloud webpanel, I deleted the default user 'ncp' there.

This makes 'ncc notification' fail in the update script.

**Comment by nachoparker** [comment]
@volanin is right. I added a quick fix

**Comment by ovpc** [comment]
@nachoparker thank you :grinning:
