### ISSUE TITLE
Restore Backup from another Device

### ISSUE THREAD

**Issue by daschmidt1994** [nextcloud/nextcloudpi#1074]
**System information**

Yesterday i tried to restore a backup from a raspberry to a ncpi instance that run on a debian homeserver. The problem is, that the old path to the datadir was /media/btrfs/ncdata and the new one is /var/data/nextcloud/data. the restore always restored in the old one. Problem is the ssd is not big enough to take all the data.

**Comment by ovpc** [comment]
ncp has no app for that, you need to edit config.php manually. Please use forum or telegram group for help.

**Comment by daschmidt1994** [comment]
i tried it but it dowsent work see yesterday on telegram 
when it doesent work its a issu

**Comment by ovpc** [comment]
Not sure how much it would take for nc-restore to have an option; where nc-data location can be different from the backup, from which one is restoring.
It would involve several steps. Editing lines in config and possibly running nc-scan to update the db.

Anyone, feeling up to the task, is free do create a pull request to devel branch. ;-)

**Comment by daschmidt1994** [comment]
https://github.com/nextcloud/nextcloudpi/issues/852#issue-423467023

Sorry i saw the sam is at pullrequest
