### ISSUE TITLE
Allow to create self signed certificate for dnsmasq domain

### ISSUE THREAD

**Issue by basxto** [nextcloud/nextcloudpi#1076]
**Description**  
Please allow in the dnsmasq settings to create a new self signed certificate for the domain configured in dnsmasq.
Some android apps for nextcloud do not accept certificates that are not issued for a domain, but I don’t want to make it accessible from outside so letsencrypt is not an option.

**Comment by ovpc** [comment]
Unless you are ready to implement this yourself, and venture a pull request, I don't see anyone else wanting or needing that.
You can use Letsencrypt without opening any ports, using dns to verify.
