### ISSUE TITLE
Install Issue on debian buster Pi 4

### ISSUE THREAD

**Issue by henosch** [nextcloud/nextcloudpi#1077]
tty: Standardeingabe: Unpassender IOCTL (I/O-Control) für das Gerät
Enter current password for root (enter for none): 
stty: Standardeingabe: Unpassender IOCTL (I/O-Control) für das Gerät
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by pepemao** [comment]
Hey, I also have this problem - I suppose that it's about line 40 of lamp.sh

**Comment by nachoparker** [comment]
the curl installer is for clean instances only, so nothing installed on them. We have orangepi images available to download
