### ISSUE TITLE
IPV6 Trusted Domain Not Recognized with any settings including wildcards

### ISSUE THREAD

**Issue by karz1** [nextcloud/nextcloudpi#1083]
/var/www/nextcloud/config/config.php
array ('::1', '[::1]','5555:*', '[5555:asterisk],'[asterisk]','[asterisk:asterisk],'asterisk',),

(* wont show properly here on github, so I put asterisk)
I found my IPV6 from ip6only.me , tried the whole address with [] and without.(5555 just an example, _not_ my real IP)
Still get error webpage
"Access through untrusted domain"
What is the proper format to allow all IPV6?
Documentation is not clear at all about IPV6

**Comment by tflidd** [comment]
It belongs to the main repository for Nextcloud. You did already post it there as well, so let's close it here. ref:
https://github.com/nextcloud/server/issues/19597
