### ISSUE TITLE
Remove weak ciphers from Apache TLS config. #ENHANCEMENT REQUEST

### ISSUE THREAD

**Issue by Kerasit** [nextcloud/nextcloudpi#1085]
#There is no need for allowing weak ciphers for TLSv1.2 anymore.

I can think of a scenario where someone uses very old clients but then it could be optional, like a checkmark:

Allow (newest TLS version always allowed):
- TLS v. 1.1?
- TLS v. 1.2?
- Only secure ciphers (WARNING! If you use an older client there is a theorethical risk that it will fail to connect)?

**Comment by nachoparker** [comment]
Hi,

Thanks for the suggestion. ATM only TLS12 is accepted, but we'll also include TLS13.

We want to be careful not to have compatibility issues though so I think we'll leave it there for now.

See https://github.com/nextcloud/nextcloudpi/issues/1281
