### ISSUE TITLE
"Scheduled datadir BTRFS snapshots settings" not updated when moving data dir

### ISSUE THREAD

**Issue by BstAA** [nextcloud/nextcloudpi#1090]
**Problem**
When moving datadir to a new location _after_ activating _Scheduled datadir BTRFS_ snapshots the corresponding cron job isn't updated.

**Diagnose**
The option _Scheduled datadir BTRFS snapshots_ generates `/etc/cron.hourly/btrfs-snp` based on the actual datadir location. i.e.
[btrfs-snp.txt](https://github.com/nextcloud/nextcloudpi/files/4272027/btrfs-snp.txt)

the new datadir location is updated only when again activating the option. i.e.
[btrfs-snp-after.txt](https://github.com/nextcloud/nextcloudpi/files/4272030/btrfs-snp-after.txt)

**Solution**
Either give a clear statement in the Move datadir action, to renew the snapshot action or update btrfs-snp without user interaction.

**System information**

[ncp-report.txt](https://github.com/nextcloud/nextcloudpi/files/4272035/ncp-report.txt)

**Comment by nachoparker** [comment]
good catch! Fixed in `v1.22.3`
