### ISSUE TITLE
Nextcloud 18 Apps Store missing

### ISSUE THREAD

**Issue by feutl** [nextcloud/nextcloudpi#1091]
Hi,
after using the latest NCP build and the option to upgrade to 18.0.1 I was having problems with Apps. They did not get updated correctly and the app store was missing as well.
After some digging I realized that the appstore settings in `config.php` have changed. I must have missed this in one of the past release notes.

My settings in `config.php` were
```
 'appstoreenable' => true,
  'appstoreurl' => 'https://api.nextcloud.com/v1',
```

I assum they were placed when I started with NCP and NC 13.x.x.x and never got removed.
Based on the new [confi.php](https://github.com/nextcloud/server/blob/master/config/config.sample.php) the appstore settings should be
```
/**
 * When enabled, admins may install apps from the Nextcloud app store.
 *
 * Defaults to ``true``
 */
'appstoreenabled' => true,

/**
 * Use the ``apps_paths`` parameter to set the location of the Apps directory,
 * which should be scanned for available apps, and where user-specific apps
 * should be installed from the Apps store. The ``path`` defines the absolute
 * file system path to the app folder. The key ``url`` defines the HTTP Web path
 * to that folder, starting from the Nextcloud webroot. The key ``writable``
 * indicates if a Web server can write files to that folder.
 */
'apps_paths' => array(
	array(
		'path'=> '/var/www/nextcloud/apps',
		'url' => '/apps',
		'writable' => true,
	),
),
```

After some reading and digging, I tried to just delete my two values. Some people in the forum recommended just do get rid of every `appstore` setting and let NC use its defaults.
This worked. So perhaps NCP could take care of this, if others have the some issue.

**Comment by nachoparker** [comment]
Thank for sharing. While it is ok that people tweak NCP/NC, if they do so they are on their own, so we will not support that.

Good to have this here though for future reference
