### ISSUE TITLE
Possibility for Trusted Proxies in case of NextcloudPi behind a Reverse Proxy

### ISSUE THREAD

**Issue by paschaef** [nextcloud/nextcloudpi#1092]
**Description**  
Add another option in the ncp-web panel similar to `nc-trusted-domains` for trusted proxies. Possibility to manually add `trusted_proxies` in `config.php`. This is important if nextcloudpi is behind a reverse proxy and wants to obtain the true client IP e.g. for using it for fail2ban (in the case ncp is running inside docker and fail2ban runs on docker host).

**Example**  
add the following php-array to to `config.php`:
```php
<?php
$CONFIG = array (
...
  trusted_proxies =>
  array (
    0 => '1.2.3.4',
  ),
...
```
where the IP address `1.2.3.4` is configurable over the ncp-web panel, as defined in the [nextcloud doc](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse%20proxy#defining-trusted-proxies)

**Comment by nachoparker** [comment]
thanks for the PR!
