### ISSUE TITLE
can certbot working on other port rather than 443???

### ISSUE THREAD

**Issue by LETMEPASSPLS** [nextcloud/nextcloudpi#1098]
I have a apache web server. and I am trying to set up the ssl with using certbot
my question is my ip has changed like http://public-ip:8100 and https://public-ip:509 for http and https. And I cannot access to http://public-ip:80 because of my local ip setting
can I use certbot to have a ssl cert on these particular port??
if yes, how can i change the default port setting??
If cant, why the others can do https on different port?? is it because they buy the ssl service on dns or there is another way to do this??

**Comment by ovpc** [comment]
Use forum please, asked and answered already [there](https://help.nextcloud.com/t/how-to-use-http-instead-of-dns-challenge-with-certbot/50685)
