### ISSUE TITLE
Support for Nextcloud 18

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/nextcloudpi#1101]
My Nextcloud tells me, that NextCloudPi requires Nextcloud 16. I have Nextcloud 18 already.

**Comment by nachoparker** [comment]
sounds like you need to upgrade ncp

**Comment by GambaJo** [comment]
@nachoparker I can only remove it or activate an untested app.
![11-03-_2020_09-01-27](https://user-images.githubusercontent.com/1378907/76395222-1acb2380-6377-11ea-9151-b254f36d2e1d.jpg)

**Comment by nachoparker** [comment]
run `sudo ncp-update` or `nc-update` from the ncp-web interface (port 4443)
