### ISSUE TITLE
Setup wizard: format USB takes wrong label

### ISSUE THREAD

**Issue by andi34** [nextcloud/nextcloudpi#1112]
While running the Setup wizard on v19.1 lables the USB drive on "Format USB" as `myCloudDrive` but on "Move data to USB" it is expecting the label to be `USBdrive`.

**Comment by nachoparker** [comment]
that's correct, they are equivalent

**Comment by andi34** [comment]
So I use the setup wizard and won't be able to finish it (if not formatting and lableling it before) using Nextcloudpi because it can not move the data?
