### ISSUE TITLE
Variable $NOTIFYUSER not defined

### ISSUE THREAD

**Issue by Tanarri** [nextcloud/nextcloudpi#1119]
**System information**
NextCloudPi version  v1.24.0
NextCloudPi image    NextCloudPi_12-20-19
distribution         Raspbian GNU/Linux 10 \n \l
automount            yes
USB devices          sda
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      38G/60G
rootfs usage         38G/60G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    18.0.3.0
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               8days

In the file nextcloudpi/bin/ncp/BACKUPS/nc-backup-auto.sh line 26 the variable "$NOTIFYUSER" is used. This variable defines the username which will be informed about failed backups.

The problem is, the user can't input the username via web-interface. The control is missing to input the username. 
The control should be defined in the file  nextcloudpi/etc/ncp-config.d/nc-backup-auto.cfg 
There is/was code which this was in --> https://github.com/nextcloud/nextcloudpi/blob/c1e1b65616389fdb72e1a4e8dadccaad630866ff/etc/ncp-config.d/nc-backup-auto.cfg --> line 46 till 51

Perhaps the code got lost.

Greetings

**Comment by nachoparker** [comment]
good catch. Fixed!

thanks
