### ISSUE TITLE
Nextcloud 19 from version 18.0.3

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1125]
### From NextcloudPi beta 18.0.3 on Armbian Odroid C2 to 19.0.0 beta4

Following apps have been disabled: news (incompatible), nextcloudpi (incompatible), previewgenerator (incompatible)

Note: 19.0.0 is running successfully so far.  Obviously, this is a test instance.  Let me know if you want any particular thing checked out.  :+1: 

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Migrate old user config

[1 / 0]: Migrate old user config

[1 / 1]: Migrate old user config

Updated "accessibility" to 1.5.0

Updated "federatedfilesharing" to 1.9.0

Updated "files_pdfviewer" to 1.8.0

Updated "files_rightclick" to 0.16.0

Updated "files_videoplayer" to 1.8.0

Updated "logreader" to 2.4.0

Updated "password_policy" to 1.9.0

Updated "photos" to 1.1.0

Updated "privacy" to 1.3.0

Updated "provisioning_api" to 1.9.0

Updated "recommendations" to 0.7.0

Updated "serverinfo" to 1.9.0

Updated "settings" to 1.1.0

Updated "support" to 1.2.0

Updated "survey_client" to 1.7.0

Updated "text" to 3.0.1

Repair step: Add background job to check for backup codes

Updated "twofactor_backupcodes" to 1.8.0

Updated "updatenotification" to 1.9.0

Updated "viewer" to 1.3.0

Updated "federation" to 1.9.0

Updated "lookup_server_connector" to 1.7.0

Repair step: Update OAuth token expiration times

Updated "oauth2" to 1.7.0

Updated "files" to 1.14.0

Updated "activity" to 2.12.0

Updated "cloud_federation_api" to 1.2.0

Repair step: Fix component of birthday calendars

Repair info: 0 birthday calendars updated.

Repair step: Regenerating birthday calendars to use new icons and fix old birthday events without year

Repair info: Adding background jobs to regenerate birthday calendar

Repair step: Fix broken values of calendar objects

[0 / 0]: Fix broken values of calendar objects

Repair step: Registering building of calendar search index as background job

Repair info: Add background job

Repair step: Registering background jobs to update cache for webcal calendars

Repair info: Added 0 background jobs to update webcal calendars

Repair step: Registering building of calendar reminder index as background job

Repair info: Add background job

Repair step: Clean up orphan event and contact data

Repair info: 0 events without a calendar have been cleaned up

Repair info: 0 properties without an events have been cleaned up

Repair info: 0 changes without a calendar have been cleaned up

Repair info: 0 cached events without a calendar subscription have been cleaned up

Repair info: 0 changes without a calendar subscription have been cleaned up

Repair info: 0 contacts without an addressbook have been cleaned up

Repair info: 0 properties without a contact have been cleaned up

Repair info: 0 changes without an addressbook have been cleaned up

Repair step: Remove activity entries of private events

Repair info: Removed 0 activity entries

Updated "dav" to 1.15.0

Repair step: Fix the share type of guest shares when migrating from ownCloud

Repair step: Copy the share password into the dedicated column

Repair step: Set existing shares as accepted

Updated "files_sharing" to 1.11.0

Updated "files_trashbin" to 1.9.0

Updated "files_versions" to 1.12.0

Updated "sharebymail" to 1.9.0

Repair step: Populating added database structures for workflows

Updated "workflowengine" to 2.1.0

Updated "comments" to 1.9.0

Updated "firstrunwizard" to 2.8.0

Updated "nextcloud_announcements" to 1.8.0

Updated "notifications" to 2.7.0

Updated "systemtags" to 1.9.0

Updated "theming" to 1.10.0

Checking for update of app "accessibility" in appstore

Checked for update of app "accessibility" in appstore

Checking for update of app "activity" in appstore

Checked for update of app "activity" in appstore

Checking for update of app "bookmarks" in appstore

Checked for update of app "bookmarks" in appstore

Checking for update of app "calendar" in appstore

Checked for update of app "calendar" in appstore

Checking for update of app "cloud_federation_api" in appstore

Checked for update of app "cloud_federation_api" in appstore

Checking for update of app "comments" in appstore

Checked for update of app "comments" in appstore

Checking for update of app "contacts" in appstore

Checked for update of app "contacts" in appstore

Checking for update of app "dav" in appstore

Checked for update of app "dav" in appstore

Checking for update of app "federatedfilesharing" in appstore

Checked for update of app "federatedfilesharing" in appstore

Checking for update of app "federation" in appstore

Checked for update of app "federation" in appstore

Checking for update of app "files" in appstore

Checked for update of app "files" in appstore

Checking for update of app "files_pdfviewer" in appstore

Checked for update of app "files_pdfviewer" in appstore

Checking for update of app "files_rightclick" in appstore

Checked for update of app "files_rightclick" in appstore

Checking for update of app "files_sharing" in appstore

Checked for update of app "files_sharing" in appstore

Checking for update of app "files_trashbin" in appstore

Checked for update of app "files_trashbin" in appstore

Checking for update of app "files_versions" in appstore

Checked for update of app "files_versions" in appstore

Checking for update of app "files_videoplayer" in appstore

Checked for update of app "files_videoplayer" in appstore

Checking for update of app "firstrunwizard" in appstore

Checked for update of app "firstrunwizard" in appstore

Checking for update of app "logreader" in appstore

Checked for update of app "logreader" in appstore

Checking for update of app "lookup_server_connector" in appstore

Checked for update of app "lookup_server_connector" in appstore

Checking for update of app "nextcloud_announcements" in appstore

Checked for update of app "nextcloud_announcements" in appstore

Checking for update of app "notes" in appstore

Checked for update of app "notes" in appstore

Checking for update of app "notifications" in appstore

Checked for update of app "notifications" in appstore

Checking for update of app "oauth2" in appstore

Checked for update of app "oauth2" in appstore

Checking for update of app "password_policy" in appstore

Checked for update of app "password_policy" in appstore

Checking for update of app "photos" in appstore

Checked for update of app "photos" in appstore

Checking for update of app "privacy" in appstore

Checked for update of app "privacy" in appstore

Checking for update of app "provisioning_api" in appstore

Checked for update of app "provisioning_api" in appstore

Checking for update of app "recommendations" in appstore

Checked for update of app "recommendations" in appstore

Checking for update of app "serverinfo" in appstore

Checked for update of app "serverinfo" in appstore

Checking for update of app "settings" in appstore

Checked for update of app "settings" in appstore

Checking for update of app "sharebymail" in appstore

Checked for update of app "sharebymail" in appstore

Checking for update of app "support" in appstore

Checked for update of app "support" in appstore

Checking for update of app "survey_client" in appstore

Checked for update of app "survey_client" in appstore

Checking for update of app "systemtags" in appstore

Checked for update of app "systemtags" in appstore

Checking for update of app "tasks" in appstore

Checked for update of app "tasks" in appstore

Checking for update of app "text" in appstore

Checked for update of app "text" in appstore

Checking for update of app "theming" in appstore

Checked for update of app "theming" in appstore

Checking for update of app "twofactor_backupcodes" in appstore

Checked for update of app "twofactor_backupcodes" in appstore

Checking for update of app "updatenotification" in appstore

Checked for update of app "updatenotification" in appstore

Checking for update of app "viewer" in appstore

Checked for update of app "viewer" in appstore

Checking for update of app "workflowengine" in appstore

Checked for update of app "workflowengine" in appstore

Checking for update of app "news" in appstore

Checked for update of app "news" in appstore

Checking for update of app "nextcloudpi" in appstore

Checked for update of app "nextcloudpi" in appstore

Checking for update of app "previewgenerator" in appstore

Checked for update of app "previewgenerator" in appstore

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair mime types

Repair step: Clean tags and favorites

Repair info: 0 tags of deleted users have been removed.

Repair info: 0 tags for delete files have been removed.

Repair info: 0 tag entries for deleted tags have been removed.

Repair info: 0 tags with no entries have been removed.

Repair step: Repair invalid shares

Repair step: Move .step file of updater to backup location

Repair info: .step file exists

Repair info: .step file moved to .step-previous-update

Repair step: Fix potential broken mount points

Repair info: No mounts updated

Repair step: Add log rotate job

Repair step: Clear frontend caches

Repair info: Image cache cleared

Repair info: SCSS cache cleared

Repair info: JS cache cleared

Repair step: Clear every generated avatar on major updates

Repair step: Add preview background cleanup job

Repair step: Queue a one-time job to cleanup old backups of the updater

Repair step: Cleanup invalid photocache files for carddav

Repair step: Add background job to cleanup login flow v2 tokens

Repair step: Remove potentially over exposing share links

Repair info: No need to remove link shares.

Repair step: Clear access cache of projects

Repair step: Switches from deprecated "production" to "stable" update channel

Repair step: Sets the enterprise logo

Repair step: Reset generated avatar flag

Starting code integrity check

Finished code integrity check

Turned off maintenance mode

Reset log level

Following apps have been disabled: news (incompatible), nextcloudpi (incompatible), previewgenerator (incompatible)

**Comment by sunjam** [comment]
Log from Admin/Administration/Support/System Report:

Server configuration detail

Operating system: Linux 5.4.28-meson64 #20.02.8 SMP PREEMPT Mon Mar 30 09:12:52 CEST 2020 aarch64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.3.22

PHP version: 7.3.11-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

Nextcloud version: 19.0.0 beta 4 - 19.0.0.5

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - bookmarks: 3.0.0-beta.2
 - calendar: 2.0.3
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.2.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.0
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - support: 1.2.0
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.12.1
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - news
 - nextcloudpi
 - previewgenerator
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "11": "52.119.120.83",
        "1": "172.17.0.2",
        "5": "nextcloudpi.local",
        "7": "nextcloudpi",
        "8": "nextcloudpi.lan",
        "20": "192.168.1.101",
        "21": "ncp.local"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.0.5",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "overwriteprotocol": "https",
    "updater.release.channel": "beta",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}


</details>

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (X11; Linux aarch64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by ovpc** [comment]
Hi,
Running nc-update-nextcloud from 18.0,7 to 19.0.1 seems to work fine (tested in a curl installed VM), it just needs/asks for:

>sudo ncc db:add-missing-columns
sudo apt install php-bcmath
sudo apt install php-gmp
sudo apt install php-imagick (at your own risk, devs recommend not to use it)

https://help.nextcloud.com/t/nextcloudpi-and-nextcloud-19/89508/5

**Comment by sunjam** [comment]
install php-imagick (at your own risk, devs recommend not to use it)

What did devs say this was a risk?  Do you mean just with deprecated
Gallery app, or with Photo app as well?

**Comment by ovpc** [comment]
https://github.com/Imagick/imagick
>We strongly recommend upgrading to the latest version (greater than 6.9.1 or 7.x) if at all possible.

Rasbian/Debian is still on
php-imagick/stable,now 3.4.3-4.1 armhf

**Comment by zweif** [comment]
They recommend that ImageMagick version should be greater than 6.9.1. The version in buster is 6.9.10 - so it should be fine, or am I missing something?

**Comment by ovpc** [comment]
when i install it in Buster I get:
Setting up php-imagick (3.4.3-4.1)
Setting up libmagickcore-6.q16-6:amd64 (8:6.9.10.23+dfsg-2.1+deb10u1)

**Comment by zweif** [comment]
>We strongly recommend upgrading to the latest version (greater than 6.9.1 or 7.x) if at all possible.

I meant this refers to the ImageMagick version which should be 6.9.10 in Buster (8:6.9.10.23+dfsg-2.1+deb10u1), not imagick version (latest version 3.4.4). So I thought it should be fine to include this.

But this refers to possible image corruption issues and not to general security considerations for running ImageMagick in a server environment (https://github.com/Imagick/imagick#security).

Just installing imagick doesn't work in docker (persistance), but I don't know if it's safe to include by default.
