### ISSUE TITLE
Can't upload large Files.

### ISSUE THREAD

**Issue by 19Topgun93** [nextcloud/nextcloudpi#1126]
Nextcloud version (eg, 18.0.2):
Operating system and version (eg, NextcloudPi 1.24.3):
Apache or nginx version (eg, Apache 2.4.38)(Raspbian):
PHP version _ Version: 7.3.14

Arbeitspeicher-Grenzwert: 2,9 GB

Maximale Ausführungszeit: 3600

Maximale Größe zum Hochladen: 100 GB

The issue you are facing:

Is this the first time you’ve seen this error? (Y/N): Yes

Steps to replicate it:

A File bigger than 4 GB can not be uploaded.
The output of your Nextcloud log in Admin > Logging:

PASTE HERE
The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):

PASTE HERE
The output of your Apache/nginx/system log in /var/log/____:

[webdav] Fatal: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 0, expected filesize: -1 ) at <<closure>>

 0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
 1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    OCA\DAV\Connector\Sabre\Directory->createFile("The Borrowers A ... v", null)
 2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "The Borrowers A ... v")
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    Sabre\DAV\Tree->copy("uploads/ncp/web ... e", "files/n***/*** ... v")
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("uploads/ncp/web ... e", "files/***/***... v")
 5. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/www/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
10. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/nextcloud/remote.php line 165
    require_once("/var/www/nextcl ... p")

MOVE /remote.php/dav/uploads/ncp/web-file-upload-65641dbeceba012ebf7a13aa935e5094-1587717677860/.file
from 192.168.178.72 by ncp at 2020-04-24T08:49:39+00:00
2. 
[no app in context] Error: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 0, expected filesize: -1 ) at <<closure>>

 0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
 1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    OCA\DAV\Connector\Sabre\Directory->createFile("The Borrowers A ... v", null)
 2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "The Borrowers A ... v")
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    Sabre\DAV\Tree->copy("uploads/ncp/web ... e", "files/ncp/Anime ... v")
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("uploads/ncp/web ... e", "files/ncp/Anime ... v")
 5. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/www/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
10. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/nextcloud/remote.php line 165
    require_once("/var/www/nextcl ... p")

MOVE /remote.php/dav/uploads/ncp/web-file-upload-65641dbeceba012ebf7a13aa935e5094-1587717677860/.file
from 192.168.178.72 by ncp at 2020-04-24T08:49:38+00:00

I have change the php.ini to larger files, but it didn't help. What can I additonal do? It seems all Data bigger than 4 GB can not be copied.
Help in German or English :)

I have installed this on a Raspberry Pi 4 B

Thanks for the Help :)

**Comment by ovpc** [comment]
No-one else reporting this afaik, so closing this, for now, for help use [https://help.nextcloud.com/tag/ncp](https://help.nextcloud.com/tag/ncp).
If you moved ncdata, Might check value of sys_temp_dir in /etc/php/7.3/fpm/php.ini .
