### ISSUE TITLE
Big Problems with Full Text Search and Nextcloudpi

### ISSUE THREAD

**Issue by Django43** [nextcloud/nextcloudpi#1128]
After I successfully installed Nextcloudpi Docker (Nextcloud 18.0.3), I tried to install Full Text Search.

First I installed the addons in my Nextcloud and then the Docker Image from Elasticsearch. Unfortunately, all of my previous attempts to get Full Text Search working completely failed.

Can it be that in combination with Nextcloudpi Docker an installation is excluded? If not, I would be happy to receive a brief note on how Full Text Search can get started with Nextcloudpi.

It would be even nicer if Full Text Search was already preconfigured in Nextcloudpi.

Thank you in advance for your help.

Wasserlaeufer

**Comment by ovpc** [comment]
Use forum please, Github is not for support
