### ISSUE TITLE
Nextcloud output after upgrade to beta 19.0.0 beta5

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1129]
NextcloudPi on Odroid C2 test instance.

There are some warnings regarding your setup.

    The database is missing some optional columns. Due to the fact that adding columns on big tables could take some time they were not added automatically when they can be optional. By running "occ db:add-missing-columns" those missing columns could be added manually while the instance keeps running. Once the columns are added some features might improve responsiveness or usability.
        Missing optional column "reference_id" in table "oc_comments".
    This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
        bcmath
        imagick

**Comment by Co0p3r21** [comment]
You can just do what is said in the warning execute "occ db:add-missing-columns" and "use forums please this is not for support".

**Comment by nachoparker** [comment]
thanks for the heads up and testing @sunjam, I'll add this command to the upgrade process

**Comment by nachoparker** [comment]
@Co0p3r21 many thanks for the help. For most users what you did is the correct thing and it helps, I appreciate it. In this case though, @sunjam is an active tester and contributor, so I appreciate his input :)

**Comment by nachoparker** [comment]
btw I wonder what app requires `bcmath`... I'll add it if needed when I test this by myself

**Comment by Co0p3r21** [comment]
Sorry if I was a little bit over the top. I didn't mean to.

**Comment by nachoparker** [comment]
no, actually that's great, we need help moderating github and the forums :)

thanks

**Comment by cscholz** [comment]
I've updated from NC 18 to NC19 RC2 and I get the same message:

> Fehlende optionale Spalte "reference_id" in der Tabelle "oc_comments".

occ did not fixed it:

```
sudo -u  $user ./occ db:add-missing-indices
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.
```
PHP and browser cache already cleared.
Is there anything else I can do?

**Comment by OSevangelist** [comment]
Same over here. After updating from 18.0.4 to 19.0.0 i executed 

`./occ db:add-missing-indices
`
and cleared the cache but the error remains the same.

**Comment by sunjam** [comment]
> Same over here. After updating from 18.0.4 to 19.0.0 i executed
> 
> `./occ db:add-missing-indices `
> 
> and cleared the cache but the error remains the same.

Try restarting Nextcloud.

**Comment by DeCorrino** [comment]
Hi,

this warning says: Missing Column
It does NOT say: Missing Index

So yo have to execute: ./occ db:add-missing-columns

Kind regards
Mario

**Comment by nachoparker** [comment]
pushed NC19.0.1 for testing, your comments were very useful, thanks.

It can be tested by running `ncp-update devel` and then either waiting for autoupgrade if it's enabled, or run `nc-update-nextcloud` with version `0`.

**Comment by ovpc** [comment]
Tried updating on my test pi but got this (I think unrelated to v1.29.0) error, 
Running nc-update-nextcloud
Nextcloud backup directory found. Interrupted installation?
Done. Press any key...

So used NC's native updater to update to the proposed 19.0.2 

Appart from having to run 
> sudo ncc db:add-missing-indices
> sudo ncc db:add-missing-columns

All seems fine, only Two Factor e-mail provider app gets disabled for being untested.

**Comment by nachoparker** [comment]
great, thanks oliver. The ncc commands are part of the upgrade so we should be good

**Comment by nachoparker** [comment]
published. Closes #1129

**Comment by ovpc** [comment]
Running nc-update-nextcloud
Current   Nextcloud version 18.0.7.1
Available Nextcloud version 18.0.8
Download Nextcloud 18.0.8...
Back up current instance...
check free space...
Maintenance mode enabled
backup database...
backup files...
backup /var/www//nextcloud-bkp_20200830_1598769774.tar.gz generated
Maintenance mode disabled
Install Nextcloud 18.0.8...
Restore apps...
 * appointments
 * calendar
 * contacts
 * deck
 * files_texteditor
 * gallery
 * groupfolders
 * guests
 * mail
 * news
 * nextcloudpi
 * notes
 * ojsxc
 * onlyoffice
 * previewgenerator
 * previewgenerator.orig
 * sharepoint
 * spreed
 * tasks
 * timetracker
 * twofactor_admin
 * twofactor_email
 * twofactor_gateway
 * twofactor_yubikey
Fix permissions...
Upgrade...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore 
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_external in appstore
Checked for update of app "files_external" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore 
Checking for update of app groupfolders in appstore
Checked for update of app "groupfolders" in appstore 
Checking for update of app guests in appstore
Checked for update of app "guests" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app news in appstore
Checked for update of app "news" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app nextcloudpi in appstore
Checked for update of app "nextcloudpi" in appstore 
Checking for update of app notes in appstore
Checked for update of app "notes" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app onlyoffice in appstore
Checked for update of app "onlyoffice" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app photos in appstore
Checked for update of app "photos" in appstore 
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in appstore 
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app support in appstore
Checked for update of app "support" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app tasks in appstore
Checked for update of app "tasks" in appstore 
Checking for update of app text in appstore
Checked for update of app "text" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app timetracker in appstore
Checked for update of app "timetracker" in appstore 
Checking for update of app twofactor_admin in appstore
Checked for update of app "twofactor_admin" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app twofactor_email in appstore
Checked for update of app "twofactor_email" in appstore 
Checking for update of app twofactor_gateway in appstore
Checked for update of app "twofactor_gateway" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Done.

                                                    
  Command "db:add-missing-columns" is not defined.  
                                                    
  Did you mean one of these?                        
      db:add-missing-indices                        
      db:convert-filecache-bigint                   
      db:convert-mysql-charset                      
      db:convert-type                               
                                                    

Abort
Clean up...
Rolling back to backup /var/www/nextcloud-bkp_20200830_1598769774-18.0.7.1.tar.gz...
check free space...
extracting backup file /var/www/nextcloud-bkp_20200830_1598769774-18.0.7.1.tar.gz...
restore files...
restore database...

**Comment by ovpc** [comment]
I think I know what went wrong
ncp v1.29.0 is for updateing to 19.0.2 not 18.0.8

**Comment by nachoparker** [comment]
I see, will fix. Thanks

**Comment by jcb-tn** [comment]
Problem not solved. 
Updated to Nextcloud 19.02 via stable channel. but get the error furthermore.

![image](https://user-images.githubusercontent.com/70505208/92220324-2158d480-ee9c-11ea-9add-ff0535250bd2.png)

**Comment by nachoparker** [comment]
you need to update through ncp-web
