### ISSUE TITLE
No update for Nextcloud 8.0.6

### ISSUE THREAD

**Issue by llucax** [nextcloud/nextcloudpi#1143]
There is a Nextcloud update for 8.0.6 available but it says the NextCloudPi extension is not available for it. Not sure how a patch release can be marked as incompatible.

![image](https://user-images.githubusercontent.com/1031485/84562198-e63e7d80-ad52-11ea-84e6-78bbb1b0a0db.png)

**System information**

Using ncp v1.26.0.

Skipping as I don't think it is relevant in this case, but I can upload if needed.

**Comment by ovpc** [comment]
https://docs.nextcloudpi.com/en/staying-up-to-date

**Comment by llucax** [comment]
Mmm, I see.

> It is highly recommended to use these tools, other methods, including NC's native updater, may or may not work, use at your own risk.

Is there a particular reason why updating via the native NC updater is not recommended? What is NCP doing that NC doesn't (or vice-versa)?

On 13 June 2020 09:09:04 GMT+02:00, Oliver V <notifications@github.com> wrote:
>https://docs.nextcloudpi.com/en/staying-up-to-date
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/nextcloudpi/issues/1143#issuecomment-643582371

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.

**Comment by ovpc** [comment]
Onother question. What is it about; Use forums please, this is not for support,.....people do not understand or choose to ignore?

**Comment by llucax** [comment]
I understand the difference between a support forum and an issue tracker, but sometimes you have to make a call.

This really felt like a bug, because I see no reason why I wouldn't be able to update NC via the official updater. It looked to me like there was some missing update for NCP to report it was compatible with the latest NC.

On 13 June 2020 09:47:02 GMT+02:00, Oliver V <notifications@github.com> wrote:
>Onother question. What is it about; Use forums please, this is not for
>support,.....people do not understand or choose to ignore? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/nextcloudpi/issues/1143#issuecomment-643586583

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.
