### ISSUE TITLE
Can't upload/create file is some Folder

### ISSUE THREAD

**Issue by Avelec** [nextcloud/nextcloudpi#115]
Hi,

Do you know why some of the folders in nextcloud show message:
"You don't have permission to upload or create files here"

I have attached a picture of the screen shot. Thanks.
![ncp](https://user-images.githubusercontent.com/1951823/29300892-7f9ccdc4-8146-11e7-8a64-5a1ed62cb47c.jpg)

**Comment by nachoparker** [comment]
You probably uploaded that folder externally? Through the terminal, SAMBA, NFS... ?

The folder (everything in your datadir, really) needs to be owned by `www-data` user

**Comment by Avelec** [comment]
Yes, I plugged the 2TB hdd to pc and copied all the folders/files. Then plugged it back to RP3. Some of the folders are ok but some are not (No permission to do anything with the files/folders). 

This is what I got:
pi@raspberrypi:~ $ ls -ld /media/USBdrive/ncdata/admin/files/
drwxrwxr-x 5 www-data www-data 4096 Aug 15 00:51 /media/USBdrive/ncdata/admin/fi                                                                                                                               les/

How can I make all the files/folders owned by www-data user? Thanks,

**Comment by nachoparker** [comment]
Try
```
sudo chown -R www-data:www-data /media/USBdrive/ncdata
```

**Comment by Avelec** [comment]
Thanks again for all your helps.

**Comment by nachoparker** [comment]
;)
