### ISSUE TITLE
Better documentation for `nc-previews-auto`

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/nextcloudpi#1153]
IMO `nc-previews-auto` is not well enough documented.

> You can specify a nightly duration in minutes, or 0.

What does "nightly duration" mean, e.g. when does it start? At midnight? 

What is the effect of `0`? Does it disable the auto-preview completely? Or rather the opposite, it sets the runtime to unlimited?

Do we need to run `nc-previews` first or will that happen automatically when enabling `nc-previews-auto`?

**Comment by daschmidt1994** [comment]
It will start every day at 2am and 0 means "until done"

**Comment by Oberlurch3000** [comment]
Is it possible to change starting time to an other value than 2am?
