### ISSUE TITLE
All connections lost to RPi after applying nc-static-ip

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [nextcloud/nextcloudpi#1157]
Hi there,

I was able to access my NCPi Panel, my NC instance, connect to my RPi through SSH and my RPi was shown on my router page before I applied nc-static-ip. After I applied it, the SSH connection to the original ip address returned a "connection timeout" and a the one to the new applied static IP returned a "connection refused". My RPi is no longer discoverable on my router page nor on Angry IP Scanner.

This is not my first encounter with this issue, it happened to me before whenever I used the default recommended static IP address (192.168.1.130) and I had to re-flash my SD card and start over.

Your help is greatly appreciated.

Thank you in advance,
Kind regards,
Mohammed Al-Haidary.

**Comment by ovpc** [comment]
Thank you for using https://help.nextcloud.com/tag/ncp to request help and assistance, or join ncp related Telegram chat https://t.me/NextCloudPi
