### ISSUE TITLE
Broken links on docs.nextcloudpi.com

### ISSUE THREAD

**Issue by mickeymau** [nextcloud/nextcloudpi#1160]
Whilst trying to access my NextCloudPi form outside my home network I see this page:
https://docs.nextcloudpi.com/en/how-to-access-from-outside-your-network/

Most links on that page refer to 
http://docs.nextcloudpi.com/en/latest/Configure/...
where the    latest/  should not be included.

Please update links. Thx.

Grtz., Frank

**Comment by ovpc** [comment]
Fixed! Thanks for pointing out.
