### ISSUE TITLE
UBOS as based OS for Nextcloud

### ISSUE THREAD

**Issue by joaopalma5** [nextcloud/nextcloudpi#1163]
**Description**  
"UBOS is a Linux distro that aims to make it 10x easier to self-host popular open-source web applications, for yourself, or for your family, on hardware or cloud servers you own."
Ubos is faster than raspbian for this reason, we can put NEXTCLOUDPI in UBOS. The result is a better performance when is running! 

**Site**  
https://ubos.net/

**Comment by nachoparker** [comment]
NCP only runs on Debian based systems
