### ISSUE TITLE
Nextcloud 19.02 database warning - The database is missing some optional column

### ISSUE THREAD

**Issue by jcb-tn** [nextcloud/nextcloudpi#1174]
I get an error after upgrading over stable channel to version 19.02:

Missing optional column "reference_id" in table "oc_comments".

![image](https://user-images.githubusercontent.com/70505208/92220615-8c0a1000-ee9c-11ea-9252-cde7f98ce1dc.png)

Like issue https://github.com/nextcloud/nextcloudpi/issues/1129

**Comment by nachoparker** [comment]
you need to upgrade through ncp-web. Go to the forums and look for the occ commands you need to run
