### ISSUE TITLE
Please update docker image from 18.0.3 to current release

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1176]
Please update docker images from 18.0.3 to current release.  19.0.2 as of this post, which appears to be built on newer php7.3.  Thanks!

**Comment by nachoparker** [comment]
the images are ready, I'll upload them soon (my upload bandwith sucks, have to do it at night).

Also, we've been using PHP 7.3 for a while :)

**Comment by sunjam** [comment]
> Also, we've been using PHP 7.3 for a while :)

True @nachoparker, but the Docker image version wants to install a specific variation of PHP 7.3* while updating beyond 18.0.3.  Just an fyi.
