### ISSUE TITLE
no automatic upload and synchronization of contacts

### ISSUE THREAD

**Issue by jekigit** [nextcloud/nextcloudpi#1178]
![Bildschirmfoto vom 2020-09-06 11-50-29](https://user-images.githubusercontent.com/70839796/92323496-96addc00-f039-11ea-9e21-243735d42a48.png)

Hey, recently the automatic upload and synchronization of contacts from the smartphone stopped working. 
On the phone of the Nextcloud Android App 3.13.0 the message - Bad Request 
From the Android App DAVx5 version 3.3-OSE, the message - HTTP server error. 

It runs Nextcloud 19.0.2 and NextcloudPi v1.30.0

Ports are open, but NextcloudPi says something else. Accessing the cloud over the internet is no problem. Changing contacts and calendar entries via Ubuntu Apps also works.

**Comment by nachoparker** [comment]
not NCP related, please report in the adecuate repo
