### ISSUE TITLE
Appearance of Checkboxes mixed up

### ISSUE THREAD

**Issue by mucke5** [nextcloud/nextcloudpi#1190]
The appearance of the checkboxes is swapped, in edit mode is the icon and in preview mode is the formatting indicator.

![image](https://user-images.githubusercontent.com/13103826/94816935-c5329300-03fc-11eb-8417-adb62fc74fa2.png)

**Comment by ovpc** [comment]
Thanks for reporting, but wrong place to post, this is for NCP NextCloudPi, it should be in Notes app section
