### ISSUE TITLE
Add options to install and enable missing packages from apt

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1192]
#1125, option to add `smbclient` from the ncp menus.
#1177 add option to add `php-imageck` and `bmath` from the ncp menus.

This feature request is for installing packages / dependencies missing within the default NextcloudPi installations.  The current method is for the admin to install these via apt-get, but that is not persistent in Docker method.  I understand these are not included by default, but it would make sense to make them a one click fix, which is also in-line with the way Docker images are designed.

Thanks for considering!

**Comment by sunjam** [comment]
If considered, [method that would make the most sense for non-interactive is](https://pythonspeed.com/articles/system-packages-docker/):

$ apt-get update
$ apt-get -y install --no-install-recommends $PACKAGE
$ apt-get clean

This avoid installing unnecessary additions outside the required packages in apt-get.

**Comment by segator** [comment]
The problem to do it by hand is that if you reinstall the docker everything is lost.. something that in case we use kubernetes to deploy applications is a very common case :(
we need a way to inject an script in runtime to install packages.

**Comment by C-Fu** [comment]
I think this would be awesome and probably needed for CUPS and the Printer App https://github.com/nextcloud/nextcloudpi/issues/1288

**Comment by nachoparker** [comment]
I think that the best way of achieving this is to build a new docker image with the NCP image as a base, and install any extra stuff you might want
