### ISSUE TITLE
nc-backup.sh - error on exfat

### ISSUE THREAD

**Issue by OlafBr** [nextcloud/nextcloudpi#1193]
Hello,
when the backup drive has exfat file system, the line 109
**chown :www-data "$destfile"**
in the file [nc-backup](https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/BACKUPS/nc-backup.sh) will throw an error: "...Operation not allowed".
So I suggest to add the "-f" option, which will supress the error:
**chown -f :www-data "$destfile"**
Olaf

**Comment by OlafBr** [comment]
Sorry,
the option "-f" only supresses the error, but the backup is still aborted.

**Comment by ovpc** [comment]
ncp only supports ext4 and btrfs afaik
