### ISSUE TITLE
Missing data in web UI after updating Nextcloud

### ISSUE THREAD

**Issue by Oberlurch3000** [nextcloud/nextcloudpi#1196]
After an update to version 19.0.4 some data is missing in the web UI.
There are missing around 400GB of data if I look into the users dataspace.

If I take a look into the folders there is data without any calculated space on the disk.
All this data take over 2GB discspace each. So I think it's a problem with big files.

Accessing the files via SMB still work. But via the web UI the files seem to be corrupted.

After the update to 19.0.4 NC asked to refresh some database tables... so I did.

Any ideas how to get them back?

**Comment by ovpc** [comment]
Looks like a Nextcloud issue, not ncp related and Github is not for support, please use forums for that.
