### ISSUE TITLE
Can't install Collabora Online - Built-in CODE Server (ARM64)

### ISSUE THREAD

**Issue by Larsene** [nextcloud/nextcloudpi#1197]
On NextCloudPi 1.30, i'm unable to install Collabora Online - Built-in CODE Server (ARM64).

First error is a timeout when installing the app (120 sec is not enough), but works with the command line occ app:install, or, perhaps NextcloudPi could set a higher timeout value for big apps in the file `lib/private/Installer.php`, line 274 

but, even if it appears running in the nextcloud interface, it is not, and Collabora App does'nt propose to use the built-in CODE Server.

Is this because NextCloudPi is built on the 32bit Raspbian OS ?

**Comment by ovpc** [comment]
Please use forum, Github is not for support.
