### ISSUE TITLE
Debian Buster: no way to uninstall - no docs about uninstall process

### ISSUE THREAD

**Issue by supersexy** [nextcloud/nextcloudpi#1221]
After a few disappointing experiences with this mess here is one last issue you should think about: 
There is no way to uninstall this stuff - also there is no documentation about how to uninstall it.
Expected: some `uninstall_nextcloudpi.sh` script that would leave a clean system.

**Comment by nachoparker** [comment]
We assume a clean Debian instance, and there is no rollback process currently.

I'm adding that to the README as well to make it more clear
