### ISSUE TITLE
Not unable to install ddclient: perl5 dependency missing on fresch Nextcloudpi 12.0.2

### ISSUE THREAD

**Issue by acatanyg** [nextcloud/nextcloudpi#123]
On a brand new installation  ist not posible  install ddclient:

pi@raspberrypi:~ $ sudo -s
root@raspberrypi:/home/pi# apt install ddclient -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ddclient : Depends: perl5
            Recommends: libio-socket-ssl-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by nachoparker** [comment]
```
sudo apt-get install -t stretch ddclient
```
