### ISSUE TITLE
Using nc-static-IP results in ghost DHCP address that occasionally takes primary, and DNS resolution borked.

### ISSUE THREAD

**Issue by ikidd** [nextcloud/nextcloudpi#1234]
Using the VM image supplied as of Dec. 31/20 from the ownbits website, I set up and configured a basic NC image on Proxmox.

Using the nc-static-IP will set a static address as primary.  The initial DHCP address obtained on boot is retained as a secondary address.  Upon reboot, or just spontaneously presumably when dhcpcd refreshes the address, this DHCP address will take over as primary IP, and then you can't contact Nextcloud as the trusted domain doesn't match up, I'm guessing.  Re-running nc-static-IP would temporarily resolve this, but then it would revert at some point.

To resolve this, change `/etc/system/network/99-dhcp.network` setting to `DHCP=no` and this address goes away and server behaves normally.

This of course now removes the DHCP obtained DNS server, so now you have to set something for systemd-resolved, I chose to set `/etc/systemd/resolved.conf.d/fallback_dns.conf` to 

[Resolve]
FallbackDNS="someDNSserver"

just in case something comes along on the NCP interface in an update that sets the DNS server properly at a higher priority in systemd-resolved.service.

This seems like a bug in the static IP setting script that should be updating to remove the DHCP request and set a user-configurable DNS.

I look at https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/NETWORKING/nc-static-IP.sh and it certainly doesn't seem to be running that script as there is no `/etc/dhcpcd.conf` generated, amongst other things.  But there is the correct script in `/usr/local/bin/ncp/NETWORKING`.  Also, that script looks like it will cp the old `interfaces` file to `interfaces-ncp-backup-orig` but that file doesn't exist.  It does, however, seem to write out the correct setttings into `/etc/network/interfaces`, which is strange.

NextCloudPi version  v1.33.0
NextCloudPi image    NextCloudPi_11-30-20
distribution         Debian GNU/Linux 10 \n \l

**Comment by nachoparker** [comment]
thanks for the detailed explanation.  I was able to verify that `dhclient` stays up, but it doesn't come back if you reboot.

A quick solution is to just kill it when activating nc-static-IP
