### ISSUE TITLE
Rebase to Raspbian 9 Stretch

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/nextcloudpi#124]
Raspbian has [released](https://www.raspberrypi.org/blog/raspbian-stretch/) new version based on Debian Stretch which includes plenty of improvements. Most notably, it includes PHP 7 in the repositories, so no need to fetch from a mirror.

**Comment by nachoparker** [comment]
Sure, this is top on the list.

I was not getting PHP or Apache from a mirror, but from the Stretch repositories already.

It will hopefully solve some incompatibilities, such as #48 and #123

**Comment by nachoparker** [comment]
Migration finished in v0.24.0

Generating new image now

Modsecurity is broken in the new image ATM. Will fix that separatedly next.
