### ISSUE TITLE
Generating rsa key pair on ncp-update

### ISSUE THREAD

**Issue by epe** [nextcloud/nextcloudpi#1244]
Calling /usr/local/bin/ncp-update does some apt updating and apt dist-upgrade. Fine. 
At the end of the command I dee this statement which makes me afraid the update could break someons setup:
_Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists._

Generating a key should happen once during a setup procedure not during an update, Agree?

BTW, is it possible, that some of these commands in the documentation are  (now?) called ncp-updateXXX rather than nc-updateXXX as stated?  https://docs.nextcloudpi.com/en/staying-up-to-date/

Output, not complete:

Reading package lists... 0%
Reading package lists... Done
Building dependency tree                                                                         
Reading state information... Done
openssh-client is already the newest version (1:7.9p1-10+deb10u2).
pv is already the newest version (1.6.6-1).
The following packages were automatically installed and are no longer required:
  dbconfig-common dbconfig-mysql libjs-openlayers libpapi5.7 libpfm4 php-apcu
  php-google-recaptcha php-mysql php-phpmyadmin-motranslator php-phpmyadmin-shapefile
  php-phpmyadmin-sql-parser php-phpseclib php-psr-cache php-psr-container php-psr-log
  php-psr-simple-cache php-symfony-cache php-symfony-expression-language php-twig-extensions
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2021-01-18 00:43:40--  https://raw.githubusercontent.com/nachoparker/btrfs-sync/master/btrfs-sync
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 
200 OK
Length: 11943 (12K) [text/plain]
Saving to: ‘/usr/local/bin/btrfs-sync’

/usr/local/bin/btrfs-syn 100%[===============================>]  11.66K  --.-KB/s    in 0.005s  

2021-01-18 00:43:40 (2.40 MB/s) - ‘/usr/local/bin/btrfs-sync’ saved [11943/11943]

_Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists._

**Comment by nachoparker** [comment]
thank you for reporting. Yes, this was not intended to happen. Pushing a quick fix
