### ISSUE TITLE
ncp-web: confirmation dialog for shutdown

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#125]
Hi
Love the 0.23.0 upgrade and the continuing brilliant work on nextcloudpi....

However the shutdown button top right caught me off guard. Great additon but could do with a drop down for 'reboot', sleep, shutdown or confirmation box of the shutdown.

Dj

**Comment by nachoparker** [comment]
Hi Del,

Yes, this is the first preliminar version of the feature, we need a confirmation dialog, see #119

**Comment by theCalcaholic** [comment]
Oh, sorry @nachoparker . I didn't see that you had assigned this issue to yourself already. Feel free to ignore my pull request if you already have worked on it.

**Comment by nachoparker** [comment]
not at all, I haven't worked on it. Thanks for the PR

**Comment by nachoparker** [comment]
Implemented in #403
