### ISSUE TITLE
Storage wrapper 'sharepermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

### ISSUE THREAD

**Issue by dotlineX** [nextcloud/nextcloudpi#1255]
I get this error message multiple times a second. The log file has become 1Mb even though I deleted it yesterday.

What is this error? I have looked it up online but couldn't find much.

Thanks,

**Comment by dogwolf** [comment]
Can you provide some log or your configuration?

Thank you

**Comment by dotlineX** [comment]
https://pastebin.com/7ujwzqMf

There is one external drive used as data storage.

**Comment by nachoparker** [comment]
this is  a NC issue, not NCP
