### ISSUE TITLE
Password is expired, please use forgot password method to reset

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1261]
For some reason all of the passwords on my machine are expiring simultaneously.  NextcloudPi arm64 Docker with 20.0.4

```
Password is expired, please use forgot password method to reset
```

Reset my passwords a couple days ago when this first happened and now they are expired once again for all accounts.  Strange, as the only updates have been automatic for ncp / apps.

**Comment by sunjam** [comment]
Will re-open with logs if any further issues.

**Comment by Jdemuren** [comment]
I am getting the same errors, however I can log in with my yubico usb key. Anyway to overcome this?
