### ISSUE TITLE
Nextcloudpi Not booting (black screen)

### ISSUE THREAD

**Issue by Pauler221** [nextcloud/nextcloudpi#1274]
I have a raspberry pi 2 and a fresh installed nextcloudpi image on it. The pi just won’t boot (black screen). Also checked the md5sum it’s the same.

**Comment by nachoparker** [comment]
older boards that are armv6 (pi zero, pi 1, pi2) are no longer supported, since NC 32bit support is shaky anyway

**Comment by Pauler221** [comment]
Ok thx! By the way pi 2 is armv7.
