### ISSUE TITLE
support Collabora Office by default

### ISSUE THREAD

**Issue by Coernel82** [nextcloud/nextcloudpi#1276]
As wished before in #51 and #343 now could be the time to integrate Collabora Office (including the Server) in Nextcloud Pi as it is now possible.

https://nextcloud.com/blog/the-nextcloud-hub-ubuntu-appliance-now-available-for-raspberry-pi-4-and-more/

**Comment by nachoparker** [comment]
unfortunately we still support some 32bit boards, so it cannot come installed by default, but it is as easy as installing the app for those who want that

**Comment by Coernel82** [comment]
Thank you for your reply! For other users who try to active the 64 Bit Collabora CODE server, there might be an error:
`App "Collabora Online - Built-in CODE Server (ARM64)" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: aarch64`

At your own risk (backups, in this case probable an SD-Card image are your friends) switch the Kernel to 64 bit
https://www.sindastra.de/p/1345/switch-your-raspberry-pi-to-64-bit-kernel-raspbian/

After installing the CODE server and the collabora app and having selected "use built in server" you might not be able to edit or create documents as the server cannot be found. ("Please try again later" - error message) Also rebooting may take very long (5 minutes or so) till you can use your Nextcloud again. Don't panic in that case - just wait.

However the error is known: https://github.com/CollaboraOnline/richdocumentscode/issues/116

So at the moment: Be patient!

**Comment by nachoparker** [comment]
thanks for the info. The raspberry pi images are NOT 32bit Raspbian, they are 64bit Debian so that shouldn't be an issue.

**Comment by Coernel82** [comment]
Should not be an issue but in fact was an issue, I had to enable the 64 bit kernel which was easy but not the default.

Am 11. April 2021 18:03:03 MESZ schrieb nachoparker ***@***.***>:
>thanks for the info. The raspberry pi images are NOT 32bit Raspbian,
>they are 64bit Debian so that shouldn't be an issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/nextcloudpi/issues/1276#issuecomment-817330546

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by nachoparker** [comment]
you must be using an older image, the latest one is 64bits

**Comment by sunjam** [comment]
Wondering about coming back to this now that we are defaulting to 64-bit builds.  The process of setting up Collabora is currently very awkward in testing and could use some possible finesse.
