### ISSUE TITLE
Nextcloudpi-Image with debian STRETCH

### ISSUE THREAD

**Issue by mysap01** [nextcloud/nextcloudpi#1277]
Hello everbody
I need a older release of nextcloudpi that work with debian STRETCH. Where i find a image or lite-release to install with WGET or something like that?
Reason: With debian BUSTER doen't work "external storage" to different nas or ftp's storage.
Best regards......Phil

**Comment by nachoparker** [comment]
external storage should work, what is the issue? older images are not available for download.

Please use the forus for support
