### ISSUE TITLE
Reopen #1256  build issue

### ISSUE THREAD

**Issue by jakern** [nextcloud/nextcloudpi#1278]
My only guess is that if you're building arm on a different server, the repo's etc/ncp.cfg isn't being updated before the build-docker.sh command is run?

Nevermind. That was a terrible guess. I'm trying to track it down now

#1256

**Comment by jakern** [comment]
I built the image myself and I do get version 20.0.8.1 by default which aligns with what it in the ncp.cfg `"nextcloud_version": "20.0.8"`. That's really the only place where this could have gone wrong and not catastrophically wrong, no?

**Comment by jakern** [comment]
It doesn't appear that using 21.0.1 in that file works though

**Comment by WeiChihChern** [comment]
the latest docker image provided is outdated and either docker or this repo have been updated for two months. Not sure why tho.

**Comment by nachoparker** [comment]
@jakern what is your issue with the build exactly?

@WeiChihChern you can always download the latest available image and then nc-update -> nc-update-nextcloud
