### ISSUE TITLE
Docker image for v1.35.0

### ISSUE THREAD

**Issue by sude22** [nextcloud/nextcloudpi#1279]
Hi,
it would be nice if you could deploy a docker image with v1.35.0.
The latest image contains NC 18.x and do not upgrade to 20.x automatically.
Thanks

**Comment by ovpc** [comment]
When I pull and run lastest image (NextCloudPi_docker_01-20-21) this day (18th of April 2021)
I get NCP 1.34.7 and NC 20.0.4
![NCPdocker-INFO-Screenshot at 2021-04-18 08-06-31](https://user-images.githubusercontent.com/8775469/115136115-e2882100-a01d-11eb-98dc-8bc46f9f102b.png)


Check [docs](https://docs.nextcloudpi.com/en/staying-up-to-date/) on how to  (auto)update
And use [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm/33/l/latest) if need assistance.
