### ISSUE TITLE
Add a link to changelog somewhere

### ISSUE THREAD

**Issue by FadeFx** [nextcloud/nextcloudpi#1284]
hi,

I would like to suggest to have a link to the github changelog pagesomewhere in the interface, so when we see an updated versiin of ncp we dont have to search for the changelog...

For example by clicking onthe version number in thetop pannel.

**Comment by nachoparker** [comment]
hi,

That was implemented years ago

**Comment by FadeFx** [comment]
Indeed, sorryfor that...
