### ISSUE TITLE
NextCloudPi Panel - no version information

### ISSUE THREAD

**Issue by wadaki** [nextcloud/nextcloudpi#1289]
I installed with the latest release v1.36.3 on my Raspberry Pi.

The installation wizard was fine until Let's Encrypt. It was not possible to finish here. All steps are fine, but could not get the certificate. Therefore, I finished by self. The wizard was closed and I'm able to see the NextCloupPi Panel.

I worked again to get the certificate in the menu of https://192.168.0.96:4443/
Networking > Let’s Encrypt

Important is, when you not enter an email address, will not get the certificate! In the wizard was the same, there is not place to enter an email address.

Now, everything is working perfect, but on top left is written my version "v0.0.0".
In the system overview also is no version.

What can I do to bring back the version for future updates?
![2021-06-14_21-51](https://user-images.githubusercontent.com/8577568/121896862-ba3a4b80-cd5c-11eb-897e-b93b03530bc1.png)

**System information**

pi@nextcloudpi:~ $ sudo ncp-report 
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

cat: /usr/local/etc/ncp-version: No such file or directory
sudo: Account or password is expired, reset your password and try again
Current password: 
New password: 
Retype new password: 
NextCloudPi version
distribution         Raspbian GNU/Linux 10 \n \l
automount            yes
USB devices          sda 
datadir              /media/myCloudDrive/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      578M/979G
rootfs usage         2.5G/58G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    20.0.10.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         yes
uptime               1day

```
</details>

**Comment by nachoparker** [comment]
Fixed in https://github.com/nextcloud/nextcloudpi/pull/1300
