### ISSUE TITLE
Image on Docker-Hub not up to date

### ISSUE THREAD

**Issue by mad73923** [nextcloud/nextcloudpi#1292]
Same issue as in #1256 
Somehow the Docker-Hub images don't get updated any more.
Stuck on v1.34.6

**Comment by ovpc** [comment]
I dont think it the container is supposed to get any updates at all, just run ncp-update inside the container.

**Comment by mad73923** [comment]
In my point of view it should. This is needed if you migrate your instance to a new machine including your data.
You can't start a new docker container with the image pulled from the hub and your dataset from a newer version.
I'll purpose an automated dockerhub push via Travis. PR pending

**Comment by nachoparker** [comment]
when you restore a backup the nextcloud files and database are included, so no issues there

**Comment by nachoparker** [comment]
> I'll purpose an automated dockerhub push via Travis. PR pending

:clap:
