### ISSUE TITLE
The homepage is down

### ISSUE THREAD

**Issue by jthaman** [nextcloud/nextcloudpi#1296]
https://ownyourbits.com/nextcloudpi/ is down.

**Comment by ovpc** [comment]
yep, thanks for reporting.
Send Nacho PM on telegram, but he's not seen it yet.
docs.nextcloudpi is down also, they are in the same hosting plan.

**Comment by zachjmurphy** [comment]
It is also down for myself as well.

**Comment by nachoparker** [comment]
Contacted the hosting company

**Comment by zachjmurphy** [comment]
Okay!

**Comment by nachoparker** [comment]
web is up again
