### ISSUE TITLE
ncp-web: button to enable SSH

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#130]
It would be useful, so people do not need to plug in keyboard and HDMI (or do the `/boot/ssh` trick) to enable SSH.

This would be reasonable to do once web authentication is in place, for security reasons

**Comment by testbird** [comment]
Ok, if with ncp-web now only installing additional services requires SSH, I'd think to require physical sdcard manipulation to obtain SSH access is an adequate security measure.

**Comment by nachoparker** [comment]
Implemented in `v0.38.0`
