### ISSUE TITLE
nc-httpsonly does not change SSLEngine setting in site config

### ISSUE THREAD

**Issue by JonasDaWi** [nextcloud/nextcloudpi#1301]
After starting a fresh docker container and setting httpsonly to "no" in ncp-config, SSLEngine is still set to "on" in /etc/apache2/sites-enabled/ncp-activation.conf and, after activation, also in /etc/apache2/sites-enabled/nextcloud.conf.

I expected it to be set to off.

**Comment by theCalcaholic** [comment]
As long as the https redirect is not active anymore, that shouldn't be an issue. Did you observe unexpected behavior?
