### ISSUE TITLE
NextCloudPi IMAGE on official webside broken?

### ISSUE THREAD

**Issue by Tesch1933** [nextcloud/nextcloudpi#1310]
Hello,

I downloaded the file "NextCloudPi_RPi_11-27-20.tar.bz2" from https://ownyourbits.com/downloads/NextCloudPi_RPi_11-27-20/ for my the PI4. 
Then I wanted to unpack the image under Windows 10.
I tried on 2 devices with winrar and 7Zip. Everywhere unsuccessful. At the end of the extraction process always appears the error message that the file is damaged. 
Am I alone with the problem.
Last month everything worked fine.

**Comment by x0rld** [comment]
![image](https://user-images.githubusercontent.com/45242856/128541660-2af515b8-6d40-4dc8-b79b-a4cbc39a6591.png)
It works on my windows 10 with 7-zip
the sha256 checksum for the file is `c2a2d1f4f4cd141e89c50b2c1cd21a8fc074c1950638df07a8d1ceb7943787e0`
maybe you had an issue while downloading
