### ISSUE TITLE
[REQUEST] changing server to download nextcloud

### ISSUE THREAD

**Issue by x0rld** [nextcloud/nextcloudpi#1313]
I'm downloading nextcloud 20.0.11 for the infos below.

Nextcloud is curently download on http://download.nextcloud.com/server but the current version weight 118MB with a really bad download speed ( less than 1MB/s) 
It could be faster to use github release cause it's only 48MB and it download at more than 1MB/s
https://github.com/nextcloud/server/archive/refs/tags/v20.0.11.tar.gz

**Comment by nachoparker** [comment]
are these tarfiles equivalent? if you want to send a PR, then we can test it

**Comment by nachoparker** [comment]
I checked. They don't seem equivalent. Thanks for the suggestion
