### ISSUE TITLE
Raspi 2B blinks 7 times

### ISSUE THREAD

**Issue by petesimonic** [nextcloud/nextcloudpi#1314]
Hello! There is a Raspberry 2B to host NCP. Tried to download image from the directory (with md5sum check) and to build from latest release. Both ways ended up with device just blinking 7 times, obviously without any response. Raspberry-OS and Lite work well. Does NCP still support this model?

**Comment by nachoparker** [comment]
only through curl installer / docker, the image is 64bits now

**Comment by petesimonic** [comment]
It would be helpful to put in documentation, since I couldn't find such a note.

**Comment by ovpc** [comment]
Thanks for pointing out, I think it was already in the FAQ, but just added a note, to the main install page.
