### ISSUE TITLE
Cannot run nc-update

### ISSUE THREAD

**Issue by lokisilverblade** [nextcloud/nextcloudpi#1317]
Hello,

i cannot perform nc-update it ends with error:

"/usr/local/bin/ncp-update: line 23: ./update.sh: File or dir not found"

Installed is NCP 1.37.2

Thank you.

**Comment by ovpc** [comment]
Please go to https://help.nextcloud.com/c/support/appliances-docker-snappy-vm/33 and use the ncp tag for support.

**Comment by lokisilverblade** [comment]
Hey, after there is a new Version i cannot perform Update. The Script means "/usr/local/bin/ncp-update: line 23: ./update.sh: File or dir not found" - Is there any chance to fix the Script?

**Comment by nachoparker** [comment]
let me look at that

**Comment by nachoparker** [comment]
that is not happening to me

**Comment by nachoparker** [comment]
are you doing `sudo ncp-update`? or how are you doing it?

**Comment by lokisilverblade** [comment]
Yes i do sudo ncp-update or update via sudo ncp-config doesent work.

**Comment by nachoparker** [comment]
try this `sudo rm /.ncp-image` and then retry

**Comment by lokisilverblade** [comment]
Thank you it works :-)
