### ISSUE TITLE
ncp-wifi not working on raspberrypi 4 (possibly due to RFKill)

### ISSUE THREAD

**Issue by ChaosNicro** [nextcloud/nextcloudpi#1320]
Heya, 
I am trying to set up NCP on a Raspberrypi 4 (4 GB Version) booting from a Sandisk extreme portable USB-SSD.
Initial setup using a wired connection was fine and SSH login worked. 

Upon login the shell warned me that RFKill would block the internal Wifi-Interface until a region was configured and that this could be done in raspi-config. Trying that gives the Error message "Could not communicate with wpa supplicant service". 
Trying to use ncp-wifi at this point shows that wicd-curses cannot find any networks because the interface is still down. (probably unrelated: wicd-curses does not respond to any menu selectors other than arrow keys, enter, h, and q). 
I was able to set the region manually using wpa_supplicant.conf and iw, making the warning on SSH-Login disappear. ifconfig and iw now recognize wlan0 as the internal wifi but wicd does not. 
If I find my external wifi-dongle, I will try to use it and see if that makes a difference.

Does the network setup that NCP uses still honor the wpa_supplicant.conf?
Does  ncp-config interfere with raspi-config?
Can raspi-config normally be used to set up wifi instead of ncp-wifi?
What does ncp-wifi actually invoke?
Was the new RFKill-enforcement considered by the NCP-Devs when it was introduced to RPI-OS?

The project looks great and I can't wait to get it running.

**Comment by nachoparker** [comment]
we are killing ncp-wifi since wicd-curses is gone from the Bullseye repo
