### ISSUE TITLE
After upgrading to bullseye, wrong update notice

### ISSUE THREAD

**Issue by BJKle** [nextcloud/nextcloudpi#1329]
I've upgrade my os to Debian 11 (**bullseye**).
After login, the following update notice is displayed:

"  Update to **buster** available. Type 'sudo ncp-dist-upgrade' to upgrade  "

***Solution?***
The update check should check / use the debian version. 

**System information**

NextCloudPi version  v1.39.0
distribution         Raspbian GNU/Linux 11 \n \l
automount            yes
USB devices          sda 
datadir              /media/myCloudDrive/ncdata
data in SD           no
data filesystem      btrfs
Nextcloud check      ok
Nextcloud version    22.1.1.2

**Comment by ovpc** [comment]
Thanks for reporting, but buster is still only NCP supported version.  It will resolve itself when NCP moves to Bullseye.
No other issues 😉?

**Comment by sunjam** [comment]
#1321 related.  Thank you for reporting!  I see you are on 22.*

**Comment by BJKle** [comment]
I just wanted to help. Nevermind.
