### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by swr85260** [nextcloud/nextcloudpi#133]
I’ve got headache with the wi-fi connection. After a week of August vaccation I lost the connection, Weired, I decided to start form the new image file.
1/ wifi is not reconized and I need to update the Pi to activate it (I have a chinese pi board, not sure this is important to know)
2/ then, I use to make the wifi setup through the wpa_supplicant.conf file and it sounds stange and does not work any more (I tried differents ways of setup : wpa_supplicant or nc-wifi). Did you change something on the latest version?

**Comment by nachoparker** [comment]
hi, 

let's see, what do you see on nc-wifi?

**Comment by swr85260** [comment]
I started form scratch, to show you evidence.
Find the screen copy enclosed with only update on rev 0.24.0


----- Mail original -----
De: "nachoparker" <notifications@github.com>
À: "nextcloud/nextcloudpi" <nextcloudpi@noreply.github.com>
Cc: "swr85260" <olivier.meunier@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 20 Août 2017 13:59:40
Objet: Re: [nextcloud/nextcloudpi] Wifi (#133)



hi, 

let's see, what do you see on nc-wifi?

**Comment by nachoparker** [comment]
mmm I don't think email attachments to github show up here, you might have to use the github web and drag the screenshot

**Comment by swr85260** [comment]
![capture2 - copie](https://user-images.githubusercontent.com/30535355/29496300-edb6965e-85cf-11e7-95f3-a77b13b925a0.JPG)
![capture - copie](https://user-images.githubusercontent.com/30535355/29496301-edb95f10-85cf-11e7-986a-1f824c36ebe1.JPG)
this is the files

**Comment by nachoparker** [comment]
raspberry pi 3?

**Comment by swr85260** [comment]
Pi 3 yes

**Comment by nachoparker** [comment]
And it works with the old image and not with the new one? even if you go back and forth between the two?

I have not changed anything, I don't think. Your wifi radio is not even detected.

Post the output of `dmesg`

**Comment by swr85260** [comment]
![capture](https://user-images.githubusercontent.com/30535355/29582000-65267fcc-877b-11e7-9458-2f22793a8886.JPG)
Works fine with 0.24.1

**Comment by nachoparker** [comment]
great!
