### ISSUE TITLE
Notifications for file drop used

### ISSUE THREAD

**Issue by Aresss** [nextcloud/nextcloudpi#1331]
**Description**  
We are hosting our company NextcloudPi and are asking our clients to upload documents in a folder that is shared with the settings "upload only". Now it would be nice if it is possible to get a notification if the client uploaded the files that we requested and we wouldnt need to actively check the folder all the time.

**Example**  
For example we have a client A. We are working together with him and see that we need more information from his side provided to us in a file. Then we will create a folder in our NextcloudPi server where he can upload the files. Unfortunately there is no way to get notified if this actually happened so we have to check the folder daily or hope the client confirms with us.

**Comment by ovpc** [comment]
This channel is for NCP bugs and dev only, your request is related to Nextcloud functionality, not NCP.
Please try https://github.com/nextcloud/ or https://help,nextcould.com
