### ISSUE TITLE
Upgrading to NC21 on docker fails to add docker IP to trusted proxies - HPB cannot be enabled

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/nextcloudpi#1345]
Updating from within docker throws the following error. Full log below.

✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
🗴 push server can't connect to the Nextcloud server
  Response from nextcloud is not a number: invalid digit found in string
notify_push setup failed. You are probably behind a proxy
Run 'ncc config:system:set trusted_proxies 15 --value=<proxy_IP>' and then 'ncc notify_push:setup https://<domain>/push to enable
Check https://help.nextcloud.com/tags/ncp for support

Issueing the commands results in:
root@nextcloudpi:/# ncc config:system:set trusted_proxies 15 --value=172.17.0.3
System config value trusted_proxies => 15 set to string 172.17.0.3
root@nextcloudpi:/# ncc notify_push:setup https://mydomain.eu/push
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
✓ push server is running the same version as the app
  configuration saved

root@nextcloudpi:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever

That IP could have been retrieved from the container.

Full update log. I wondered a bit about all the disabled apps, but the rest seems ok.

root@nextcloudpi:/# ncp-update-nc 21.0.4
Current   Nextcloud version 20.0.12.1
Available Nextcloud version 21.0.4
Download Nextcloud 21.0.4...
Back up current instance...
check free space...
Maintenance mode enabled
backup database...
backup files...
backup /var/www//nextcloud-bkp_20210923_1632421521.tar.gz generated
Maintenance mode disabled
Install Nextcloud 21.0.4...
Restore data...
Fix permissions...
Upgrade...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: apporder
Disabled incompatible app: bruteforcesettings
Disabled incompatible app: calendar
Disabled incompatible app: contacts
Disabled incompatible app: deck
Disabled incompatible app: end_to_end_encryption
Disabled incompatible app: extract
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: groupfolders
Disabled incompatible app: notes
Disabled incompatible app: tasks
Disabled incompatible app: twofactor_nextcloud_notification
Disabled incompatible app: twofactor_totp
Updating <federation> ...
Updated <federation> to 1.11.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.9.0
Updating <oauth2> ...
Updated <oauth2> to 1.9.0
Updating <password_policy> ...
Updated <password_policy> to 1.11.0
Updating <files> ...
Updated <files> to 1.16.0
Updating <activity> ...
Updated <activity> to 2.14.3
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.4.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [->--------------------------]   0%
Updated <dav> to 1.17.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.13.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.11.0
Updating <files_versions> ...
Updated <files_versions> to 1.14.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.11.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.3.0
Updating <comments> ...
Updated <comments> to 1.11.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.10.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.10.0
Updating <notifications> ...
Updated <notifications> to 2.9.0
Updating <systemtags> ...
Updated <systemtags> to 1.11.0
Updating <theming> ...
Updated <theming> to 1.12.0
Updating <accessibility> ...
Migrate old user config
 Done
    3/3 [============================] 100%
Updated <accessibility> to 1.7.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.2.0
Updating <dashboard> ...
Updated <dashboard> to 7.1.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.11.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.1.0
Updating <files_rightclick> ...
Updated <files_rightclick> to 1.0.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.10.0
Updating <logreader> ...
Updated <logreader> to 2.6.0
Updating <photos> ...
Updated <photos> to 1.3.0
Updating <privacy> ...
Updated <privacy> to 1.5.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.11.0
Updating <recommendations> ...
Updated <recommendations> to 1.0.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.11.0
Updating <settings> ...
Updated <settings> to 1.3.0
Updating <support> ...
Updated <support> to 1.4.0
Updating <survey_client> ...
Updated <survey_client> to 1.9.0
Updating <text> ...
Updated <text> to 3.2.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.10.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.11.0
Updating <user_status> ...
Updated <user_status> to 1.1.1
Updating <viewer> ...
Updated <viewer> to 1.5.0
Updating <weather_status> ...
Updated <weather_status> to 1.1.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore 
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore 
Checking for update of app dashboard in appstore
Checked for update of app "dashboard" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app nextcloudpi in appstore
Checked for update of app "nextcloudpi" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app photos in appstore
Checked for update of app "photos" in appstore 
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in appstore 
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app support in appstore
Checked for update of app "support" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app text in appstore
Checked for update of app "text" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_status in appstore
Checked for update of app "user_status" in appstore 
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app weather_status in appstore
Checked for update of app "weather_status" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Checking for update of app apporder in appstore
Checked for update of app "apporder" in appstore 
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore 
Checking for update of app deck in appstore
Checked for update of app "deck" in appstore 
Checking for update of app end_to_end_encryption in appstore
Checked for update of app "end_to_end_encryption" in appstore 
Checking for update of app extract in appstore
Checked for update of app "extract" in appstore 
Checking for update of app files_automatedtagging in appstore
Checked for update of app "files_automatedtagging" in appstore 
Checking for update of app groupfolders in appstore
Checked for update of app "groupfolders" in appstore 
Checking for update of app notes in appstore
Checked for update of app "notes" in appstore 
Checking for update of app tasks in appstore
Checked for update of app "tasks" in appstore 
Checking for update of app twofactor_nextcloud_notification in appstore
Checked for update of app "twofactor_nextcloud_notification" in appstore 
Checking for update of app twofactor_totp in appstore
Checked for update of app "twofactor_totp" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Check indices of the share table.
Check indices of the filecache table.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Check columns of the comments table.
Done.
Check primary keys.
Done.
All tables already up to date!
notify_push 0.2.4 installed
notify_push enabled
notify_push already enabled
Module proxy already enabled
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
Considering dependency proxy for proxy_wstunnel:
Module proxy already enabled
Enabling module proxy_wstunnel.
To activate the new configuration, you need to run:
  service apache2 restart
System config value trusted_domains => 3 set to string mydomain.eu
System config value overwrite.cli.url set to string https://mydomain.eu/
System config value trusted_proxies => 11 set to string 127.0.0.1
System config value trusted_proxies => 12 set to string ::1
System config value trusted_proxies => 13 set to string mydomain.eu
System config value trusted_proxies => 14 set to string 77.6.220.222
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
🗴 push server can't connect to the Nextcloud server
  Response from nextcloud is not a number: invalid digit found in string
notify_push setup failed. You are probably behind a proxy
Run 'ncc config:system:set trusted_proxies 15 --value=<proxy_IP>' and then 'ncc notify_push:setup https://<domain>/push to enable
Check https://help.nextcloud.com/tags/ncp for support
Backup stored at /var/www/nextcloud/data/ncp-update-backups/nextcloud-bkp_20210923_1632421521-20.0.12.1.tar.gz
Clean up...

**Comment by svenb1234** [comment]
Systeminfo before updating:

NextCloudPi version | v1.39.13
-- | --
NextCloudPi image | NextCloudPi_docker_01-19-21
distribution | Debian GNU/Linux 10 \n \l
automount | no
USB devices | sda sdb
datadir | /var/www/nextcloud/data
data in SD | yes
data filesystem | ext2/ext3
data disk usage | 944G/2.0T
rootfs usage | 944G/2.0T
swapfile | /var/swap
dbdir | /data/database
Nextcloud check | ok
Nextcloud version | 20.0.12.1
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
HPB service | down
Postfix service | up
internet check | ok
port check 80 | open
port check 443 | open
IP | 172.17.0.3
gateway | 172.17.0.1
interface | eth0

**Comment by svenb1234** [comment]
Actually this did not work completely since using the dynamic DNs domain results in the usage of a self-signed certificate instead of the available letsencrypt one.

**Comment by nachoparker** [comment]
try activating letsencrypt, even if it's already active

**Comment by svenb1234** [comment]
Tried that already. But trying to access via the domain still uses the localhost certificate.

root@nextcloudpi:/# ncc config:system:set trusted_proxies 15 --value=172.17.0.3
System config value trusted_proxies => 15 set to string 172.17.0.3
Running letsencrypt
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/mydomain.eu-0001/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/mydomain.eu-0001/privkey.pem
   Your cert will expire on 2021-12-22. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

System config value trusted_domains => 22 set to string mydomain.eu
System config value trusted_domains => 3 set to string mydomain.eu
System config value overwrite.cli.url set to string https://mydomain.eu/
System config value trusted_proxies => 11 set to string 127.0.0.1
System config value trusted_proxies => 12 set to string ::1
System config value trusted_proxies => 13 set to string mydomain.eu
System config value trusted_proxies => 14 set to string 77.6.220.222
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
✓ push server is running the same version as the app
  configuration saved
enabled letsencrypt
Done. Press any key...

**Comment by svenb1234** [comment]
root@nextcloudpi:/# service apache2 reload
[FAIL] Reloading Apache httpd web server: apache2 failed!
[warn] The apache2 configtest failed. Not doing anything. ... (warning).
Output of config test was:
AH00526: Syntax error on line 5 of /etc/apache2/sites-enabled/ncp.conf:
SSLCertificateFile: file '/etc/letsencrypt/live/yxc.selfhost.eu/fullchain.pem' does not exist or is empty
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by svenb1234** [comment]
root@nextcloudpi:/# ls /etc/letsencrypt/live/mydomain.eu
ls: cannot access '/etc/letsencrypt/live/mydomain.eu': No such file or directory
root@nextcloudpi:/# ls /etc/letsencrypt/live/               
README                mydomain.eu-0001/ 
root@nextcloudpi:/# ls /etc/letsencrypt/live/mydomain.eu-0001/
README         cert.pem       chain.pem      fullchain.pem  privkey.pem

**Comment by svenb1234** [comment]
After adding the -0001 to the docker data folder  etc/apache2/sites-available/ncp.conf it works. The nextcloud.conf did have it already.

Is that sa temporary fix and will be overwritten? If so, how do I fix it permanentely?

**Comment by nachoparker** [comment]
I added some improvements to detect the `-0001`  suffix that some people are seeing lately. Can you update to the latest NCP and try again? just run the following and share output please

```
sudo su
set -x
source /usr/local/etc/ncp-templates/nextcloud.conf.sh
```

**Comment by githubtefo** [comment]
I'm not on docker, but also have to reactivate Let's Encrypt manually and run it after NC21 update to avoid the use of self-signed certificate.
I'm also having the issue
`🗴 push server can't connect to the Nextcloud server
ncpi is not configured as a trusted domain`
I tried to manually add my domain to the trusted list but it seems not working.
Everything seems to be working anyway.
