### ISSUE TITLE
unable to log in from LAN,Trusted domain error

### ISSUE THREAD

**Issue by acavalli67** [nextcloud/nextcloudpi#135]
Hi my name is Andrea,
I've faced this new problem if I try to login form the Lan.
I don't have any problem to log from external connection.....
That's the message:

You are logging on to the server from an untrusted domain.

Contact your system administrator. If you are an administrator of this instance, configure the "trusted_domains" setting in config / config.php. A sample configuration is available in config / config.sample.php.
Depending on your configuration, you can also use the bottom button to make this domain trusted as an administrator.

Pls help me.
Many thanks.

**Comment by nachoparker** [comment]
How are you accessing? ip address? domain name?

**Comment by acavalli67** [comment]
Ip address

**Comment by nachoparker** [comment]
can you post the output of `ip address`?

**Comment by acavalli67** [comment]
I'm so sorry but I don't know how I've to do, it's the first time that I'm using the Raspberry.... :-))

**Comment by nachoparker** [comment]
no worries ^^

have you tried again?

do you have monitor and keyboard connected to the pi?

**Comment by acavalli67** [comment]
yes

**Comment by nachoparker** [comment]
ok, use password `raspberry` and user `pi` to log in, and then tell me the output of this command

```
ip address | grep glo
```

you have tried to connect again, right? it can take some seconds the first time you turn it on

**Comment by acavalli67** [comment]
inet 192.168.1.111/24 brd 192.168.1.255 scope global eth0
inet 192.168.1.103/24 brd 192.168.1.255 scope global secondary eth0

**Comment by nachoparker** [comment]
have you done any network configuration at all?

**Comment by acavalli67** [comment]
Solved.... was incorrect the script for the network configuration of the fixed IP of Raspberry.....
Many thanks again.
Andrea

**Comment by nachoparker** [comment]
no problem ;)
