### ISSUE TITLE
update is stopped if any running other process name has 'apt' in it

### ISSUE THREAD

**Issue by ChristophRg** [nextcloud/nextcloudpi#1354]
Issue is in update.sh line 56
pgrep apt &>/dev/null && { echo "apt is currently running. Try again later";  exit 1; }

Root cause:
pgrep syntax: pgrep 'options' 'pattern' 
pgrep interpretes 'pattern' as regular expression. If a process e.g. called 'capture' is running the update is stopped. 

Fix:
Whole process name to be checked with option -x. Beside apt also apt-get might be checked.
pgrep -x "apt|apt-get" &>/dev/null && { echo "apt is currently running. Try again later";  exit 1; }

**Comment by nachoparker** [comment]
good catch. Care to send a PR?

**Comment by ChristophRg** [comment]
thanks for taking my first PR that fast!
