### ISSUE TITLE
update to 19.39.19 on debian stretch fails 

### ISSUE THREAD

**Issue by chromoxdor** [nextcloud/nextcloudpi#1355]
_Downloading updates
Performing updates
Installing nc-restore
Running nc-httpsonly
Forcing HTTPS On
System config value overwriteprotocol set to string https
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
Error while applying update 1.40.0. Exiting..._

stretch doesn´t know  "--allow-releaseinfo-change".

**Comment by nachoparker** [comment]
stretch is not supported, only buster
