### ISSUE TITLE
Data folder invalid

### ISSUE THREAD

**Issue by acavalli67** [nextcloud/nextcloudpi#136]
Hi again,
It was  working  perfectly, but this new message....
I did'nt change nothing.
"The data folder is invalid
Make sure there is a .ocdata file in the root of the date folder.
Can not create the "date" folder......"

![img_0183](https://user-images.githubusercontent.com/31183958/29503641-c2cfa3f8-8639-11e7-8dd2-c528590be652.PNG)

Many thanks.
Andrea

**Comment by JimmyKater** [comment]
have you moved your datadirectory to an external device? if so pls check if its mounted properly.

**Comment by acavalli67** [comment]
Solved. Many thanks 
Ciao
Hasta Luego
Bye 
Andrea
