### ISSUE TITLE
Overview Update Button bug

### ISSUE THREAD

**Issue by officeralpha** [nextcloud/nextcloudpi#1361]
Hello,
For me, the update button in the Nextcloud instance itself has been bugged recently. 
Does anyone know how to fix this bug?
Thanks
![Screenshot (590)](https://user-images.githubusercontent.com/90962104/136734256-c13d817f-b7cc-439e-bfdd-a33a3723a253.png)

**Comment by OfficerAlpha** [comment]
Thanks I will try
Oliver V ***@***.***> schrieb am Mo. 11. Okt. 2021 um 08:02:
