### ISSUE TITLE
ncp docker instance startup issues

### ISSUE THREAD

**Issue by sensharma** [nextcloud/nextcloudpi#1376]
**System information**
ncp docker container on RPi4 running Ubuntu server. 

Not sure the first point is a bug but the second definitely seems to be one.

1. The trusted domain does not work with the command mentioned [here](https://ownyourbits.com/2017/11/15/nextcloudpi-dockers-for-x86-and-arm/). It has to be manually changed in the php.config file. The relevant link for this does come up when the initial untrusted domain error appears.
2. Once we get to the first page, there are 2 initial long passwords given. The one for Nextcloud Web Interface does not work. The initial password for the Nextcloud Web Interface is still _ownyourbits_.

**Comment by nachoparker** [comment]
Just tested all of this and it works as intended. The password is not ownyourbits
