### ISSUE TITLE
Improve space usage on screen

### ISSUE THREAD

**Issue by guandalf** [nextcloud/nextcloudpi#1377]
**Description**  
Enlarge the ouput box to use all available space

**Example**  
Often output from commands is not easily visible 'cause the window is small. Just using the whole available space would improve the output display.

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/122050/140499861-2fc2ec28-e90a-4f4c-ad22-e9cc3ed6593b.png">

**Comment by ovpc** [comment]
Ctrl+Shift++ does that for me
Closing this for now, as no one seems interested in implementing this. PR's are welcome tho, and feel free to reopen.
