### ISSUE TITLE
Only 1 trusted_domain is being added, in nextcloudpi even after adding 3 domains

### ISSUE THREAD

**Issue by rmiddle** [nextcloud/nextcloudpi#1379]
**Issue**
Only 1 `trusted_domain` is being added, in **nextcloudpi** even after adding 3 domains.

**Example**
If I add these:
```
Trusted Domain #1: cloud.example.com
Trusted Domain #2: 172.35.0.2
Trusted Domain #3: 192.168.0.2
```
Then only last address is being added to `trusted_domains`,
```
trusted_domains: {
    ...
    22=> 192.168.0.2
    ...
}
```

**Comment by nachoparker** [comment]
that has been fixed already, thanks for reporting
