### ISSUE TITLE
Update to 21.0.5 and 21.0.6

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/nextcloudpi#1383]
Currently NCP is two minor versions behind the official Nextcloud releases.

Not sure what the reasons are but keeping up with upstream stable channel release sounds reasonable.

**Comment by ovpc** [comment]
We have only a few users helping out testing and even less devs to help to implement. 
It is all volunteer work. PR's are very welcome ;-)

I have tested upgrade to 21.0.6 using ncp-config>nc-update-nc manually setting version to 21.0.6
all working good for me on Debian10. 
sudo ncc app:list
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.13.0
  - bookmarks: 10.0.2
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.6
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - music: 1.4.1
  - nextcloud_announcements: 1.10.0
  - nextcloudpi: 0.0.1
  - notes: 4.1.1
  - notifications: 2.9.0
  - notify_push: 0.3.0
  - oauth2: 1.9.0
  - onlyoffice: 7.2.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.2.0
  - theming: 1.12.0
  - timetracker: 0.0.72
  - twofactor_backupcodes: 1.10.0
  - twofactor_gateway: 0.19.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
Disabled:
  - dashboard
  - encryption
  - files_external
  - updatenotification
  - user_ldap
