### ISSUE TITLE
Error Message PHP

### ISSUE THREAD

**Issue by OfficerAlpha** [nextcloud/nextcloudpi#1384]
Hello,
I keep getting the following error message:
[ nc-limits ] (Fri 12 Nov 17:06:09 CET 2021) Using 2984527872B for PHP grep: /etc/php/7.3/fpm/pool.d/www.conf: No such file or directory Using 6 PHP threads sed: can't read /etc/php/7.3/fpm/pool.d/www.conf: No such file or directory sed: can't read /etc/php/7.3/fpm/pool.d/www.conf: No such file or directory Using 944510976 memory for the database

Is this a problem for my Nextcloud or can I ignore it?

**Comment by ovpc** [comment]
Please use help.nextcloud.com
