### ISSUE TITLE
PHP 7.4 (or higher) on NextcloudPi Docker image

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1392]
Currently the Docker image is relying on PHP 7.3 so it will need to be updated to supported PHP 7.4 for use with Nextcloud 21/22.  Full support is available until the release of 24.

- [ ] https://github.com/nextcloud/server/pull/29286

Cheers!

**Comment by nachoparker** [comment]
bullseye comes with php7.4, we can track there #1342
