### ISSUE TITLE
HDD spindown time and ncdatabase/swap

### ISSUE THREAD

**Issue by catfluoride** [nextcloud/nextcloudpi#140]
### Expected behavior

External HDD to go to sleep after 30 minutes when hdparm -S 241 /dev/sda is used in /etc/rc.local

### Actual behaviour

HDD never goes to sleep if ncdatabase and swap file are both on the same external HDD

### Steps to reproduce, from a freshly installed image
Put ncdatabase and swapfile on the external USB HDD to reproduce the isues.

Hi!
First of all, thank you for your work! It works flawlessly and saved me a lot of time trying to putting a working Nextcloud server together on my Raspberrypi 3
I have a question: as I moved both ncdatabase and swap on the same external HDD that I use for ncdata, it seems like the HDD never goes into standby (I issue the appropriate hdparm -S command at boot time from rc.local, to make the HDD go to sleep after 30').
Can you tell me if this behavior is caused by the swap of ncdatabase? Is really the database so busy even when Nextcloud is “at idle” (i.e., not operating on files?). If so, would it be dangerous for the lifespan of the sdcard to move it back?
On the other hand, can this behaviour be caused by the swap file? I guess this is not the case, as the swap file hasn’t be touched anyway until now, but still…
Have you any suggestion to point me inthe right direcction to discover WHY the HDD never goes to sleep?
Please note that on a different "hand-made" owncloud install, with both the database and the swap on the same SDcard, the issue was not present.

Thanks a lot in advance!

**Comment by nachoparker** [comment]
Hi,

Well, the reason that I move everything to the HDD or to RAM is to preserve the flash for longer. 

I really haven't tested the situation you describe, I guess you can try moving the database to the SD card and see if it goes to sleep or not. If it's true that there's constant writing into the database... I guess it could be detrimental for your SD lifespan

I don't think the swap would prevent it from sleeping if it's not being used

Hope it helps, and if you test this, let us know!
