### ISSUE TITLE
Feature request: Photoprism integration for sbc

### ISSUE THREAD

**Issue by jacobkaad01** [nextcloud/nextcloudpi#1407]
I was wondering if it would be possible to have either the ability to easily add other Dockers or have Photoprism preinstalled/configured for SBCs. Ideally this would configure the external access like it does with Nextcloud. Reason I ask specifically for Photoprism is it has complimentary uses with Nextcloud (I know Nextcloud has photos but Photoprism is more in line with a replacement for something like Google photos with Nextcloud being a better Google suite replacement). There by giving us a full house easy setup consumer Google replacement except maybe for easy setup email. If Photoprism is too specific then general Docker support with easy configuration for external/remote access would be great as well. I know there's the docker version of  Nextcloudpi that would work on any OS for docker but I was hoping for something that I just install on an HC1 or Rpi4 and not have to separately configure remote for Photoprism like Nextcloudpi provides for Nextcloud.

Thank you regardless of outcome for the work you do it's very much appreciated.

**Comment by ovpc** [comment]
Photoprism already provides for integration with Nextcloud via WebDav. Althought admit I have not tried to.

![Photoprism-SetWebdav-Screenshot at 2021-12-26 17-52-10](https://user-images.githubusercontent.com/8775469/147415036-12fb2c57-6d10-45f1-a8b5-ce42ec4d6488.png)

Anything is possible, but at what cost; time and effort. 
I use it, and it is so simple with,[ docker compose](https://docs.photoprism.app/getting-started/docker-compose/)  to run Photoprism. 

I'm closing this, anyone can reopen or continue discussion, if wants to take this further though. PR's are most welcome ;-)
I dont see how this relates to NCP or SBC's specifically?
You could request extra features from devs of NC's[ photo app](https://github.com/nextcloud/photos)
