### ISSUE TITLE
Remove Samba from the LXC/LXD build or at least make it optional

### ISSUE THREAD

**Issue by geppi** [nextcloud/nextcloudpi#1416]
**Description**  
In a containerized environment it is most often better to run the file sharing service in a designated container or with KSMBD now available even on the host. Therefore it would be desirable to have the possibility to build the LXC/LXD containers without Samba.

**Background**  
Commit [26edf1f7b0594c4923828e1979cb53f50e5c23a0](https://github.com/nextcloud/nextcloudpi/commit/26edf1f7b0594c4923828e1979cb53f50e5c23a0) did _add LXC/LXD support_ and did make the exclusion of _samba_ depend on the fact that it's a docker build. In _update.sh_ `samba` is only added to the `EXCL_DOCKER` variable when `is_docker` returns _True_ but no check for `is_lxc` is made.

**Request**
Add `samba` to the `EXCL_DOCKER` variable also when `is_lxc` is _True_ or at least provide an environment variable that can be set to exclude _samba_, i.e. something like `WITH_SAMBA` which would be set to _True_ in _install.sh_ if it is not defined in the environment and make the exclusion of _samba_ in _update.sh_ depend on this variable.

**Comment by nachoparker** [comment]
Sorry but we don't have the manpower to fine tune this. You can always uninstall it from your container or disable the service
