### ISSUE TITLE
Wizard USB Configuration Autodetect bug makes Nextcloud unusable

### ISSUE THREAD

**Issue by Beast-Panik** [nextcloud/nextcloudpi#1419]
I installed Nextcloudpi in proxmox and wanted to move the data folder to an external USB SSD. I tried the whole thing with the wizard but it seems to have tried to format the wrong partition without asking. Result is that NextcloudPi no longer starts. 

**Output of the log window**
`[ nc-automount ] (Sun Jan 30 11:16:51 CET 2022)
Created symlink /etc/systemd/system/multi-user.target.wants/nc-automount.service → /lib/systemd/system/nc-automount.service.
Created symlink /etc/systemd/system/multi-user.target.wants/nc-automount-links.service → /lib/systemd/system/nc-automount-links.service.
automount enabled

[ nc-format-USB ] (Sun Jan 30 11:17:03 CET 2022)
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
Error: Partition(s) 1, 5 on /dev/sda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.`

![Screenshot 2022-01-30 at 11-18-28 NextCloudPi Wizard](https://user-images.githubusercontent.com/55361239/151695866-de626efb-57a9-4330-b49e-0c3cc41116c9.png)

**Comment by theCalcaholic** [comment]
Hey @Beast-Panik, thanks for reporting. I pushed a fix for this to devel today. So if you run `ncp-update devel` before formatting the disk, it should be fine now. After some more testing I'll merge it into master.
