### ISSUE TITLE
64bit on Raspberry PI

### ISSUE THREAD

**Issue by ADadlDudlDa** [nextcloud/nextcloudpi#1422]
Raspibian has released the 64 bit version of Rapberry OS:
[https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/)

I request to also to provide a 64bit immage to install on RapberryPI. This should also inclulde 64bit PHP.

**Comment by mbousq** [comment]
it's already 64 bit
