### ISSUE TITLE
Error during first boot on RPi 4 after flashing SD Card: "This board requires newer software"

### ISSUE THREAD

**Issue by wewisch** [nextcloud/nextcloudpi#1425]
Dear Own your bits-team,

i just wanted to set up a new instance of NextCloudPi on a Raspberry Pi 4 Model B after my old one crashed due to a broken SD card and downloaded the latest SD card image from your website (NextCloudPi_RPi_10-08-21). 

After flashing to a new SD Card with Raspberry Pi Imager (Etcher failed several times for some reason) i put the new SD card back into my Pi and tried to boot. I promptly got this error message:

```
start4.elf: is not compatible
This board requires newer software
Get the latest software from https://www.raspberrypi.org/downloads/
```

So a new installation is currently not working on a Raspberry Pi 4.

Thank you for your support and the effort you put into this project the past several years!

**Comment by erase-xcv** [comment]
Hi 

I'm facing the same problem.
Seems that the firmware + kernel on the latest NextCloudPI image are not compatible with the 8 GB Version of the Rasberry Pi 4 Model.

It would be nice if ownyourbits would deliver an updated image :)
Otherwise there are workarounds, but I haven't been able to successfully do it by now.

Let me know if you figure something out.

**Comment by sirdrakeistda** [comment]
There is a workaround:
Download the raspbian or debian 64-bit image and flash it to the SD-card. Then use the following command to install nextcloud
``` curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash ```

**Comment by nachoparker** [comment]
new build coming out this week. Please re-open if this still fails

**Comment by nachoparker** [comment]
ownyourbits.com/downloads/testing

**Comment by wewisch** [comment]
Thank you! New image works fine.
