### ISSUE TITLE
App and TOTP

### ISSUE THREAD

**Issue by acavalli67** [nextcloud/nextcloudpi#143]
Hi,
When you've activated the TOTP, could you connect with the app installed in the IPAD or Android Phone?
Thanks.
Andrea

**Comment by JimmyKater** [comment]
ummm... as i didn't try it i don't really know. but i remember that i read somewhere that there could be problems using totp and clients...

**Comment by nachoparker** [comment]
honestly, haven't tried that myself. Has somebody tried this?

**Comment by escoand** [comment]
Yes, for me this is working.
