### ISSUE TITLE
Extract of NextCloudPi_RPi_03-02-22.tar failed

### ISSUE THREAD

**Issue by MarvvanPal** [nextcloud/nextcloudpi#1441]
I'm not able to extract the NextCloudPi_RPi_03-02-22.tar to get the .img-File

![grafik](https://user-images.githubusercontent.com/79196690/157923276-f8f817c3-9231-4297-918d-a83cf8c297ec.png)
Downloadlink / Source: https://ownyourbits.com/downloads/NextCloudPi_RPi_03-02-22/NextCloudPi_RPi_03-02-22.tar.bz2

MD5 Checksum failed:
![grafik](https://user-images.githubusercontent.com/79196690/157930335-498364db-745c-460b-9566-1c7cbe460546.png)
should be: 5eccfd25cb6b9474e35a75e4ce54107b

Getting the .img-file for Bananapi is possible.

Can someone check the archive NextCloudPi_RPi_03-02-22.tar.bz2 from the mentioned source?

Workaround: Use Torrent via Transmission to get the .tar.bz2.

OS: WIndows 10 21H2
7Zip: 21.07

**Comment by adeekshith** [comment]
I was able to extract it fine but the image does not load on my Raspberry Pi 2B

**Comment by heimwege** [comment]
I have exactly the same issue with the archive

**Comment by Jeanoo** [comment]
Look here  https://help.nextcloud.com/t/impossible-to-write-nextcloudpi-image-3-02-22-to-sd-card/138388/12

**Comment by heimwege** [comment]
Thanks for the quick reply @Jeanoo 
Actually I tried both 7zip (21.07) and winrar (6.11) and none of them worked for me 🙈 
Additionally tried Bandzip because it was mentioned in the link you provided but got the same error.

**Comment by Jeanoo** [comment]
you have to download the file again with the torrent link. The normal download link, it always failed in my pc
