### ISSUE TITLE
nextcloudpi website ist not available

### ISSUE THREAD

**Issue by Marvout** [nextcloud/nextcloudpi#1488]
Sorry to bother, but i cannot reach the nextcloudpi website.
So at the moment i just downloaded nextcloudpi from github,
but anything else doesnt work. Does anyone have the same problems ?

**Comment by tflidd** [comment]
Yes, they work on it: https://github.com/nextcloud/nextcloudpi/issues/1485

**Comment by sunjam** [comment]
Documentation has migrated from the dead `docs.nextcloudpi.com` to the forum.

https://help.nextcloud.com/c/ncpdocs/178

**Comment by ajdste** [comment]
> Documentation has migrated from the dead `docs.nextcloudpi.com` to the forum.
> 
> https://help.nextcloud.com/c/ncpdocs/178

Thanks!  :)
But ...

I just tried there. The only pages resolving For Me are these:
"About" (https://help.nextcloud.com/t/about-the-nextcloudpi-documentation-category/125977)
"Index" (https://help.nextcloud.com/t/index-nextcloudpi-documentation/126448)

The links on the "Index" page brings up this:
"Oops! That page doesn’t exist or is private."

I am signed in on my Nextcloud account.

Anyone have another idea?  :)

**Comment by sunjam** [comment]
> I just tried there. The only pages resolving For Me are these:

Thank you for the feedback.  I'm going through and publishing any pages that are still in private draft.  I'm not finding a lot of them, but happy to correct.  Who are you on the forum?  Truth is no one else has given any feedback yet, so it really helps.  Let me know your username there and I'll add you to the document group if you are okay with that.

**Comment by ajdste** [comment]
Hey Sunjam ~~

Thank you for fixing the NextCloudPi Documentation! It works now.  :)

https://help.nextcloud.com/t/index-nextcloudpi-documentation/126448


Cheers!
aj

**Comment by aadithya96** [comment]
@sunjam It still doesn't work for me. All links either resolve to the FAQ or the "How and where to  get help" section.

**Comment by rababerladuseladim** [comment]
The dead domain is still contained in the Readme and wiki. Should these be updated or donyou want to wait until you have a new hosting solution?

**Comment by theCalcaholic** [comment]
https://www.nextcloudpi.com is now available again. We're working on https://nextcloudpi.com and docs.nextcloudpi.com
