### ISSUE TITLE
I can't run an image of nextcloudpi compiled by myself

### ISSUE THREAD

**Issue by AprentiUnity** [nextcloud/nextcloudpi#1490]
I've just compiled the nextcloupi image for my raspberry pi 4 4go and once I get the raspberry pi and try to connect to it, it tells me it doesn't allow the connection.

**Comment by theCalcaholic** [comment]
Sorry to hear that, but I can't really provide support for that apart from specific questions. However, there have been a few changes that affect the RPI build - maybe you have more luck if you try again :)
