### ISSUE TITLE
Shieldy (Telegram) ban new users by name

### ISSUE THREAD

**Issue by blubclimbs** [nextcloud/nextcloudpi#1493]
There are a bunch of spam bots joining a telegram chat, and I would like to add to the following Shieldy Configuration so that Shieldy automatically boots users with the following emojis in their names or bios: 👙 💦 🔥 🍆 etc. (Is this possible?)
Shieldy Bot Conifguration
Add @shieldy_bot then
Promote to admin
PASTE
/setConfig

shieldyRole: administrator
language: en
captchaType: digits
timeGiven: 60
adminLocked: false
restrict: true
noChannelLinks: false
deleteEntryMessages: false
greetsUsers: false
customCaptchaMessage: false
strict: true
deleteGreetingTime: 0
banUsers: false
deleteEntryOnKick: false
cas: true
underAttack: false
noAttack: false
buttonText: Not set
allowInvitingBots: false
skipOldUsers: false
skipVerifiedUsers: false
restrictTime: 24
banNewTelegramUsers: false
greetingButtons:
Not set

**Comment by theCalcaholic** [comment]
Closed because I am not really certain how we can benefit from this config. If you would like to elaborate on which problem it solves exactly, I'm happy to reopen.
