### ISSUE TITLE
NCPi Panel shows PHP service down after upgrade to v. 8.0.1.8

### ISSUE THREAD

**Issue by Oberlurch3000** [nextcloud/nextcloudpi#1505]
Since updating my NC to php version 8 the NCPi panel shows my php service was down also it isn't.
I came from php version 7.4.
If i take a look in NC admin panel php 8 is activated and used. Just to NCPi doesn't notice.

How to find out why NCPi doesn't get the right infomation about the php service?

Thanks!

**Comment by theCalcaholic** [comment]
The reason for this is, that php 8 is not supported by NCP yet. PHP 8 support will probably added along with NC 24 support.
