### ISSUE TITLE
Question: NextCloudPi on external HDD booting from USB

### ISSUE THREAD

**Issue by elessarelfstar** [nextcloud/nextcloudpi#151]
### What version of NextCloudPi are you using? ( eg: v0.17.2 )
0.24.1

### What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )
NextCloudPi_08-16-17 (but currently up to date)

### Question
I've used the official method to enable boot from USB. I've flashed the NextCloudPi image directly to an external HD and am running straight from that with no sdcard present. All of the functions I use have been running fine (including updating from 0.24.0 to 0.24.1 and updating to the new Raspbian version). I haven't seen anyone else say they were doing this, so just want to see if there are any known reasons that this would be a bad idea for NextCloudPi. Thanks!

**Comment by frank-44** [comment]
I'm also running NextCloudPi without sd-card.
Everything fine.

**Comment by elessarelfstar** [comment]
@frank-44 Good to know. Thanks!

_Sent from my Google Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nachoparker** [comment]
yeah guys, good to know. I haven't even tried that myself ;)

Let us know if there are issues.

**Comment by deljones** [comment]
Interested to loose the SD card for nextcloudpi..Where can I find the HOWTO? 

Dj

**Comment by frank-44** [comment]
I used this description: 

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

**Comment by deljones** [comment]
@frank-44 many thanks.. I have a good working system right now but would love to get it of the SD card for the usual reason… Bit nervous about changing it now.. I’ll have a look at this and probably try with a new setup to see how it goes…

 

Thanks

 

Dj
