### ISSUE TITLE
compress sd card images differently 

### ISSUE THREAD

**Issue by steviehs** [nextcloud/nextcloudpi#1512]
I know I shouldn't but for reasons :-) I use balenaEtcher... and also for piping directly to dd I would suggest to pack the images different:
not the img in a tar.gz but directly gzip, or bzip2 or zip the image:  foo.img.gz and foo.img.bz2 work with balenaEtcher, just tested it. 
Thx!

**Comment by theCalcaholic** [comment]
Thanks for the suggestion.
Images are now zipped :)

https://github.com/nextcloud/nextcloudpi/releases/tag/v1.49.0
