### ISSUE TITLE
Q: Using a subdomain to access my nextcloud instance

### ISSUE THREAD

**Issue by greembow** [nextcloud/nextcloudpi#1523]
Hi there, I'd like to use a subdomain to access the nextcloud instance, but the file /etc/apache2/sites-available/nextcloud.conf has a warning at the top stating not to edit it... How can I make apache serve nextcloud on the cloud.XXXXXX.XXX subdomain using a virtualhost?

**Comment by theCalcaholic** [comment]
Just use the subdomain instead of the base domain in the NCP web panel under `letsencrypt`



![Image](https://user-images.githubusercontent.com/6317548/182552781-aea57581-0e46-411b-969e-509016d707f1.png)
