### ISSUE TITLE
ncp-scan error

### ISSUE THREAD

**Issue by fab1ton** [nextcloud/nextcloudpi#154]
Out of nowhere I am getting the following error. Anybody knows how to fix that?

<img width="953" alt="screen shot 2017-08-23 at 10 35 12 pm" src="https://user-images.githubusercontent.com/31043795/29651085-a0d5403e-8853-11e7-9c33-c080b3b92d9b.png">

**Comment by nachoparker** [comment]
aaah that happened to me once but can't remember right now how I fixed it.

Have you tried rebooting? xD

**Comment by fab1ton** [comment]
Yes, couple of times but unfortunately that didn't help. I also rebooted my router. No success either.

**Comment by nachoparker** [comment]
does that file `<your datadir>/<your username>/files/e848...` exist?

Is your database ok? ( output of `systemctl status mysqld` )

**Comment by Segdon** [comment]
I have the same thing
i want to view the locked files in mysql, but how can i get in?
i have no password for the root user

**Comment by nachoparker** [comment]
@Segdon really? what where you guys doing when it happened?

**Comment by Segdon** [comment]
i think i found the problem
when copying from the disk, it took $RECYCLE.BIN along
i think scan flips on it? -does this sound possible?
deleted it and scan is running

**Comment by nachoparker** [comment]
lol, it is quite possible because in bash and php the dollar sign `$` is a special character
