### ISSUE TITLE
trusted domain detection fails with ipv6

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#156]
From #150

**Comment by nachoparker** [comment]
fixed `v0.24.7`

**Comment by mrkskwsnck** [comment]
I ran into an issue considering IPv6 with a fresh install from the Raspberry Pi image [NextCloudPi_RPi_01-13-19](https://ownyourbits.com/downloads/NextCloudPi_RPi_01-13-19/). The NCP version was 1.4.x something...

The IPv6 of the Raspberry Pi was already added to the trusted domains list. But I needed to surround it with [square brackets] to have an effect, like it is mentioned in the [documentation](https://docs.nextcloud.com/server/15/admin_manual/installation/installation_wizard.html#trusted-domains).

**Comment by nachoparker** [comment]
@mrkskwsnck thanks for the heads up, would you be able to send a PR with this?
