### ISSUE TITLE
Nextcloudpi icon pointing to ownyoursbits.com

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1571]
![image](https://user-images.githubusercontent.com/1787238/192153435-d2eb53f1-b472-4255-bfd7-c2d0bf6fd2c3.png)
Icon re-directing to ownyourbits.com
That path could use a refresh to somewhere else.

docs.nextcloudpi.com
nextcloudpi.com

**Comment by coltkondo** [comment]
I would like to work on this issue, is there any additional info on where the code for this icon is located?

**Comment by theCalcaholic** [comment]
@coltkondo Thanks! Should be in [this file](https://github.com/nextcloud/nextcloudpi/blob/devel/ncp-web/index.php)
