### ISSUE TITLE
Provide docker image for 1.50

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/nextcloudpi#1574]
It would be nice if there was a docker image for v1.50. Currently there is only 1.49.1

**Comment by theCalcaholic** [comment]
Yes, there has been an issue with the deployment pipeline. I'm working on it :)

**Comment by theCalcaholic** [comment]
FYI: Docker images won't be provided for 1.50.0, but the next release (1.50.1) will include them again.

**Comment by sunjam** [comment]
v1.50.1 has been released, but in testing I found #1565 so still figuring out why that is

**Comment by ZendaiOwl** [comment]
@sunjam 
Both of those should be sovled now 🙏 

See closed #1590

**Comment by svenb1234** [comment]
1.50.2 available. Closing.
