### ISSUE TITLE
"Latest" does not pull latest image, but "v1.50.1" does

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1590]
When pulling on docker-compose `ownyourbits/nextcloudpi:latest` fails ala #1577  but `ownyourbits/nextcloud:v1.50.1` succeeds to pull the image.

[Logs](https://bin.disroot.org/?fde083c10537828d#AYtTjXB3dUocYBX9YwmcsowvZYpo9RGvE6xhfCWXP1zK)

Also see #1565 as HPB will not restart after moving to v1.50.1 in my testing

**Comment by ZendaiOwl** [comment]
Should work as shown with my test above :pray:

**Comment by ZendaiOwl** [comment]
I'm re-opening this issue primarily to make it more visible, so users unfamiliar with GitHub have an easier time to locate it and the information above :pray: we can close it again once the docker issues are fully resolved and have calmed down

**Comment by ZendaiOwl** [comment]
I found another issue on that version, wrote to you in Matrix chat

The `:latest` tag is only build using the `amd64` platform tag, use the version itself when pulling from the docker hub to get the correct architecture

**Comment by theCalcaholic** [comment]
@ZendaiOwl Thanks, should be fixed now

**Comment by theCalcaholic** [comment]
I deleted the v1.50.1 release for now
