### ISSUE TITLE
RaspberryPi Image1.50.1 - It's not possible to login as user pi (This account is currently not available)

### ISSUE THREAD

**Issue by noisie86** [nextcloud/nextcloudpi#1595]
Hi all,
after a complete new setup with image 1.50.1 for raspi, it is neither possible to get access via ssh nor to login directly in terminal as pi user.
I use Raspberry Pi 4B 8GB with 32GB flash.

When i tried to login with user pi, system tells "This account is currently not available"

Wrote the image several times new on flash, with previous image version it works!

**Comment by theCalcaholic** [comment]
Yes, the pi user has been disabled for security reasons. Please use the ncp user to login (after activating via https://nextcloudpi.local) :)

**Comment by noisie86** [comment]
Thanks for quick response @theCalcaholic,
but even after activating and using ncp user with generated pw I'm not able to login!
Same reply: "This account is currently not available"

Is there any way to login in terminal to change things like mount devices or other configs?

thanks in advanced.

**Comment by ZendaiOwl** [comment]
I think @theCalcaholic meant that you should use the NCP user to login in the browser. You can configure ssh with the ssh part in the admin web interface and activate ssh for the pi user by changing password, iirc

**Comment by noisie86** [comment]
I'm still not able to login as user pi or ncp, even after activating ssh in the nc panel admin settings.
![grafik](https://user-images.githubusercontent.com/114591695/192878646-4e983fbc-e5b7-4b62-b282-89a405fe201f.png)

Even when I'm trying to connected directly to raspi with monitor and keybord its not possible to login as user pi or any other way ;-(

Steps after first boot after image installation:
-> Activate NCP via https://nextcloudpi.local)https://nextcloudpi.local/ web interface
-> Go through the ncp first installation wizard
-> Activate ssh in ncp network setting (User pi, new password test1234)
-> Reboot raspi

Its a clean new image installation, i am wondering that others dont have this behavior.
No clue what is going wrong there, would appreciate all helpful ideas...

**Comment by theCalcaholic** [comment]
Alright, I'll investigate this. Others don't have this issue, because it was a fairly recent change :)

**Comment by pcomputerhelp** [comment]
On the first boot can't log in as user: pi and password: raspberry. It looks like this <img src="https://ams03pap001files.storage.live.com/y4mqhTl6RcwiEXaajHGdNa-YQrDfLJ1ee6eA20MqhY5u5ZbYZkfhmsvh7TvzNnZwvZZuN-S_GuE203IsnT9_pAjFUrhM36ysSW2ymVqExdBiX3zKmq4extILme7qSAzZcMvsUWlIU4VmOXEHX9IW_Wvv40sdF1Z81J2Lu2ai89xIWY?width=496&height=660&cropmode=none" width="496" height="660" />

**Comment by ZendaiOwl** [comment]
@theCalcaholic 
@pcomputerhelp 

The `pi` user has been set with `/no/login` shell, without any other user to use instead after initial install it seems 🙏

https://help.nextcloud.com/t/nextcloudpi-ssh-enable-not-working-probably/146444/3?u=zendaiowl

**Comment by theCalcaholic** [comment]
> @theCalcaholic @pcomputerhelp
> 
> The `pi` user has been set with `/no/login` shell, without any other user to use instead after initial install it seems pray
> 
> https://help.nextcloud.com/t/nextcloudpi-ssh-enable-not-working-probably/146444/3?u=zendaiowl

Oh :D
That's unfortunate... I'll remove the last two RPI releases until this is fixed

**Comment by ZendaiOwl** [comment]
Good question 🤔 .. could maybe mount the ISO and check /etc/passwd and see. Working today tho, not mistaken this time 😂, so can't really check for a while

**Comment by theCalcaholic** [comment]
> I'm still not able to login as user pi or ncp, even after activating ssh in the nc panel admin settings. ![grafik](https://user-images.githubusercontent.com/114591695/192878646-4e983fbc-e5b7-4b62-b282-89a405fe201f.png)
> 
> Even when I'm trying to connected directly to raspi with monitor and keybord its not possible to login as user pi or any other way ;-(
> 
> Steps after first boot after image installation: -> Activate NCP via https://nextcloudpi.local)https://nextcloudpi.local/ web interface -> Go through the ncp first installation wizard -> Activate ssh in ncp network setting (User pi, new password test1234) -> Reboot raspi
> 
> Its a clean new image installation, i am wondering that others dont have this behavior. No clue what is going wrong there, would appreciate all helpful ideas...

You would need to use user `ncp` in the SSH section. Then you should be able to login as that user

**Comment by theCalcaholic** [comment]
Yeah, I think the actual issue is that the pi user is configured by default in the SSH section on a raspberry pi.

Fix is prepared in https://github.com/nextcloud/nextcloudpi/pull/1604

**Comment by theCalcaholic** [comment]
I added a not on the release page

**Comment by xp1ode** [comment]
I don't mean to hijack the thread but is there a way to fix this? It seems my issue is exactly the same with the added issue that even the NCP account doesn't work. I can't login in through SSH with neither pi nor ncp. I gave up trying with pi after finding this thread yesterday but i have been trying with ncp to no avail. I tried with an install on a pi (tried installing 3 times) and now i moved to a VM install on proxmox. No matter how many times i change the pw through the webui and SSH i cannot get past the "this account is currently not available. Connection to XX.XX.XX closed"

**Comment by nimnananuk** [comment]
@xp1ode If you are also currently setting up your nextcloud, try using the 1.49 image. I just used this one and everything works. In 1.50 I was also not able to add trusted proxies

**Comment by theCalcaholic** [comment]
I'm building a test image with the fix, should be ready in about an hour. Would anyone be willing to test if it resolves the issue?

**Comment by xp1ode** [comment]
I installed with the curl script, i'd be willing to test it out.

**Comment by noisie86** [comment]
I could test it tot...

**Comment by noisie86** [comment]
I could test it too...

**Comment by noisie86** [comment]
@theCalcaholic  pi user works again with test image!
But unfortunately ncp user still cannot be activated. (Yes I activated ncp user in pi panel admin section first!)
![grafik](https://user-images.githubusercontent.com/114591695/193422829-71f9fa9b-0da4-4bf5-b3ad-2a732712d1df.png)

**Comment by ZendaiOwl** [comment]
Could you please confirm by checking the login shell in `/etc/passwd` for `ncp` perhaps? 🙏

It will say `/no/login` if no login shell is configured. 

Ex. `grep ncp /etc/passwd`

**Comment by noisie86** [comment]
Yes /nologin shell is configured for ncp.

**Comment by theCalcaholic** [comment]
@noisie86 Thanks a lot for testing! You can just stay on that image. It will update to the next release like a normal release

**Comment by theCalcaholic** [comment]
@xp1ode Are you sure you enabled ssh in the admin interface for user ncp?

**Comment by noisie86** [comment]
Don’t mention it, happy that guy's like you support and provide stuff like nextcloudpi <3.

**Comment by xp1ode** [comment]
> @xp1ode Are you sure you enabled ssh in the admin interface for user ncp?

Yes i'm very certain of it, I am able to change the pw through the webui but when i log in through SSH, it'll accept the password change but it will automatically log me out with the error message that the account is unavailable .

**Comment by theCalcaholic** [comment]
The fix is now in master and will be included in the image v1.50.3
@xp1ode You can run an update via the web ui and then reapply your SSH settings (for either user). Afterwards, ssh access should work.
