### ISSUE TITLE
Maybe a wrong address in lamp.sh

### ISSUE THREAD

**Issue by csnol** [nextcloud/nextcloudpi#1618]
**System information**

There is a wrong address https://packages.sury.org on line 29-30 in [lamp.sh](https://github.com/nextcloud/nextcloudpi/blob/master/lamp.sh)

``    29      wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg``

``  30      echo "deb https://packages.sury.org/php/ ${RELEASE%-security} main" > /etc/apt/sources.list.d/php.list``

- Needs changed to https://origin.sury.org

``  29      wget -O /etc/apt/trusted.gpg.d/php.gpg https://origin.sury.org/php/apt.gpg``

``    30      echo "deb https://origin.sury.org/php/ ${RELEASE%-security} main" > /etc/apt/sources.list.d/php.list``

Maybe the folder be changed by [sury.org](https://deb.sury.org/)

That's all

**Comment by theCalcaholic** [comment]
The url given by sury is packages.sury.org

Quote from https://deb.sury.org/:

> ### Debian DPA
>
>  [packages.sury.org/php](https://packages.sury.org/php/) – the main PHP repository for Debian
