### ISSUE TITLE
NCP panel says update available to 1.50.3 but the nc-autoupdate-ncp is missing from the left panel

### ISSUE THREAD

**Issue by HenrysCat** [nextcloud/nextcloudpi#1631]
![ncp](https://user-images.githubusercontent.com/47726287/195429501-4887ebc0-b09f-45ae-a41e-6d908ce7822f.jpeg)

**Comment by svenb1234** [comment]
I guess you are using the docker image?

**Comment by theCalcaholic** [comment]
Compare https://github.com/nextcloud/nextcloudpi/issues/1628

Docker needs to be updated by pulling a later image
