### ISSUE TITLE
Unattended-update on Docker

### ISSUE THREAD

**Issue by DanySupernova** [nextcloud/nextcloudpi#1635]
Hi guys, first of all thank you for this great product :)

I have a question: I have used Nextcloudpi in the past and now I have re-installed it on my homeserver via docker

The day after the first installation I found nextcloud dead, I don't remember exactly the problem but among the many attempts I solved it by doing an apt-update and apt-upgrade inside the container.

It started working again but since then once every 2 reboots found password = default inside the file /root/.my.cnf and Nextcloud dead due to no connection to the database

I therefore suspected that the 2 problems were generated by the unattended updates

So I recreated the container from scratch, deactivating unattended-updates and since then, after a week, everything has worked perfectly; this reinforced in me that the problem had been generated by the unattended updates

So my question is: since the docker version does not need to be updated from the inside but from the outside by updating the container (which I set automatically via Watchtower), can I disable unattended-updates or are there any risks?

Thank you very much!

**Comment by DanySupernova** [comment]
Perfect, thank you very much! :)

**Comment by pwright225** [comment]
i have the same issue as the OP, and i found to start from stract properly i had to unlink my data path.  there is apparently some info in there that is being picked up and pointing the fresh install to auto updated php.  probably have to manually move all my files out to another folder, once i am done setting up again, and making sure autoupdates are off, etc etc etc.

**Comment by theCalcaholic** [comment]
@DanySupernova I do not recommend to disable `unattended-upgrades` (as we don't release new containers whenever there are new apache/php packages available), but ncp auto updates should be disabled (and  are not available for recent containers).
`unattended-upgrades` should definitely not replace my.cnf - if that happens again, please let us know!

**Comment by DanySupernova** [comment]
@theCalcaholic 
Sorry, you are right... excuse me. 
The problem Is not unattended-updates, but that at the first boot of the container mariadb is inaccessible, and therefore ncp-provisioning does not work and does not create the random password.

I reinstall all from scratch and I confirm this behaviour.

A docker restart resolves the issue.

I have the same error in the log reported here: https://github.com/nextcloud/nextcloudpi/issues/1127

Mi config Is:
Acer AC100 
Xeon e1260l
16gb RAM
Proxmox VE as Hypervisor
Debian 11 as vm that run the nextcloudpi container

I tried to reinstall Debian vm and nextcloudpi container and the problem returns.

Docker container into a qemu vm Is the problem?

Sorry, thank you very much!

**Comment by theCalcaholic** [comment]
@DanySupernova Are you running ncp with an existing data directory or is it a completely fresh installation? Could you share the full docker run command (or docker-compose file)?

I can't reproduce this issue with a new docker container

**Comment by Itchyfantastico** [comment]
> @DanySupernova I do not recommend to disable `unattended-upgrades` (as we don't release new containers whenever there are new apache/php packages available), but ncp auto updates should be disabled (and are not available for recent containers). `unattended-upgrades` should definitely not replace my.cnf - if that happens again, please let us know!

How come that the documentation says that internal updates should not be done?
[https://help.nextcloud.com/t/staying-up-to-date/126259](url)

Since I recently had to set up a new container because I suddenly couldn't log into Nextcloud anymore, I'm interested in what is the correct behavior now

**Comment by theCalcaholic** [comment]
@Itchyfantastico For recent versions of NCP, anything that you can enable won't break your system. :)
