### ISSUE TITLE
Open ports check fail due to an url change in ncp-diag file

### ISSUE THREAD

**Issue by CarlosCastaneda** [nextcloud/nextcloudpi#1643]
I unintentionally closed Ticket #1641 and cannot open this again. All said in Ticket #1641 is still valid. Hence this new case.

**Comment by ZendaiOwl** [comment]
Fix is in PR below, this issue will be closed automatically when it has been merged

- #1647

**Comment by ZendaiOwl** [comment]
The one above was decided not to be implemented, I've made a new change which I've commented about here: https://github.com/nextcloud/nextcloudpi/issues/1641#issuecomment-1364734088

I'll close this since it's a duplicate of #1641
