### ISSUE TITLE
Nextcloud restore "Invalid origin"

### ISSUE THREAD

**Issue by Jannik44** [nextcloud/nextcloudpi#1654]
![grafik](https://user-images.githubusercontent.com/76906033/200193047-77293db8-f6fe-4bf5-b0fc-0da46a450799.png)

i used the preconfigured docker image and tried to restore from a .tar and .tar.gz file, ~20Gb large, and after a few minutes it starts eating up the ram

**Comment by schoetju** [comment]
Please check the forum.
In best case, this one might be exactly the same?
https://help.nextcloud.com/t/unable-to-restore-from-an-ncp-backup-in-docker/121902
