### ISSUE TITLE
LXC image for Proxmox?

### ISSUE THREAD

**Issue by p-bo** [nextcloud/nextcloudpi#1659]
You're trying to create an LXC container from a LXD image - I don't think that can work...

        I'll send you an LXC image to try

_Originally posted by @theCalcaholic in https://github.com/nextcloud/nextcloudpi/issues/1553#issuecomment-1229234816_

This is confusing a bit because instructions on project webpage are:
![obrazek](https://user-images.githubusercontent.com/12208593/201217635-5f261a70-1b12-41d7-8d87-42964907e62c.png)

**Comment by csiber** [comment]
https://tteck.github.io/Proxmox/

**Comment by ZendaiOwl** [comment]
Updated, so I'm closing this :slightly_smiling_face:
