### ISSUE TITLE
Install XMPP chat server for chat app

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#167]
so the chat app can have federated chat access

**Comment by testbird** [comment]
Ha, ha, missed this issue. Thats how I came to try out making a sdcard from freedombox.org

**Comment by nachoparker** [comment]
we're undecided wether this would be useful/popular to allocate resources to. Opinions are welcome.

**Comment by deljones** [comment]
For me the nextcloudpi has been excellent, I use it every day. I use all of the core service from nextcloud so adding chat, whilst useful for some users, can only eat away at the limited and finite resources of the pi and I would not like to see speed and efficiency compromised...

There are lots of chat clients available that are private and 'off the radar' so to speak so for me leave it out

Just my thoughts

Dj

On 19 October 2017 10:58:23 WEST, nachoparker <notifications@github.com> wrote:
>we're undecided wether this would be useful/popular to allocate
>resources to. Opinions are welcome.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/nextcloudpi/issues/167#issuecomment-337860059

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

+447957140511

**Comment by nachoparker** [comment]
thanks very much @deljones

Keep in mind that if it is not activated from ncp-web it would not consume resources because it would not be running, but it would be preinstalled and preconfigured if somebody wants to activate it.

**Comment by deljones** [comment]
Yep get that but even so tight and tiny works for me for the pi.. :)

Dj

On 19 October 2017 11:07:36 WEST, nachoparker <notifications@github.com> wrote:
>thanks very much @deljones
>
>Keep in mind that if it is not activated from ncp-web it would not
>consume resources because it would not be running, but it would be
>preinstalled and preconfigured if somebody wants to activate it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/nextcloudpi/issues/167#issuecomment-337862348

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

+447957140511

**Comment by nachoparker** [comment]
well, I guess it is a little bit out of scope of NCP. We'll use our limited resources for something else.
