### ISSUE TITLE
lxc import fails Error: Backup is missing index.yaml

### ISSUE THREAD

**Issue by r1ckdu** [nextcloud/nextcloudpi#1700]
**System information**
Intel NUC7CJYH Ubuntu 22.02 LTS

When importing the latest release (lxc import NextcloudPi_LXD_v1.50.5.tar.gz)  the process reports:
Error: Backup is missing index.yaml

How can we get rid of this?

**Comment by ZendaiOwl** [comment]
Could you give it a try with `lxc image import` and see if that works?

**Comment by r1ckdu** [comment]
That does not return an error but lxc list is empty and lxc start ncp reports that the instance does not exist

Jan 14, 2023 00:31:32 Victor-ray, S ***@***.***>:

**Comment by ZendaiOwl** [comment]
`lxc image list images:`

https://www.cyberciti.biz/faq/how-to-list-vm-images-in-lxd-linux-containers/

**Comment by ZendaiOwl** [comment]
I think the commands in the readme are not correct. I'll look into it when I have some time to spare, or if someone else comes along before then and can do it

**Comment by theCalcaholic** [comment]
For reference, this is how we do it in the CICD pipeline:

```sh
lxc image import "NextcloudPi_LXD_v1.50.5.tar.gz" --alias "nextcloudpi"
lxc launch "nextcloudpi" ncp
```

So that *should* work

**Comment by r1ckdu** [comment]
I tried with a bit different naming but yeah it works!

**Comment by r1ckdu** [comment]
after doing the launch one can start it with

`lxc start ncp`

**Comment by ZendaiOwl** [comment]
I've updated the commands on the website and an update for the readme is pending in a pull request so I'm closing this issue
