### ISSUE TITLE
Docker "latest" tag doesn't point to latest image (i.e. 1.51.0)

### ISSUE THREAD

**Issue by BstAA** [nextcloud/nextcloudpi#1712]
Is there is a build-in delay after publishing or another rule?

I.e. this time: 

- V 1.15.0 pushed 16-hours ago Digest: bd642105d6d3
- "latest" pushed 13-day ago. Digest: 0c62dcd79058

**Comment by ZendaiOwl** [comment]
@BstAA @theCalcaholic 

No there isn't a delay, the workflow failed to push the `latest` tag, thank you for letting us know 🙏 for now you can use the `v1.51.0` tag, it should work

**Comment by theCalcaholic** [comment]
Thanks for reporting, I fixed that manually now.
