### ISSUE TITLE
Reverse nc-snapshot-sync

### ISSUE THREAD

**Issue by ttavenard** [nextcloud/nextcloudpi#1722]
I just set up a synchronization of snapshots through the internet via ssh thanks to nc-snapshot-sync and everything works perfectly,
Thank you for all the hard work here!

I am now looking to secure the snapshots that are stored on my backup site a little more.
Indeed, I am not very reassured to have exposed the web and ssh ports on my main site (this is the first time I have done so) and I tell myself that an attacker, if he manages to take control of my main site, could very easily do the same on my backup site thanks to the connection without password set up for nc-snapshot-sync and therefore also delete the backup site snapshots

I am therefore looking to synchronize the snapshots, via a scrip and a crontab, but executed FROM the backup site.

So only the main server would expose the ssh port. The synchronization script will do snapshot **pulls**, rather than **push** from the main

Do you have any idea how to accomplish this?
I thought about how to modify btrfs-sync, but it's out of my skills... :(

Thanks for your help

**Comment by theCalcaholic** [comment]
> erratum, the btrfs-sync script seems to work with an src path wich is over ssh i'm going to test

Yes, the script is able to do that, but it's not possible to configure it for this using the NCP UI, so manual configuration is required.
