### ISSUE TITLE
Stop /etc/resolv.conf from being overwritten on reboot

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/nextcloudpi#1723]
**Description**  
When rebooting NectcloudPi, the `/etc/resolv.conf` file gets overwritten with:

`nameserver 127.0.0.1`

This prevents external network access and prevents DNS from working. Therefore all NextcloudPi features that require an internet connection stop working. I usually have `resolv.conf` that works, set up as:

```
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Suggestion**
Figured this shouldn't be a bug report as it isnt really related to Nextcloud or NextcloudPi. I suggest a setting in the NextcloudPi panel to be added to stop the system from overwriting the `resolv.conf` file. Or adding something to `ncp-config`.

**Current Workaround**
Had to search for a while to get an answer. Not really sure if this should be set like this but the workaround I found is to lock `/etc/resolv.conf/` by using command: `sudo chattr +i /etc/resolv.conf`

**Comment by theCalcaholic** [comment]
Manually editing resolv.conf is generally not advised anymore, afaik, but it depends on the exact system you are running. How are your running ncp?

**Comment by OfficialMuffin** [comment]
It's just the basic NCP installation using the curl script.

**Comment by theCalcaholic** [comment]
@OfficialMuffin In that case, you should use `systemd-resolved` (and it's cli `resolvectl`) to manage DNS resolution
