### ISSUE TITLE
NCP Mastodon Account Access

### ISSUE THREAD

**Issue by michuvon** [nextcloud/nextcloudpi#1725]
NextcloudPi is on Mastodon. https://mastodon.social/@NextCloudPi
However, the account is inactive, and it is unclear who has the account credentials.

Back in 2021 I have tried to find the last known volunteer who run the NCP Mastodon account; however, I was unsuccessful, and sadly, I did a pretty bad job documenting my attempt. The only thing I noted down was the following two users had the credentials at some point in the past:

> REMOVED SENSITIVE VALUES

Anyone knows their usernames here on GitHub?

---

This **issue** is a further attempt to get back access and bring the account back to life. I will document any progress made, and I'm asking for your help as well. Thanks.

**Comment by theCalcaholic** [comment]
Panteleimon Sarantos is @Pant on GH
I don't know what's ShadowStreik's user

**Comment by theCalcaholic** [comment]
Please don't expose users' names on Telegram (because that isn't public data) :)
Sorry for editing the issue.

One of the users you are looking for is @Pant  - I don't know about the other one

**Comment by michuvon** [comment]
https://mastodon.social/@NextCloudPi is back alive.
