### ISSUE TITLE
Icon missing on Nextcloud v25

### ISSUE THREAD

**Issue by kojid0** [nextcloud/nextcloudpi#1734]
Seems like the icon / logo at the left side of the top bar is somehow gone. Fresh install on docker (portainer) with latest versions
![grafik](https://user-images.githubusercontent.com/24477557/219449077-e113440f-c907-4e91-8184-d4872ed30db4.png)

Also on the sign-in page
![grafik](https://user-images.githubusercontent.com/24477557/219449440-20333f6d-6500-4353-996f-068ef27701af.png)

**Comment by Schniefel** [comment]
I jad the same problem

**Comment by REAPERSbattlecry** [comment]
The reason is that the way the logo is used changed.
The logo can be changed at settings > Design > Logo
This was used only for the login page. With NC25 it is used for the login page and the logo in the left upper corner.

**Comment by nenderlein** [comment]
I don't know why, but uninstalling php-imagick / php8.1-imagick also fixed the issue for me.

**Comment by kojid0** [comment]
> The reason is that the way the logo is used changed. The logo can be changed at settings > Design > Logo This was used only for the login page. With NC25 it is used for the login page and the logo in the left upper corner.

Thanks for the information. I just changed the logo by uploading a picture at settings > Design > Logo, then reset the logo to the default. Now I see the correct "original" logo.

I keep the issue open as this is only a workaround.

**Comment by schoetju** [comment]
There has been a similar issue reported as part of nextcloud/server itself
https://github.com/nextcloud/server/issues/35871
so i don't think this is related to Nextcloud**Pi**

**Comment by svenb1234** [comment]
You can just go to the admin's settings in the web ui and reset the logo and background to default, i.e. not ncp.

**Comment by theCalcaholic** [comment]
This should now be fixed in version v1.51.1
