### ISSUE TITLE
Extend default value or make max_allowed_packet configurable

### ISSUE THREAD

**Issue by feutl** [nextcloud/nextcloudpi#1752]
`120611 16:12:30 [Warning] Aborted connection 2619503 to db: 'db_name' user: 'user_name' host: 'webapp_hostname' (Got an error reading communication packets)`

This is the error I was seeing in the logs and had issues with some of the apps in Nextcloud. The problem is the low `max_allowed_packet` value used for mysql/mariadb. I assume it is the default one which is `16MB` and it is too low. It starts raising random error on the contacts web app or syncing files etc.

Based on the documentation, we could simply raise the default setting without problems because the amount does not get pre-occupied.
http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_max_allowed_packet
https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets

For docker setups, the value does not stick after a reboot
Add
```
[mysqld]
max_allowed_packet=256M
```
to `/etc/mysql/mariadb.conf.d/91-ncp.cnf `

and restart the server afterwards `service mariadb --full-restart`

**Comment by theCalcaholic** [comment]
Thanks for the report. Will be fixed in v1.51.2 :)
