### ISSUE TITLE
No apache2 folder in /etc/php8.1

### ISSUE THREAD

**Issue by Oberlurch3000** [nextcloud/nextcloudpi#1756]
First: I'm not sure if this is a bug or a problem. If not I'm sorry to post here.

I've set up a new NC instance on my pi4 via curL install script. I am used to see a apache2 folder in /etc/php/ where I have to set up memory limit and opcache options for php. But the instance is working without this. How/where do I change these values with NCpi if necessary? Currently php memory limit ist set to 768M but I don't know where.

**Comment by theCalcaholic** [comment]
Hi,

You can go to the admin web ui and configure the PHP memory limit through the option `nc-limits`

**Comment by Oberlurch3000** [comment]
Ok, where are those settings stored? I'm just curious.

**Comment by theCalcaholic** [comment]
The ncp web UI settings are stored in `/usr/local/etc/ncp-config.d` (but mostly have no effect when edited by hand). The PHP memory limit itself is configured via config files in `/etc/php/<VERSION>/fpm/`
