### ISSUE TITLE
update NextCloudPi via webGUI

### ISSUE THREAD

**Issue by user-jan** [nextcloud/nextcloudpi#176]
Hi Nacho,

When I try to update NextCloudPi (v0.25.2) via the webGUI it does everything fine until the end when it gives me the message "Something went wrong. Try refreshing the page" and when I try to refresh the page it says "Service Unavailable". When I do the update via ssh & terminal it works fine.

Cheers,
Jan

Here are 2 screenshoots of it:

<img width="1252" alt="screen shot 2017-09-04 at 10 19 14 am" src="https://user-images.githubusercontent.com/31073831/30017835-f43e56ce-915a-11e7-9830-7fe7270fa8ed.png">
<img width="1274" alt="screen shot 2017-09-04 at 10 22 44 am" src="https://user-images.githubusercontent.com/31073831/30017852-041e4072-915b-11e7-9400-70d4788c7239.png">

**Comment by JimmyKater** [comment]
+1 here.

**Comment by nachoparker** [comment]
Hi,

Yes, I noticed and I created a bug #174 

Everything works, but when it finishes it throws that error instead of the green circle.

I'll close as duplicate. Just ignore it for now, is a false alarm

Thanks for reporting ;)

**Comment by user-jan** [comment]
You're welcome ;)

**Comment by nachoparker** [comment]
Actually I am going to reopen, I want to make sure it's a different thing.

BTW jan, I was talking about you the other day at the Nextcloud conference, it will be on video soon ;)

**Comment by JimmyKater** [comment]
could be b/c there might be missing an apache reload or such... at the end. just guessing. not knowing. since running ncp-update from cli works as a problem solver. it occured after 24.3 with me.

**Comment by nachoparker** [comment]
yes, that's exactly when SSE events were introduced.

There's a restart of PHP in the update script, to make the change to the new system, so at this point it can be removed. Unfortunately, it causes that message in the web UI

I think it's just a matter of removing that restart, in any case it has already taken place so it's no longer needed.

**Comment by nachoparker** [comment]
Hi Jan, you were right

Fixed in `v0.26.3`

Thanks for telling us

**Comment by nachoparker** [comment]
@user-jan [my thanks to you in public](https://ownyourbits.com/2017/09/10/nextcloudpi-at-the-nextcloud-conference/)

**Comment by arikalfus** [comment]
Note: this exact error occurred for me for the update to 0.62.2 from 0.60.x (Forget what my previous patch version was).

My guess is because of the change from PHP 7.0 to 7.2.

**Comment by nachoparker** [comment]
probably. That's a harmless thing though. The process went through fine

**Comment by arikalfus** [comment]
Yeah, it failed over the web UI but proceeded fine with `ncp-update` on the box. Didn't see a more relevant issue but wanted to drop that comment for anyone else that would search the issues list for this.
