### ISSUE TITLE
webui is getting packed full - are directories possible?

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/nextcloudpi#177]
hey nacho...

I see progress in NCP. yaaaay. perfect!
thanks for all you're doing for us...

but as now the options on the left side in webui are getting more and more i wonder if it was possible to move some of those options into a folder... 
like freeDNS and no-ip into a directory called DDNS-services?
or nc-notify-updates, nc-webui, nc-news (?), nc-autoupdate-ncp into one called ncp-config? 
and so on

cheers
jimmy

**Comment by nachoparker** [comment]
added to the wishlist

**Comment by nachoparker** [comment]
btw, you can thank @Pant for the freeDNS client ;)

**Comment by JimmyKater** [comment]
i already did. ans saw just now that you told me so... 😸

**Comment by nachoparker** [comment]
this will finally come with the overhaul from #380
