### ISSUE TITLE
Open port check fails because a url is not accesseble

### ISSUE THREAD

**Issue by robgerrit** [nextcloud/nextcloudpi#1783]
The " System Info" page reports ports 80 and 443 are closed. This, while other tools (including https://www.yougetsignal.com/tools/open-ports/) indicate that the ports are open. A small investigation shows that the site https://checkport.zendai.net.eu.org/check referenced in ncp-diag in the browser returns this response: " Error conncecting to checkport.zendai.net.eu.org. PR_CONNECT_RESET_ERROR. 

Output of `sudo ncp-report` -->
[ncp-report230612.txt](https://github.com/nextcloud/nextcloudpi/files/11721107/ncp-report230612.txt)

**Comment by ZendaiOwl** [comment]
Thank you for raising the issue and letting us know

I noticed the issue as well a little earlier and fixed it, it works again for me at least when testing, so it should be resolved.

Can you try again and see if it works for you now?

**Comment by ZendaiOwl** [comment]
Great! I'm glad to hear it's working again for you as well

Since the issue seems to be fully resolved I'm closing this issue
