### ISSUE TITLE
https://docs.nextcloudpi.com/ is not working

### ISSUE THREAD

**Issue by zelgit** [nextcloud/nextcloudpi#1784]
Hi, the documentation is not working properly. The page shows up but it seems it gets stuck on loading the articles. I was excited to try out my first self-hosting but now it's hard without the docs.
Link: https://docs.nextcloudpi.com/

Thanks in advance and for all your precious work!
P.S. I'm sorry if this was the wrong place to create the ticket.

**Comment by theCalcaholic** [comment]
Thanks for the report! I just fixed the site.

**Comment by sunjam** [comment]
#1824
