### ISSUE TITLE
Feature Request: ncp-update should respect memory caching choice

### ISSUE THREAD

**Issue by berbigou** [nextcloud/nextcloudpi#1799]
**Description**  
it seems to me that ncp-update should check if notify_push--Client Push app--Redis is in use in config.php and/or just raise a warning if not.

**Example**  
"Warning: NCP likes Redis server, you should use it !! Messing around with config.php is not recommended !!!"

**Explanations**
Hello, I don't use NCP the right way, I upgraded NC manually to  27.0.1 and I keep using NCP web interface even if it is not the recommended combination (for the fun, for the System-Info-page, for the scripts).
During the execution of ncp-update 1.51.0 to 1.52.0, I encountered an error saying approximatively "Cannot start push_notify, redis not running".
I don't use Redis but an APCu local cache as described in [https://docs.nextcloud.com/server/19/admin_manual/configuration_server/caching_configuration.html]
I traced this error to /usr/local/bin/ncp-update line 45 `/update.sh || exit $?` and then /tmp/ncp-update.XXXXXX/update.sh line 188 `start_notify_push` , commenting this line got the process to run until the end (even if I don't recommend messing with scripts I didn't write myself, and I know it can mess my whole setup).
So, I don't want to bother the devs with my little problems, but it seems to me that ncp-update should check if notify_push--Client Push app--Redis is in use in config.php and/or just raise a warning.

I hope this will help someone.
Thanks for all your work, ncp was my entry-point to my Nextcloud adventure !

**Comment by theCalcaholic** [comment]
Manual configuration like setting up a custom cache is not supported with NCP. That's by design, a necessary limitation to make things easier to automate.
