### ISSUE TITLE
NCP Docker 1.51.5 again shows available ncp-update

### ISSUE THREAD

**Issue by BstAA** [nextcloud/nextcloudpi#1800]
![Screenshot 2023-07-25 155435](https://github.com/nextcloud/nextcloudpi/assets/47305437/0d7b749e-e4ba-4270-b903-d832452f9ef9)

**System information**

See closed [#1778](https://github.com/nextcloud/nextcloudpi/issues/1778)

**Comment by theCalcaholic** [comment]
Oh crap. Thank you for letting me know!

**Comment by theCalcaholic** [comment]
Fixed in v1.51.6
