### ISSUE TITLE
NextcloudPi v1.52.3 offered through ncp-update

### ISSUE THREAD

**Issue by OfficialMuffin** [nextcloud/nextcloudpi#1806]
When SSH'ing into my NCP server, it offers a new update to NextcloudPi, but the GitHub latest version is currenlty `1.52.2`

```
NextCloudPi v1.52.2 is outdated
update to v1.52.3 through 'ncp-config' or type 'sudo ncp-update'
```

**Comment by theCalcaholic** [comment]
Yes, the release process for v1.52.3 is not yet complete. Updates can be installed, images will follow soon

**Comment by OfficialMuffin** [comment]
Has the images been posted? The latest version here is still incorrect.
