### ISSUE TITLE
Nextcloud 27.1 Support

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1810]
For internal testing and notes. Do not expect support!!!!!! Please do report testing issues here.
[Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule)

Beta 1 | 2023-08-10 | feature freeze, base for screenshots for launch marketing
-- | -- | --
Beta 2 | 2023-08-17 |  
Beta 3 | 2023-08-24 |  
RC 1 | 2023-08-31 | string freeze
RC 2 | 2023-09-07 |  
RC 3 | 2023-09-14 | optional
Final | 2023-09-16 |  

[Nextcloud 27.1 Milestones](https://github.com/nextcloud/server/milestone/233)
- #1790

**Comment by schoetju** [comment]
This issue can be closed, since NCP v1.53.0 supports now NC 27.1.3 
(see https://github.com/nextcloud/nextcloudpi/pull/1845 )
