### ISSUE TITLE
NextcloudPi RSS bot not relaying from forum to chat

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1817]
Seems the RSS bot is no longer listed as an admin/mod in NCP general chat on Matrix.  Perhaps this was intentional, but it last relayed from the forum on April 17, 2023.  Unsure of what changed.  :heart: 

`https://help.nextcloud.com/tag/ncp.rss`

**Comment by schoetju** [comment]
Relay of NCP forum to Matrix-Chat is working again since some weeks (not sure, why... or who brought it back).
Anyway - issue can be closed.
