### ISSUE TITLE
Wrong size for big folders

### ISSUE THREAD

**Issue by rottw75** [nextcloud/nextcloudpi#182]
### What version of NextCloudPi are you using? ( eg: v0.17.2 )
v0.26.6
### What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )
NextCloudPi_08-20-17
### Expected behavior
Web UI to show correct user quota
Web UI to show correct folder size
### Actual behaviour
When adding folders with big content (I tried 4.5 GB), the content shown for the folder is wrong and the user quota shown on the page is wrong
### Steps to reproduce, from a freshly installed image
I have assigned to a user a quota of 200 GB on an external USB disk.
I copy from an NFS mount some big folders (4.5 GB) into the nextcloud data folder for that user
I fix ownersip/group to www-data
I run the scan file from the NCPi web admin page, no errors on screen
Check the user web page:
the used size is wrong (expected 5.5 GB, says 1.9)
the user quota is wrong (expected 200 GB, says 196)
the folder size is wrong (expected 5,5 GB, says 0.7)
![screenshot from 2017-09-05 06-25-22](https://user-images.githubusercontent.com/31643199/30046167-e37e0efc-9208-11e7-91e0-5aea29a54593.png)
![screenshot from 2017-09-05 06-24-49](https://user-images.githubusercontent.com/31643199/30046168-e3814504-9208-11e7-8502-6427a4a2c7d7.png)
![screenshot from 2017-09-05 06-09-37](https://user-images.githubusercontent.com/31643199/30046169-e3819ae0-9208-11e7-9276-31c911a70826.png)

### Include logs
<details>
<summary>Nextcloud logs</summary>

Level | App | Message | Time
-- | -- | -- | --
Error | index | OCP\Files\NotFoundException: | 2017-09-05T06:58:56+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css.gzip because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:56+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css.deps because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:56+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:56+0200
Error | index | OCP\Files\NotFoundException: | 2017-09-05T06:58:14+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css.gzip because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:14+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css.deps because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:14+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/css/theming/06e729704af0add597048a63e3bc9cb9-theming.css because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T06:58:14+0200
Error | index | OCP\Files\NotFoundException: | 2017-09-05T05:50:16+0200
Error | PHP | touch(): Unable to create file /nextcloud/data/appdata_ocl1ces56tzv/theming/9/icon-core-filetypes_text.svg because No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#199 | 2017-09-05T05:50:16+0200
Warning | core | Trusted domain error. "193.63.58.83" tried to access using "87.4.28.109" as host. | 2017-09-05T05:01:01+0200
Error | PHP | file_get_contents(/nextcloud/data/appdata_ocl1ces56tzv/theming/images/background): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#209 | 2017-09-04T23:09:55+0200
Warning | core | Login failed: 'mauro' (Remote IP: '82.54.105.254') | 2017-09-04T22:43:26+0200
Warning | core | Trusted domain error. "193.205.213.82" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T17:17:06+0200
Error | PHP | OC\HintException: Memcache OCMemcacheAPCu not available for local cache at /var/www/nextcloud/lib/private/Memcache/Factory.php#96 | 2017-09-04T15:53:40+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:12+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:12+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:07+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:51:00+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:57+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:57+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:57+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:57+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:57+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:56+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:51+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:51+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:50+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:50+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:50+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:49+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:32+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:31+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:31+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:31+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:31+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:28+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:24+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:23+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:22+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:22+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:22+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:21+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:21+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:21+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:21+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:20+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:20+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:18+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:18+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:18+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:17+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:17+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:17+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:16+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:16+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:16+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:15+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:15+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:15+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:15+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:14+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:14+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:50:14+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:50+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:49+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:43+0200
Warning | core | Login failed: 'admin' (Remote IP: '193.205.213.82') | 2017-09-04T14:49:43+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:42+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:27+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:49:26+0200
Warning | core | Trusted domain error. "193.205.213.82" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T14:37:27+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:37:27+0200
Warning | core | Trusted domain error. "193.205.213.82" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T14:37:27+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T14:37:27+0200
Warning | core | Trusted domain error. "60.191.38.77" tried to access using "82.54.105.254:443" as host. | 2017-09-04T11:26:01+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T11:26:01+0200
Warning | core | Trusted domain error. "118.193.31.222" tried to access using "82.54.105.254:443" as host. | 2017-09-04T10:38:29+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T10:38:29+0200
Warning | core | Trusted domain error. "193.205.210.41" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T08:58:07+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T08:58:07+0200
Warning | core | Trusted domain error. "193.205.210.41" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T08:58:06+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T08:58:06+0200
Warning | core | Trusted domain error. "82.54.105.254" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T07:25:52+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T07:25:52+0200
Warning | core | Trusted domain error. "82.54.105.254" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T07:25:52+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T07:25:52+0200
Warning | core | Trusted domain error. "82.54.105.254" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T07:24:49+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T07:24:49+0200
Warning | core | Trusted domain error. "82.54.105.254" tried to access using "mfgehueller.hopto.org" as host. | 2017-09-04T07:24:47+0200
Warning | no app in context | Temporary directory /nextcloud/tmp is not present or writable | 2017-09-04T07:24:47+0200
Fatal | cron | An exception occurred while executing 'UPDATE `oc_jobs` SET `reserved_at` = '0' WHERE `id` = ?' with params ["10"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2017-09-04T06:30:11+0200
Error | core | Error while running background job (Doctrine\DBAL\Exception\DriverException): An exception occurred while executing 'UPDATE `oc_jobs` SET `execution_duration` = ? WHERE `id` = ?' with params [3, "10"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2017-09-04T06:30:11+0200
Error | files | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT s.*, `f`.`fileid`, `f`.`path`, `f`.`permissions` as `f_permissions`, `f`.`storage`, `f`.`path_hash`, `f`.`parent` as `f_parent`, `f`.`name`, `f`.`mimetype`, `f`.`mimepart`, `f`.`size`, `f`.`mtime`, `f`.`storage_mtime`, `f`.`encrypted`, `f`.`unencrypted_size`, `f`.`etag`, `f`.`checksum`, `st`.`id` AS `storage_string_id` FROM `oc_share` s LEFT JOIN `oc_filecache` f ON `s`.`file_source` = `f`.`fileid` LEFT JOIN `oc_storages` st ON `f`.`storage` = `st`.`numeric_id` WHERE (`share_type` = ?) AND (`share_with` = ?) AND ((`item_type` = ?) OR (`item_type` = ?)) ORDER BY `s`.`id` ASC LIMIT 18446744073709551615 OFFSET 0' with params [0, "admin", "file", "folder"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away | 2017-09-04T06:30:11+0200
Error | PHP | Error while sending QUERY packet. PID=1583 at /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91 | 2017-09-04T06:30:08+0200

Login as admin user into your Nextcloud and copy here the logs from
https://example.com/index.php/settings/admin/logging

If you don't have access to the web interface, open a terminal session and paste the last 100 lines of /var/www/nextcloud/data/nextcloud.log
```
</details>
<details>
<summary>Apache logs</summary>

```
Paste the output of `systemctl status apache2`
Paste the output of `tail -n 100 /var/log/apache2/*.log`
apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: active (running) (Result: exit-code) since Mon 2017-09-04 17:33:59 CEST; 13h ago
  Process: 31955 ExecReload=/usr/sbin/apachectl graceful (code=exited, status=1/FAILURE)
  Process: 539 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 664 (apache2)
   CGroup: /system.slice/apache2.service
           ├─664 /usr/sbin/apache2 -k start
           ├─665 /usr/sbin/apache2 -k start
           └─666 /usr/sbin/apache2 -k start

set 04 17:33:59 mauro-pi apachectl[539]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'Serve
set 04 17:33:59 mauro-pi systemd[1]: Started The Apache HTTP Server.
set 05 06:25:02 mauro-pi systemd[1]: Reloading The Apache HTTP Server.
set 05 06:25:02 mauro-pi apachectl[31955]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'Ser
set 05 06:25:02 mauro-pi apachectl[31955]: (2)No such file or directory: AH02291: Cannot access directory '/var/www/nextcloud/data/' for error log of vhost defin
set 05 06:25:02 mauro-pi apachectl[31955]: AH00014: Configuration check failed
set 05 06:25:02 mauro-pi apachectl[31955]: Action 'graceful' failed.
set 05 06:25:02 mauro-pi apachectl[31955]: The Apache error log may have more information.
set 05 06:25:03 mauro-pi systemd[1]: apache2.service: Control process exited, code=exited status=1
set 05 06:25:03 mauro-pi systemd[1]: Reload failed for The Apache HTTP Server.

</details>
<details>
<summary>mariaDB logs</summary>
Paste the output of `systemctl status mysqld`
 mariadb.service - MariaDB database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-09-04 20:01:31 CEST; 11h ago
  Process: 4379 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 4376 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
  Process: 4346 ExecStartPre=/bin/sleep 10 (code=exited, status=0/SUCCESS)
  Process: 4248 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environmen
  Process: 4244 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 4241 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 4349 (mysqld)
   Status: "Taking your SQL requests now..."
   CGroup: /system.slice/mariadb.service
           └─4349 /usr/sbin/mysqld

set 04 20:01:18 mauro-pi systemd[1]: Starting MariaDB database server...
set 04 20:01:30 mauro-pi mysqld[4349]: 2017-09-04 20:01:30 1989152768 [Note] /usr/sbin/mysqld (mysqld 10.1.23-MariaDB-9+deb9u1) starting as process 4349 ...
set 04 20:01:31 mauro-pi systemd[1]: Started MariaDB database server.

```
</details>

**Comment by JimmyKater** [comment]
it's clearly a problem of nextcloud not of nextcloudpi.
pls refer to https://help.nextcloud.com/t/update-12-size-of-cloud-data-wrongly-displayed/19370 
and/or here https://help.nextcloud.com/t/files-folders-wrong-or-pending-size/14133

**Comment by nachoparker** [comment]
Hello,

Yes, like says it is a known issue of the NC server. I will mark as external bug. You can try applying the correction manually if you want.

Thanks @JimmyKater
