### ISSUE TITLE
The PHP module "imagick" is not enabled although the theming app is. For favicon generation to work correctly, you need to install and enable this module.

### ISSUE THREAD

**Issue by janvlug** [nextcloud/nextcloudpi#1821]
**Description**  
I get this message in Security & setup warnings:
"The PHP module "imagick" is not enabled although the theming app is. For favicon generation to work correctly, you need to install and enable this module."

Please provide a default configuration where the PHP module "imagick" is enabled by default.

**Comment by theCalcaholic** [comment]
The imagick module is disabled, because imagick is plagued by security issues. Enable at your own risk

**Comment by piiskop** [comment]
Why are we getting the warning message then?
