### ISSUE TITLE
docs.nextcloudpi.com does not load articles 

### ISSUE THREAD

**Issue by gooseyman** [nextcloud/nextcloudpi#1824]
[docs.nextcloudpi.com ](https://docs.nextcloudpi.com/) does not load the articles (documents). See the screenshot below. 

I have tried a few different browsers and computers. 

![image](https://github.com/nextcloud/nextcloudpi/assets/46906376/8b68dfc4-0637-414a-b56d-f98d3516d3d3)

**Comment by relaxmax68** [comment]
same problem here

**Comment by sunjam** [comment]
Working for me.

**Comment by theCalcaholic** [comment]
Yeah, the issue should be fixed now :)
