### ISSUE TITLE
Link to Helper Script Wrong

### ISSUE THREAD

**Issue by rocket-plane** [nextcloud/nextcloudpi#1834]
Hi,

on the website [https://nextcloudpi.com/](https://nextcloudpi.com/) under LXD/LXC it says, that I should call
`bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi-v5.sh)"`
for proxmox installation. But that link results in a 404: [https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi-v5.sh](https://github.com/tteck/Proxmox/raw/main/ct/nextcloudpi-v5.sh)
It would be nice if this would be fixed.

**Comment by theCalcaholic** [comment]
Thank you for the heads-up. That's outdated, you can now just use the official LXC container from https://github.com/nextcloud/nextcloudpi/releases to install NCP on Proxmox

**Comment by theCalcaholic** [comment]
I fixed the link and added the documentation for the LXC image installation method
