### ISSUE TITLE
Add Orange Pi 5 Plus board

### ISSUE THREAD

**Issue by dedsecproyt** [nextcloud/nextcloudpi#1844]
**Description**  
I need clear image NextCloudPI for Orange Pi 5 Plus

**Example**  
Orange Pi 5 Plus more batter then RPI-5. Orange PI has two 2.5GB ethernet for faster transfer data. more powerfull cpu for hard work or many users. has a lot of ram (up to 32GB). has M.2 SSD and M.2 WIFI slot for easy upgrade. have external 16GB/32GB/64GB/128GB/256GB eMMC module

**Comment by PeterGamma** [comment]
Since Corona we don t trust in Rasbperry Pi anymore. The Orange Pi 5 and the Orange Pi zero 2 w are our alternatives. And we miss a NextCloud image for these SBCs.

**Comment by theCalcaholic** [comment]
There is now a hardware survey for NCP: https://cryptpad.fr/form/#/2/form/view/M7tS0U81qlmc4HsQzrJist5HudbCxBfaN6Zz3HL-tz0/

But yes, Orange Pi 5 support is likely to happen :)

**Comment by PeterGamma** [comment]
This is good news. The Orange Pi 5 is one of the best Rasbperry Pi alternatives so far according to my own little experience. And I would like to avoid to have a stock of Raspberry Pi's in my screed to be save during the next Corona crisis. Support of the Orange Pi 5 would solve this problem.

**Comment by theCalcaholic** [comment]
The Orange Pi 5 and 5 plus are now officially supported as of v1.55.0

**Comment by PeterGamma** [comment]
Thank you, theCalcaholic, I am very happy to hear about that.
