### ISSUE TITLE
Raspnerry PI 5 not working with unofficial power supply

### ISSUE THREAD

**Issue by Aditya-R-K** [nextcloud/nextcloudpi#1863]
**System information**

Using raspberry pi 5 with 5V 3A power supply, I flashed the img file on sd card I connected with ethernet to router,
about 20 minutes it's fan running on fully speed and still haven't connected to router no new devices in router
img version 
NextCloudPi_RaspberryPi_v1.53.0.zip

**Comment by m-breitbach** [comment]
Raspberry Pi 5 requires Debian 12 (Bookworm) which is not yet supported by NextcloudPi. See #1730. #

**Comment by theCalcaholic** [comment]
See #1832
