### ISSUE TITLE
NCP Docker Image is outdated

### ISSUE THREAD

**Issue by kojid0** [nextcloud/nextcloudpi#1864]
When I pull the latest version of the NCP docker image to my server via `docker pull ownyourbits/nextcloudpi:latest` it's shown that I'm running v1.51.6. It should pull v1.53.0.  Looks like the image is outdated?

**Comment by m-breitbach** [comment]
NextcloudPi for Docker is discontinued since November 2023 (see [this blog post](https://help.nextcloud.com/t/nextcloudpi-planning-to-discontinue-its-docker-version-with-nc-25/158895).)
