### ISSUE TITLE
[IMPORTANT] nc-encrypt will totally brick the entire installation

### ISSUE THREAD

**Issue by Sabering1** [nextcloud/nextcloudpi#1874]
Using the **nc-encrypt** will totally brick the entire installation, rendering everything unusable and unfixable, all the pages will be locked and a ERROR 403 will appear on everysingle page.

To get this error, install ncp the normal way, and enable that feature in the config, everything will be lost.

This feature should be disabled until it can be fixed

**Comment by theCalcaholic** [comment]
This is now fixed as of NCP v1.55.0. encryption processes are daemonized and running in the background independent from the PHP process
