### ISSUE TITLE
How to set radio 0 hard disk backup in nextcloudPI; how to mount different hard disk partitions for different users,

### ISSUE THREAD

**Issue by pythonmanGo** [nextcloud/nextcloudpi#1882]
nextcloudPI as a home document sharing and video sharing center, how to set up the system:
1. How to set radio 0 hard disk backup in nextcloudPI;
2, how to mount different hard disk partitions for different users, as the user's data directory, such as for more users to download movies mounted solid state hard drive, increase speed. Increased reliability for mounting mechanical hard drives with more documentation than price.

thk a lot

**Comment by theCalcaholic** [comment]
Hi,

it sounds like what you are asking are general questions related to Nextcloud and linux server administration. This issue tracker is solely for bugs and feature requests within NextcloudPi. Please ask your questions in the [Nextcloud help forum](https://help.nextcloud.com) instead.
