### ISSUE TITLE
Remove Docker from project about and tags

### ISSUE THREAD

**Issue by janvlug** [nextcloud/nextcloudpi#1890]
According to the README, Docker support has been discontinued.

I think it would be good to remove Docker then also from the project about description and the project tags:

![image](https://github.com/nextcloud/nextcloudpi/assets/5903208/1e1921ac-a481-4d48-9e7b-b739f0d7931d)

**Comment by theCalcaholic** [comment]
Agreed, thanks for the suggestion :)
