### ISSUE TITLE
Add support for Nextcloud 28.0.4

### ISSUE THREAD

**Issue by janvlug** [nextcloud/nextcloudpi#1894]
Nextcloud 28.0.4 is available, please add support for updating to this version.

**Comment by twnl** [comment]
> Nextcloud 28.0.4 is available, please add support for updating to this version.

GitHub has a search function that let's you search for anything related to NC28

https://github.com/nextcloud/nextcloudpi/issues/1790
https://github.com/nextcloud/nextcloudpi/pull/1877

@theCalcaholic @ZendaiOwl I think you can close this.

**Comment by theCalcaholic** [comment]
Support for NC 28.0.4 has been added in 1.53.3
