### ISSUE TITLE
Share link has never been succeed 

### ISSUE THREAD

**Issue by jeffkz** [nextcloud/nextcloudpi#19]
Generating link to share to others will also crash the server. I need to reboot the server to get it back to work. 

Now i turned off the function.

**Comment by nachoparker** [comment]
Hello,

I was just testing this on a fresh nextcloudpi installation, and sharing via link works fine.

What do you men crash the server? Could you provide some logs? What are the steps to reproduce?

Thanks for feedback

**Comment by nachoparker** [comment]
It has been a month. I will close this now.
