### ISSUE TITLE
ncp-web: provide hints to the user

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#191]
Provide suggestions such as 

 - detect that ports are not open
 - suggest to move to external drive
 - use letsencrypt
 - use dnsmasq if necessary

**Comment by Brennii96** [comment]
Revert database to default location would be good as well. I had to start again twice as I had it stored on an external HDD which was turned off by mistake.

**Comment by nachoparker** [comment]
hints are now part of nc-info... they'll make their way to ncp-web
