### ISSUE TITLE
php.ini conflict when updating to 1.54

### ISSUE THREAD

**Issue by janvlug** [nextcloud/nextcloudpi#1919]
I ran from the web interface Update NextCloudPi (nc-update).

After a while, I got this screen:

![2024-05-04_new_version_php_ini_interaction_required](https://github.com/nextcloud/nextcloudpi/assets/5903208/ccdd73ee-781c-45ae-aa82-eef59d0ebc68)

and could not continue in the web interface.

I tried to fix this on the command line.

Here is the diff:

```
jan@nextcloudpi:~ $ diff /usr/lib/php/8.1/php.ini-production /etc/php/8.1/fpm/php.ini
774c774
< ;sys_temp_dir = "/tmp"
---
> sys_temp_dir = /media/nextcloudpi_data/ncdata/data/tmp
851c851
< ;upload_tmp_dir =
---
> upload_tmp_dir = /media/nextcloudpi_data/ncdata/data/tmp
1432,1436d1431
< ; Debian Default Value: 0
< ; This is disabled in the Debian packages due to the strict permissions
< ; on /var/lib/php. Instead, GC is performed through /etc/cron.d/php,
< ; which uses the session.gc_maxlifetime setting. Please, check
< ; /usr/share/doc/php8.2-common/README.Debian.gz for further reference.

```
I decided to keep the original php.ini

**Comment by theCalcaholic** [comment]
Hi, thank you for letting me know. Keeping the original php.ini was the right thing to do. I pushed a fix just now.
