### ISSUE TITLE
RelatedResourceProviderNotFound

### ISSUE THREAD

**Issue by Ste-denko** [nextcloud/nextcloudpi#1945]
Hi All,

I am running NextCloudPi v1.54.2 on RaspberryPi5.

When checking the logs there are plenty of entries with the following error message about RelatedResourceProviderNotFound.

Error message from logs:

`{"reqId":"ZoZcNMfRmfQtQZQ9ZC0IJAAAVQA","level":3,"time":"2024-07-04T08:24:20+00:00","remoteAddr":"x.x.x.x","user":"ncp","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/account?itemId=inwand&resourceType=talk&limit=5&format=json","message":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0","version":"28.0.5.1","exception":{"Exception":"OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":173,"function":"getRelatedResourceProvider","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","line":127,"function":"retrieveRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/apps/related_resources/lib/Controller/ApiController.php","line":108,"function":"getRelatedToItem","class":"OCA\\RelatedResources\\Service\\RelatedService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getRelatedResources","class":"OCA\\RelatedResources\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/related_resources/lib/Service/RelatedService.php","Line":605,"message":"","exception":[],"CustomMessage":"Exception thrown: OCA\\RelatedResources\\Exceptions\\RelatedResourceProviderNotFound"},"id":"668660d1d5591"}`

I do not know what this is about.
I would really appreciate any help or fix for this.
Thank you very much in advance.

Love NextcloudPi!
Cheers

**Comment by theCalcaholic** [comment]
This error seems to be related to [this nextcloud app](https://apps.nextcloud.com/apps/related_resources) and not to NextcloudPi specifically :)
