### ISSUE TITLE
Changed IP - NC Website and 4443 Site wont work anymore

### ISSUE THREAD

**Issue by Phadda** [nextcloud/nextcloudpi#196]
Hello,
i set up the "NextCloudPi v0.26.22" with an IP like 192.168.0.235 and after everything works fine, i changed it my old OC BananPi IP 192.168.0.234 ... After a Reboot i cant access the NC Website also the Config 4443 Website.
Did i must change in some configs the 1st catched IP Address to the new one?

**Comment by nachoparker** [comment]
hi,

from now on, we have decided to move technical questions to the forum so we can benefit of a better environment for discussion.

Please, open a thread [here](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)
