### ISSUE TITLE
Incorrect message while upgrading

### ISSUE THREAD

**Issue by janvlug** [nextcloud/nextcloudpi#1964]
I did an upgrade from 28.0.8 to 28.0.9, and got these messages:

```
Current Nextcloud version 28.0.8
Available Nextcloud version 28.0.9
INFO: You have requested an update to '28.0.7', but a direct update to '28.0.7' cannot be performed, so the latest available version that can be updated to has been selected automatically.
```

The INFO message is incorrect.

Here a screenshot with the same message:

![image](https://github.com/user-attachments/assets/eb2f562a-3c77-4e2f-9f63-5aa91b16477d)

**Comment by theCalcaholic** [comment]
Thabk you, this will be fixed in the next release
