### ISSUE TITLE
Ownership transfer states failed but hasn't

### ISSUE THREAD

**Issue by DanielLBarlow** [nextcloud/nextcloudpi#1966]
Hi,

I have run into what looks like a bug to me. 
I was trasnsferring a folder from one user to another. When I log into the user to accept the trasnfer request and then go back to the other user, it states that the request was denied.

I tested this a coupel times to make sure i wasn't clicking soemthing wrong and confirmed this to be the case.
But even though it says the transfer was the denied, the user that I transffered the folder to, does now have access to that folder and it does not show up on the original person anymore. So it appears the tranfer is working as intended but the notification is not reporting correct;y

My nextcloud version is 28.0.9

I've a slight feeling this might not be the right place for me to post this, so if it is not then my apolgogies. I'm running my instance on a Pi hence my post here

Thanks

**Comment by theCalcaholic** [comment]
You're transferring from within Nextcloud, right? Then, https://github.com/nextcloud/server would be the right place to report it
