### ISSUE TITLE
ncp-web: diagnostics

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#197]
such as: open port detection, free space, mount points...

**Comment by Shadowstreik** [comment]
This is a very good idea.

I use an application from Google Play that may provide a good reference for this ticket. I use it just to peek at a few items such as temperature and memory usage on the SD card. Perhaps, it may be a good reference...

https://play.google.com/store/apps/details?id=de.eidottermihi.raspicheck

**Comment by nachoparker** [comment]
cool, thanks ;)

**Comment by nachoparker** [comment]
we have this now in form of nc-info and ncp-report
