### ISSUE TITLE
Update NCP v1.53.1 to 1.55.1 does not work

### ISSUE THREAD

**Issue by ElHummlo** [nextcloud/nextcloudpi#1976]
I tried to update, but i get the following error:

> Downloading updates
> Performing updates
> Installing template ‘apache2/ncp.conf.sh’…
> ERROR: Site nextcloud does not exist!
> Error while applying update 1.53.1. Exiting…

Any idea how to fix this?

**Comment by Dreistein75** [comment]
why was this closed? Did you solve it? If so: how? I am having exactly the same issue
