### ISSUE TITLE
Install script failing due to private DNS server requirement

### ISSUE THREAD

**Issue by gitarman94** [nextcloud/nextcloudpi#1977]
I may have found an issue with the installer script?  I've got protected DNS, and force all traffic on my network to go through my DNS server, all other traffic gets blocked (for security reasons).  The installer script kept failing saying it couldn't find the raw.githubusercontent.com website, but apt was able to install packages just fine prior to the attempted product install.  After looking at the code, I found the below...

cat <<'EOF' >/etc/systemd/resolved.conf
[Resolve]
DNS=8.8.8.8
FallbackDNS=8.8.4.4
EOF

It appears that you're manually pointing the lxc to google as a valid DNS server to resolve addresses.  In my case, this broke the installer as I'm blocking google DNS (for security/tracking purposes).  I was able to modify the file post failure to point at my DNS server, and then copy/paste the remainder of the script, but this code should probably default to the base system's dns server (or utilize the address that was prompted for during the setup wizard).

**Comment by theCalcaholic** [comment]
Hi, thanks for reporting!
Where exactly did you find this in the code?

**Comment by gitarman94** [comment]
Sorry, it looks like it was an installer script from Proxmox community-scripts, this issue can be closed and I’ll open a ticket with them.

**Comment by theCalcaholic** [comment]
Ah I see. For Proxmox I usually only test the official LXC image, but I have heard good things about the installer from tteck
