### ISSUE TITLE
Nextcloud Version wasn't updated through nc-update

### ISSUE THREAD

**Issue by GHoeher** [nextcloud/nextcloudpi#198]
### QUESTIONS
I just detected that, if I logon to my NextCloud webpage as admin, my NextCloupPi installation states that NextCloud 12.0.2 is available although im running the latest version of NextCloudPI.
I thought, NextCloud was updated to 12.0.2 in v0.22.0 of NextCloudPi?!?
Any idea what's wrong? Or did I missed a configuration step?

On the webpage, I see:
`Version`
`12.0.1`
`A new version is available: Nextcloud 12.0.2  <Open Updater>`

`Update channel: stable`

`You can always update to a newer version / experimental channel. But you can never downgrade to a more stable channel. Note that after a new release it can take some time before it shows up here. We roll out new versions spread out over time to our users and sometimes skip a version when issues are found.`

### What version of NextCloudPi are you using? ( eg: v0.17.2 )
v0.26.27
### What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )
NextCloudPI_07-29-17 upgraded to Strech and now v0.26.27

**Comment by nachoparker** [comment]
hi,

`nc-update` only updates NextCloudPi related stuff. In order to upgrade the Nextcloud instance itself you should do it through the internal updater (in admin section of NC)
