### ISSUE TITLE
Redis errors

### ISSUE THREAD

**Issue by musklor** [nextcloud/nextcloudpi#1987]
Hi,
I have installed nextcloudpi LXC with helper script. (Proxmox up to date)
Redis seems to be broken.

[no app in context] Erreur: Connection lost
	de ? par -- à 27 sept. 2024, 19:19:02

[no app in context] Fatal: Could not boot workflowengine: Redis server /var/run/redis/redis.sock:0 went away
	de ? par -- à 27 sept. 2024, 18:56:29

[serverinfo] Fatal: Error during app loading: Redis server /var/run/redis/redis.sock:0 went away
	de ? par -- à 27 sept. 2024, 18:56:29

**Comment by theCalcaholic** [comment]
Yes, that's unfortunately an upstream bug. See #1940
