### ISSUE TITLE
[Pi5] add SSD / M.2 support (dtparam)

### ISSUE THREAD

**Issue by Bingo2023** [nextcloud/nextcloudpi#2006]
In Raspbian this can be done by:

Raspbian:
/boot/firmware/config.txt    -> add line "dtparam=pciex1"
(-> check various sources in web)

This is not working in Armbian.
I'd like to boot from a M.2 SSD (Pi5 with extension head).

Can this be done already or do we need a new feature to support SSD ?

**Comment by theCalcaholic** [comment]
According to this post:
 https://forum.armbian.com/topic/26136-guide-how-to-boot-orange-pi-5-from-sata-m2-ssd-for-orange-pi-os-and-armbian/

it seems to work out of the box with NVME M2 SSDs, but requires a custom bootloader for SATA M2 SSDs.
