### ISSUE TITLE
PHP 8.0 reaches EOL 11/26

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#2009]
Related to
- #2008 
- https://github.com/nextcloud/server/issues/40636

Unsure if this is already resolved, but just want to point out the window is closing for the server supporting 8.0 moving forward. Cheers!

**Comment by theCalcaholic** [comment]
Thanks for the heads up! NCP already supports PHP 8.3 though (and auto upgrades along with Nextcloud)
