### ISSUE TITLE
Backup of config/data/database?

### ISSUE THREAD

**Issue by bernhardhohensinn** [nextcloud/nextcloudpi#202]
First I have to say, that I use Nextcloudpi since a few days and I am impressed how easy it is to install and configure.
Thanks very much for the work!!!
Is it possible to restore only the config-/data-folder as well as the database with nc-restore?
If not, I would appreciate, if that would be made possible.

Bernhard

**Comment by nachoparker** [comment]
hi,

I didn't understand very well your question. what do you mean with "Is it possible to restore only the config-/data-folder as well as the database"?

In any case, see the following copy/paste

Thanks

---

from now on, we have decided to move technical questions to the forum so we can benefit from a better environment for discussion.

Please, open a thread [here](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)
