### ISSUE TITLE
ownyourbits.com down, where to download the IMG file ?

### ISSUE THREAD

**Issue by Larsene** [nextcloud/nextcloudpi#206]
Hi,

where can i download the Raspberry IMG for nextcloudpi as https://ownyourbits.com is down ?

**Comment by nachoparker** [comment]
I have contacted support. Hopefully it will be up soon again.

Please, use the forums in the future for this kind of question 

---

from now on, we have decided to move technical questions to the forum so we can benefit from a better environment for discussion.

Please, open a thread [here](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)

**Comment by feutl** [comment]
it happened again :)
Own your bits is down!!!
