### ISSUE TITLE
Can not connect to NextCloudPi

### ISSUE THREAD

**Issue by RalfJahns** [nextcloud/nextcloudpi#21]
I installed NextCloudPi but when I open the IP of the the Pi in the browser (from PC in local LAN or with browser on my mobile phone (not connected to WLAN)), it gives me the following message:

![grafik](https://cloud.githubusercontent.com/assets/15796653/26777691/722c0e42-49de-11e7-8ede-fe4f2fa865c3.png)

Translation from german by me and my english is not that good:

You access the server from a not trusted domain.

Please contact your administrator. If you are the Administrator of this instance, configure the “trusted_domains”-setting in config/config.php. A sample configuration …
If your configuration allows, as administrator you can use the following button, to set this domain as a trusted domain.

I don’t understand that, so I clicked the button.

Then my firefox complains that it can not connect!?
The browser shows the following URL:
https://localhost/index.php/settings/admin?trustDomain=nextcloudpi

Don't understand why it shows "localhost"?!?

Let's encrypt worked:
Launching letsencrypt
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for **********.dyndns.org
Waiting for verification...
Cleaning up challenges
Deploying Certificate for **********.dyndns.org to VirtualHost /etc/apache2/sites-available/nextcloud.conf
Adding Strict-Transport-Security header to ssl vhost in /etc/apache2/sites-available/nextcloud.conf

-------------------------------------------------------------------------------
Congratulations! You have successfully enabled https://**********.dyndns.org

You should test your configuration at:
https://www.ssllabs.com/ssltest/analyze.html?d=**********.dyndns.org
-------------------------------------------------------------------------------

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/**********.dyndns.org/fullchain.pem. Your
   cert will expire on 2017-09-03. To obtain a new or tweaked version
   of this certificate in the future, simply run letsencrypt-auto
   again with the "certonly" option. To non-interactively renew *all*
   of your certificates, run "letsencrypt-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

Done. Press any key...

**Comment by nachoparker** [comment]
Hello,
Thanks for the feedback.

It seems like you are using DynDNS. Is that right?
Did you use your DynDNS domain in `letsencrypt` in `nextcloudpi-config`?
Did you *NOT* activate `dnsmasq` from `nextcloudpi-config`?

If all of the above is correct, I think I know what is happening. Please confirm.

**Comment by nachoparker** [comment]
I have included a fix for this use case. Please, update to v0.12.16 with `sudo ncp-update` and retry.

I'll now close this. Feel free to reopen if the problem persists

**Comment by RalfJahns** [comment]
Huge thank you for your quick action. Unfortunately I still have exactly the same problem :-(

You asked if I used my DynDNS domain in letsencrypt and that is exactly what I did. You also asked if I activated dnsmasq and I didn't do it.

One more thing: When I access my raspberry from the local LAN, my browser shows this URL: https://nextcloudpi/index.php because nextcloudpi is the network device name of my raspberry. And this is exactly the domain, that is shown in the screenshot above (the one I could add as a trusted domain by pressing the button). When I try to access the raspberry from outside (mobile phone without WLAN) I use the URL https://**********.dyndns.org and then the button (in the screenshort) shows exactly this URL as the untrusted domain that I could add.

Google took me to a few sites, that told me I should add something to the trusted_domains section in the config.php but I don't want to break your fine distribution by doing modifications I don't really understand.

**Comment by nachoparker** [comment]
I recommend that you use *****.dyndns.org from inside your house as well. It is the most convenient setup, for instance to tell your Android apps how to access your cloud independently of wether you are at home or outside.

You can do this from `sudo nextcloudpi-config` dnsmasq section.

Read also this https://ownyourbits.com/2017/03/09/dnsmasq-as-dns-cache-server-for-nextcloudpi-and-raspbian/
