### ISSUE TITLE
option to change password

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#210]
with the addition of password authentication to ncp-web (https://github.com/nextcloud/nextcloudpi/issues/132), it would be important to be able to change the default password.

Requirements

 - ask for password in two boxes and check that they are the same
 - then, just call `passwd` for the selected user ( _pi_ by default ). Check not root.

If anybody is up to help, you can check [this developer guide](https://github.com/nextcloud/nextcloudpi/wiki/Developer-guide). It is pretty easy.

**Comment by nachoparker** [comment]
update: this is open for discussion... maybe it is not the best idea to allow this?

**Comment by drolex2** [comment]
How do you currently change the password for ncp-web?

**Comment by nachoparker** [comment]
@drolex2 exactly

**Comment by nachoparker** [comment]
Duplicate of #279
