### ISSUE TITLE
Spotted minor typo

### ISSUE THREAD

**Issue by ObfuscateTheWeb** [nextcloud/nextcloudpi#219]
![typo](https://user-images.githubusercontent.com/22144143/30848196-f00b5b60-a2d0-11e7-8a30-58cd6f2a636b.PNG)

Typo highlighted yellow, I think it was suppose to be authority 
Nothing much, just wanted to point it out

**Comment by nachoparker** [comment]
lol thanks

will fix now

**Comment by ObfuscateTheWeb** [comment]
welcome
