### ISSUE TITLE
Apache doesn't start with ramlogs

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#222]
See https://github.com/nextcloud/nextcloudpi/issues/211#issuecomment-332221028

**Comment by Larsene** [comment]
same issue for me/ Thanks for linking your comment that helps me a lot !

**Comment by nachoparker** [comment]
ok, seems like the automatic update replaced the systemd apache unit. Activating ramlogs again reconfigures it properly.
