### ISSUE TITLE
Nextcloudpi storage problem 12.0.3

### ISSUE THREAD

**Issue by karpaz** [nextcloud/nextcloudpi#225]
1. > Nextcloud version 12.0.3
2. > Nextcloudpi panel v0.30.0
3. > DEVICE: Raspberry 3 type B
4. > MEMORY: Micro SD card (16Gb) class10
5. > Background jobs: Cron

I have problem with storage, i have in Nextcloud, 2 users and both have unlimited Quota. 
Nextcloud show me that i have(admin) 1mb of 375Mb and my next user have 5mb of 374.1Mb total.

My question is what really take nextcloudpi with raspbian OS. I mean size of the nextcloud and OS?

My installed apps is default and `calendar, contacts, news, ocDownloader, Dashboard`

What set in NextCloudPi Panel (webUI) `NC-limits` > `Memorylimit 768M` i changed it to `10G` ,but the total storage is still same.

**Comment by nachoparker** [comment]
Hello,

We no longer use github for questions. Please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for this. It is a better environment for discussion ;)
