### ISSUE TITLE
[question] is there a way to copy contents to your folder locally?

### ISSUE THREAD

**Issue by JVAQUEROM** [nextcloud/nextcloudpi#231]
Thinking about doing a faster first sync, I was considering copying some data to the HDD connecting it to my laptop USB and copying it. Can this be done? Or it would break Nextcloud database or something like that? If it can be done, where exactly is all the files stored?

Thank you!

**Comment by nachoparker** [comment]
hi javier,

please use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for question. It is a better environment for that ;)
