### ISSUE TITLE
fail2ban email notifications

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#232]
make it so you receive notifications from attempts or blocks

**Comment by HrJosch** [comment]
Am I assuming right, that it's simply necessary to rerun ncp-fail2ban, to receive email about abandoned attempts?

**Comment by nachoparker** [comment]
I still haven't had a look at it. I don't know if it is possible to configure fail2ban to send emails or how that works. I don't think that comes enabled by default, maybe it sends emails to root in `/var/mail` out of the box? 

I don't know.

**Comment by nachoparker** [comment]
Implemented `v0.31.12`
