### ISSUE TITLE
can't log in via NCP Web

### ISSUE THREAD

**Issue by user-jan** [nextcloud/nextcloudpi#236]
Hi Nacho,
I recently updated to the latest version and when I try to call up the NCP WEB GUI it presents me with the following dialogue:

<img width="632" alt="screen shot 2017-10-02 at 7 12 46 pm" src="https://user-images.githubusercontent.com/31073831/31089821-bf48a184-a7a5-11e7-9656-af1868606b5c.png">

Now, when I try to input my current password it won't accept it...

Best,
Jan

What version of NextCloudPi are you using? ( eg: v0.17.2 )

v0.31.6 

What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )

NextcloudPi_09_03_17 (the command says "untagged" but I keep the downloaded image in my pc).

Expected behavior

Connect to Nextcloud via https://19x.16x.x.x:4443

Actual behaviour

Can't log in

**Comment by nachoparker** [comment]
Hi Jan,

You have to use user `pi` and the password for that user. This is `raspbian` by default, but hopefully you have changed it already ;)

**Comment by user-jan** [comment]
Thanks a lot Nacho for your untiring assistance :-)
