### ISSUE TITLE
nc-wifi: Instructions not consistent with screen flow

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloudpi#238]
### What version of NextCloudPi are you using? ( eg: v0.17.2 )

NextcloudPi Config ver 0.31.0

### What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )

NextCloudPi_09-27-17

The instructions for nc-wifi are not consistent with the screen flow.

Step 1 of the instructions says to choose a wifi network, however, prior to that step, there is another screen that just says `"ACTIVE: no"` and no further instruction to the user. I assume you should enter "yes" here but it's not clear to the user.

![img_20171003_143615](https://user-images.githubusercontent.com/295122/31125582-0582a2a0-a849-11e7-93bd-b260ed6e5161.jpg)

This screen should be mentioned in the instructions as step 1, prior to selecting the wifi network:

![img_20171003_143621](https://user-images.githubusercontent.com/295122/31125583-05affc64-a849-11e7-97f6-3ec811d1cad9.jpg)

### Expected behavior

The steps in the instructions should reflect the actual screenflow.

### Actual behaviour

The first screen after the instruction screen is not listed/mentioned in the instructions.

**Comment by nachoparker** [comment]
That's right, that step was introduced after the instructions were written.

changed it `v0.31.9`

Thanks
