### ISSUE TITLE
nc-wifi: unable to enter wifi network configuration: ValueError: dbus.Boolean(True) is not in list

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloudpi#239]
### What version of NextCloudPi are you using? ( eg: v0.17.2 )

NextcloudPi Config ver 0.31.0

### What is the base image that you installed on the SD card? ( eg: NextCloudPi_07-21-17 )

NextCloudPi_09-27-17

### Expected behavior

I should always be able to enter the configuration of a wifi network via nc-wifi.

### Actual behaviour

Once I configured my wifi network, entered the correct wifi key, I am still having problems connecting. Not sure what's wrong.
Anyway, I have no way to enter the configuration of the wifi network again. When I select the wifi network and hit the right arrow key, I am getting the message below, which only appears for a few milliseconds:

![screenshot_20171003-143452](https://user-images.githubusercontent.com/295122/31125849-1289c3a6-a84a-11e7-95ce-7c6b08d3f6c0.png)

Instead of coming to the wifi configuration screen, I just get a "Done. Press any key" message.

Here is a video / screencast I took: https://www.dropbox.com/s/nm7ss2jfweh5b7w/VID_20171003_143557.mp4?dl=0

### Steps to reproduce, from a freshly installed image

Not sure how to reproduce it regularly. I guess the error message is best to track the issue:

`ValueError: dbus.Boolean(True) is not in list`

### Off-topic 

Apart from the original issue: another thing that came up during this nc-wifi: I think it might be confusing to a regular user to see his network twice but for various channels. For example, my wifi network shows up twice, at channel 6 and channel 11. Of course, for IT admins it's not a problem, but I'm just thinking of keeping it as simple as possible for regular user that just want to choose their wifi network and enter the key, not having to deal or know about wifi network channels. Or maybe just choose the one with the best strength.

**Comment by nachoparker** [comment]
Hi,

Again, thanks for the good feedback.

Unfortunately this is another external bug. The suggestion is also nice, but I suggest you forward it to the `wicd-curses` developers.

The only alternative to those things would be to implement our own wifi picker.

I tried, but I could not reproduce it.
