### ISSUE TITLE
nc-wifi: when in wifi network configuration, "scanning for networks" message gets in the way

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/nextcloudpi#240]
### What version of NextCloudPi are you using?

NextcloudPi Config ver 0.31.0

### What is the base image that you installed on the SD card?

NextCloudPi_09-27-17

### Expected behavior

When I'm in nc-wifi and have selected a wifi network to configure, the network scan (I guess there is a time interval in the background) should pause and not interfere with the user input.

### Actual behaviour

Sometimes in nc-wifi it happens that I select a wifi network to configure (hitting the right-arrow key) and am about to enter wifi password, etc. when the "Scanning for networks" message appears again and brings me back to the network list afterwards, causing all my configuration input that I haven't saved yet to be gone.

**Comment by nachoparker** [comment]
Hi,

Thanks for your feedback. Unfortunately this is a `wicd-curses` issue. I suggest you report this to them.
