### ISSUE TITLE
The nc-backup shows an error about managing access.log

### ISSUE THREAD

**Issue by Larsene** [nextcloud/nextcloudpi#242]
### PROBLEMS

After running nc-backup to generate a backup of the database, there's an error about the access.log file : 

![nextcloudpi](https://user-images.githubusercontent.com/8544729/31171201-21489ca4-a8ff-11e7-8c5f-192501d84ec2.jpg)

### Steps to reproduce, from a freshly installed image

After some use, try to launch the nc-backup script from nextcloudpi-config

**Comment by nachoparker** [comment]
Hi,

The warning about 'file changed as we read it' shouldn't make the thing fail, it is only a warning.

That was fixed for nondata backups but thanks to your report I also fixed it for data backups.

Please, update to `v0.31.11` and try again

Thanks for your feedback

**Comment by Larsene** [comment]
Perfect, it now works whithout any (message) errors.

thanks !
