### ISSUE TITLE
LetsEncrypt set up problems

### ISSUE THREAD

**Issue by fab1ton** [nextcloud/nextcloudpi#244]
I am facing the following issue while setting up letsencrypt:

> Launching letsencrypt
> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Plugins selected: Authenticator apache, Installer apache
> Obtaining a new certificate
> Performing the following challenges:
> tls-sni-01 challenge for fabian-spranger.com
> Error while running apache2ctl graceful.
> httpd not running, trying to start
> Action 'graceful' failed.
> The Apache error log may have more information.
> 
> AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
> (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs
> 
> Cleaning up challenges
> Error while running apache2ctl graceful.
> httpd not running, trying to start
> Action 'graceful' failed.
> The Apache error log may have more information.
> 
> (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs
> 
> Encountered exception during recovery
> Error while running apache2ctl graceful.
> httpd not running, trying to start
> Action 'graceful' failed.
> The Apache error log may have more information.
> 
> (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs
> Traceback (most recent call last):
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
>     self.funcs[-1]()
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 284, in _cleanup_challenges
>     self.auth.cleanup(achalls)
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1910, in cleanup
>     self.restart()
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1799, in restart
>     self._reload()
>   File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1810, in _reload
>     raise errors.MisconfigurationError(str(err))
> MisconfigurationError: Error while running apache2ctl graceful.
> httpd not running, trying to start
> Action 'graceful' failed.
> The Apache error log may have more information.
> 
> (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs
> 
> Error while running apache2ctl graceful.
> httpd not running, trying to start
> Action 'graceful' failed.
> The Apache error log may have more information.
> 
> AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
> (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
> (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs
> 
> Done. Press any key...
> 

If anybody knows how to solve that problem, please let me know.

Much appropriated!

**Comment by nachoparker** [comment]
It seems like you are using the ports for something else, like other web service.

Please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for community support on this (unless we find a bug over there ;) ).
