### ISSUE TITLE
Request: Replicate Google Takeout backups in NextcloudPi

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#250]
[Would it be possible to have backups be handled in a similar fashion to Google Takeout](https://myaccount.google.com/?pli=1), allowing for selectable back up items + a final, singular tar or zip archive containing all of the data?

Example:    
- Show sub-menu of items being backed up or exported (Per App Configurations, Files)
- Show Additional list of items not supported (Installed Apps not yet supported by NextcloudPi backup)
- Time stamps

Why?
For easier migration of data and configurations to additional Nextcloud instances.

**Comment by nachoparker** [comment]
added to the wishlist

**Comment by nachoparker** [comment]
seems a bit out of scope right now, unless somebody wants to take on it
