### ISSUE TITLE
Let's Encrypt issue

### ISSUE THREAD

**Issue by fab1ton** [nextcloud/nextcloudpi#255]
My ports are both open, TCP 80 and 443 which I checked on portchecker.co.

The error I am getting is the following:

Domain: XXXX
   Type:   connection
   Detail: Connection refused

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

Not sure how I can fix that. Like I said my port are both open and I am able to connect to my cloud outside of my network.

Thanks for your help!

**Comment by j-ed** [comment]
Usually I would say that this is a pure RaspberryPi web server configuration problem and not a Nextcloud problem. You should make sure that `http://<yourserver>/.well-known/acme-challenge/` can be accessed from the Internet by the Let's Encrypt servers to be able to verify the generate challenge.

**Comment by Shadowstreik** [comment]
It could, also, be useful to check if your ISP happens to block those ports. Some do. Though, I believe a lot don't. Mine doesn't, luckily.

**Comment by fab1ton** [comment]
I was actually able to fix the problem. All good. Thanks guys!

**Comment by j-ed** [comment]
@fab1ton To allow other users to learn from this issue it would help if you could describe how you solved it instead of only writing `it's ok now` ;-)

**Comment by fab1ton** [comment]
Oh sorry. I am having a DD-WRT which runs OpenVPN. My ports weren’t opened by just forwarding them. I either had to add them manually into the firewall or I excluded my Nextcloud IP from the OpenVPN, which I did. After that I was able to set up Let’s Encrypt.
