### ISSUE TITLE
No internet connectivity

### ISSUE THREAD

**Issue by cryptodigger** [nextcloud/nextcloudpi#257]
I am getting the following issue message once I try to open nextcloudpi-config:

> sudo nextcloudpi-config
> No internet connectivity

This problem is caused by dnsmaq when I add my local IP. Not sure why that is happening..
Is it also possible to add the DNS of my VPN? I dont like to use public dns from google

Thanks for your help!

**Comment by nachoparker** [comment]
hi,

I suggest you use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) in the future for questions like this.

You can use other DNS, yes. Actually I would prefer that everyone uses different from Google, but I use it as a convenient example for users that don't know what they are doing.

Having no internet connectivity is not a problem. It is only that it tries to look for updates if possible. 

Obviously, there must be a network misconfiguration for that to happen.
