### ISSUE TITLE
Where is the "static IP" information stored?

### ISSUE THREAD

**Issue by JVAQUEROM** [nextcloud/nextcloudpi#264]
Hello,

I am recently having problems with ethernet connection. It appears as connected but I certainly cannot connect. I think it may be related to the "Gateway" being set as `0.0.0.0` instead of `192.168.1.1`. I'd like to change the config file that controls that but I don't really know what `nc-static-ip` does.

**Comment by Pant** [comment]
It simply writes some lines to `/etc/dhcpcd.conf`. It gets $GW and $DNS from current dhcp settings.
```
interface eth0
static ip_address=$IP_/24
static routers=$GW
static domain_name_servers=$DNS
```
If you see wrong gateway and DNS IPs, then change them in `/etc/dhcpcd.conf`. Also verify that your interface is eth0. If not change that accordingly at that file too.

Feel free to reopen this issue if problem persists.
