### ISSUE TITLE
32GB SD Card only has 2GB usable - how to resize?

### ISSUE THREAD

**Issue by chapman57** [nextcloud/nextcloudpi#266]
<!--
Platform:
Raspberry Pi 3
SanDisk 32GB Ultra SD Card
NextcloudPi ver 10.xxx 

After installing and getting everything running I immediately ran out of space. My SD card is 32GB but apparently is only formatted for 2GB.

I tried using parted to resize the partition, but resize has been removed from parted.

I searched around and cannot fine any procedure for resizing the partition so I can use the full 32GB.

I found this out when copying files. So I added a USB drive and moved the database and files over to it - but the drive went bad so I had to start from scratch. I am waiting on a new SSD to use for the storage.

Thanks,
Don

**Comment by PunkRa1n** [comment]
sudo raspi-config -> 7 Advanced Options -> A1 Expand Filesystem 
Reboot - Done

**Comment by chapman57** [comment]
Huh - never thought of raspi-config. Is that still there in the nextcloudpi image? Need that option in the nextcloudpi-config utility

Thanks,
Don

**Comment by PunkRa1n** [comment]
Yes, it is. The lastest image (10-02-17) is based on "Raspbian GNU/Linux 9 (stretch)"
You can jump from raspi-config directly to nextcloudpi-config (fist option "0 NextCloudPi Configuration")

If you need more information like Distribution Name, Distribution Release Version, Release Notes, Distribution Codename and Distribution Description...
type:
cat /etc/*-release

**Comment by nachoparker** [comment]
thanks @PunkRa1n 

That is correct. I thought that the filesystem was automatically expanded though. 

At least it was last time I tried

**Comment by nachoparker** [comment]
For technical (or any) questions, please try to use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) in the future ;)

**Comment by chapman57** [comment]
Thanks guys. Worked like a champ. I got the SD card expanded and an external 250GB SSD drive configured and everything moved over.

I am very impressed with what you have here and I can finally pull everything off of dropbox and I have a TON more space!

I wish I could contribute! I do write code, C#, VB.Net and Android - Java  (beginner at Android) but I don't know linux.

**Comment by nachoparker** [comment]
great, that's the idea! make it easy for everyone to host their own stuff.

Well, some contributors with web development skills would be really useful!

Also helping others, testing, reporting are [good ways to help](https://ownyourbits.com/2017/07/07/how-can-you-help-own-your-bits/). You can also have a look at github issues with the tag 'help wanted' to see if they fit you ;)

**Comment by chapman57** [comment]
I'll take a look. :)
