### ISSUE TITLE
Let's encript and collabora

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/nextcloudpi#268]
Hi
I'm trying to put collabora working in my nextcloudpi (ex in ricarcloudx.duckdns.org).
The thing is that i need to have a subdomain to host the collabora (e.x. ofice.ricarcloudx.duckdns.org) which has to have a SSL certificate.

My question is:
If i run the module of let's encript in nextcloudpi-config and put the domain of the collabora host, the previous certificate of nextcloud domain is lost? and if not it will ruin the nextcloud configuration?

Maybe an enhancement of nextcloudpi is to have the abitily to incorporate the collabora right of the box from the image! just a suggestion. I don't know if it's possible but it would be really nice!

thanks

**Comment by nachoparker** [comment]
Hi,

For general questions (not bugs/feature requests) please try to use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) in the future.

> If i run the module of let's encript in nextcloudpi-config and put the domain of the collabora host, the previous certificate of nextcloud domain is lost? and if not it will ruin the nextcloud configuration?

that shouldn't be a problem. Each domain certificate is kept in a different folder under `/etc/letsencrypt`

> Maybe an enhancement of nextcloudpi is to have the abitily to incorporate the collabora right of the box from the image! just a suggestion. I don't know if it's possible but it would be really nice

We have already a request for this, but there are technological challenges and I don't have the time right now to try crosscompiling it #51

cheers!
