### ISSUE TITLE
wiki: backup and restore a NCP instance process

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#269]
It is common for people to want  to migrate to a new Pi or upgrade the base system. 

This would be a nice addition to the wiki

**Comment by ovpc** [comment]
[Backup](https://docs.nextcloud.com/server/12/admin_manual/maintenance/backup.html)
and
[Restore](https://docs.nextcloud.com/server/12/admin_manual/maintenance/restore.html)
are already documented. 
You want a NCP specific step-by-step ?

**Comment by nachoparker** [comment]
well, I was more thinking about the steps using `nc-backup`, `nc-restore`, `nc-import` and `nc-export`

**Comment by ovpc** [comment]
Started [wiki](https://github.com/nextcloud/nextcloudpi/wiki/How-to-backup-and-restore-a-NextCloudPi-instance-using-nextcloudpi-config) and listing screenshots used here for practical purpose only.
![01-backup-nc-instance-to-a-file](https://user-images.githubusercontent.com/8775469/34511790-5bedb6f4-f05e-11e7-9d60-bba86e2c2166.png)
![02-nc-backup-terminal-output](https://user-images.githubusercontent.com/8775469/34511800-664637ac-f05e-11e7-995c-f23e05d143ed.png)
![03-nc-auto-backup-settings](https://user-images.githubusercontent.com/8775469/34511804-692730ac-f05e-11e7-9ab0-f0ad3500d4df.png)
![06-export-ncp-config](https://user-images.githubusercontent.com/8775469/34511805-6b475358-f05e-11e7-84a8-bb9b48995efd.png)
![07-ncp-export-config-set-location](https://user-images.githubusercontent.com/8775469/34511811-72e6c85a-f05e-11e7-803f-bf306a539cf6.png)
![08-export-ncp-config-terminal-output-press-any-key](https://user-images.githubusercontent.com/8775469/34511813-74e6f3aa-f05e-11e7-9b41-40f9535606a9.png)
![10-nc-snapshot-create-btrfs-snapshot-of-the-datadir](https://user-images.githubusercontent.com/8775469/34511814-776e2dfa-f05e-11e7-8b42-fc4ed7a777df.png)
![11-nc-snapshot-warning](https://user-images.githubusercontent.com/8775469/34511817-7a0bae8e-f05e-11e7-86fa-9866889b36c4.png)
![12-nc-snapshot-terminal-output-maintenance-mode](https://user-images.githubusercontent.com/8775469/34511818-7c1d397c-f05e-11e7-86bc-88d5e3f4fc3c.png)

**Comment by nachoparker** [comment]
great thanks! tell us when you are done, and so we can review it

**Comment by ovpc** [comment]
Adding some more screenshot for nc-backup with ncdata
![20-nc-backup-select-in-ncp-config](https://user-images.githubusercontent.com/8775469/34664327-9c050340-f45b-11e7-82ec-fe4beab8017b.png)
![21-nc-backup-set-destination-and-include-data](https://user-images.githubusercontent.com/8775469/34664336-a17b62ec-f45b-11e7-9d1d-a31f2dccc90b.png)
![22-nc-backup-launch-backup-nc-bkp_date-tar-created](https://user-images.githubusercontent.com/8775469/34664359-c022104c-f45b-11e7-9acd-a333c3363ffd.png)

+ screenshots for nc-restore process

![30-nc-restore-select-in-ncp-config](https://user-images.githubusercontent.com/8775469/34664376-e0e1036a-f45b-11e7-850e-7a1ed4cd6d89.png)
![31-nc-restore-configure-location](https://user-images.githubusercontent.com/8775469/34664380-e942ef78-f45b-11e7-80ce-b7201909e7e9.png)
![32-nc-restore-overwrite-old-instance-terminal-output](https://user-images.githubusercontent.com/8775469/34664383-ed643652-f45b-11e7-9a43-1f36790b5336.png)

**Comment by nachoparker** [comment]
thanks for the documentation @ovpc !

**Comment by voldemort13** [comment]
How do I know where the backup file is going? I have an usb stick connected to raspberry and the backup works fine but i cant find the generated file anywhere

**Comment by Oceania2301** [comment]
Where can I find information about to restore data using nc- snapshots ?

**Comment by ovpc** [comment]
[Here](https://ownyourbits.com/category/btrfs/) is what Nacho has added to his blog concerning btrfs and snapshots. There is no wiki page for that yet......

**Comment by nachoparker** [comment]
> Where can I find information about to restore data using nc- snapshots ?

In order to restore the data from a snapshot, you have to replace the `ncdata` subvolume, something like

```
sudo btrfs subvolume delete /media/USBdrive/ncdata   # remove datadir
sudo btrfs subvolume snapshot /media/USBdrive/ncp-snapshots/daily-xxxxx /media/USBdrive/ncdata                      # restore old copy
nc-scan                                       # update NC database with the new/old files
```

It would be great to add that to the wiki

**Comment by ovpc** [comment]
Made start at this [here](https://github.com/nextcloud/nextcloudpi/wiki/How-to-snapshot-with-btrfs) will add steps to enable snapshot auto later.

**Comment by kpleines** [comment]
I've run NextcloudPi inside Docker with an exportet /data volume.
Backup seems to run smoothe but ends with the following error message:

tar: /data/app/data/..: Cannot open: No such file or directory

Can I fix this problem myselfe? Thx
![unbenannt](https://user-images.githubusercontent.com/12126050/50511097-871c7880-0a8c-11e9-898e-9a7a06e3bacc.PNG)

**Comment by nachoparker** [comment]
this might have been already fixed. Please update to the latest version (`v0.67.11`) and try again.

**Comment by StevenDecatur** [comment]
This might be obvious to people who know what they are doing, but what is the purpose of backing up the configuration file with nc-export-ncp when you restore the instance with the file made by nc-backup?  Do you need the configuration backup file made by nc-export-ncp when restoring?

Also, if you restore from a dataless backup, do you just copy the data back to the data directory when it finishes? For example, if you used rsync to save the data elsewhere?

**Comment by ovpc** [comment]
nc-export-ncp exports the setting of NCP only (app enabled/disabled/settings), not NC's config, maybe wiki does need clarification, feel free to edit/add information to improve usability, thank you

You don't need it, to restore from a backup made previously. 
After restore from data less backups: you can set /path/to/ncdata in config and run nc-scan

**Comment by kpleines** [comment]
Update to the latest Version works. Thx

**Comment by SoongJr** [comment]
Thanks for the guide!
I'm trying to replace my old ncp image with a docker instance on my RaspberryPi 2, so I made a backup of the old one as per the guide, flashesd a new card with default Raspberry OS, started up the docker container and restored the data.

I've had some issues I could work around myself, so now restore has succeeded, but my SSL certificate does not seem to have been restored. Is this not part of the backup? I thought controlling the whole environment was the reason for having NCP int he first place, so all the DynDNS and SSL and firewall stuff should be part of a backup, no?
Am I just using the wrong kind of backup and should have done nc-export-ncp or something or do I have to manually transfer my ssl certificates? What else do I have to do manually that one could expect ncp-backup to be doing for me? 😉

**Comment by ovpc** [comment]
@SoongJr Please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm/33) to ask questions or if need assistance.

**Comment by SoongJr** [comment]
> @SoongJr Please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm/33) to ask questions or if need assistance.

OK thanks, will do. The guide itself said to "please comment or ask for help HERE", so that's what I did ;)

**Comment by johnmcd88** [comment]
Question - when you choose to include data in your ncp-backup, do external folders from network shares that you've added to NCP get backed up?

Thanks

**Comment by ailieff** [comment]
> Question - when you choose to include data in your ncp-backup, do external folders from network shares that you've added to NCP get backed up?
> 
> Thanks

That is something that I was wondering too? Or maybe just the reference to the files/mounts and you have to restore the configuration, too.
