### ISSUE TITLE
Install NCP too an external USB drive booting with Berryboot

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#271]
This issue is to separate the conversation that started here https://github.com/nextcloud/nextcloudpi/issues/209

@ovpc has implemented the port to berryboot/squashfs and is in conversation with them to include the image.

Also, he is going to write instructions in the wiki

Thanks for all that ;)

**Comment by ovpc** [comment]
Just screenshots for wiki in progress ;-)
![welcomescreenberryboot](https://user-images.githubusercontent.com/8775469/32147239-5a3d5218-bce4-11e7-9947-c54a0e8d1357.png)
![chooseinstalldrivescreenberryboot](https://user-images.githubusercontent.com/8775469/32147241-6218820a-bce4-11e7-9d74-26066dff5424.png)

**Comment by ovpc** [comment]
An issue :( with berryboot image: cant run : sudo raspi-config, it throws error that /boot is not mounted and only option is exit ...nextcloudpi-config runs tho. Will post at maxnet with screenshot, they got theirs working on NC11.img, /boot is on sdcard managed by berry. That doent seem to work with raspi-config out of the box......

**Comment by nachoparker** [comment]
looks great, thank you very much!

**Comment by ovpc** [comment]
Uncommenting the line for /boot in /etc/fstab and pointing it LABEL=boot resolved the issue
![raspi-config-nextcloudpi-config-access2017-11-01_08-52-37-resolved](https://user-images.githubusercontent.com/8775469/32265795-d97c3e16-bee4-11e7-9af6-7ad739d7550d.png)
BTW Had not noticed yet there is a link to nextcloudpi-config inside raspi-config, nice job !

Please grab berryboot NCP torrent from 
[HERE](https://drive.google.com/open?id=0B1wGkGPW-CxLeXFnUWNlb09oMWc)
and help us seed, thank you

**Comment by nachoparker** [comment]
good job! thanks
