### ISSUE TITLE
wiki: run NextCloudPi in VirtualBox (maybe virt-manager too)

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#273]
It would be nice to have the steps to do this for developers to be able to help easier.

[I develop using QEMU](https://ownyourbits.com/2017/02/06/raspbian-on-qemu-with-network-access/) but that is a Linux only approach and it doesn't work right away for instance in Fedora or Mac.

Should be identical to running Raspbian

**Comment by ovpc** [comment]
Looking at [this VirtualBox solution](http://ediy.com.my/index.php/blog/item/52-virtualbox-raspberry-pi-emulator), not tested yet.

**Comment by nachoparker** [comment]
great!
