### ISSUE TITLE
Performance enhancements

### ISSUE THREAD

**Issue by wompydomp** [nextcloud/nextcloudpi#277]
Hi,

I've been using owncloud later nextcloud for a couple of years now. In the early days I crashed my sqlite DB every now an then, but for the last 2 to 3 years I was able to establish a good backup routine. When I saw that you guys created this faboulous nextcloudpi project I wanted to get rid of all the configuration affort I have under arch linux and migrated my database first to mariadb and afterwards over to a new nextcloudpi image.

Since the late Nextcloud 11 versions I've been struggling with the performance. The patch here initially helped me a a lot, but my NC install is still very very slow (compared to where it was half a year ago on exactly the same hardware).
https://github.com/nextcloud/server/issues/2272

I was wondering if you have any recommendations on how to identify bottlenecks. I currently don't even know if the database is the problem, if the nextcloud code is the problem or if I configured stuff incorrectly.

Since this project focuses on limited hardware resources, I thought it might be helpful to have a conversation here. Discussions about performance in other places on github usually includes people with high powered VM's and endless RAM - not really what we have here.

**Comment by nachoparker** [comment]
Hi,

You are right that there needs to be a community that also represents users on low power devices.

Seems like the web implementation is really slow, but they are improving it in NC 13.

The correct place to have conversations/discussions is the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm), so I suggest that you copy-paste your question there, where also more people can contribute to the conversation.
