### ISSUE TITLE
Option for using duckdns?

### ISSUE THREAD

**Issue by klundry** [nextcloud/nextcloudpi#28]
I prefer to use duckdns.org for my dynamic dns, as it doesn't require me to log in and confirm that I'm still using it every so often and it is free.  It has very good documentation and now supports TXT record for use with letsencrypt.  [DuckDNS spec](http://www.duckdns.org/spec.jsp). Is it possible to get support for it added along with No-IP?

**Comment by nachoparker** [comment]
Implemented in `v0.30.0`
