### ISSUE TITLE
Docker install fail, no login screen but config

### ISSUE THREAD

**Issue by sutolaci** [nextcloud/nextcloudpi#284]
Hi,

I've tried to install nextcloud on raspberry pi3 with the docker installation instructions. I've created the container with the command:

docker run -d -p 443:443 -p 88:80 -v ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi 192.168.1.42

When I hit the url in browser I've got the attached screen where I have to specify database user, password, name, host.

What could be the problem.

Log:
pi@raspberrypi:~ $ docker container logs nextcloudpi 
Starting PHP-fpm
Starting mariaDB
2017-11-06 23:16:57 1996144640 [Note] mysqld (mysqld 10.1.22-MariaDB-) starting as process 8 ...
Nextcloud is not installed - only a limited number of commands are available

                                                                   
  [Symfony\Component\Console\Exception\CommandNotFoundException]   
  There are no commands defined in the "config:system" namespace.  
                                                                   

Nextcloud is not installed - only a limited number of commands are available

                                                                   
  [Symfony\Component\Console\Exception\CommandNotFoundException]   
  There are no commands defined in the "config:system" namespace.  
                                                                   

Starting Apache
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Starting cron
Done

![screen shot 2017-11-07 at 22 17 32](https://user-images.githubusercontent.com/3977964/32518408-bddf2176-c409-11e7-9ee5-4cf441e216b6.png)

**Comment by nachoparker** [comment]
I suggest you try again with the [new containers](https://ownyourbits.com/2017/11/15/nextcloudpi-dockers-for-x86-and-arm/)

Please, report if there's any problem

Thanks
