### ISSUE TITLE
Let's Encrypt Expiry Bot

### ISSUE THREAD

**Issue by user-jan** [nextcloud/nextcloudpi#285]
Hi Nacho,

I recently got the following email concerning "Let's Encrypt."

Do I need to do anything, or will NCP take care of it?

I've updated to NCP v0.32.3 and I have "run" letsencrypt with both ports 80 and 443 accessible from the internet:

<img width="479" alt="letsencrypt" src="https://user-images.githubusercontent.com/31073831/32663574-b77a71d8-c62e-11e7-8c6c-d25a5a2b9efc.png">

Slds,
Jan

**Comment by nachoparker** [comment]
Hi!

NCP should update it every month. If you get problems, just run letsencrypt again.

From now on, we will try to keep questions and conversation [in the forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)

Cheers!
