### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by redone101** [nextcloud/nextcloudpi#294]
Hello,

few days ago, my Nextcloudpi was unreachable from my phone.
As i checked, the webgui wasn't accessible too.

I just get a blank page in the webbrowser.

After some google search, i think that i found what the problem is.

For some reason, the "nc-database" option is active/checked, with the path to my usb-stick:
DBDIR         /media/USBdrive/ncdatabase

I didn't activate this option, as i use the usb-stick only for backups.

When i run "sudo nextcloudpi-config" and want to aprove any changes, i get this message in german when i get out of the nextcloudpi-config menu:

grep: /etc/mysql/mariadb.conf.d/50-server.cnf: Datei oder Verzeichnis nicht gefunden

It says, that the file or directory can't be found.

In the "nc-database" option there is a hint:

** If it ever fails with a white page, move the database back to the SD ** 

**My question is, how do i move the database back to the SD?**

By the way, there is no "ncdatabase" directory on my usb-stick!

pi@raspberrypi:/usr/local/etc $ cat ncp-baseimage
untagged
pi@raspberrypi:/usr/local/etc $ cat ncp-version
v0.34.10

Here are some checks:

pi@raspberrypi:/etc $ systemctl status mysqld
● mysqld.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

pi@raspberrypi:/etc $ tail -n 100 /var/log/mysql/*.log            

No output of this command.

pi@raspberrypi:/etc $ systemctl status apache2
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled)
   Active: active (running) since Sam 2017-11-11 23:48:35 CET; 2 days ago
 Main PID: 1888 (apache2)
   CGroup: /system.slice/apache2.service
           ├─ 1888 /usr/sbin/apache2 -k start
           ├─24316 /usr/sbin/apache2 -k start
           └─24317 /usr/sbin/apache2 -k start

**Comment by sunjam** [comment]
Hey, I've got some info for you.  Problem you're experiencing (and myself) is the the USB mounting point has changed from what you initially set as of a reboot.  Question is, how do we change the location of ncdata and database as identified by our instance.    
    
My usb drive was originally assigned as `/media/USBdrive3`, but is also shows up as` /media/usb1/` and is currently inaccessible + mounted as `/media/USBdrive4/` as of my last reboot. `nextcloudpi-config` will only move an existing directory to a new location.... @nachoparker how do we just literally reassign the locations for ncdata and the database without moving anything?  We need nextcloudpi-config to recognize the changes, even if they are made externally from the app.

**Comment by sunjam** [comment]
@redone101 I was able to re-create and fix this issue by editing `/etc/fstab` to permanently mount the external USB drive.  Please close the issue if this works for you.  Cheers.  I agree that "moving back to SD" is not a clear method in the official documentation.

`# vi /etc/fstab`
* use `df -h` to confirm current location of your USB drive.  You can also mount by UUID. Be sure to set correct partition format (mine is ext4).
* add `/path/to/usb/ /path/you/set/in/nextcloudpi ext4 defaults 0 0`
`# mount -a`
`# systemctl start mysql`

**Comment by nachoparker** [comment]
hi @redone101 , @sunjam 

It seems that you are running Jessie still, is that correct? Jessie is not supported anymore since we moved to Stretch.

> For some reason, the "nc-database" option is active/checked?

Is this checked in `nextcloudpi-config`? if not, then you have not moved it. Look in `nextcloudpi-config`, not in ncp-web.

What is the output of

```
sudo grep -r datadir /etc/mysql
```

and 

```
systemctl status mysql
```

and

```
ls -l /media

@sunjam thanks for the help

what you are seeing probably is that the old automount [was rewritten](https://ownyourbits.com/2017/09/05/nextcloudpi-gets-freedns-better-automount-notifications-samba-and-web-improvements/) some months ago.

If you want to control exactly the location, 

 - use fstab and disable automunt, or
 -  label the disk, so that it will be automounted in `/media/label/`
```

> I agree that "moving back to SD" is not a clear method in the official documentation.

Aggree, we'll improve this

**Comment by redone101** [comment]
hi sunjam, hi nachoparker

thx for your replies.

I have an entry of my usb-stick in the /etc/fstab and the stick is also mounted:

pi@raspberrypi:~ $ cat /etc/fstab
proc            /proc           proc    defaults          0       0
PARTUUID=b6a83eb5-01  /boot           vfat    defaults          0       2
PARTUUID=b6a83eb5-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that

# Rules for automounting both at boot and upon USB plugin. Rely on udev rules

UUID=4d5451ff-f164-43e8-ae12-13aaef4ca72d  /mnt/backup_usb ext4         defaults,noatime,auto 0 0


pi@raspberrypi:/etc $ sudo blkid 
/dev/mmcblk0: PTUUID="b6a83eb5" PTTYPE="dos"
/dev/mmcblk0p1: LABEL="boot" UUID="70CE-EB76" TYPE="vfat" PARTUUID="b6a83eb5-01"
/dev/mmcblk0p2: UUID="f2100b2f-ed84-4647-b5ae-089280112716" TYPE="ext4" PARTUUID="b6a83eb5-02"
/dev/sda1: LABEL="SD32GB" UUID="4d5451ff-f164-43e8-ae12-13aaef4ca72d" TYPE="ext4" PARTUUID="433808f1-7038-4d36-90f6-e94d788c78f8"


pi@raspberrypi:~ $ df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/root        29G     18G  9,4G   66% /
devtmpfs        458M       0  458M    0% /dev
tmpfs           462M       0  462M    0% /dev/shm
tmpfs           462M     13M  450M    3% /run
tmpfs           5,0M    4,0K  5,0M    1% /run/lock
tmpfs           462M       0  462M    0% /sys/fs/cgroup
/dev/sda1        29G     17G   11G   62% /mnt/backup_usb
/dev/mmcblk0p1   41M     21M   20M   52% /boot
tmpfs            93M       0   93M    0% /run/user/1000

As i understand it, the mount is ok.
Correct me, if i am wrong.

All changes that i ever did, were made in the nextcloudpi-config.
The "nc-database" option is active/checked in the nextcloudpi-config.

Here are the outputs you asked for nachoparker:

pi@raspberrypi:~ $ sudo grep -r datadir /etc/mysql
/etc/mysql/my.cnf:datadir		= /var/lib/mysql

pi@raspberrypi:~ $ systemctl status mysql
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql)
   Active: active (running) since Sam 2017-11-11 23:40:35 CET; 4 days ago
   CGroup: /system.slice/mysql.service
           ├─788 /bin/bash /usr/bin/mysqld_safe
           ├─935 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --skip-log-error --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld...
           └─936 logger -t mysqld -p daemon.error

pi@raspberrypi:~ $ ls -l /media
insgesamt 8
drwxr-xr-x 3 root root 4096 Aug 22 10:49 backup_usb
lrwxrwxrwx 1 root root   16 Aug 15 10:13 SD32GB -> /media/USBdrive5
lrwxrwxrwx 1 root root   16 Aug 15 10:13 Stick32GB -> /media/USBdrive5
drwxr-xr-x 2 root root 4096 Aug 15 10:13 USBdrive5

Those are the only files i can find on the usb-stick:

pi@raspberrypi:/media/backup_usb/backup $ ls
nextcloud-bkp_20171015.tar 
nextcloud-bkp_20171028.tar 
nextcloud-bkp_20171104.tar  
nextcloud-bkp_20171111.tar

I was never sure, if i should upgrade the pi-os it self, because i activated the automatic updates in the nextcloudpi-config and was not sure, if those updates are nextcloud only or the OS-updates too.

pi@raspberrypi:/etc $ cat debian_version
8.0

Still don't know, how to get the database running -_-

**Comment by sunjam** [comment]
afaik I'm seeing multiple entries for the same external storage device.  I bet you'll find all of your data is currently living at **/media/USBdrive5**
    
drwxr-xr-x 3 root root 4096 Aug 22 10:49 **backup_usb**
lrwxrwxrwx 1 root root 16 Aug 15 10:13 **SD32GB** -> /media/USBdrive5
lrwxrwxrwx 1 root root 16 Aug 15 10:13 **Stick32GB** -> /media/USBdrive5
drwxr-xr-x 2 root root 4096 Aug 15 10:13 USBdrive5

**Comment by redone101** [comment]
Unfortunately i can't see no data there:

pi@raspberrypi:/media/USBdrive5 $ ls -la
insgesamt 8
drwxr-xr-x 2 root root 4096 Aug 15 10:13 .
drwxr-xr-x 4 root root 4096 Aug 22 10:49 ..

I could try to make a restore?

**Comment by nachoparker** [comment]
> I could try to make a restore from nextcloudpi-config?

Yes, I suggest you start from the latest image and do that, if you have time and energy ;D

I'll close but we can continue talking

**Comment by nachoparker** [comment]
keep in mind that debian 8 is not supported by NCP anymore, so I suggest you backup and restore if you can, your database is up, so it is working, don't worry about it's location.

**Comment by redone101** [comment]
Hi nachoparker,

that means, i can install a new image of nextcloudpi and just restore
the backup?

Am 17.11.2017 10:01 schrieb nachoparker: 

> keep in mind that debian 8 is not supported by NCP anymore, so I suggest you backup and restore if you can, your database is up, so it is working, don't worry about it's location. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nextcloud/nextcloudpi/issues/294#issuecomment-345184458
[2]

**Comment by nachoparker** [comment]
> that means, i can install a new image of nextcloudpi and just restore the backup?

that's exactly right

**Comment by redone101** [comment]
I installed a new nextcloudpi on a other sdcard and restored the
backup, but the again got the blank page.

After that i again did some google search and found this:

https://github.com/nextcloud/nextcloudpi/issues/287

After i applied the changes you wrote on that page, the page was
accessible again :D
It seems, i had two problems...

The thing now is, that i can't make an update.

Right now i have v0.34.15 and when i do the update i don't get an error
message, but even if i reboot, the version stays on v034.15.

I think it hast still to do with this error message on the database:

grep: /etc/mysql/mariadb.conf.d/50-server.cnf: Datei oder Verzeichnis
nicht gefunden => means the file can't be found

So i looked up:

pi@raspberrypi:/etc/mysql $ ls -l
insgesamt 16
drwxr-xr-x 2 root root 4096 Aug 18 06:54 conf.d
-rw------- 1 root root 333 Mai 23 20:23 debian.cnf
-rwxr-xr-x 1 root root 1312 Mai 7 2017 debian-start
-rw-r--r-- 1 root root 3533 Jän 17 2017 my.cnf

Now that the page is accesible i made a new backup and tried to restore
it on the new installation of the nextcloudpi (other sdcard).
After the restore, i again got the blank page.

This is the output of the restore:

Launching nc-restore
INFO: overwriting old instance
extracting backup file /mnt/backup_usb/nextcloud-bkp_20171118.tar...
tar:
nextcloud/data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-1:
time stamp 2017-11-19 14:23:53 is 83823.169033031 s in the future
tar:
nextcloud/data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-4:
time stamp 2017-11-19 14:24:08 is 83838.118279934 s in the future
tar:
nextcloud/data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-2:
time stamp 2017-11-19 14:23:56 is 83826.066892706 s in the future
tar:
nextcloud/data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-3:
time stamp 2017-11-19 14:24:06 is 83836.020887395 s in the future
tar: data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-1:
time stamp 2017-11-19 14:23:53 is 82737.284355395 s in the future
tar: data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-4:
time stamp 2017-11-19 14:24:08 is 82750.841928317 s in the future
tar: data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-2:
time stamp 2017-11-19 14:23:56 is 82738.651894842 s in the future
tar: data/Amira/cache/IMG_20171117_153808361.jpg-chunking-48480119-3:
time stamp 2017-11-19 14:24:06 is 82748.600360603 s in the future
restore files...
sed: can't read config/config.php: No such file or directory
restore database...
restore datadir to /var/www/nextcloud/data...
backing up existing /var/www/nextcloud/data
An unhandled exception has been thrown:
DoctrineDBALDBALException: Failed to connect to the database: An
exception occured in driver: SQLSTATE[HY000] [1045] Access denied for
user 'ncadmin'@'localhost' (using password: YES) in
/var/www/nextcloud/lib/private/DB/Connection.php:61
Stack trace:
#0
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429):
OCDBConnection->connect()
#1
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389):
DoctrineDBALConnection->getDatabasePlatformVersion()
#2
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328):
DoctrineDBALConnection->detectDatabasePlatform()
#3
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623):
DoctrineDBALConnection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(148):
DoctrineDBALConnection->setTransactionIsolation(2)
#5
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172):
OCDBConnection->__construct(Array,
Object(DoctrineDBALDriverPDOMySqlDriver),
Object(DoctrineDBALConfiguration), Object(DoctrineCommonEventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(150):
DoctrineDBALDriverManager::getConnection(Array,
Object(DoctrineDBALConfiguration), Object(DoctrineCommonEventManager))
#7 /var/www/nextcloud/lib/private/Server.php(588):
OCDBConnectionFactory->getConnection('mysql', Array)
#8
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#9
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OCP\IDBConnecti...')
#10 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OCP\IDBConnecti...')
#11
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163):
OCServerContainer->query('OCP\IDBConnecti...')
#12
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109):
OCAppFrameworkUtilitySimpleContainer->OCAppFrameworkUtility{closure}(Object(OCServer))
#13
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('DatabaseConnect...')
#14 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('DatabaseConnect...')
#15 /var/www/nextcloud/lib/private/Server.php(1345):
OCServerContainer->query('DatabaseConnect...')
#16 /var/www/nextcloud/lib/private/Server.php(309):
OCServer->getDatabaseConnection()
#17
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#18
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OC\Authenticati...')
#19 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OC\Authenticati...')
#20 /var/www/nextcloud/lib/private/Server.php(313):
OCServerContainer->query('OC\Authenticati...')
#21
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#22
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OC\Authenticati...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OC\Authenticati...')
#24
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163):
OCServerContainer->query('OC\Authenticati...')
#25
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109):
OCAppFrameworkUtilitySimpleContainer->OCAppFrameworkUtility{closure}(Object(OCServer))
#26
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OC\Authenticati...')
#27 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OC\Authenticati...')
#28 /var/www/nextcloud/lib/private/Server.php(329):
OCServerContainer->query('OC\Authenticati...')
#29
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#30
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OCP\IUserSessio...')
#31 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OCP\IUserSessio...')
#32
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163):
OCServerContainer->query('OCP\IUserSessio...')
#33
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109):
OCAppFrameworkUtilitySimpleContainer->OCAppFrameworkUtility{closure}(Object(OCServer))
#34
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('UserSession')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('UserSession')
#36 /var/www/nextcloud/lib/private/Server.php(1220):
OCServerContainer->query('UserSession')
#37 /var/www/nextcloud/lib/private/Server.php(939):
OCServer->getSession()
#38
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#39
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OC\Security\CSR...')
#40 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OC\Security\CSR...')
#41 /var/www/nextcloud/lib/private/Server.php(935):
OCServerContainer->query('OC\Security\CSR...')
#42
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#43
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('CsrfTokenManage...')
#44 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('CsrfTokenManage...')
#45 /var/www/nextcloud/lib/private/Server.php(1693):
OCServerContainer->query('CsrfTokenManage...')
#46 /var/www/nextcloud/lib/private/Server.php(769):
OCServer->getCsrfTokenManager()
#47
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#48
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OCP\IRequest')
#49 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OCP\IRequest')
#50
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163):
OCServerContainer->query('OCP\IRequest')
#51
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109):
OCAppFrameworkUtilitySimpleContainer->OCAppFrameworkUtility{closure}(Object(OCServer))
#52
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('Request')
#53 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('Request')
#54 /var/www/nextcloud/lib/private/Server.php(1087):
OCServerContainer->query('Request')
#55 /var/www/nextcloud/lib/private/Server.php(416):
OCServer->getRequest()
#56
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113):
OCServer->OC{closure}(Object(OCServer))
#57
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('OCP\L10N\IFacto...')
#58 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('OCP\L10N\IFacto...')
#59
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163):
OCServerContainer->query('OCP\L10N\IFacto...')
#60
/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109):
OCAppFrameworkUtilitySimpleContainer->OCAppFrameworkUtility{closure}(Object(OCServer))
#61
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115):
PimpleContainer->offsetGet('L10NFactory')
#62 /var/www/nextcloud/lib/private/ServerContainer.php(132):
OCAppFrameworkUtilitySimpleContainer->query('L10NFactory')
#63 /var/www/nextcloud/lib/private/Server.php(1274):
OCServerContainer->query('L10NFactory')
#64 /var/www/nextcloud/lib/private/Server.php(1285):
OCServer->getL10NFactory()
#65 /var/www/nextcloud/lib/base.php(225): OCServer->getL10N('lib')
#66 /var/www/nextcloud/lib/base.php(678): OC::checkConfig()
#67 /var/www/nextcloud/lib/base.php(1086): OC::init()
#68 /var/www/nextcloud/console.php(56):
require_once('/var/www/nextcl...')
#69 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#70 {main}Done. Press any key...

pi@nextcloudpi:~ $ 

Sholud i open a new case for this problem?

Am 17.11.2017 10:01 schrieb nachoparker: 

> keep in mind that debian 8 is not supported by NCP anymore, so I suggest you backup and restore if you can, your database is up, so it is working, don't worry about it's location. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nextcloud/nextcloudpi/issues/294#issuecomment-345184458
[2]

**Comment by nachoparker** [comment]
did you install the latest image?

**Comment by nachoparker** [comment]
ok, I think I know what it is. Can you update to `v0.37.1` with `sudo ncp-update` (or the web) and try `nc-restore` again?

**Comment by redone101** [comment]
Hello,

as i checked couple days ago, the update was made by it self (it is
activated), so that worked!
After that a manual update was possible too!
Today i made a fresh backup and restored it on the other sdcard with
raspbian? 9 and it worked, wohooo :D
So everything is fine again!
Many thanks for your help and time :)

If i may ask you two last questions:

When ncupdate is made, does it also update the os (raspbian)?
If so, how should i know, when the version of the raspbian is not
supported any more, since i still get the ncupdates, but no warning?

If you didn't told me, that the version 8 is not supported any more and
that there is a new version 9, i would have never known,

Thanks one more time!

Am 19.11.2017 23:13 schrieb nachoparker: 

> ok, I think I know what it is. Can you update to v0.37.1 with sudo ncp-update (or the web) and try nc-restore again? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nextcloud/nextcloudpi/issues/294#issuecomment-345554371
[2]

**Comment by nachoparker** [comment]
I am glad that it worked.

> When ncupdate is made, does it also update the os (raspbian)?

No, that's up to the user. The good thing is that each Raspbian release is good for two years.

> If so, how should i know, when the version of the raspbian is not supported any more, since i still get the ncupdates, but no warning?

I did announce it in ownyourbits.com. [link](https://ownyourbits.com/2017/08/20/nextcloudpi-updated-to-raspbian-9-stretch/). I recommend that you follow the blog for announcements.

That being said, I am developing suggestions in `nc-info` and I would like to have them pop up as notifications.
