### ISSUE TITLE
NextcloudPi not yet listed on Berryboot project

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#297]
[Reported here as Issue 447 on the Berryboot github page.  Currently their featured image within Berryboot is for an older Nextcloud 11.0 image as of 11/13/2017.](https://github.com/maxnet/berryboot/issues/447)

**Comment by nachoparker** [comment]
thanks for the support!

**Comment by nachoparker** [comment]
after a month of no response from them, I think we can clean this up. They don't seem interested

thanks
