### ISSUE TITLE
Fail2ban script bug

### ISSUE THREAD

**Issue by Iolaum** [nextcloud/nextcloudpi#299]
### Expected behavior

Nextcloud config starts without errors from shell

### Actual behavior

After we connect through ssh:

```
$ sudo nextcloudpi-config 
/usr/local/etc/nextcloudpi-config.d//fail2ban.sh: line 67: syntax error near unexpected token `}'
/usr/local/etc/nextcloudpi-config.d//fail2ban.sh: line 67: `}'
# Exit the GUI from the shell to see the error messages above.
$
```

### Steps to reproduce, from a freshly installed image

See Actual behaviour.

### Notes: 

1. As a result of this [lines](https://github.com/nextcloud/nextcloudpi/blob/634bc335d05db8ea06999a38fd10133f9101dd94/etc/nextcloudpi-config.d/fail2ban.sh#L62-L66) of fail2ban install code will not execute when a user tries to set it up.

2. I believe the issue was caused by 6b9699c870cf4 and I am sending a PR with a fix.

**Comment by nachoparker** [comment]
Many thanks for reporting and for the PR, actually I accidentally removed a line, so it's fixed now

https://github.com/nextcloud/nextcloudpi/commit/c4a0bba8170c118e4941f98b3d6af26ec8d6a5c9
