### ISSUE TITLE
NextcloudPi-config updates -- what is being updated?

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#301]
Would it be possible to list what is actually being changed with each Nextcloudpi-config update..?  The dialog windows asks for update approval, but gives no description or recap of what is actually changing.
![nextcloudpi-config-changes](https://user-images.githubusercontent.com/1787238/32919341-52a3d8a2-cada-11e7-8bc7-bde5bbfb49e7.png)

**Comment by nachoparker** [comment]
in ncp-web you can click the version number, which will take you to the [changelog](https://github.com/nextcloud/nextcloudpi/blob/master/changelog.md)

in nextcloudpi-config... I guess we could add the URL as well...

**Comment by nachoparker** [comment]
How about this

![screenshot_2017-11-17_11 53 26](https://user-images.githubusercontent.com/21343324/32944039-6885ee4e-cb8e-11e7-8243-e34e283f83bf.png)

**Comment by sunjam** [comment]
Do you think it would be possible to list the changes within ncp since the last upgrade?
![nextcloudpi-config-changes-example](https://user-images.githubusercontent.com/1787238/32967074-1fbd9c72-cb91-11e7-9bd1-a883a3e3bd04.png)

**Comment by nachoparker** [comment]
I guess it would be possible ;D

**Comment by nachoparker** [comment]
implemented `v0.41.6`

![screenshot_2017-12-05_17 35 55](https://user-images.githubusercontent.com/21343324/33618757-b22998e4-d9e3-11e7-9ed4-81ee497c88c4.png)
