### ISSUE TITLE
Looking for ncp-web login credentials

### ISSUE THREAD

**Issue by cottoa00** [nextcloud/nextcloudpi#307]
Has been in the web admin portal at :4443. My notes say the access creds were pi/raspberry.... current docs suggest ncp/ownyourbits... and my impression is that they could not be changed.
Regardless, I cannot get in... even tried my regular next cloud admin creds... no go.

Remember a prior issue with having to sign-in multiple times to get in. Any help appreciated. Can SSH in and have v0.31.14.

**Comment by aramsichord** [comment]
pi/ownyourbits or ncp/ownyourbits. If you have changed the pi user password then it is pi/[newpassword]. I hope that helps, I had trouble with it as well.
