### ISSUE TITLE
"Distro not supported"

### ISSUE THREAD

**Issue by tarbucndge** [nextcloud/nextcloudpi#315]
Paste the output of `sudo ncp-report`

**Comment by tarbucndge** [comment]
I have tried to run this command: "curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash" on my raspberry pi3 (the current image on the sdcard is dietpi) and I got the "Distro not supported" message. 
Please anyone let me know why? And what should I do?
Thanks very much.

**Comment by nachoparker** [comment]
You need to be on Raspbian 9 stretch to use the 'curl installer'. You are probably on jessie 8

```
cat /etc/issue
```

**Comment by tarbucndge** [comment]
Thank you very much.

**Comment by nachoparker** [comment]
if you don't want to upgrade your distro, you can use the docker image

**Comment by tarbucndge** [comment]
how would I do that? I am a newbie
Thank you

**Comment by nachoparker** [comment]
https://ownyourbits.com/2017/06/08/nextcloudpi-docker-for-raspberry-pi/

**Comment by tarbucndge** [comment]
I will give it a try. Thank you!
