### ISSUE TITLE
vm.overcommit_memory = 1 after sudo ncp-update

### ISSUE THREAD

**Issue by brotonmail** [nextcloud/nextcloudpi#316]
Hi Guys

My nextcloudpi is working perfectly. The only thing I'm concerned about is that every time I issue sudo ncp-update it replies "vm.overcommit_memory = 1". It seems to still be updating to new versions. Is this something to be concerned about or safely ignore?

**Comment by nachoparker** [comment]
nothing to worry about. It seems like it confuses people, so I will silence that message

cheers
