### ISSUE TITLE
Upgrade to 12.0.4 breaks my custom theme

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#318]
After upgrading, my custom login page and logo have been replaced by the stock Nextcloud logo and backdrop.    
    
My custom Name, Web Address, and Slogan are still correct.

**Comment by nachoparker** [comment]
how did you change the theme? through admin settings?

**Comment by sunjam** [comment]
Yes, I changed the theme through admin settings a couple weeks ago.  The image and logo were replaced with Nextcloud's default during the upgrade to 12.0.4, but my custom theme color is still correct.  
![theme-broken](https://user-images.githubusercontent.com/1787238/33625170-92bf29d4-d9ab-11e7-99f2-9aa1e34fe9e4.png)    
Interestingly, the NextcloudPi logo and my yellow theme do show up once I'm logged in...
![logo-still-shows](https://user-images.githubusercontent.com/1787238/33625177-9877b77e-d9ab-11e7-84fd-2da8f83e4db2.png)

**Comment by nachoparker** [comment]
I tested upgrading from 12.0.3 and the NCP theme was unaffected. I suggest you report this to nextcloud/server
