### ISSUE TITLE
Offer different SSL configurations 

### ISSUE THREAD

**Issue by Daniel-Krebs** [nextcloud/nextcloudpi#322]
It would be great if we could offer different SSL configurations, depending on your need for compatibility for old(er) devices. This way we could use modern cypher suites like Salsa20/ChaCha.

[Mozilla](https://mozilla.github.io/server-side-tls/ssl-config-generator/) offers a nice tool to generate an Old,  Intermediate or Modern configuration. 
This should give as better performance / lower battery usage especially on mobile phones, see this link from [cloudfare](https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography/) for more information.

**Comment by nachoparker** [comment]
Implemented and testing some improvements to `v0.46.15`

- updated cyphers ( chacha and others )
- OCSP stapling

Thanks!
