### ISSUE TITLE
Can't get No-IP to work

### ISSUE THREAD

**Issue by CarlosElViper** [nextcloud/nextcloudpi#33]
Hello,
I am logged in as pi.
When I run **sudo raspi-config** -> **0 NextCloudPi Configuration**** ->**no-ip**
My data for Active, User, Pass, Domain & Time are correct.
I get this error:
Launching no-ip
update-rc.d: error: no runlevel symlinks to modify, aborting!
Done. Press any key...

When I enter: **sudo noip2 -S**
I get this:

No noip2 processes active.

Configuration data from /usr/local/etc/no-ip2.conf.
Account xxxxxxx@sbcglobal.net
configured for:
	host  -.fakename.com
	host  ftp.fakename.com
	host  mail.fakename.com
	host  www.fakename.com
Updating every 30 minutes via /dev/eth0 with NAT enabled.

Any help would greatly appreciated.
thanks
carlos

**Comment by nachoparker** [comment]
You are forgetting to set `ACTIVE=yes`. 

What you are getting is a harmless error message that occurs when you are trying to deactivate what never was activated before (because of `ACTIVE=no`

That situation has been covered by v0.14.9, so the error message should dissappear

**Comment by CarlosElViper** [comment]
thank you
