### ISSUE TITLE
Can't ssh into docker image

### ISSUE THREAD

**Issue by peter-sc** [nextcloud/nextcloudpi#333]
Hi, after running the latest docker image `ownyourbits/nextcloudpi-x86` and forwarding port for ssh
`0.0.0.0:2442->22/tcp`, and enabling SSH via ncp-web, I'm unable to login via SSH.
After activating SSH, it says:  `Invalid origin` and the icon is red.
Sorry, but what am I missing? 
I also tried to attaching to the container, but that didn't quite worked for me (not so experienced with docker yet).

**Comment by nachoparker** [comment]
SSH option shouldn't be there in docker, it has to be removed. Just use `docker exec -ti nextcloudpi bash` to access
