### ISSUE TITLE
Workaround for lack of NAT loopback

### ISSUE THREAD

**Issue by koen84** [nextcloud/nextcloudpi#34]
I can do DDNS and uPnP, but it seems the router doesn't support NAT loopback / hairpin NAT.  Any possible workarounds ?

**Comment by nachoparker** [comment]
Sure, you can setup a DNS server in your RPi from `nextcloudpi-config`

Details [here](https://ownyourbits.com/2017/03/09/dnsmasq-as-dns-cache-server-for-nextcloudpi-and-raspbian/)

I'll close the issue, but we can continue talking here
