### ISSUE TITLE
data dir new location error

### ISSUE THREAD

**Issue by pi930n** [nextcloud/nextcloudpi#350]
getting a error when i try to move my drive location

INFO: /media/mYcLOUD is not empty. Creating backup /media/mYcLOUD-01-09-18
mv: cannot move '/media/mYcLOUD' to '/media/mYcLOUD-01-09-18': Device or resource busy
Only ext/btrfs filesystems can hold the data directory

**Comment by nachoparker** [comment]
did you format the drive properly? please, output of

```
sudo ncp-report
```

**Comment by pi930n** [comment]
Sorry super new at at pi & linux I think I have it fixed. I didnt add ncdata on the end... thanks so much

**Comment by nachoparker** [comment]
no problem! please use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions like this in the future
