### ISSUE TITLE
what does exactly nc-fix-permissions?

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/nextcloudpi#352]
What is the objective of nc-fix-permissions?
When should i use it?

thanks

Paste the output of `sudo ncp-report`

**Comment by ovpc** [comment]
It makes sure permissions are set up correctly.
Use when you get permission errors.
All ncp-web scripts are stored in 
`/usr/local/etc/nextcloudpi-config.d/`
To view content and what the script does exactly:
`sudo cat /usr/local/etc/nextcloudpi-config.d/nc-fix-permissions.sh`
