### ISSUE TITLE
Graphic missing in shared email notification

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#36]
When sending a share to an external email user the recipient
 email has all the correct details with a banner but the graphic is broken..

<img width="240" alt="brokenbanner" src="https://user-images.githubusercontent.com/2440463/27843997-26f215c4-6113-11e7-8595-e534e47d31f5.PNG">

New fresh install, so far excellent.. Many thanks

Del

**Comment by nachoparker** [comment]
anything you configured activated in `nextcloudpi-config` or elsewhere?

**Comment by nachoparker** [comment]
probably related to #54 or #42. Will close for now. Please, reopen if it continues with the update to 12.0.1
