### ISSUE TITLE
No internet connectivity

### ISSUE THREAD

**Issue by SukerYan** [nextcloud/nextcloudpi#365]
Paste the output of `sudo ncp-report`
I very like Nextcloudpi. I don't report a issue here, just a suggestion. I know the scripts will check the internet status by ping google.com. Unfortunately I am in China. We can't visit any google service. Is it possible to change another domain to check the internet? Such as amazon.com, this is ok for Chinese people. Thanks.

**Comment by tflidd** [comment]
You can replace google.com by any other domain:
https://github.com/nextcloud/nextcloudpi/search?q=google.com&type=Code&utf8=%E2%9C%93

We could ping different services and the setup is only considered offline when all fail. Or at least take some service that is not blocked anywhere.

**Comment by SukerYan** [comment]
@tflidd Thanks.

**Comment by Pant** [comment]
I made a pull request #389 changing 'google.com' to 'nextcloud.com'.

**Comment by nachoparker** [comment]
wow didn't think of that... originally I was pinging github, but then it seems like it filters ping in some countries, like Germany, so I changed to google...

another option is to check just 8.8.8.8...

@SukerYan, can you ping 8.8.8.8 from china?

@Pant thank you for your PR!

**Comment by SukerYan** [comment]
no, i can not ping 8.8.8.8 from China. :(

2018年2月5日 20:24，"nachoparker" <notifications@github.com>写道：

**Comment by nachoparker** [comment]
can you ping 4.2.2.1 or 4.2.2.2?

**Comment by SukerYan** [comment]
they are fine. thanks.

2018年2月6日 01:19，"nachoparker" <notifications@github.com>写道：

**Comment by nachoparker** [comment]
applied in `v0.46.1`

**Comment by nachoparker** [comment]
I'll reopen and implement it a bit better, but just relying on the return value of the clone operation

**Comment by nachoparker** [comment]
Implemented in `v0.46.4`
