### ISSUE TITLE
nc-restore strange behaviour

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/nextcloudpi#374]
I've installed a fresh nextcloud instance, and then i've tried to do a nc-restore and something is not right

this is the result in terminal

![image](https://user-images.githubusercontent.com/30478928/35392471-e5cb4bf2-01d9-11e8-9c0f-aed8a6396ddc.png)
 
On the past i've made a sucessfull restore of this same tar file. So I don't get what's happening...

Someone explains me what to do?

best regards 

Paste the output of `sudo ncp-report`

**Comment by nachoparker** [comment]
well that message just means that the system has auto-updated and needs to be rebooted. It will be rebooted automatically at 4:00 am

so those messages have nothing to do with the restore process, which at the moment of the screenshot is still taking place. 

just ignore those messages and wait for the restore to finish, you can also reboot yourself
