### ISSUE TITLE
From Owncloud to Nextcloud keeping only data directory (not the database). How ?

### ISSUE THREAD

**Issue by TheTiPi** [nextcloud/nextcloudpi#39]
I’ve been using a Pi 2 + owncloud + external USB SSD (no encrypted datas) for 2 years.
I’m seting up a Pi 3 + Nextcloud (+ moved USB SSD from the Pi2).
I want the same directory with ocdata to be used by Nextcloud (not the database). I want to keep the document, photos & co at the same place.

How do I make Nextcloud scan for files in the directory and updating Nextcloud database (assuming the path is right in config.php) ?

**Comment by nachoparker** [comment]
Hi,

You can 

 - optionally, move the datadir with `nc-datadir` from `nextcloudpi-config`
 - manually copy the files to `<datadir>/username/files`
 - from `nextcloudpi-config`, run `nc-scan` to update your database with the externally copied files

See more info in [this article](https://ownyourbits.com/2017/04/18/different-ways-to-access-your-nextcloud-files/)

**Comment by TheTiPi** [comment]
Thanks
