### ISSUE TITLE
NCP based on 64 bit SUSE/OpenSUSE?

### ISSUE THREAD

**Issue by maanloper** [nextcloud/nextcloudpi#401]
### QUESTIONS

I do not know if this is the correct place to ask this, if not please direct me to the correct place.

I just installed NCP and it works pretty well, so thanks to that for everyone who made this possible. However, it does have a problem with syncing larger files (>2 GB) with the desktop (windows) client. (not browser/PHP related). It gives a "chunks on server do not sum up to X but to X" which is the same number. I read that this is because the Pi runs a 32 bit Raspbian OS which makes an integer value overflow?

Now, I was just googling around and found that SUSE/OpenSUSE have 64 bit versions running and supported for the Pi 3. I have to confess I am a complete beginner with Linux/server installations/etc, that is why I took the ready-to-use NCP image, this was my first installation.

But would it be possible to create a NCP image based on a SUSE 64 bit version that would eliminate those RPi-specific 32-bit problems?

Love to hear about the (im)possibilities!

**Comment by testbird** [comment]
IMHO the web stack is not the right thing to use for file syncing, and how many years has OC/NC sync been in this and other states?

Syncthing is much better for syncing in many ways (e.g. speed, direct local syncs without server,...). The NCP distribution has the advantage to allow syncthing to be installed in parallel (apt-get, or docker), and the files be included in NC for the web access.

**Comment by nachoparker** [comment]
please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for conversation.

We can talk there ;)
