### ISSUE TITLE
Issue with nc-database.sh?

### ISSUE THREAD

**Issue by daffyd** [nextcloud/nextcloudpi#41]
Am I just missing where the default admin passwd is ?
I ended up using 
sudo -u www-data php /var/www/nextcloud/occ user:resetpassword admin

After trying to move my database a couple of times, I dove into the code.

nc-database.sh:
  local SRCDIR=$( grep datadir /etc/mysql/my.cnf | cut -d= -f2 )

This is not going to work with:
pi@raspberrypi:~ $ grep -r datadir /etc/mysql/
/etc/mysql/mariadb.conf.d/50-server.cnf:datadir         = /var/lib/mysql

though this does:
local SRCDIR=$( grep -r datadir /etc/mysql/ | cut -d= -f2)
but then the issue is in the fixup.

I did it manually. Looks like a running system now :-)
Thanks for your efforts.

**Comment by nachoparker** [comment]
Hi,

You are right, it seems they changed the location of the configuration from `/var/lib/mysql` to `/etc/mysql/mariadb.conf.d/50-server.cnf`.

Fixed that, thank you

The default admin password is _ownyourbits_. You it is specified in the [instructions](https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/)

Thanks for digging into the code. This is becoming very popular and it is hard to keep up with everything. Any help is welcome!
