### ISSUE TITLE
Redis password is not reused

### ISSUE THREAD

**Issue by Aeon512** [nextcloud/nextcloudpi#414]
Hi,
when using the docker version and shutting down the running instance with 
`docker-compose -f <file> down`, pulling a new image `docker pull ...`, and starting up again with `docker-compose -f <file> up -d`, the new image has a new _redis_ password which does not fit to the one stored in `/data/app/config/config.php`.

As a consequence, the redis authentication fails.

Suggestion:
During startup, check if `/data/app/config/config.php` already exists, and adjust either password (I would suggest to adjust the password in the image)

**Comment by nachoparker** [comment]
good catche, we'll talk in #415
