### ISSUE TITLE
Background missing when accessing externally

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#42]
Odd one this....

If I log into my ncPI locally I get the background that I installed however when I access my site externally the back ground is missing and I just get the colour that I chose in THEMING. I can still login and everything works as normal... Any ideas what happening

Regards

Del

**Comment by deljones** [comment]
Fixed...

Did a reboot of the PI and all good

Del

**Comment by nachoparker** [comment]
Hi,

Mmmm it seems it really happens.

It has been reported before here #35 

I could not reproduce it. I will try again. If you guys are able to reproduce it that would help.

**Comment by nachoparker** [comment]
Duplicate of #35
