### ISSUE TITLE
No Web(dav) access

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#421]
Upgraded to NC13 and 46.13. Worked for about two days then suddenley no access at all via web or client. I can SSH into ncp and sometimes ncpweb but thats it, blank screen if I try any web access inside or outside my network.

If I try to nc - info i get the following:

```
Launching nc-info
Cannot load Zend OPcache - it was already loaded
Gathering information...
NextCloudPi version  v0.46.13
NextCloudPi image    NextCloudPi_12-04-17
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda sdb 
datadir              /media/USBdrive/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      25G/932G
rootfs usage         1.9G/15G
swapfile
Nextcloud check      error
HTTPD service        up
PHP service          up
MariaDB service      down
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.0.11
gateway              192.168.0.1
interface            eth0
certificates         digitalcarnage.webhop.me 
certs due            37 days 
NAT loopback         no
uptime               4min
```

I see that the database is down. 

Tried: sudo systemctl restart mysqld and got:
Job for mariadb.service failed because a fatal signal was delivered to the 
control process.

I'm lost!

Best wishes

Dj

**Comment by nachoparker** [comment]
you can check the status with

```
systemctl status mysqld
```

and the logs by running 

```
sudo ncp-report
```

**Comment by deljones** [comment]
Hi and thanks for your reply.. Please close this issue for now. I will have to reburn a card and start again.. Many thanks

Dj
