### ISSUE TITLE
recent ncp/nc on odroid HC1 notably slower

### ISSUE THREAD

**Issue by testbird** [nextcloud/nextcloudpi#423]
Has there been a relevant change in the update?
I noticed login and page loading isn't so snappy anymore with unchanged data.

**Comment by nachoparker** [comment]
So it is better now?

What update are you refering to?

https://github.com/nextcloud/nextcloudpi/blob/master/changelog.md

**Comment by testbird** [comment]
I refer to the update to NC13 and subsequent ncp-docker update. The slowdown is (still) there, despite NC13 is said to be faster. Asking if anybody else experienced this.

**Comment by nachoparker** [comment]
what's snappy? the web ui? downloads? sync?
