### ISSUE TITLE
SMB/CIFS for data directory

### ISSUE THREAD

**Issue by RyanTG** [nextcloud/nextcloudpi#424]
Is there a workaround to `Only ext/btrfs filesystems can hold the data directory`? I was hoping to use a mounted remote drive for storage. Thanks.

I mount the drive via `//192.168.1.1/unit /media/cloud cifs workgroup=WORKGROUP,users,auto,user_xattr 0 0`

and it's a nas hooked up to my router, with FS fat32.

**Comment by nachoparker** [comment]
hi,

please use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for technical questions and conversation

**Comment by RyanTG** [comment]
Hmm OK. I think nextcloud generally supports smb/cifs. But it's your https://github.com/nextcloud/nextcloudpi/etc/nextcloudpi-config.d/nc-datadir.sh script that is saying nope. I'll just set it up manually.

**Comment by theCalcaholic** [comment]
I think you can just use nc-datadir with different file formats and ignore the warning. You should just be aware that some file systems don't support the Linux permission system.
