### ISSUE TITLE
Ncp-web not displaying on retina screen ipad

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#428]
Ncp-web logs in, but this white screen is all I get.
![7981754c-3697-44a8-beb2-074a05174486](https://user-images.githubusercontent.com/1787238/36623331-83c31566-18b8-11e8-8f98-884502fb4c66.jpeg)

**Comment by nachoparker** [comment]
it should be fixed in `v0.46.34`. Please, reopen if this is not the case
