### ISSUE TITLE
document/force to secure the system with own passwords

### ISSUE THREAD

**Issue by yo-k** [nextcloud/nextcloudpi#430]
It is unclear which passwords and how they have to be changed to secure the system. Description and FAQ exists but they are not complete or outdated.

Did you know that you could log in as ncp with default password via ssh/terminal, too? This is not mentioned anywhere (2018-03-01) - or I didn't found it. Good luck with your system in the wild!

 * There should be a complete list with services/logins/ default passwords
 * There should be a complete how to to change those passwords
 * May be it would be possible to force the admin to change those passwords?

From ownyourbits site (2018-03-01). https://ownyourbits.com/2018/02/06/nextcloudpi-updated-to-nc13-brings-ufw-security-improvements-auto-snapshots-and-more/ .

In addition to the big changes, there is a small but important change: from now on, images will default to user ncp and password ownyourbits for all services, including not only the admin user of Nextcloud, but also SAMBA, ncp-web and elsewhere. As those features appeared organically each one with a different password, it became an unnecessary complication for people wanting to try out NextCloudPi for the first time.

From FAQ site (2018-03-01): https://github.com/nextcloud/nextcloudpi/wiki/FAQ
What are pre-set users/passwords on NextCloudPi?

    For ssh or terminal pi/raspberry (root/1234 on armbian)
    For nextcloudpi.local:4443 ncp/ownyourbits,
    For nextcloudpi.local ncp/ownyourbits
    For Database user is ncadmin/password is generated dynamically and stored in /root/.my.cnf

**Comment by nachoparker** [comment]
Hi, thanks for your feedback

> Did you know that you could log in as ncp with default password via ssh/terminal, too?

If you enable SSH through ncp-web or ncp-config, then it forces you to change this password. Also, this user has no privileges whatsoever.

The wiki is open for anyone to contribute, so if you found something missing or confusing, please feel free to improve the documentation for the rest of the community!
