### ISSUE TITLE
[Maybe critical] md5sum is different between the img and the md5sum file. 

### ISSUE THREAD

**Issue by prog-amateur** [nextcloud/nextcloudpi#432]
Hi, when I download the latest image of NexcloudPi 02-06-18 at [ownyourbits](https://ownyourbits.com/downloads/NextCloudPi_02-06-18/), the md5sum file mentions `94ef1d010a7b0f676202b205f07cb319` while the terminal command md5sum of the img file displays `fff0c97d9d4eaa64ab79333db02afd81`. 

Is it normal ? Is the repo safe ? Did I tried the wrong method ? 

Thank you.

**Comment by Pant** [comment]
The md5sum is for the compressed file, the one you download, not the img file!

**Comment by prog-amateur** [comment]
Thank you very much. I apologize for this mistake, and I am happy to see that the compressed file md5sum matched with the one in the file.
