### ISSUE TITLE
Initial installation for raspberry PI3 failed with  etc/nextcloudpi-config.d/nc-nextcloud.sh: line 89: /usr/lib/systemd/system/nc-provisioning.service: No such file or directory

### ISSUE THREAD

**Issue by asv285041** [nextcloud/nextcloudpi#433]
Hey,

i have rasPI3 and latest image Raspi lite 
when i start script i faced with error below

Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
./etc/nextcloudpi-config.d/nc-nextcloud.sh: line 89: /usr/lib/systemd/system/nc-provisioning.service: No such file or directory

Checked folders and there is no such folder /usr/lib/systemd/system

So error appears and cannot continue installation. 
if you create this folder - installation can be started again and continue

**Comment by wouterbr** [comment]
Hi theresame here;
Executing: /lib/systemd/systemd-sysv-install enable redis-server
./etc/nextcloudpi-config.d/nc-nextcloud.sh: line 89: /usr/lib/systemd/system/nc-provisioning.service: No such file or directory

**Comment by fspin** [comment]
this is a quickfix: 

in my case i had to create the folder `system`
`mkdir /usr/lib/systemd/system`

and touch the file:
`touch /usr/lib/systemd/system/nc-provisioning.service`.

after that, you'll be able to run the script again.

**Comment by nachoparker** [comment]
Fixed in `v0.46.36`.

Thanks for reporting
