### ISSUE TITLE
user pi sudo &&  slow outside access

### ISSUE THREAD

**Issue by luckymedog** [nextcloud/nextcloudpi#436]
1) Will nextcloud, db, postfix, etc work if I disable sudo for user pi (or remove pi user completely)

2) Forwarded ports on router & accessed nextcloud from internet, but logging into nextcloud stuck/timed-out
Removed user ncp as admin
Enabled UFW (changed all ufw before.rules for icmp to DROP) and fail2ban
Changed config.php for allowed domain (1=> mydomain.com)
Could any of these be causing the inability to login to nextcloud?

3) Never able to login to nextcloudpi.local:4443

**Comment by nachoparker** [comment]
please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions.

thanks!
