### ISSUE TITLE
How to setup Nextcloud Pi on Banana pi M2U

### ISSUE THREAD

**Issue by prog-amateur** [nextcloud/nextcloudpi#442]
Hello, thank you very much for your Nextcloudpi. This "issue" is not a real one, just a question. 

I struggle to install Nextcloudpi on a Banana pi M2 Ultra. This board has an Allwinner R40 SoC (ARM Cortex A7), they say it is fully compatible with Raspbian. 

So I guessed Nextcloupi would run on it, however when I flash the Raspbian 9 version of Nextcloudpi image, the Banana pi doesn't boot. 

Please, how can I flash the image ? I would like to avoid the docker version as the the maker is not willing to upgrade Raspbian/Ubuntu MATE OS (it is still 16.04). Thank you very much for your help.

**Comment by nachoparker** [comment]
There is no image for the Banana Pi. This board is supported by armbian, so [images could be built for it](https://ownyourbits.com/2017/12/04/nextcloudpi-comes-nc-12-0-4-odroid-hc1-and-armbian-support-btrfs-snapshots-diagnostics-tools-and-an-awesome-case/) if there were someone volunteering to do that.

What you can do is to install a Debian 9 image for the Banana Pi, and then run

```
# curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash
```

For questions, better to use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)
