### ISSUE TITLE
using x86 docker image, got "Error MySQL/MariaDB enter the database username and name."

### ISSUE THREAD

**Issue by carlhung** [nextcloud/nextcloudpi#444]
I followed the link:
https://ownyourbits.com/2017/06/08/nextcloudpi-docker-for-raspberry-pi/
to install step by step.

I also move the root dic of the docker that also following the link to move the root dic to external HDD.

I can successfully see the site, I typed the username and password, then, I got this error on top of username field and below the Nextcloud's logo:
username field: admin or ncp
password: ownyourbits
Error MySQL/MariaDB enter the database username and name.

**Comment by nachoparker** [comment]
you need to wait until you see 'nc init done' in the logs the first time

**Comment by carlhung** [comment]
I can't even login. where to find "nc init done"?
thanks
