### ISSUE TITLE
Updating error log

### ISSUE THREAD

**Issue by StefvanEgmond** [nextcloud/nextcloudpi#445]
Hai,

I updated my pi with some difficulties, the updater stopped and I needed to login into SSH and disable maintenance and resume the updater. Now, I jumped into my logs and found this:

> OC_USER_SQL | Failed to connect to the database: Unsupported type:

This is being echo'd every 100 mm I think...

Running cloud v13.0.1 and NextCloudPi v0.47.3

**Comment by nachoparker** [comment]
hi, this seems to be an issue more related to the web updater itself. You can try in the [forums](https://help.nextcloud.com) or the nextcloud updater github issue tracker.
