### ISSUE TITLE
successfully run x86 nextcloudpi container. but what are login, password, database, etc?

### ISSUE THREAD

**Issue by carlhung** [nextcloud/nextcloudpi#447]
I successfully run the x86 container.
but I can't login without the information below for the first time:
username
password
database user
database password
database name
database host

I need the information above to login.
I can't just type in username and password to login. I will get error.
username: ncp or admin
password: ownyourbits
not enough information to login.
I got this error: Error MySQL/MariaDB enter the database username and name.

**Comment by nachoparker** [comment]
you have to wait reading the docker container logs until the message nc-init the first time. You might have to completely remove the volume first.

you do not need database info, it is automatically done for you the first time. for the rest... read the wiki

please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions
