### ISSUE TITLE
Manually trigger nc-scan remotely?

### ISSUE THREAD

**Issue by ro-76** [nextcloud/nextcloudpi#452]
Is it possible to trigger a manual scan remotely without accessing the configuration web ui? I.e. Can I trigger it from within the nextcloud Web user site?

**Comment by theCalcaholic** [comment]
You can not trigger our manage ncp-apps from the nextcloud web site.

However you could log into your server with ssh and type `sudo ncp-config`. That will give you a command line version of the administration web ui (ncp-web).

If you're on windows you can use putty as ssh client, although windows 10 supports ssh natively I believe.

I think, we have an article about this in the wiki, let me see...

**Comment by ro-76** [comment]
Thanks for the reply.  I'm not that comfortable exposing SSH to the internet. I was hoping it could be triggered from within the user web ui.

**Comment by nachoparker** [comment]
@ro-76 you can also trigger it every X days with the feature `nc-scan-auto`.

Also note that SSH configuration has been hardened in NCP, and you could also further enhance it by disabling password logins.
