### ISSUE TITLE
Not able to format Drives in NCP

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#456]
I have come across an issue regarding formatting drives.

So I have i USB drive called myCloudDrive which as my NCP, database and ncdata.. All good.
I switch off the pi unplug the drive and plug in a new blank USB drive (1TB) which will be my back up. I will call it ncpbackup. When I start the format I fill in the name of the drive and hit return but get back the following message:

ERROR: Counted 5 devices. Please, only plug in the USB drive you want to format.

It is the only USB drive plugged in. When I unplug it the Counted devices drops to 4.

The only storage drives plugged in to the pi is a fresh SD card with ncpi and a blank USB drive. Have I missed a step somewhere? 

Thanks
DJ

**Comment by nachoparker** [comment]
what is the output of

```
lsblk -l -n
```

**Comment by nachoparker** [comment]
I'll close because of cleanup, you can continue when you have the time

**Comment by nachoparker** [comment]
There was a fix for a similar situation when the power is cut without shutting down the pi. Probably your issue was the same

**Comment by TomTurnschuh** [comment]
This issue also occurs, if the drive should be formated while ZRAM is enabled.
