### ISSUE TITLE
Webfilter workaround

### ISSUE THREAD

**Issue by ro-76** [nextcloud/nextcloudpi#458]
I have my NCP setup at home and have a ddns address setup with no-ip to access from outside, which is working great. 

I also have my own domain (managed by godaddy) and have a subdomain setup to forward to the ddns address. 

The issue is that I cannot access a ddns address from my work LAN because the webfilter blocks ddns under the category 'webhosting '. I can access my home IP directly OK.

I added my home IP under 'trusted_domains'. I also setup another subdomain to direct to the home IP. This now works ok from my work LAN using either the IP or the subdomain linked directly to the IP, with the one small issue that the letsencrypt certificate is invalid. 

Is there a mechanism that I can have the certificate updated to the IP address in an automated manner? Is there any other workaround for this?

Thanks!

**Comment by nachoparker** [comment]
certificates are linked to domains, not IP addresses so I don't see a workaround

In any case, please use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions, and github for bug reports.
