### ISSUE TITLE
How to install Etherpad (Lite) / Ownpad

### ISSUE THREAD

**Issue by R4U5CH1337** [nextcloud/nextcloudpi#462]
Hi there

I was wondering how to install the Ownpad / Etherpad app?
Is there any tutorial for the NextcloudPi? 
I don't like any experiments (by my own), because I'm happy with my running config and also kinda noobish with extra installs.
Is node.js already installed on the NCPi?
What else do I need to know?

Thanks so much.

**Comment by nachoparker** [comment]
please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions
