### ISSUE TITLE
keep stopping in the initialiing page, any idea to solve?

### ISSUE THREAD

**Issue by kentcc88** [nextcloud/nextcloudpi#483]
i run the following commond on my raspberry pi 3B + (made in UK):
`docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi-armhf 192.168.3.231`
everything is ok when i install, and the docker is running well.

when i open the the page on the browser "https://192.168.3.231:4443", it is working, but, when i open the homepage of the nextcloud "https://192.168.3.231", it stops on the initializing page and keeps refreshing itself, don't know what happen. Can anybody help or have any idea on it?
![20180418000105](https://user-images.githubusercontent.com/18288037/38944320-2c3aa6fa-4366-11e8-8095-8c070e9079ce.png)

**Comment by nachoparker** [comment]
first time initialization can take a long time.

you can check with `docker logs -f nextcloudpi` what's going on
