### ISSUE TITLE
Wrong docker commands on main site

### ISSUE THREAD

**Issue by Robert-turbo** [nextcloud/nextcloudpi#486]
Hi,

on https://ownyourbits.com/nextcloudplus/ there is

`docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v ncdata:/data –name nextcloudpi ownyourbits/nextcloudplus-x86 $DOMAIN
`

but should be `--name` instead of `–name`

**Comment by nachoparker** [comment]
woops, somehow pasting it into the blog converted it into a long hyphen `--` `–`

fixed, thanks!
