### ISSUE TITLE
USB only

### ISSUE THREAD

**Issue by Brennii96** [nextcloud/nextcloudpi#491]
Is it possible to ditch the SD card and use just the external USB hard drive to run nexcloudpi? 

I've ran out of storage on my 32GB SD card for some reason and want to drop it altogether and move it all onto my external USB HDD so I don't run into this again. 
I'm assuming I would need to disable the auto mounting feature for this to work and all the mount things to USB?

**Comment by nachoparker** [comment]
You can use the berryboot version. 

Please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions and conversation
