### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")

### ISSUE THREAD

**Issue by ilkkaya** [nextcloud/nextcloudpi#493]
pi@raspberrypi:~ $ docker logs -f nextcloudplus
Making /etc/shadow persistent ...
Starting PHP-fpm
Starting Apache
AH00534: apache2: Configuration error: No MPM loaded.
Action 'start' failed.
The Apache error log may have more information.
Provisioning
Provisioning Redis password
Provisioning MariaDB password
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
PHP threads set to 4
Starting Redis
Starting Cron
Starting Postfix
Uninitialized instance, running nc-init...
Activating nc-init
Setting up a clean Nextcloud instance... wait until message 'NC init done'
Setting up database...
2018-04-27 17:49:43 1995796480 [Note] mysqld (mysqld 10.1.26-MariaDB-0+deb9u1) starting as process 198 ...
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
Init done

i need help

**Comment by nachoparker** [comment]
please, reopen if you still see this
