### ISSUE TITLE
Question: How to configure Apache Reverse Proxy for Docker access

### ISSUE THREAD

**Issue by TimmThaler** [nextcloud/nextcloudpi#496]
Hi there,

I tried a lot of things already, but I don't get it running. So I just ask here, perhaps somebody can help me.

My configuration is the following:
- I installed the NextcloudPi SD card image and everything is running very well.
- Then I installed Docker and installed an ebook library image/container which I can access via the configured port. And again, everything is working wonderfully.

Now, I would like to access the ebook library docker container via mycloud.url/library, but I'm having problems to configure the Apache Reverse Proxy right.
I tested copying
> ProxyPass         /library http://127.0.0.1:8080/library
> ProxyPassReverse  /library http://127.0.0.1:8080/library

into the nextcloud.conf and into a new conf file and the configuration from [here](https://airsonic.github.io/docs/proxy/apache/), but when I try to load mycloud.url/library in my browser, I'm always redirected to the Nextcloud login screen.

I already consulted the Apache Documentation, Documentations to other docker images etc.

Does somebody of you got an idea how to do this correctly? I just don't get any further.
Any help would be great!

Best regards :smile:

**Comment by nachoparker** [comment]
Hi,

Better to use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for consultation.

Thanks ;)
