### ISSUE TITLE
Docker image nextcloudplus based on debian instead of raspbian?

### ISSUE THREAD

**Issue by P4yload** [nextcloud/nextcloudpi#498]
Hi pulling the new 13.0.2 image from
https://hub.docker.com/r/ownyourbits/nextcloudplus-armhf/
gives a debian 9.4 jessie image (using the lsb_release -a command) instead of raspbian. No wonder that syncing files crashes the container since debian docker container (on top of raspbian) cant handle it. The previous nextcloudpi docker image 13.0.0 was based upon raspbian and worked fine. 

Is this your intention? Should the docker image not be based on raspbian instead of debian since it's more lightweight?

Thanks!

Paste the output of `sudo ncp-report`

**Comment by nachoparker** [comment]
Hi,

> Is this your intention? Should the docker image not be based on raspbian instead of debian since it's more lightweight?

raspbian is debian, and it's not more lightweight. Actually, the armhf docker container for debian is really small, and there is no raspbian container out there that is that small. I used to create mine, but then debian kept improving their containers to the point that they are 50 MB now.

If it crashes it must be for other reasons. Please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions and conversation.
