### ISSUE TITLE
Missing access to apps

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#50]
Done my third install today, due to my own stupidity. As a result I know what should be in the apps library to enable and what isn't... I have finally got a complete secure install but noticed on this one I am missing a bunch of apps like, Weather, Notes, and a bunch more on top...

Has anyone had a similar experience and is there a way to refresh or get access to these missing apps to install them
Del

**Comment by nachoparker** [comment]
I can see them all... Notes is there under "office & text'

Reopen if this is not the case for someone

Thanks for feedback again
