### ISSUE TITLE
[HC2] SSH shut down automatically

### ISSUE THREAD

**Issue by traptoo** [nextcloud/nextcloudpi#505]
First of all: nice work!

Got a problem to connect to a fresh NCP install on a HC2.
Web interface works well, but when i activate the SSH option and try to connect with putty after changing the password putty instantly shut down. 
No way to connect with SSH. Any idea?

**Comment by nachoparker** [comment]
thanks!

the ideal place for questions is the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm), please ask there in the future.

the first time you connect it forces you to change the password. The second time, you can access with the newly changed password
