### ISSUE TITLE
can not reach another webinterface - it craches apache 

### ISSUE THREAD

**Issue by Peter753** [nextcloud/nextcloudpi#509]
Hello and thank you for this realy nice projekt.
I would like to insall backupPc but unfortunately it crashes apache.

May 19 13:48:40 nextcloudplus apachectl[1899]: AH00526: Syntax error on line 1 of /etc/apache2/conf-enabled/backuppc.conf:

I deletet this file and now it works again, but I could not start the webinterface from BackupPC.
Has anybody an idea how to modify the apache files to reach this webinterface?
Normaly it shold be something like: mywebsite/backuppc …

Thanks in advance
Peter
``
This is my /etc/apache2/conf-enabled/backuppc.conf
```
Alias /backuppc /usr/share/backuppc/cgi-bin/

<Directory /usr/share/backuppc/cgi-bin/>
	AllowOverride None
	Allow from all

        # Uncomment the line below to ensure that nobody can sniff importanti
        # info from network traffic during editing of the BackupPC config or
        # when browsing/restoring backups.
        # Requires that you have your webserver set up for SSL (https) access.
        #SSLRequireSSL
					
	Options ExecCGI FollowSymlinks
	AddHandler cgi-script .cgi
	DirectoryIndex index.cgi

        AuthUserFile /etc/backuppc/htpasswd
	AuthType basic
	AuthName "BackupPC admin"
	require valid-user

</Directory>
```

**Comment by nachoparker** [comment]
Hi,

This is not a specific NCP bug, so better ask for help in the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)

;)
