### ISSUE TITLE
Arbitrary File Read

### ISSUE THREAD

**Issue by ProDigySML** [nextcloud/nextcloudpi#519]
# The Issue
An attacker can arbitrarily read files (which the user running the web application has permission to read) using unsanitised user input passed to the `file_get_contents` PHP function

# Where the Issue Occurred
An attacker can control the file path of a file using the line of code below:
https://github.com/nextcloud/nextcloudpi/blob/6600972eb07a743ac3b796342c5b07d6c762ba93/ncp-web/ncp-launcher.php#L104

This variable is then passed to the `file_get_contents` PHP function and reads the files
https://github.com/nextcloud/nextcloudpi/blob/6600972eb07a743ac3b796342c5b07d6c762ba93/ncp-web/ncp-launcher.php#L110-L111

As displayed above, `.sh` is appended to the file name, however this can be bypassed (in some versions of PHP) using a null byte terminator (`%00`)

**Comment by nachoparker** [comment]
fixed in `v0.56.17`

thanks for reporting!
