### ISSUE TITLE
Download md5sum Mismatch

### ISSUE THREAD

**Issue by cottoa00** [nextcloud/nextcloudpi#52]
Hello... love the work your doing. Was so excited to find an alternative to the Ubuntu Core (and Ubuntu One SSO reqmt) ;-)

My problem is when I downloaded the tar.bz2 and untar'd it, I got the folowing md5sum;
5fb9f9ce68d64e0889e7c416e3b2c6c6  NextCloudPi_06-28-17.img

From the website it says I should get;
2217552d5d33b927e3c85a5c5953984

Did a second download (sorry no Torrent but made a donation ;-) and got the same result?

**Comment by nachoparker** [comment]
Haha thank you, and thanks also for contributing!

`2217552d5d33b927e3c85a5c5953984`... is the checksum of the download, this is, the md5sum of the `tar.bz2` file.

Not the first person to ask this, so I am glad it will remain registered in github as a `question`

Working on some new stuff! ;)
