### ISSUE TITLE
Reflected XSS

### ISSUE THREAD

**Issue by ProDigySML** [nextcloud/nextcloudpi#520]
# The Issue
NextcloudPi allows users to pass input to its scripts, however these inputs are overly trusting. The inputs are not sanitised which can allow an attacker to execute JavaScript code in the context of a user's browser. This could be used to steal cookies and content from the victim's browser. 

# Where the Issue Occurred 
The overly permissive usage of the `$_POST['ref']` variable can be seen below:
https://github.com/nextcloud/nextcloudpi/blob/6600972eb07a743ac3b796342c5b07d6c762ba93/ncp-web/ncp-launcher.php#L132

**Comment by nachoparker** [comment]
fixed in `v0.56.17`

thanks for reporting!
