### ISSUE TITLE
Command Injection

### ISSUE THREAD

**Issue by ProDigySML** [nextcloud/nextcloudpi#521]
# The Issue
An attacker can use the `$_POST['ref']` variable to inject commands, allowing the attacker to execute arbitrary commands on the server. Usually these commands would run in the context of the user running the commands, however NextcloudPi runs the injectable command with `sudo` allowing the attacker to gain root privileges. 

# Where the Issue Occurred
An attacker can use the `$_POST['ref']`  variable to control the content of the `$file` variable:
https://github.com/nextcloud/nextcloudpi/blob/6600972eb07a743ac3b796342c5b07d6c762ba93/ncp-web/ncp-launcher.php#L104

The `$file` variable is then used within the call to the `exec` without proper sanitisation:
https://github.com/nextcloud/nextcloudpi/blob/6600972eb07a743ac3b796342c5b07d6c762ba93/ncp-web/ncp-launcher.php#L136

**Comment by nachoparker** [comment]
fixed in `v0.56.17`

thanks for reporting!
