### ISSUE TITLE
help for login

### ISSUE THREAD

**Issue by xinyan3** [nextcloud/nextcloudpi#522]
i cant login nextcloud when i first dock success.i can`t input activate page and can`t have username and pswd.please help me  i use images latest .and i container with portainer . mapping three: 3333:80 3334:443 3335:4443  at CMD i give 192.168.99.153. my docker portainer is work on 192.168.99.153..this is all i make .and at least ,help me

**Comment by xinyan3** [comment]
i fix it !

**Comment by nachoparker** [comment]
good! please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for help and questions in the future
