### ISSUE TITLE
Enabling SSH fails with a "<user> doesn't exit" error

### ISSUE THREAD

**Issue by BlinkyBillToo** [nextcloud/nextcloudpi#526]
I am unable to login via ssh to run `sudo ncp-report`.

I'm unable to enable SSH via the nextcloudPi web panel, the process fails with a "'user' doesn't exist" error for both pi and a new user.

I'm running the following configuration on an Odroid HC2:
![image](https://user-images.githubusercontent.com/23483257/40892128-416e50ee-6760-11e8-9b0a-dcef98bd1ac4.png)

When I try enabling with the pi user the results are:
![image](https://user-images.githubusercontent.com/23483257/40892134-52765828-6760-11e8-802b-731c48194f7f.png)

When I try enabling SSH with a new user the results are:
![image](https://user-images.githubusercontent.com/23483257/40892116-120074cc-6760-11e8-83ce-3316f6744ab8.png)

**Comment by nachoparker** [comment]
in armbian, there is no `pi` user. You can set the password for the `root` user
