### ISSUE TITLE
static IP adress with nc-static-ip on an Odroid HC2 failed

### ISSUE THREAD

**Issue by clown522** [nextcloud/nextcloudpi#528]
Hi,
thank you for your hard effort! This helped me a lot to create my own NextCloud-Server.

I had some problems with the static ip with your newest nexcloudpi image (v0.56.15), because he did not found eth0.

i decided to search with: 

1. ifconfig -a

my controller is called: enx001e06328ba8 instead of eth0, so i edited this file:

2. sudo nano /etc/network/interfaces

3. i replaced everything eth0 to enx001e06328ba8.

4. sudo reboot

Maybe somebody else has this problem too with Odroid.

**Comment by nachoparker** [comment]
Hi @clown522 

Indeed, eth0 is [hardcoded](https://github.com/nextcloud/nextcloudpi/blob/master/etc/ncp-config.d/nc-static-IP.sh#L78) in the current version.

We would need to detect it for each different system instead. This seems like a good first contribution if anyone is interested ;)

Again, thanks for the valuable feedback!

**Comment by nachoparker** [comment]
fixed in `v0.57.2`
