### ISSUE TITLE
How to use SAMBA on nextcloudpi?

### ISSUE THREAD

**Issue by clown522** [nextcloud/nextcloudpi#529]
Hi,
sorry for asking but how does your samba at the nexcloudpi panel works?

Which path can i mount under windows?
for example this does not work for me:
\\ip-nextcloud\
\\ip-nextcloud\media\Nextcloud_Drive

thank you very much for your support!

EDIT: i know it, you have to go to: sudo nano /etc/samba/smb.conf
and look at the samba shares.

**Comment by StefvanEgmond** [comment]
Still not sure where to look at.

**Comment by ovpc** [comment]
Not much, but[ all there is right now](https://github.com/nextcloud/nextcloudpi/wiki/Configuration-Reference#samba)

**Comment by nachoparker** [comment]
this is a bit outdated, but could help https://ownyourbits.com/2017/04/16/share-your-files-in-your-lan-with-samba/
