### ISSUE TITLE
fail2ban invalid input at the nextcloudpi-panel

### ISSUE THREAD

**Issue by clown522** [nextcloud/nextcloudpi#530]
Fail2Ban works as intended but i can not update my settings which are still working.
i only get: invalid input. It does not make any difference, which data i want to change. It resets all changes instantly after one refresh.
I restarted fail2ban already.
It also bans as intended and knows where my data and log are mounted.
Thanks for your help!
I use: Odroid HC1 with v.0.56.18
Is it possible that my first config does not work properly  because of the mail. i get at this log:

EDIT: works with ssh: sudo ncp-config
![fail2ban](https://user-images.githubusercontent.com/24324981/41102684-b6cb600c-6a67-11e8-9281-ac66426f2323.PNG)

**Comment by nachoparker** [comment]
Thank you for your feedback.

You found a bug. I introduced some security sanitizing and it wasn't well adjusted to fail2ban.

It should be fixed by upgrading to `v0.56.20`.

Thanks again
