### ISSUE TITLE
Update to NextCloud 13.0.3 not offered

### ISSUE THREAD

**Issue by Aeon512** [nextcloud/nextcloudpi#537]
Nextcloud 13.0.3 is available since June 7th.
But neither the nc-update in ncp nor the build-in updated in nextcloud offers this version as an update.
They still claim the version is up-to-date...

But scan.nextcloud.com reports correctly that this version is not on the latest patch level.

What's going wrong here?

**Comment by ovpc** [comment]
`sudo ncp-update`
should update you to version v0.56.18 of NCP from command line.

Updating Nextcloud to 13.0.3 is done from the admin page once logged into your NC instance go to >settings>basic settings. You can launch update from there. It may take some time for it to become available everywhere, depending location. In mine it is not yet available at the moment.

**Comment by Aeon512** [comment]
NCP is up to date with v0.56.18 that's not the issue.
However, I expect that under >settings>basic settings the updater will over me 13.0.3?
It has already been released 3 days ago...

But if I get you right it is normal that it will take some time to become available, correct?

**Comment by ovpc** [comment]
Yes that is correct and it is really a general NC question, please use [help.nextcloud.com](https://help.nextcloud.com/) Thanks
