### ISSUE TITLE
Changed router, no longer connecting, externally

### ISSUE THREAD

**Issue by shadowstreik** [nextcloud/nextcloudpi#542]
Good morning.
I changed routers, yesterday, and can no longer connect, externally (from internet).

I updated config.php with the new internal IP info, forwarded the ports, still no connection, externally.

Would something in LetsEncrypt require updating?

Is there a set of instructions of some type that covers what to do when changing routers? I've looked, here, but can't seem to find something that would apply.

Thank you.

**Comment by nachoparker** [comment]
hi,

for questions like this, better use the [forums,](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) you will get much more help
