### ISSUE TITLE
ncp/ownyourbits does not work at first start-up

### ISSUE THREAD

**Issue by c-val** [nextcloud/nextcloudpi#544]
Hi,

I followed today the docker-arm tutorial https://ownyourbits.com/2017/06/08/nextcloudpi-docker-for-raspberry-pi/
I followed instructions down to : 
"The admin user is ncp, and the default password is ownyourbits. Login to create users, change default password and other configurations."

But the ncp/ownyourbits login does not seem to work int the login web interface.

I have no idea how to login otherwise.

Thank you for any help!

**Comment by nachoparker** [comment]
Hi, 

That info is a bit updated. You should be faced with an activation page where you are presented with random passwords that you have to write down.

In any case, please use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for general help

Cheers!
