### ISSUE TITLE
 Data moved to USB drive but remains on SD Card as well - How to remove?

### ISSUE THREAD

**Issue by PStewardYUL** [nextcloud/nextcloudpi#545]
I recently moved all my data from the internal SD card to an externally mounted USB drive however it appears that the data stayed on the SD Card. How can this be purged from the SD card without affecting the installation?

```
automount | yes
USB devices | sda
datadir | /media/USBdrive/ncdata
data in SD | no
data filesystem | btrfs
data disk usage | 38G/299G
**rootfs usage | 28G/30G**
swapfile | /var/swap
Nextcloud check | ok

```

Thanks,

--Phil

**Comment by nachoparker** [comment]
It should be safe to delete stuff from `/var/www/nextcloud/data`

please, use the [forums](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions
