### ISSUE TITLE
Add database location to System Info

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/nextcloudpi#546]
I moved it to my USB hard drive, but can't see evidence of that on the System Info summary like I can for datadir. It would be nice to see it there. That's all.

**Comment by nachoparker** [comment]
good idea

**Comment by nachoparker** [comment]
would you be brave enough to make this change and send me a PR? ;)

**Comment by bernd-wechner** [comment]
Brave enough yes, but low on time for it right now, would have to set up a dev environ for it first. Might get around to it in time if no-one else has.

**Comment by nachoparker** [comment]
alright! I am short on time myself too, but there's no hurry. I don't think you need a separate environment for this. Just backup the `/usr/local/bin/ncp-diag` and play around with it ;)

**Comment by kanuahs** [comment]
added in #553

**Comment by nachoparker** [comment]
> added in #553

true! thanks again
