### ISSUE TITLE
ncp-config programs fail to match passwords when they have spaces

### ISSUE THREAD

**Issue by JVAQUEROM** [nextcloud/nextcloudpi#565]
I have realized that the programs in ncp-config that change your password (ssh, nc-password,..) they fail when your password uses spaces. It takes the first "word" as first input and the second as the "repeat password". So it fails.

**Comment by mschilli87** [comment]
@JVAQUEROM: Seems to me like escaping the spaces as `\ ` or quoting the whole password in `'`...`'` should fix the issue.

**Comment by JVAQUEROM** [comment]
I tried using double quotes `"..."` and that didnt work. I'll try the other

**Comment by nachoparker** [comment]
hi, I am assuming you are doing this from the terminal, with `ncp-config` right? because ncp-web wouldn't even let you try to use spaces.

**Comment by JVAQUEROM** [comment]
yes, from the terminal. By the way, the other options do not work either.

**Comment by nachoparker** [comment]
what other options?

**Comment by mschilli87** [comment]
@nachoparker: I guess escaping via `\ ` or `'`...`'` instead of `"`..`"`:

@JVAQUEROM 
> I tried using double quotes "..." and that didnt work. I'll try the other

**Comment by nachoparker** [comment]
well, I'll see if I can correct this behaviour without need to escape anything

btw, thanks for reporting!!

**Comment by JVAQUEROM** [comment]
I thought I had answered. The escaping via `\` didn't work and the `'...'` didn't either, as @mschilli87

**Comment by nachoparker** [comment]
I just looked at this, and the way things are coded now, spaces cannot be supported. I have added a check though for spaces as an invalid character.

Thank you for the feedback!
