### ISSUE TITLE
No Auto-Update for spdyn DynDNS Provider

### ISSUE THREAD

**Issue by RiSK1979** [nextcloud/nextcloudpi#569]
I'm using my Odroid HC2 with latest NCP installation for 2 weeks now and I have noticed that my DynDNS-Account at spdyn.de is not automatically updating, once my IP changes.

I got into my account settings in NCP WbUI and was able to perform a manual update, but while being in the menu I noticed that - unlike any other DynDNS Provider supported in NCP - the spdyn entries show no update interval and does not allow for changing it. Does that mean that NCP doesn't support auto-updates for spDyn or is that a bug?

**Comment by nachoparker** [comment]
Hi,

Please, use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions.

As indicated in the instructions when you open an issue, this is only for bugs and feature requests.

Thanks!
