### ISSUE TITLE
Url rewriting not working

### ISSUE THREAD

**Issue by docteurem** [nextcloud/nextcloudpi#570]
Hello,
I'd like to remove the "index.php" part of my ncp URL. I've already added "'htaccess.RewriteBase' => '/'" into the config.php file of nextcloud and ran "sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess"; the htaccess is successfully updated but the index.php is still there, in every url of my nextcloud instance.
I checked the virtualhost file of apache and "AllowOverride All" is there. 
Any suggestion is welcome!

**Comment by nachoparker** [comment]
Hi,

Please, use the forums for this kind of technical support. Thank you!
