### ISSUE TITLE
Letsencrypt issue

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#586]
Hi

I'm not able to renew my Letsencrypt certificate. I get the following error:

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: digitalcarnage.webhop.me
   Type:   unauthorized
   Detail: Invalid response from
   http://digitalcarnage.webhop.me/.well-known/acme-challenge/05zHN-V4P_aPBJ9WtjMrTBzdqhgzxB8K8unsNyfbgGk:
   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
   <html><head>
   <title>404 Not Found</title>
   </head><body>
   <h1>Not Found</h1>
   <p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
Done. Press any key...

If I'm correct the Port Forwarding has to work for the Letsencrypt certificate to work? I've changed isp recently and all ports are open however when I run Port Forwarding it fails with the following error:

Launching nc-forward-ports
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46/desc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46_ptm0/WANPPPConn1.ctl
Local LAN ip address : 192.168.0.11
UPNP_DeletePortMapping() returned : 501
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46/desc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46_ptm0/WANPPPConn1.ctl
Local LAN ip address : 192.168.0.11
UPNP_DeletePortMapping() returned : 501
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46/desc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46_ptm0/WANPPPConn1.ctl
Local LAN ip address : 192.168.0.11
ExternalIPAddress = 31.185.210.255
AddPortMapping(443, 443, 192.168.0.11) failed with code 501 (Action Failed)
InternalIP:Port = :0
external 31.185.210.255:443 TCP is redirected to internal :0 (duration=0)
upnpc : miniupnpc library test client. (c) 2005-2014 Thomas Bernard
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46/desc.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:2555/upnp/DSLF_PlusnetHubOne-1_A0-39-EE-72-26-46_ptm0/WANPPPConn1.ctl
Local LAN ip address : 192.168.0.11
ExternalIPAddress = 31.185.210.255
AddPortMapping(80, 80, 192.168.0.11) failed with code 501 (Action Failed)
InternalIP:Port = :0
external 31.185.210.255:80 TCP is redirected to internal :0 (duration=0)
Done. Press any key...

I can access externally but unsecured (http) Any ideas appreciated...

Del

**Comment by ovpc** [comment]
Thanks for reporting.
Looks like you will have to manually set port forwarding. (Login at 192.168.0.1)
Both ports 80 and 443 have to be forwarded to the local LAN ip address (192.168.0.11) for letsencrypt renewal to work.
Suggest you look for "how to" on help.nextcloud.com, [telegram](https://t.me/NextCloudPi)  or search web with : how to port forward with <your new ISP name> and <router-model>.
I am closing this now here, as it seems it is not an issue or a bug, you can still answer or reopen if it turns out otherwise.
