### ISSUE TITLE
Cannot log in to users after sharing

### ISSUE THREAD

**Issue by new-on-github** [nextcloud/nextcloudpi#59]
I have a Problem:

Situation: I create a new user, log the new user in, everything seems fine.

Problem: After sharing something with the new user, the log-in doesn't work any more. The web gui says

> Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.4.25 (Raspbian) Server at [...]

After unsharing, the user can log in again.

My configuration: nextcloudpi on 64GB sd-card, everything in the standard config, nothing else on the raspberry, raspberry up to date trough apt-get update/upgrade, nextcloud up to date through the build in tool, database on an external usb-hdd through the build in tool

**Comment by new-on-github** [comment]
Sorry, was my fault!

**Comment by nachoparker** [comment]
haha thanks, I'll test this soon

**Comment by new-on-github** [comment]
If I share something from a "normal"-user to the admin-account, the log in to the admin-account also fails.
--> Sharing seems to be impossible...

**Comment by new-on-github** [comment]
Any news on this problem?

**Comment by nachoparker** [comment]
Hi,

I have tested manually with a fresh installation and could not reproduce this problem. Steps I took

 - log in admin user
 - create test user
 - upload a small file
 - share with test user
 - log in test user -> ok
 - upload a small file
 - share with admin user
 - logout and in with admin user -> ok
