### ISSUE TITLE
Grouping of configuration items

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#593]
Some kind of grouping of the configuration items would be nice.
E.g. all the DDNS options could be grouped together.

**Comment by testbird** [comment]
Right, same issue in the freedombox debian project:
https://salsa.debian.org/freedombox-team/plinth/issues/1226

**Comment by nachoparker** [comment]
Hi,

Thanks for the suggestion. This has already been suggested in #177. We included this as part of #380 because it requires a deep redesign.
