### ISSUE TITLE
SMB External Storage

### ISSUE THREAD

**Issue by superstardj1979** [nextcloud/nextcloudpi#608]
Just sharing what I've encountered.
I've spent this weekend reinstalling my home cloud with the current image of nextcloudpi and for the life of me could not make the SMB external drive work. After trying to use the FTP function (that took forever to load adn eventually didn't work) I've downgraded the nexcloud from 13 to 12.0.4. First try and the SMB function worked. Don't know if it's a nextcloud issue or something else. Just sharing because I've looked averywhere for a solution and could not find any. Maybe there is something worth investigating.

**Comment by nachoparker** [comment]
Hi, 

Nothing has changed from the NCP side. I suggest you take this to the corresponding nextcloud server / external app github issue tracker.

NCP is using Debian Stretch, and the php-smbclient package is installed. The rest is a Nextcloud issue.

Cheers
