### ISSUE TITLE
file transfer via samba creates hidden files of the files that has been transferred....

### ISSUE THREAD

**Issue by chromoxdor** [nextcloud/nextcloudpi#610]
I started to use samba for local integration of the storage.
After i copied some pictures and performed a file scan i opened the gallery app and found some weird thumbnails. Somehow the filescan added hidden files of the files i copied and the gallery tries to display them. These hidden files are not existent in the folder when i access it via samba.
This is not just limited to picures... it happens with all files.

<img width="1680" alt="cloud" src="https://user-images.githubusercontent.com/33860956/44818427-52d1a200-abe9-11e8-922d-0d0ff92213aa.png">

edit: i just found out that there are few folders without hidden files but i can´t see a pattern...

NextCloudPi version  v0.58.1
NextCloudPi image    NextCloudPi_06-27-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /media/McCloud/ncdata
data in SD           no
data filesystem      btrfs
data disk usage      130G/932G
rootfs usage         2.0G/7.2G
swapfile             /dev/zram3
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    13.0.5.2
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   192.168.188.33
gateway              192.168.188.1
interface            wlan0
certificates         cloud.myftp.org
NAT loopback         no
uptime               20:52

**Comment by chromoxdor** [comment]
creating those files seems to be a mac related issue as others have experienced this too:1
[https://apple.stackexchange.com/questions/136248/disable-storage-of-invisible-files-on-my-cfs-or-smb-network-storage](url)
 but since it seems to be impossible to prevent macos from doing so it would be the best to prevent the gallery.app from including hidden files into the previews....

**Comment by nachoparker** [comment]
I have seen this before, yes. I suggest you open a request in the gallery repo
