### ISSUE TITLE
Nextcloudpi docker download does not work

### ISSUE THREAD

**Issue by GarySheldon** [nextcloud/nextcloudpi#611]
Hi,

I can't download the docker container from the repository, terminal tells me: "Tag latest not found in repository docker.io/ownyourbits/nextcloudpi-armhf"

Thanks

**Comment by nachoparker** [comment]
hi, 

are you on windows or mac?

https://github.com/docker/docker.github.io/issues/6910

**Comment by GarySheldon** [comment]
I use Raspbian. I have created a docker account and I still can not download it.

**Comment by GarySheldon** [comment]
I tried to download another image of you (minidebian) and it worked for me. Nextcloudpi still unable to download.

**Comment by nachoparker** [comment]
just tried it and it works. Could `git pull` no problem
