### ISSUE TITLE
ownyourbits/nextcloudpi-x86 latest docker setup issues, stuck at initializing

### ISSUE THREAD

**Issue by feutl** [nextcloud/nextcloudpi#626]
Hi,

I am trying to migrate my existing Nextcloud setup to docker running on my QNAP NAS with its ContainerStation.

I downloaded latest ownyourbits/nextcloudpi-x86 from DockerHub

I assigned a fixed IP to the docker and setup the /data directory directly do a directory on the NAS
The container boots up, I can activate it and directories are being created in the /data directory which I see on the NAS directly.

I can create backups from the Admin Panel BUT the Nextcloud sticks with “Initializing …”
I have no clue why and how I can resolve this.

Another issue I have is to provide the “trusted host”, not yet an issue but it is getting as soon as I put this productive because QNAP ContainerStation does not allow me to push values without variable names via the GUI. Every environment variable needs a name and a value which for IP/DOMAIN seems not the case.

This was already mentioned here
https://help.nextcloud.com/t/nextcloudpi-ownyourbits-nextcloudpi-x86-latest-docker-setup-issues/35971
but based on the response I thought it makes sense opening a ticket to increase visibility.

Thanks

**Comment by nachoparker** [comment]
until this becomes something to fix, let's discuss it in the forums

**Comment by feutl** [comment]
👍
