### ISSUE TITLE
Keep language setting of the NCP web interface when updating NCP

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#627]
After updating NCP the language of the NCP web interface gets resetted to "auto". It would be nice if the language setting could be kept on the initially set value.

**Comment by chiyi4488** [comment]
What is your language? Because ncp will automatically query the language of your computer system and update it automatically. If not, you should skip to English. Or.... I don't know. This may be a bug in the language code of ncp.

**Comment by TomTurnschuh** [comment]
@chiyi4488: My auto language is German, but I usually switch to English. After an NCP update, the language setting is "auto" and thus German again.

**Comment by chiyi4488** [comment]
Ok, this may require someone else to help, I don't know how to write programs and fixes. Sorry.

**Comment by nachoparker** [comment]
fixed in `v0.60.8`
