### ISSUE TITLE
Modify the language option bar text to white(web)

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/nextcloudpi#628]
as the picture shows

![default](https://user-images.githubusercontent.com/30853081/45484089-9a2d6600-b785-11e8-9b21-ad84c0e64dd8.png)
![default](https://user-images.githubusercontent.com/30853081/45484119-b4674400-b785-11e8-9313-d739eb0dad3f.png)
![default](https://user-images.githubusercontent.com/30853081/45484134-c0530600-b785-11e8-8897-559e6dc6ad9c.png)
![default](https://user-images.githubusercontent.com/30853081/45484148-ca750480-b785-11e8-8571-9b1439f4d601.png)
![default](https://user-images.githubusercontent.com/30853081/45484159-d4970300-b785-11e8-9083-cff3df8c99b9.png)

**Comment by nachoparker** [comment]
that is really weird @chiyi4488. It doesn't happen to me in Firefox Linux. gi what browser are you using?

**Comment by nachoparker** [comment]
anybody else seeing this?

**Comment by chiyi4488** [comment]
chrome
I am not sure everyone is like this, but at least all my computers are like this.

**Comment by hurrikan77** [comment]
I have this issue too.
I use vivaldi which is based on chromium as I know.

But in Firefox the languages ar shown in black.

**Comment by nachoparker** [comment]
That's so weird... I mean it's just a HTML dropdown

**Comment by nachoparker** [comment]
This must be a browser issue, nothing to fix

Thanks for reporting

**Comment by nachoparker** [comment]
I can't reproduce it, so if somebody has the issue please send me the fix
