### ISSUE TITLE
Password in web GUI are all visible 

### ISSUE THREAD

**Issue by prog-amateur** [nextcloud/nextcloudpi#629]
Hello, 

Maybe this issue has been raised but, surprisingly, I couldn't find it (sorry if another thread is already open). 
I think it must be discussed as it is a serious security risk. 
 
The problem is that **all passwords** (admin, SSH, etc.) can be clearly seen on the web-GUI. This is a high security risk. For example, let's imagine 2 scenarios : 

1. Somebody with a camera (over the shoulder)
2. Screenshot malware

My proposal is to proceed like any other software : to replace the characters by **dots**. 

So instead of : 
`5Eguj9dC8sVwdf4gfydfGJbvxcwJ_ZR`

To have : 
`*******************************`

Optionally, near the field, we can have a kind of Eye logo (to see/hide the password just if necessary). Of course password must be hidden by default. 

Technically, I don't know exactly how to do it, but I could find some interesting links here : 
HTML : 
http://www.echoecho.com/htmlforms06.htm
Hide/See a password : 
https://codepen.io/Sohail05/pen/yOpeBm
Others : 
https://stackoverflow.com/questions/24199203/how-to-convert-password-inputs-to-dots-instead-of-the-text
https://stackoverflow.com/questions/40359824/replacing-the-password-character-to-dot-in-jpasswordfield

Just for information, if I remember well, I was also shocked to see clearly the user & password in the classic Nextcloud (standard version not Pi) in a file (maybe `/var/www/Nextcloud/config.php`) which is easy to get from a good hacker. If this file is also the same on NextcloudPi, we can also try to solve this issue. In any case, Web-GUI issue is the main priority. 

Please, don't take it personally, the way I alert may be misunderstood, it's not a criticism but an alert that must be made to improve this great software that is NextcloudPi. 

Thank you so much for all you have done so far and please feel free to feedback.

**Comment by TomTurnschuh** [comment]
This has already been mentioned in #380 together with other issues. But it's a good point.
Nextcloud and NextCloudPi are more or less independent from each other. Their configurations are not directly linked in any way.

**Comment by nachoparker** [comment]
If this has not been done already is for lack of manpower, but I will add it to the wishlist in #622 in case a webdev steps in to help
