### ISSUE TITLE
How to mount NFS on NCP (Nextcloud Pi, Rock64)

### ISSUE THREAD

**Issue by prog-amateur** [nextcloud/nextcloudpi#639]
Hello. First of all, I have post an issue in the Nextcloud community forum without any feedback so I try there as it is related to NCP (not the same way as Nextcloud classic).  

I have tried to follow [this tutorial](https://ownyourbits.com/2017/04/13/share-your-files-in-your-lan-with-nfs/) in order to setup an NSF share between Nextcloud pi and my desktop (Ubuntu). 

However, I receive some error messages, mainly something like _"permission denied by the server"._ 

This is how I have set it up : 

0. My desktop is `192.168.0.17` and Nextcloud Pi server is `192.168.0.18`. My firewall allows only port `443` & `4443`. I don't want/need port `80` so far. It means `192.168.0.18:443` and `192.168.0.18:4443` only. 

1. First, I have enabled NFS through the web-GUI with `/media/USBdrive/ncdata/user/files`,  `192.168.0.17` as IP address, and `www-data` as user & group. 

2. Then I access Nextcloud Pi through SSH as root and put in `/etc/exports` : `/media/USBdrive/ncdata/user/files 192.168.0.17(rw,sync,all_squash,anonuid=33,anongid=33,no_subtree_check)` 

3. So I save and do in the terminal `sudo exportfs -ra`

4. Now I go on the desktop and use in the terminal : `mkdir mnt/NCP` to make the mounting folder. 

5. Then `sudo mount 192.168.0.18:/media/USBdrive/ncdata/user/files /mnt/NCP` to mount the NFS. **This is where it send the error message regarding the access denied by the server.** 

6. So I continue anyway with : `gedit admin:///etc/fstab` to add the following line : `192.168.0.18:/media/USBdrive /mnt/NCP nfs     rw,user,exec    0       0` to hope an auto-boot, even if I know that something was previously wrong. And finally, nothing happen, no NFS. 

So do you think if maybe a firewall issue ? In the tutorial, it is said that the _NFS server relies on RPCbind (also known as portmapper)_ which _runs on TCP and UDP port `111`_. So shall I make a port forwarding like `192.168.0.18:111` and/or `192.168.0.17:111` ?  

Is there anything else I have forgot to install or did anything wrong ? 

Thank you very much for your help.

**Comment by nachoparker** [comment]
This is not the place for questions. Please, use the forums for that

Thanks!
