### ISSUE TITLE
Retrieve admin password

### ISSUE THREAD

**Issue by JVAQUEROM** [nextcloud/nextcloudpi#64]
Hi,

It seems that I am a bit dumb and I forgot my admin password!! I'd swear I have read in some issue that there was a file (which you can only access as root) where you can read the password...where is that?

**Comment by nachoparker** [comment]
From [the official docs](https://docs.nextcloud.com/server/12/admin_manual/configuration_user/reset_admin_password.html)

You can copy and paste these commands

```
sudo su
cd /var/www/nextcloud
sudo -u www-data php occ user:resetpassword admin
```

**Comment by JVAQUEROM** [comment]
Thank you!!
