### ISSUE TITLE
error message in Automatic signed SSL certificates module

### ISSUE THREAD

**Issue by hurrikan77** [nextcloud/nextcloudpi#640]
Hi all

I want to create a new certificate for an new dyndns urls.

In module "letsencrypt" I entered all required data and press "run"

After that I got  the error message:

[ letsencrypt ]
./letsencrypt.sh: line 63: letsencrypt: command not found

Best regards

**Comment by nachoparker** [comment]
You probably missed an important update?

```
sudo apt-get update
sudo apt-get install letsencrypt
```

**Comment by hurrikan77** [comment]
Hi nachoparker

you are right. I copied back an old image and only updated all with the ncp funktionality but not with the system functionality. There were some other update waiting for installation ;-)

Thx for your help.
