### ISSUE TITLE
Access data files from outside container with user pi

### ISSUE THREAD

**Issue by tjaadvd** [nextcloud/nextcloudpi#648]
I use the docker image on my Raspberry Pi 2. I want to backup my ncp configuration and data from outside the container with Duplicati. However, the user pi can not reach most of the directories and files. It works when I change the owner, but that breaks ncp.
Is it possible to use the same user in the container as outside the container? So that pi can access the files. I think LinuxServer.io does this by using the "-e PUID=<uid> -e PGID=<gid>" parameter ([see info](https://www.linuxserver.io/docs/running-our-containers)).

**Comment by nachoparker** [comment]
Hello,

This is not a support or questions forum, please use the forums as explained in the issue template instructions.
