### ISSUE TITLE
NC14 setup error.

### ISSUE THREAD

**Issue by deljones** [nextcloud/nextcloudpi#651]
I have just recently upgraded my NCpi to NC 14. All seems to be fine but in the overview I am getting the following error regarding the setup...

I have tried to do my pwm research before asking but now I am at a loss...

Del

--------------------
There are some warnings regarding your setup.

    The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
        Missing index "parent_index" in table "oc_share".
        Missing index "fs_mtime" in table "oc_filecache".

---------------------------

**Comment by nachoparker** [comment]
did you upgrade using `ncp-web`? I think you didn't. In the future, please use that tool for NCP to avoid issues.

In any case, run

```
sudo ncc db:add-missing-indices
```
