### ISSUE TITLE
Trailing slash in CLI URL required

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#652]
In order for `nc_prettyURL` to work, the domain in `overwrite.cli.url` must have a trailing `/` – at least, if the domain has no path, cf. nextcloud/server#10678. Hence, a trailing `/` should be added in all apps where `overwrite.cli.url` is defined.

**Comment by ignacionunez** [comment]
I just upgraded to NC14.0.1 and PHP7.2 and noticed that prettyURLs are not working. Will have to look into this later, maybe that's the reason.

They did work before the upgrade.

On a different note @TomTurnschuh you might want to join the telegram group to have a more direct communication channel. Don't need to, but you can ;)

**Comment by TomTurnschuh** [comment]
> I just upgraded to NC14.0.1 and PHP7.2 and noticed that prettyURLs are not working. Will have to look into this later, maybe that's the reason.

Yes, this is probably the reason. It works if you add the trailing slash in `overwrite.cli.url`. I opened a pull request to catch this error as a first step.

**Comment by nachoparker** [comment]
fixed in devel, thanks!
