### ISSUE TITLE
Activate NCP too early -> No automatic reload

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#657]
When trying to activate a new NCP too early, the info shows up that it isn't yet initialized and will try again in a few seconds. However, this "trying again" seems not to work. I always have to reload the page (and then get new passwords).
Can anybody confirm that?

I tried with an ODROID device and Firefox.

![screenshot_ncp not yet initialized](https://user-images.githubusercontent.com/36013390/46248008-e3331a80-c413-11e8-9050-64805cdfc69b.png)

**Comment by nachoparker** [comment]
I haven't seen this, can you check `/var/log/ncp.log`?

**Comment by TomTurnschuh** [comment]
There is nothing irregular in `ncp.log`. The first entries are `nc-limits`, `nc-admin` and `nc-passwd`, without any errors.

**Comment by nachoparker** [comment]
trying to reproduce to no avail. Please, reopen if somebody sees this again
