### ISSUE TITLE
App state is changed even in case of failure

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#658]
#### Issue
Many apps can be activated or deactivated. If e.g. the activation fails, such as with ramlogs on armbian, the state of this app is still changed to `active`, even though this is wrong.

#### Solution
It would be nice if failures in activation or deactivation could be detected and the corresponding app state be restored to the previous.

**Comment by nachoparker** [comment]
Regarding this, it needs to be done in a per case basis with `is_active()` as mentioned here https://github.com/nextcloud/nextcloudpi/pull/654#pullrequestreview-160708025
