### ISSUE TITLE
Automount not working with clean install of RPi_10-01-18 image

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/nextcloudpi#674]
Hey! Thanks for the new RPi image with NC version 14!

I burned the new RPi_10-01-18 image to a 32GB sd card and powered up my RPi. As I started the configuration wizard and tried to move the data dir to an connected 3TB harddrive this error was shown:

    [ nc-automount ]
    automount enabled

    [ nc-datadir ]
    /media/USBdrive does not exist

But as the output of fdisk shows, the drive is detected (/dev/sda1). It was formated with the previous nextcloudPi version with btrfs.

Hope this helps you out! Any idears, how I could fix the problem? Mounting with sudo mount did not work:

    pi@nextcloudpi:~ $ sudo mount /dev/sda1 /media/USBdrive
    mount: unknown filesystem type 'btrfs'

Greetings, Daniel

<details>
<summary>sudo fdisk -l</summary>

pi@nextcloudpi:~ $ sudo fdisk -l
Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram2: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram3: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram4: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram5: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram6: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram7: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram8: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram9: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram10: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram11: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram12: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram13: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram14: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/ram15: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/mmcblk0: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xef9bb2fd

Device         Boot Start      End  Sectors  Size Id Type
/dev/mmcblk0p1       8192    96663    88472 43.2M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      98304 62333951 62235648 29.7G 83 Linux

Disk /dev/sda: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: CFF27F19-CC99-429C-97E4-31DF31C41E59

Device     Start        End    Sectors  Size Type
/dev/sda1   2048 5860532223 5860530176  2.7T Linux filesystem

</details>

**System information**

<details>
<summary>NextCloudPi diagnostics</summary>

```

NextCloudPi version  v0.62.5
NextCloudPi image    NextCloudPi_10-02-18
distribution         Raspbian GNU/Linux 9 \n \l
automount            yes
USB devices          sda 
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      2.1G/30G
rootfs usage         2.1G/30G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    14.0.1.1
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        open
port check 443       open
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               18min

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "1": "192.168.178.30"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https"
    }
}

```
</details>

<details>
<summary>HTTPd logs</summary>

```

[Thu Oct 04 19:43:08.092111 2018] [proxy_fcgi:error] [pid 994:tid 1691620384] [client 192.168.178.54:52552] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'
[Thu Oct 04 19:43:09.997001 2018] [proxy_fcgi:error] [pid 994:tid 1691620384] [client 192.168.178.54:52552] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'
[Thu Oct 04 19:43:12.943278 2018] [proxy_fcgi:error] [pid 994:tid 1691620384] [client 192.168.178.54:52552] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'
[Thu Oct 04 19:43:14.483725 2018] [proxy_fcgi:error] [pid 994:tid 1691620384] [client 192.168.178.54:52552] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'
[Thu Oct 04 19:44:18.342774 2018] [proxy_fcgi:error] [pid 994:tid 1851114528] [client 192.168.178.54:52552] AH01067: Failed to read FastCGI header
[Thu Oct 04 19:44:18.342936 2018] [proxy_fcgi:error] [pid 994:tid 1851114528] (104)Connection reset by peer: [client 192.168.178.54:52552] AH01075: Error dispatching request to :4443: 
[Thu Oct 04 19:44:19.943152 2018] [mpm_event:notice] [pid 779:tid 1996222848] AH00491: caught SIGTERM, shutting down
[Thu Oct 04 19:44:30.073995 2018] [ssl:warn] [pid 485:tid 1995514240] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Thu Oct 04 19:44:30.082842 2018] [ssl:error] [pid 485:tid 1995514240] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=archlinux / issuer: CN=archlinux / serial: 93BEECEAEF551B82 / notbefore: Oct  2 01:03:54 2018 GMT / notafter: Sep 29 01:03:54 2028 GMT]
[Thu Oct 04 19:44:30.082937 2018] [ssl:error] [pid 485:tid 1995514240] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Thu Oct 04 19:44:31.042672 2018] [ssl:warn] [pid 850:tid 1995514240] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Thu Oct 04 19:44:31.042951 2018] [ssl:error] [pid 850:tid 1995514240] AH02217: ssl_stapling_init_cert: can't retrieve issuer certificate! [subject: CN=archlinux / issuer: CN=archlinux / serial: 93BEECEAEF551B82 / notbefore: Oct  2 01:03:54 2018 GMT / notafter: Sep 29 01:03:54 2028 GMT]
[Thu Oct 04 19:44:31.043034 2018] [ssl:error] [pid 850:tid 1995514240] AH02604: Unable to configure certificate localhost:4443:0 for stapling
[Thu Oct 04 19:44:32.003084 2018] [mpm_event:notice] [pid 850:tid 1995514240] AH00489: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2l configured -- resuming normal operations
[Thu Oct 04 19:44:32.003243 2018] [core:notice] [pid 850:tid 1995514240] AH00094: Command line: '/usr/sbin/apache2'
[Thu Oct 04 19:44:32.653210 2018] [proxy_fcgi:error] [pid 857:tid 1682510880] [client 192.168.178.54:52556] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Thu Oct 04 19:47:13.879636 2018] [proxy_fcgi:error] [pid 857:tid 1690911776] [client 192.168.178.54:52556] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/wizard/index.php on line 21\nPHP message: PHP Warning:  ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/ncp-web/wizard/index.php on line 23\n'
[Thu Oct 04 19:47:14.840136 2018] [proxy_fcgi:error] [pid 857:tid 1690911776] [client 192.168.178.54:52556] AH01071: Got error 'PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /var/www/ncp-web/ncp-output.php on line 81\n'
[Thu Oct 04 19:47:48.240585 2018] [proxy_fcgi:error] [pid 857:tid 1682510880] [client 192.168.178.54:52556] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'
[Thu Oct 04 19:47:57.703110 2018] [proxy_fcgi:error] [pid 857:tid 1682510880] [client 192.168.178.54:52556] AH01071: Got error 'PHP message: PHP Warning:  fopen(ncp-web.cfg): failed to open stream: No such file or directory in /var/www/ncp-web/L10N.php on line 145\n'

```
</details>

<details>
<summary>Database logs</summary>

```

2018-10-04 19:44:20 1954538288 [Note] /usr/sbin/mysqld: Shutdown complete

2018-10-04 19:44:51 1995706352 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-10-04 19:44:51 1995706352 [Note] InnoDB: The InnoDB memory heap is disabled
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-10-04 19:44:51 1995706352 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Using Linux native AIO
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Using generic crc32 instructions
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Completed initialization of buffer pool
2018-10-04 19:44:51 1995706352 [Note] InnoDB: Highest supported file format is Barracuda.
2018-10-04 19:45:00 1995706352 [Note] InnoDB: 128 rollback segment(s) are active.
2018-10-04 19:45:00 1995706352 [Note] InnoDB: Waiting for purge to start
2018-10-04 19:45:00 1995706352 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.35-80.0 started; log sequence number 3697216
2018-10-04 19:45:00 1430238000 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-10-04 19:45:00 1995706352 [Note] Plugin 'FEEDBACK' is disabled.
2018-10-04 19:45:00 1995706352 [Note] Server socket created on IP: '127.0.0.1'.
2018-10-04 19:45:00 1995706352 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.1.23-MariaDB-9+deb9u1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Raspbian 9.0

```
</details>

<details>
<summary>Nextcloud logs</summary>

```

{"reqId":"6MBqeXepbvdKlFetHA20","level":3,"time":"2018-10-02T01:30:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":660,"function":"checkInstalled","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/base.php","Line":277,"CustomMessage":"--"},"userAgent":"--","version":""}

```
</details>

**Comment by chiyi4488** [comment]
I think you need to change a clerk adapter.

**Comment by nachoparker** [comment]
Hi,

This is a kernel problem. Let's deal with this here https://github.com/nextcloud/nextcloudpi/issues/668

Thanks for reporting

**Comment by nachoparker** [comment]
Fixed in the latest image
