### ISSUE TITLE
Misplaced nc-init.sh in x86 docker

### ISSUE THREAD

**Issue by ParentM** [nextcloud/nextcloudpi#684]
In the latest build of the nextcloudpi-x86 docker (10-02-2018), nc-init.sh is located in the root folder instead of /data/ncp/ with the other NCP bash scripts.
This causes the initial setup of NCP to get stuck; moving nc-init.sh to /data/ncp/ seems to fix the problem.

**Comment by nachoparker** [comment]
Hi,

that script is fine where it is. I use the docker x86 container every day and it works.

you must have been seeing other issue

thanks for reporting
