### ISSUE TITLE
dummy issue to upload pictures

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/nextcloudpi#689]
Github is dumb and won't let you upload directly to the wiki

**Comment by nachoparker** [comment]
![ncp_activation_tests](https://user-images.githubusercontent.com/21343324/47269136-56c6d400-d549-11e8-8711-fecac8f86c7f.png)
![ncp_nextcloud_tests](https://user-images.githubusercontent.com/21343324/47269138-57f80100-d549-11e8-933a-ff37160bc862.png)
![ncp_system_tests](https://user-images.githubusercontent.com/21343324/47269139-58909780-d549-11e8-9686-69122d986b51.png)

**Comment by ovpc** [comment]
![ncp-logo-photo_2017-11-05_09-52-26](https://user-images.githubusercontent.com/8775469/52916959-edcc4e80-32e5-11e9-88dc-cc084de702a1.jpg)
for wiki conf ref footer lol
