### ISSUE TITLE
libcurl4 : Conflicts: libcurl3 upgrade to v0.64.11

### ISSUE THREAD

**Issue by ovpc** [nextcloud/nextcloudpi#697]
Found email from nc-autoupdate pasted content at [pastebin](https://pastebin.com/BAS2xZDx)
Link to pastebin with ncp-report below.

Then checked on instance (Production on NUCi5 Debian9), everything seems to be running fine (NC 14.0.3 NCP v0.64.11) No such report/issue on my test RPI3.

sudo apt update && sudo apt upgrade -y
Ign:1 http://ftp.nl.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease                            
Get:3 http://ftp.nl.debian.org/debian stretch-updates InRelease [91.0 kB]                             
Get:4 http://deb.debian.org/debian buster InRelease [150 kB]                    
Hit:5 http://ftp.nl.debian.org/debian stretch Release                                                                                 
Get:6 https://packages.sury.org/php stretch InRelease [6907 B]                                                                        
Get:8 http://deb.debian.org/debian buster/main amd64 Packages.diff/Index [27.9 kB]
Get:9 http://deb.debian.org/debian buster/main Translation-en.diff/Index [27.9 kB]
Get:10 http://deb.debian.org/debian buster/non-free amd64 Packages.diff/Index [27.8 kB]
Get:11 https://packages.sury.org/php stretch/main amd64 Packages [104 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 Packages 2018-10-29-0216.10.pdiff [20.8 kB]
Get:12 http://deb.debian.org/debian buster/main amd64 Packages 2018-10-29-0216.10.pdiff [20.8 kB]
Get:13 http://deb.debian.org/debian buster/main Translation-en 2018-10-29-0216.10.pdiff [855 B]
Get:14 http://deb.debian.org/debian buster/non-free amd64 Packages 2018-10-29-0216.10.pdiff [224 B]
Get:13 http://deb.debian.org/debian buster/main Translation-en 2018-10-29-0216.10.pdiff [855 B]
Get:14 http://deb.debian.org/debian buster/non-free amd64 Packages 2018-10-29-0216.10.pdiff [224 B]
Get:15 http://deb.debian.org/debian buster/main amd64 DEP-11 Metadata [3716 kB]                                                       
Get:16 http://deb.debian.org/debian buster/main DEP-11 64x64 Icons [7364 kB]                            
Fetched 11.5 MB in 9s (1224 kB/s)                                                                                                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1433 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcurl4 : Conflicts: libcurl3 but 7.52.1-5+deb9u7 is to be installed
E: Broken packages

**System information**

  
[ncp-report29102018](https://pastebin.com/3cAZvdXS)

**Comment by nachoparker** [comment]
you after the latest `ncp-upgrade` you shouldn't have buster sources anymore
