### ISSUE TITLE
Release tags for docker images

### ISSUE THREAD

**Issue by de-code** [nextcloud/nextcloudpi#698]
**Description**  

The current docker images only contain the `latest` tag which makes it impossible to downgrade or make a setup reproducible by keeping the version stable. It would be great if the docker images had release version tags (that don't change).

**Example**  

e.g. `13.0.7` (see official nextcloud docker image)

**Comment by nachoparker** [comment]
The reason why older versions are not kept is because NCP has rolling updates and running an update on an instance older than one month is not guaranteed to work.

In other words, we have to upgrade at least once a month, or ever better turn on autoupdates

**Comment by de-code** [comment]
I was under the impression that it's "just" a wrapper around nextcloud which seem to work with the release versions.

I'd feel more comfortable with code that I own (or the team / company I work for owns). For third parties it seems preferable to have some control over when and what is upgraded. If your docker account is getting hacked, someone could just deploy malicious code to all of the instances running NextCloudPi.

**Comment by nachoparker** [comment]
NCP adds quite a bit of stuff on top of Nextcloud. You are absolutely free to build your own docker container, as all the code is free. There are instructions on the main page.

You are free to upgrade in however fashion you like, but I am a single person doing all this as volunteer work and I can't support rolling upgrades for more than a month
