### ISSUE TITLE
Allow nextcloudpi devices to seed the nextcloudpi torrent

### ISSUE THREAD

**Issue by jonim8or** [nextcloud/nextcloudpi#70]
In a blogpost you mentioned the cost of hosting the nextcloudpi image. Maybe it is a good idea to use torrent more:

1. get new updates via torrent
2. (optional, can be enabled/disabled via checkbox) let the nextcloudpi instances seed the latest image for a while

This way all the updating-related traffic would be reduced to almost zero, and any torrent-download of the whole image will be blazingly fast

I know that these are actually two suggestions in one, but I post them together because I think they are related a lot.

**Comment by nachoparker** [comment]
could be a little bit of work to pull off... but brilliant idea!

thanks

**Comment by grphx7** [comment]
I would love to be able to seed the image in a torrent, on my pi.  Please keep in mind the throughput on a pi is somewhat slow though so maybe don't allow the torrent to have 100% of the bandwidth?  I do seed the image torrent on my main server though to help out currently.

**Comment by nachoparker** [comment]
> I do seed the image torrent on my main server though to help out currently.

Thanks for that! :D

**Comment by sunjam** [comment]
fyi, this could be achieved using [ocDownloader](https://apps.nextcloud.com/apps/ocdownloader) app, which is currently being maintained by an active fork on Github... see their [github page here](https://github.com/e-alfred/ocdownloader).  It would be cool to add via the web menu, much like the News App Updater.

**Comment by nachoparker** [comment]
cool, thanks for the info!

**Comment by nachoparker** [comment]
At this moment we don't have the resources to implement this, and also right now the torrent state is healthy. 

Close for now

**Comment by sunjam** [comment]
Any idea of what resources are needed to implement it?

**Comment by nachoparker** [comment]
I mean mostly manpower, pretty busy right now

The idea is great though, thanks

 :D
