### ISSUE TITLE
Add a feature to redirect

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/nextcloudpi#700]
**Description**  
I was thinking maybe I could do a direct home ip to the domain. I have a simple test (PHP), but some problems will occur.
**Example**  

`<?php
header ("Location: http://www.bbb.com") ;
exit ;
?>`

**Comment by chiyi4488** [comment]
You can also direct the incorrect domain directly to the correct domain, but I really don't know how to set the nextcloud, maybe it needs to be discussed.

**Comment by nachoparker** [comment]
thanks for the ideas, but I don't think we should do this

cheers!
