### ISSUE TITLE
MD5 checksum for rpi_10-23-18 doesn't match download.

### ISSUE THREAD

**Issue by ssaury** [nextcloud/nextcloudpi#701]
The md5 checksum for nextcloudpi_rpi_10-23-18.tar.bz2 on https://ownyourbits.com/downloads/NextCloudPi_RPi_10-23-18/ doesn't match the download.
Downloading the file (tar.bz2) and running an md5sum on it gives a different result from the md5sum file in provided on the download page.

**Comment by nachoparker** [comment]
You must be doing something wrong
```
$ md5sum torrent/NextCloudPi_RPi_10-23-18/NextCloudPi_RPi_10-23-18.tar.bz2
5d1afe4ee1b3c5bee8f242e8607b0349  torrent/NextCloudPi_RPi_10-23-18/NextCloudPi_RPi_10-23-18.tar.bz2

$ cat torrent/NextCloudPi_RPi_10-23-18/md5sum
5d1afe4ee1b3c5bee8f242e8607b0349  torrent/NextCloudPi_RPi_10-23-18/NextCloudPi_RPi_10-23-18.tar.bz2
```

Thanks for the heads up

**Comment by ssaury** [comment]
Quite possibly but that's what I get:

 md5sum NextCloudPi_RPi_10-23-18.tar.bz2
c270cf0a0addf4b01c8fa4bf7549a978  NextCloudPi_RPi_10-23-18.tar.bz2

Am I doing something wrong when downloading the tar.bz2 file?


________________________________

**Comment by nachoparker** [comment]
Tried downloading it again, just click on your link

```
$ md5sum Downloads/NextCloudPi_RPi_10-23-18.tar.bz2
5d1afe4ee1b3c5bee8f242e8607b0349  Downloads/NextCloudPi_RPi_10-23-18.tar.bz2
```

**Comment by ssaury** [comment]
Downloaded it again and it now match the check sum. Not sure what happened first time round.

Sorry for the bother and thanks for your help.


________________________________
