### ISSUE TITLE
login on Odroid

### ISSUE THREAD

**Issue by Spielmops** [nextcloud/nextcloudpi#711]
I downloaded the image for Odroid and startet it on an Odroid XU4. It works and I can activate the server. But I can not login to the computer with "pi" and "raspberry". I can not access the machine via ssh, because the zero-byte-file ssh on the sd-card did nothing. I can not activate ssh from the web-interface, because with pi:
"[ SSH ] Refusing to use the default Raspbian user and password. It's insecure"
and with ncp:
[ SSH ] Enter new UNIX password: Retype new UNIX password:
passwd: password updated successfully
Synchronizing state of ssh.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable ssh
The user root is using the default password. Refusing to activate SSH
SSH disabled

I could login direct to the Computer with ncp and password, the screen shows the usual login-"image" and loged me out, now even that is impossible.

I wrote the image again to sd-card and tried the thing again - to no avail.

What's the matter with this images?

Spielmops

**Comment by nachoparker** [comment]
please, read the wiki for a guide.

in odroid there is no pi user. you have to do `root` and then a new password that is not the default `1234`

you can activate SSH through ncp-web

cheers!
