### ISSUE TITLE
"file permissions" to change file size 

### ISSUE THREAD

**Issue by swr85260** [nextcloud/nextcloudpi#72]
I’ve got a minor issue, when I change the file size through the nextcloud administration interface, there is an Error
```
Warning	files	Can’t write upload limit to /var/www/nextcloud/.htaccess. Please check the file permissions
```
The size can be set through the raspian interface and is applied to nextcloud with sucess

**Comment by nachoparker** [comment]
Thanks for the feedback.

Mmmm, just tried and couldn't reproduce


![change_size](https://user-images.githubusercontent.com/21343324/29096935-77b8dfca-7c97-11e7-9eeb-d86d300eb683.jpg)
