### ISSUE TITLE
Upstream pgp provider packages incompatible armhf 

### ISSUE THREAD

**Issue by CoolSilver** [nextcloud/nextcloudpi#722]
https://github.com/oerdnj/deb.sury.org/issues/1006

Bricks SSH and SSL and unstable system. Happens with Rasbian and the latest nextcloudpi image when updating.

**Comment by nachoparker** [comment]
thanks for reporting @CoolSilver. Indeed they don't have their stuff very well put together with their naming of _armhf_ architecture.

This is only with pi1/zero right? (armv6)

**Comment by CoolSilver** [comment]
This was on a Pi 3 I believe. If not a Pi 2. I will verify tonight

**Comment by CoolSilver** [comment]
You're right it is a B+ 1.2. No wonder why I was thinking it should perform better.

**Comment by nachoparker** [comment]
maybe next summer we'll support it again once Raspbian is on buster

**Comment by nachoparker** [comment]
armv6 pi versions, like 1b and zero are supported again.

Also NCP can work with different PHP versions, even though PHP7.2 or greater is required for NC16
