### ISSUE TITLE
no update to nc 14.0.4 possible

### ISSUE THREAD

**Issue by hurrikan77** [nextcloud/nextcloudpi#723]
hi

I actuall got the message that nc 14.0.4 is available.
If I start the online updater I got the error message that the following extra file ".well-known" was found.

Is this an file from nextcloudpi?
And why is ist not possible to update the nc via ncpi panel (There is only 14.0.3 available)?

Best regards

Kilian

**Comment by ovpc** [comment]
PLease use [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions.
