### ISSUE TITLE
nc-restore.sh: Fails, if the backup file resides on a non-Linux file system (NTFS)

### ISSUE THREAD

**Issue by LittleAlf** [nextcloud/nextcloudpi#724]
I use a Windows network share to store the NC backup files. Backup works fine without a problem.

Lately, I wanted to do a restore of my production NC running on a raspberry pi to my test NC running in a VM. This did **not** work, and the procedure got stuck:

When I looked into the directory, where the backup file resided I noticed, that a new directory was created 'ncp-restore.S1N9TU'. As far as I could see, this directory contained all the extracted data (i.e. subdirectories 'ncdata' and 'nextcloud' with their own subdirectories and files, and the file 'nextcloud-sqlbkp_20181118.bak' on the top level.) But then it did not continue.

In the log file in `/var/log/ncp.log` the only entries are:

> [ nc-restore ]
> extracting backup file /mnt/winbackup/nc-backups/nc-bkp_20181118_1542553461.tar...

#### Remedie:
I copied the desired backup file to a btrfs volume. Running `nc-restore.sh` pointing to the file in the new location it worked flawlessly.

#### Suggestion:
Looking into `nc-restore.sh` I noticed, that the same drive where the backup file resides, is being used for the temporary directory. I assume, that the procedure did not continue because some features required for the proper restore were not available. Or the assumption, that the backup file would reside on the same drive like the install of NC. (Sorry, I am relatively new to Linux; that is why I couldn't figure it out looking at `nc-restore.sh`.)

**One suggestion** is, that the filesystem, where the backup file is stored, is being checked if it is a suitable Linux file system. As far as I know, the backup can be restored on any Linux file system. So, the task would be, if the file system is being reported as `cifs` - in this case it would be a Windows share, and the execution being aborted.

I took this as a challenge and tried to do it in two bash lines (applying the concepts used in `nc-restore.sh`):
```
BACKUPFSTYPE="$(findmnt -o FSTYPE "$(df --output=target "$BACKUPFILE" | tail -1)" | tail -1)"
[[ $BACKUPFSTYPE = "cifs" ]] && { echo "Cannot restore, if backup file resides on non-Linux file system"; exit 1; }

```
**Another suggestion** would be, that if the filesystem the backup file is stored is a non-Linux file system, the backup file is moved/copied to another location. But this would require a heck of a lot of additional checks and would make `nc-restore.sh` much more complicated.

**Comment by nachoparker** [comment]
added in `v0.67.4`, thanks for the feedback ;)
