### ISSUE TITLE
Fail2ban - nextcloud

### ISSUE THREAD

**Issue by Haraade** [nextcloud/nextcloudpi#726]
fail2ban is not prepared by moving nextcloud data.
logpath /var/www/nextcloud/data/nextcloud.log
will fail.
logpath must be /media/"myLabel"/ncdata/nextcloud.log

**Comment by nachoparker** [comment]
Hi,

when you run `fail2ban` or `nc-datadir` the logpath gets updated

**Comment by Haraade** [comment]
Sorry, but it did not happen to me.
My logpath in fail2ban was still /var/www/nextcloud/data/nextcloud.log
after nc-datadir was updated.
So fail2ban failed at startup.

Armbian OdroidXu4.

Is in any case aware of this in the future. Thanks.
