### ISSUE TITLE
NCP Web-GUI Improvement

### ISSUE THREAD

**Issue by klerai** [nextcloud/nextcloudpi#732]
**Better sorted list of available user actions **  

nc-update-nextcloud    =>      nc-update
nc-autoupdate-nc         =>      nc-update-auto

nc-update                     =>      ncp-update
nc-autoupdate-ncp       =>      ncp-update-auto
nc-update-ncp              =>      ncp-update
nc-export-ncp               =>      ncp-export
nc-import-ncp               =>      ncp-import

**Comment by nachoparker** [comment]
thanks  for the suggestion

one day we want to group ncp-apps together, this is already in the wishlist 

https://github.com/nextcloud/nextcloudpi/issues/622

cheers!
