### ISSUE TITLE
Timezone configuration in docker container

### ISSUE THREAD

**Issue by klerai** [nextcloud/nextcloudpi#734]
For those running the docker container on a server with a timezone other then UTC have no direct possibility to adjust the zone information through the user interface.

Following the usage pattern from the guys at LinuxServer.io, I suggest to use the additional volume parameter within the docker run command.
  -v /etc/localtime:/etc/localtime:ro \

**Comment by nachoparker** [comment]
good idea, thanks

**Comment by vgdh** [comment]
thanks!
