### ISSUE TITLE
freeDNS update does not work

### ISSUE THREAD

**Issue by KUGA2** [nextcloud/nextcloudpi#735]
In the WebUI I enter mydomain and my hash and press run. It gets green, but the ip in the freeDNS web interface does not change. I cannot acces via my domain.
Clicking the link in the freeDNS web interface instantly works

The log shows:
[ DDNS_freeDNS ]
System config value trusted_domains => 3 set to string ***
System config value overwrite.cli.url set to string https://***/
FreeDNS client is enabled

My setup:
NextCloudPi version | v0.67.5
-- | --
NextCloudPi image | NextCloudPi_11-22-18
distribution | Raspbian GNU/Linux 9 \n \l
automount | yes
USB devices | sda
datadir | /media/USBdrive/ncdata
data in SD | no
data filesystem | btrfs
data disk usage | 100M/4.6T
rootfs usage | 1.9G/7.2G
swapfile | /var/swap
dbdir | /var/lib/mysql
Nextcloud check | ok
Nextcloud version | 14.0.4.2
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
Postfix service | up
internet check | ok
port check 80 | open
port check 443 | open
IP | 192.168.178.10
gateway | 192.168.178.1
interface | eth0
certificates | ***
NAT loopback | no
uptime | 23:49

**Comment by nachoparker** [comment]
cc @Pant

**Comment by nachoparker** [comment]
asked in the Telegram group, people are using it fine so it must be a network configuration issue on your end.

Thanks for reporting
