### ISSUE TITLE
Timestamp differs after copying files via usb hdd

### ISSUE THREAD

**Issue by chromoxdor** [nextcloud/nextcloudpi#739]
since i use my nextcloud for backup i clone folders from my macbook via sambashare to the cloud.
so far so good.
For a very large folder i used a different way.... i cloned it to an external hdd und connected it to the raspberrypi (much faster)..... then is used cp -a to preserve everything ...especially the timestamp because after copying i wanted to backup changes through the sambashare.
I have on both devices the same timezone (etc) but on the raspberry the timestamps are all 2hours behind so the backup programm thinks that these are different files and start to copy everything.
what can i do?
any suggestions?
thanks in advance

**Comment by nachoparker** [comment]
Hello,

please use the forums for questions like this
