### ISSUE TITLE
How to assing eth0 static IP?

### ISSUE THREAD

**Issue by polmourgos** [nextcloud/nextcloudpi#74]
How to assing eth0 static IP?

**Comment by nachoparker** [comment]
NextCloudPi is based on Raspbian, so any of the methods that can work on Raspbian will work for you.

For instance, you can

```
cat >> /etc/dhcpcd.conf <<EOF
interface eth0
static ip_address=192.168.0.131/24
static routers=192.168.0.1
static domain_name_servers=192.168.0.1
EOF
```

**Comment by polmourgos** [comment]
Thank you.
I worked.

I  keep try to make my final setup
