### ISSUE TITLE
Bug in DDNS_spDYN.sh script

### ISSUE THREAD

**Issue by Serviton** [nextcloud/nextcloudpi#748]
NextCloudPi v0.67.8

Hi, I discoverd some problems when I use the NextCloudPi Configuration tool to configure DDNS_spDYN it says:

[badauth] Not a valid username/password

when I try ‘the same’ with the spdnsUpdater.sh script, with the same hostname and updatetoken, everything works fine.

Found the Bug in the etc/ncp-config.d DDNS_spDYN.sh
script.

Line 112: “$INSTALLPATH”/spdnsUpdater.sh “$DOMAIN_” “$TOKEN_” “$IPv6_”
Here the update Script is called, but with 3 Parameters.
In the update Script is a line which checks all parameters, in case of 3 it will expect $DOMAIN $USERNAME $PASSWORD
There is no support for a IPv6 Parameter.

Solution: removed the “IPv6_” Parameter, everything works fine now. :slight_smile:

It would be great if a fix or correct IPv6 implementation will be made to the script.

Greetings
Serviton

**Comment by nachoparker** [comment]
cc @TomTurnschuh

**Comment by TomTurnschuh** [comment]
You must have an old version of this script. The mentioned `case` section has been removed.
However, the automatic reinstallation has been removed during the latest cleanup of the update script.

@Serviton: Could you please run the following code as root user?:
```
rm -r /usr/local/etc/spdnsupdater
cd /usr/local/etc/ncp-config.d
install_script DDNS_spDYN.sh
```

**Comment by Serviton** [comment]
Hi Tom,
I tried to use the 'install_script' command but then I got:
Command not found.
unfortunately I am not that familiar with the use of these scripts

**Comment by TomTurnschuh** [comment]
Hi Serviton

Sorry, my mistake.
The following code should work:
```
rm -r /usr/local/etc/spdnsupdater
cd /usr/local/etc/ncp-config.d
source DDNS_spDYN.sh
install
```

**Comment by Serviton** [comment]
No problem, after a quick search my way was a little bit different, I used:

  `source library.sh`
 ` install_script DDNS_spDYN.sh `
