### ISSUE TITLE
exFat support by default?

### ISSUE THREAD

**Issue by dxnacho** [nextcloud/nextcloudpi#752]
As many of us use exfat disks in order to be compatible with Tv, Android Boxes, and many other devices, and I personally use Nexcloutpi also to store and copy movies, would be very useful to provide by default exfat-fuse exfat-utils packages by default.

Many thanks for your great work, it makes many people's life easier! :)

**Comment by nachoparker** [comment]
hello,

thanks for your suggestion. Unfortunately only Linux filesystems are supported, because we rely on Unix permissions.

cheers

**Comment by dxnacho** [comment]
I meant support for external devices, not for the system itself...
