### ISSUE TITLE
Raspi Login problems / no space left on device

### ISSUE THREAD

**Issue by lotiolentus** [nextcloud/nextcloudpi#753]
Hi everyone,

thanks for this amazing piece of software! I tried it, it worked like a charm, I loved it, now I'm having some problems :-/

I use a RasPi 3 B+ with Berryboot installed on a 16GB microSD to mount the image NextCloudPi_RPi-Berryboot_07-03-18.img from an external 1.4TB HDD and it worked for a couple of months.
Twice I had to manually disable maintenance mode after an NCP update ([that way](https://www.reddit.com/r/NextCloud/comments/7jy2gy/nextcloudpi_went_into_maintenance_mode/)), the last time was some 2 weeks ago. A little after that my Windows desktop and Android clients stopped working. Via SSH a did a ncp-info and discovered that
1. the MariaDB service was down and
2. 1.4TB/1.4TB of my external USB drive were in use.

I had no time to look into it back then and now I'm paying the price.

For a week now SSH access isn't working either. I attached my Pi to a screen + keyboard and everytime during boot a couple of services fail (it's different every time, sometimes the HTTP server, sometimes the time sync service, always MariaDB and "Advanced key-value store"). Then I get one of the following errors:
1) Booting stops at some point. I get some [ OK ] ... or [FAILED] ... and nothing more happens
2) I get stuck at the login prompt: I can enter anything including line breaks, everything I type is displayed at the screen. The password prompt never pops up but about 15s after hitting return (I can still type after that), the login prompt re-appears (see attached screenshot)
3) I get the password prompt, but instead of logging in it says something like "error initializing module" and I get the login prompt again.
4) I managed to properly login only once and found the following:
a) any command in ncp-config would only give me the attached error message but appearantly wouldn't be executed
b) I tried to free up some space (as suggested in #201 ) but the Pi would tell me that `apt-get` was an unknown command and the remove command didn't work either
c) I tried `ls` in root and it would give me an error and the info that there are 0 entries.

I'm sorry that I can't even tell you my NCP or NC version, since I can't get that login working again (and I forgot to document it when it worked that one time, shame on me). I assume it's pretty much up to date though, because i had the unattended auto updates activated.

I would be thankful for any suggestions! :-)
I'd rather not do a full reset (it took forever to backup all my photos), but if I had to I would at least like to understand what caused the problem to not run into it in another 3 months ...

Merry Christmas and thanks a lot,
lotiolentus

error message after any command in ncp-config
![img_20181226_194134436](https://user-images.githubusercontent.com/46168467/50456340-fb073580-0953-11e9-9b00-1d966bd2a87b.jpg)

raspi login problem
![img_20181226_200851694](https://user-images.githubusercontent.com/46168467/50456341-fb9fcc00-0953-11e9-90ad-a0bf30735fbe.jpg)

**Comment by ovpc** [comment]
Hi,
Please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for help.
Thank you

**Comment by lotiolentus** [comment]
So this a Nextcloud problem then, which is unrelated to NCP?

**Comment by ovpc** [comment]
It is most likely related to; no disk space left.
Github is for NCP bugs and NCP wiki discussions. **Not for asking questions!**
The community forum is for getting help with both NC and NCP.

> Please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for help.
> Thank you
