### ISSUE TITLE
Rethink update process for apps

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/nextcloudpi#759]
### Momentary situation
At the moment, all backward fixes are included in the file `update.sh`, which (for good reason) gets cleaned up once in a while.
If for some (not so good) reason no regular updates were made (no internet connection, error in the update process, ...) the system might get messed up if those changes are not made in a later update.

Further, those backward fixes are repeatedly executed in every update, which takes unnecessary update steps.

### Future situation (suggestion)
I would suggest to perform only the updates that are necessary for a given installation.

For doing that, the following structure could be useful:

Every bash file in in the folder `ncp-config.d` can contain an additional function `update()` which contains update instructions of the following style:

<details>
<summary>Style 1</summary>

```
update()
{
  "0.65.3":
  {
    _update commands for versions before 0.65.3_
  }
  "0.67.11":
  {
    _update commands for versions before 0.67.11_
  }
}
```
</details>

<br>

An easier (from the system programmers perspective) style could be similar to the following:

<details>
<summary>Style 2</summary>

```
update()
{
  [[ $VERSION < 0.65.3 ]] && {
    _update commands for versions before 0.65.3_
  }
  [[ $VERSION < 0.67.11 ]] && {
  {
    _update commands for versions before 0.67.11_
  }
}
```
</details>

<br>

During the update process, the updater then checks this function and only executes the relevant parts. If the order is kept as above, the updater can just run those lines from top to bottom.

#### System updates
For system updates, the same structure could be used in the existing `update.sh`.

**Comment by nachoparker** [comment]
Implemented https://github.com/nextcloud/nextcloudpi/pull/928
