### ISSUE TITLE
Can't connect to APPS

### ISSUE THREAD

**Issue by polmourgos** [nextcloud/nextcloudpi#76]
One more issue i have is I can't connect to apps.I have installed till now 6 times the nextcloudpi to raspberry cose i didnt know how to resolve deferent issues.The last problem i face is the nextcloud do not connect to apps so i can download what i want.I really cant solve this.All the rest works exelent
Thanks for any help again.

Here is the log 

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Resolving timed out after 10520 milliseconds/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103:GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132:GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25:GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)/var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php- line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134:GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165:GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125:GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))/var/www/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //apps.ne...', Array)/var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 99:OC\Http\Client\Client->get('https //apps.ne...', Array)/var/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 66:OC\App\AppStore\Fetcher\Fetcher->fetch('"2017-07-17 19 ...', '[{"id" "audiopl...')/var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 162:OC\App\AppStore\Fetcher\AppFetcher->fetch('"2017-07-17 19 ...', '[{"id" "audiopl...')/var/www/nextcloud/lib/private/Installer.php - line 394:OC\App\AppStore\Fetcher\Fetcher->get()/var/www/nextcloud/settings/Controller/AppSettingsController.php - line 291: OC\Installer isUpdateAvailable('nextcloud_annou...', Object(OC\App\AppStore\Fetcher\AppFetcher))[internal function] OC\Settings\Controller\AppSettingsController->listApps('installed')/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160:call_user_func_array(Array, Array)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90:OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AppSettingsController), 'listApps')/var/www/nextcloud/lib/private/AppFramework/App.php - line 114:OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AppSettingsController), 'listApps')/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'listApps', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/nextcloud/lib/private/Route/Router.php - line 299:call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/settings/apps/...')/var/www/nextcloud/index.php - line 40: OC handleRequest(){main}
```

**Comment by nachoparker** [comment]
Hi,
Can you explain what you mean by "cannot connect to apps"?

do you mean "installing apps from the admin panel of Nextcloud?"

**Comment by polmourgos** [comment]
> do you mean "installing apps from the admin panel of Nextcloud?"

**Comment by nachoparker** [comment]
Do you have internet access from your RPi? 

I know you set up a static address, so... did you correctly set up the gateway?

Can you `ping ownyourbits.com` from your RPi?

It seems to me like you just didn't configure your network correctly

**Comment by polmourgos** [comment]
Yes i have internet and  ping to sites.
When I clik on the apps then a circle appears and stay there spinning and spinning and after some time only some basics apps appears.I really like the nextcloupi img and I really want to have a successfull instalation.But till now I dont have success.  I wont give up.
Thank you nachoparker for your help.

**Comment by nachoparker** [comment]
I have never seen that before, seems to me like you have a connectivity issue... can you try the following from the RPi?

```
curl https://apps.nextcloud.com | head -30
```

and paste the output here?

**Comment by polmourgos** [comment]
Issue has solved after I did a clear installation to RP3.
I think was router port port forward  problem.

**Comment by nachoparker** [comment]
good job :)

**Comment by polmourgos** [comment]
I haft to say that i reinstall the nextcloudpi and have again the same problem as before.It is something that is not going well.    I gave  the above command and i got this answer,


curl https://apps.nextcloud.com | head -30
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/assets/img/favicon.png"/>
    <title>All apps - App Store - Nextcloud</title>
    <link rel="stylesheet" href="/static/assets/css/fonts.css">
    <link rel="stylesheet"
          href="/static/vendor/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/css/style.css">
    <link rel="stylesheet" href="/static/assets/css/theme.css">
    <link rel="alternate" type="application/atom+xml" title="News" href="/en/feeds/releases.atom" />
    <link rel="alternate" type="application/rss+xml" title="News" href="/en/feeds/releases.rss" />
    <script src="/static/vendor/bootstrap.native.min.js" async></script>
    <script src="/static/vendor/element-closest.js" defer></script>
    
    <script defer src="/static/public/app/list.js"></script>

</head>

<body>
<div id="container">
    

<div class="banner">
curl: (23) Failed writing body (0 != 5758)

I am very qurious to discover why this happening.Thanks for any help. 
Pol

**Comment by nachoparker** [comment]
I think there's something wrong with your hardware/network :S

**Comment by polmourgos** [comment]
`I think there's something wrong with your hardware/network :S`

When i readed your suggestion i couldn't take to serius.But after all my efforts that did not have results i decide to try a friend's router .And this was my problem.After I replaced it everything worked like it sould be.My ZTE router was a disaster.The new TPLink  is life saver.Tooks me so many days tasting and trying diferent thinks.All ports forwording corect,also the https ssl  everything.
I apologize that i din't belied you from the begin.A big thank you Nachoparker.

**Comment by nachoparker** [comment]
Nice, I am glad it finally works! :)

It can be hard to spot faulty hardware
