### ISSUE TITLE
Field to choose IPv4 or IPv6 (spdns)

### ISSUE THREAD

**Issue by traori** [nextcloud/nextcloudpi#761]
**Description**  
In the window DDNS_spDYN it have 3 Fields.
1. ACTIVE (YES/NO)
2.DOMAIN
3.TOKEN

In the script spdnsUpdater.sh is at the beginning a param. IPv6=$3.But there are nowwhere to choose.
The problem is IPv6 with DS-Lite.

**Example**  
.
.
3.TOKEN
4.IPv6 (YES/NO)
or
4.Internet Protocol (IPv4/IPv6)

@TomTurnschuh : Is this a problem to implement? I don`t know how to change the GUI of the script.

**Comment by TomTurnschuh** [comment]
Hi traori

It actually is implemented – but obviously, no numbers are allowed for `ncp-config` in shell.

Thanks for the report.

Until the implementation of a solution, you can use `ncp-web` instead.

<kbd><img src="https://user-images.githubusercontent.com/36013390/50575808-49f61480-0e05-11e9-88dd-520fd1edf870.png" /></kbd>

**Comment by TomTurnschuh** [comment]
@nachoparker: Is this possible to fix this in `ncp-config` by allowing numerics?

**Comment by traori** [comment]
Hello,
my problem is, that the ncb-web not work and had never work for me. I don't know why. Also after fresh install it doesn't work.

**Comment by nachoparker** [comment]
@TomTurnschuh I am not sure of what you mean. ncp-config and ncp-web accept numbers

**Comment by TomTurnschuh** [comment]
> 
> 
> @TomTurnschuh I am not sure of what you mean. ncp-config and ncp-web accept numbers

If you open `DDNS_spDYN` in `ncp-config` (I use SSH with PuTTY), there is no option `IPv6`, as it is supposed to be and as is available in `ncp-web`. If I remove the mumber `6` in the .sh file, the option is also available in `ncp-config`.

**Comment by nachoparker** [comment]
ah I see, well just wait for `v1.0.0` to land. after the rework there is no such restriction to the name of the fields.

**Comment by TomTurnschuh** [comment]
@traori: As a temporary solution, you can change the respective option to `yes` in `/usr/local/etc/ncp-config.d/DDNS_spDYN.sh` line 15. Afterwards, you can use `ncp-config` for setting the other options and running the script.

**Comment by nachoparker** [comment]
`v1.x` has been released

**Comment by traori** [comment]
Hi,
for me don`t work. Some solution ?

**Comment by nachoparker** [comment]
fixed
