### ISSUE TITLE
Cant connect to kodi

### ISSUE THREAD

**Issue by GuardDog04** [nextcloud/nextcloudpi#767]
I am unable to add my Nextcloud adress to my local KODI.

My configuration is:
1. NextcloudPi on a RPi3
2. Kodi on FireTV Stick

The URL I used is:
- 192.168.178.26
- nextcloud/remote.php/dav/files/MYUSERNAME/

I use the IP since I dont use port-forwarding nor an dyndns.
KODI shows that it can't connect to the server.

**Comment by ovpc** [comment]
Please use the [forum](https://help.nextcloud.com/tags/ncp) for questions and to find help. Thank you.
Github is forNCP  bug, feature or wiki related discussions only.
