### ISSUE TITLE
Access Web-UI via ipv6

### ISSUE THREAD

**Issue by lenzls** [nextcloud/nextcloudpi#770]
Hello,

it seems to me that the nextcloudpi web-ui does not work with ipv6.

After some tinkering around I noticed that I was greeted by a "403 Forbidden" error when accessing "https://nextcloudpi:4443"

After a quick check I noticed that I was trying to connect via ipv6 but the configuration has this not on the whitelist.

When I add my ipv6 ip to 
`/etc/apache2/sites-enabled/ncp.conf`
```
[..]
<RequireAny>
      Require host localhost
      Require local
      Require ip 192.168
      Require ip 172
      Require ip 10

      # added by me
      Require ip fd00::4077:0027:d823:a11b/64
</RequireAny>
[..]
```

I can access the web-ui without any problems.

I don't know what could be done about that but it seems to me like an issue not only I would experience.

regards

**Comment by nachoparker** [comment]
Hello,

Good catch, could you try doing `Require ip fd00::/8` instead of your rule, and see if it works for you?

Thanks!

**Comment by lenzls** [comment]
Thanks for the quick response.

Your suggested rule seems to work as well :)

**Comment by nachoparker** [comment]
awesome, thanks

>Will the 1.3.7 update then just override my ncp.conf?

yes

**Comment by mrkskwsnck** [comment]
I ran into exactly that same issue with a fresh install from the Raspberry Pi image [NextCloudPi_RPi_01-13-19](https://ownyourbits.com/downloads/NextCloudPi_RPi_01-13-19/). The NCP version was 1.4.x something. Luckily, I found this bug report and so I was able to apply the fix manually. Thanks a lot!

**Comment by nachoparker** [comment]
@mrkskwsnck if you update to the latest version that should work without manual intervention

**Comment by mrkskwsnck** [comment]
@nachoparker, in fact I already updated to NCP version 1.5.x while writing my above comment. It didn't solve the problem.

**Comment by nachoparker** [comment]
@mrkskwsnck how does your  `/etc/apache2/sites-enabled/ncp.conf` look?

**Comment by mrkskwsnck** [comment]
My current `ncp.conf` file looks like:

```

**Comment by nachoparker** [comment]
thanks, does changing that line for `Require ip fd00::/8` work for you?

**Comment by mrkskwsnck** [comment]
Unfortunately no, it does not work with

```apache
Require ip fd00::/8
```

for me :-1: Neither via my domain nor using the IPv6 address within the browser.

**Comment by n-b** [comment]
Shouldn’t we allow link-local addresses as well? (i.e.`Require ip fe80::/10`) This was needed in my case.

**Comment by nachoparker** [comment]
thanks, changed to `fe80::/10`

**Comment by n-b** [comment]
I suspect both `fe80::/10ˋ (link-local) and `fd00::/8` (“Unique local”) are necessary depending of the local network configuration.
