### ISSUE TITLE
using backedup volume - tries to (unsuccessfully re-initialize)

### ISSUE THREAD

**Issue by LukasWerfel** [nextcloud/nextcloudpi#775]
Hi,

I am using the dockerized version of ncp. You can find my setup [here](https://github.com/LukasWerfel/server-setup/blob/master/docker-compose-local.yml#L4-L12).

After some cleaning up I cannot start the ncp docker anymore. I safed the volume and re-added it. 
Now all I get is an endless 
> Initializing NextCloudPi for the first time

which refreshes itseld every few seconds.

How can I restore the ncp instance?

**Comment by ovpc** [comment]
Not sure if related, but might be useful info [forum](https://help.nextcloud.com/t/nextcloudpi-1-2-nc15-0-2-a-call-for-testing/44986/15) 
Something about removing data/bin from ncp volume. When creating new container with existing volume.
