### ISSUE TITLE
armhf / Docker: Services missing such as NTP and Samba

### ISSUE THREAD

**Issue by retani** [nextcloud/nextcloudpi#776]
This probably relates to: https://help.nextcloud.com/t/setup-samba-on-odroid-hc1-using-nextcloudpi-testing-image/24523

I have installed nextcloudpi on Odroid HC2 using docker:

> docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi-armhf $DOMAIN

It works, but it seems that several of the services are missing, for example NTP and Samba – see screenshot. I have updated to the latest version 1.3.6 but the problem remains.

The TUI (terminal interface) offers the same options as the web interface, so it lacks these services, too. I also couldn't find a way to install them, if this is the way to go. Thanks a lot!

![image](https://user-images.githubusercontent.com/3465427/51217845-13061f80-192a-11e9-9393-5b0d9d65890e.png)

````
NextCloudPi version  v1.3.6
NextCloudPi image    NextCloudPi_docker_01-13-19
distribution         Debian GNU/Linux 9 \n \l
automount            no
USB devices          sda
datadir              /data/app/data
data in SD           no
data filesystem      ext2/ext3
data disk usage      173G/7.3T
rootfs usage         4.1G/30G
swapfile             none
dbdir                /data/database
Nextcloud check      ok
Nextcloud version    15.0.2.0
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        closed
port check 443       closed
IP                   ***REMOVED SENSITIVE VALUE***
gateway              ***REMOVED SENSITIVE VALUE***
interface            eth0
certificates         ***REMOVED SENSITIVE VALUE***
NAT loopback         no
uptime               15:39
````

**Comment by nachoparker** [comment]
Please use the forum for questions.

Those services are not available in the docker version

**Comment by retani** [comment]
Thanks! And sorry for being in the wrong place. I checked the forum and found the reply that suggested to open an issue. Thanks again.

**Comment by nachoparker** [comment]
no problem :)
