### ISSUE TITLE
Update to v1.4.5 via ncp-update fails when cron.hourly is empty

### ISSUE THREAD

**Issue by necopinus** [nextcloud/nextcloudpi#784]
When `/etc/cron.hourly` is empty (which can happen in docker containers), the update to v1.4.5 fails (because `chmod 755 /etc/cron.daily/* /etc/cron.hourly/*` on line 276 of `update.sh` takes an error). To account for this case, `update.sh` should test if various `/etc/cron.*` contain any files of interest before applying the fix.

Pull request incoming momentarily.

**Comment by ovpc** [comment]
I can confirm this also happens on Debian9 (curl installed)
[ncp-update 1.4.1 fails to update to 1.4.5](https://pastebin.com/Xb8LstPy)

**Comment by nachoparker** [comment]
Thanks for the fix!

**Comment by ovpc** [comment]
Cool, thanks for fix
When exiting ncp-config v1.4.6 I now get following output:

> sudo ncp-config
/usr/local/bin/ncp-config: line 18: local: can only be used in a function
/usr/local/bin/ncp-config: line 19: local: can only be used in a function
/usr/local/bin/ncp-config: line 20: local: can only be used in a function

**Comment by ovpc** [comment]
Thanks @necopinus 
@nachoparker let me know when/if want me to run  **ncp-update devel**

**Comment by nachoparker** [comment]
thanks!
