### ISSUE TITLE
Cron job ncp-notify-update & ncp-notify-unattended-upgrade

### ISSUE THREAD

**Issue by funkmastergst** [nextcloud/nextcloudpi#788]
Hi,
after turning on "unattended upgrades" in NCP-WebGUI for the first time I regularly got an hourly e-mail at the 40th minute if an update is available or not. This results in a lot of e-mails in my inbox. Does this interval is as you intended?
The behaviour is defined here: /etc/cron.d/ncp-notify-updates
I changed the beginning from "40  */1" into "0  0" to receive notifications once a day which is ok for me.

Also its not quiet clear to me how "unattended upgrades" interacts with "nc-autoupdate-nc" and "nc-autoupdate-ncp" if the former is switched on and the last two options are deactivated. Does this config triggers any unattended upgrades at all or just the notifications?

Kind regards
funkmastergst

**Comment by nachoparker** [comment]
Hello,

Notify updates and unattended upgrades are completely separate things. The first one checks for NCP updates, the second one auto-intalls debian packages.

In the future, please use the forums for questions, and leave this for bug reports.
