### ISSUE TITLE
NC-backup-auto enhancements

### ISSUE THREAD

**Issue by Shadowstreik** [nextcloud/nextcloudpi#79]
Request for time-of-day selection fields for NC-backup-auto. None currently exist.

Thank you.

Issue reference #78

**Comment by nachoparker** [comment]
- [ ] backup every X days even if there are reboots
- [ ] make it not depend in systemd timers ( so it can be included in docker version )
- [ ] make it happen at night

**Comment by nachoparker** [comment]
implemented in `v0.46.40`
