### ISSUE TITLE
nc-snapshot trying to create snapshots outside of data filesystem

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/nextcloudpi#794]
[This line in nc-snapshot.sh](https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/BACKUPS/nc-snapshot.sh#L37) tries to set a directory outside of the src filesystem as btrfs-snapshot target (usually in the root FS). This will fail if the parent file system is not in btrfs format (which it usually is not).

The resulting error message is:
```
ERROR: not a btrfs filesystem: /media/cloud/../ncp-snapshots
```

Could it be that the variable which was intended to be used here is `$DATADIR` instead of `$MOUNTPOINT`?

**EDIT1:** The same would apply to [nc-snapshot-auto.sh](https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/BACKUPS/nc-snapshot-auto.sh#L42)

**EDIT2:** My configuration:
```sh
> DATADIR=$( sudo -u www-data php /var/www/nextcloud/occ config:system:get datadirectory )
> MOUNTPOINT="$( stat -c "%m" "$DATADIR" )" || return 1
> stat -fc%T "$MOUNTPOINT"
btrfs
```

**Comment by theCalcaholic** [comment]
The same would apply to [nc-snapshot-auto.sh](https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/BACKUPS/nc-snapshot-auto.sh#L42)

**Comment by theCalcaholic** [comment]
Ah, I suppose I'm missing a btrfs subvolume

**Comment by ekorn** [comment]
I have the same problem could you explain in more detail what you did to solve the Problem ?

**Comment by Itchyfantastico** [comment]
I have the same issue.
It does work with the btrfs-snp command via SSH and leaving out the ../ directory jump

**Comment by milianw** [comment]
I'm also running into this issue. what is the purpose of the relative path, or snapshotting the whole disk instead of just the datadir?
