### ISSUE TITLE
impossible to connect to nextcloud when I turn off the raspberry

### ISSUE THREAD

**Issue by pruna1971** [nextcloud/nextcloudpi#806]
Good afternoon . I bought a new 64GB card and I have made a new installation of nextcloud through docker. all perfect . It works very well . but when I restart the raspberry pi then there is no way to connect again. I never unplug the raspberry directly. What could be the problem? It seems like some configuration. Thank you .

**Comment by shadowstreik** [comment]
A link to the support page can be found, here...

https://mastodon.social/@NextCloudPi

**Comment by nachoparker** [comment]
Thanks for using the forums for support

help.nextcloud.com
