### ISSUE TITLE
Internal Server Error after Update

### ISSUE THREAD

**Issue by misterlindsey** [nextcloud/nextcloudpi#818]
Looked through previous concerns from Oct, but not seeing a resolution that fits my issue. 

After running sudo apt update and sudo apt upgrade I am not able to load the page at drive.mattlindsey.com. During the update, I got a config question regarding PHP 7.2, some file that was different. I opted to keep the existing file. I believe it was a php.ini that was too long to use the compare option. 

Any pointers on what might be causing this would be greatly appreciated. I'm not sure what error log would give me more verbose information about this.

**Comment by misterlindsey** [comment]
Updated NextCloudPi in admin console and everything is back up. Not sure what happened.

**Comment by shadowstreik** [comment]
Possible hint - NCP is written in such a way that running update and upgrade may not necessarily be required. turning on auto updates may already cover everything needed to operate the software, properly.

A link for support is available on the NextCloudPi Mastodon page...

https://mastodon.social/@NextCloudPi

Thank you.

**Comment by nachoparker** [comment]
thanks @shadowstreik
