### ISSUE TITLE
Docker: Expose Let's Encrypt certificate for other containers or services

### ISSUE THREAD

**Issue by giddyhup** [nextcloud/nextcloudpi#819]
**Description**  
It would be useful to make the certificate available for other services or containers on the same server.

**Example**  
I already use the certificate in a non-containerized Nextcloudpi instance for an MQTT broker. It would be good if a configuration were possible where certificate data would be made available to the host or other containers via a volume.

**Comment by nachoparker** [comment]
hello,

thank you for the suggestion. I am afraid this is out of the scope of NCP. The standard thing to do is to set up a reverse proxy container (and deactivate https-only in NCP)

cheers
