### ISSUE TITLE
Raspberry pi images not available?

### ISSUE THREAD

**Issue by CollinChaffin** [nextcloud/nextcloudpi#820]
When I follow the recently updated wiki (2/26) in this repo to this link: `https://ownyourbits.com/nextcloudpi`

Has a link with this text: `preinstalled SD card images` that links to `https://ownyourbits.com/nextcloudpi/#download` and is a loop where at no time are any actual pi image files listed.

Is something under construction, or is the wiki update incorrect, or ?

Can someone please indicate where I can actually download the `.img` files for a pi that are continually referred to and I'm guessing are still available somewhere?  TIA!

**Comment by ovpc** [comment]
https://ownyourbits.com/downloads/
