### ISSUE TITLE
Got error 'PHP message

### ISSUE THREAD

**Issue by Haraade** [nextcloud/nextcloudpi#821]
![screenshot_20190302-131815__01](https://user-images.githubusercontent.com/23292068/53681836-53a9d480-3cef-11e9-8b93-49d19aa3f59f.jpg)
![screenshot_20190302-131737__01](https://user-images.githubusercontent.com/23292068/53681837-53a9d480-3cef-11e9-8780-fb09541b4ea2.jpg)

**System information**

NextCloudPi version  v1.8.0
distribution Debian GNU/Linux 9 \n \l

!-- Paste the output of `sudo ncp-report` -->

Sat Mar 02 11:49:06.639559 2019] [proxy_fcgi:error] [pid 5074:tid 2765796400] [client 192.168.0.2:47302] AH01071: Got error 'PHP message: PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /var/www/ncp-web/ncp-output.php on line 37\n'

**Comment by nachoparker** [comment]
This has been fixed in `devel`. Run `sudo ncp-update devel`, or wait a couple days for the regular update

thank you for reporting

**Comment by Haraade** [comment]
Thank you!
