### ISSUE TITLE
Port 80 and 443 are blocked by my ISP

### ISSUE THREAD

**Issue by Chippel** [nextcloud/nextcloudpi#824]
I don't know what to do now. Seems like my ISP blocked port 80 and 443. I forwarded them in my router but outside access still doesn't work. 

Any workaround to acess my Nextcloud when I'm not at home?

**Comment by ovpc** [comment]
Should really use [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions.
As long as you forward to internal 80 and 443 you can use any other free external port you want, for example 8880 and 8843.

**Comment by Chippel** [comment]
But how do I do that?

**Comment by ovpc** [comment]
https://is.gd/XAxZG8 or  use forum for questions.Thank you!
