### ISSUE TITLE
Rock64 3-7-19 image no video 

### ISSUE THREAD

**Issue by MichaelVash7886** [nextcloud/nextcloudpi#829]
Extracted the image from the tar file and used etcher to create a burn to a miscrosd. Plugged everything in but getting no video on two different monitors with two different hdmi cables.

Going to try to reflash the image to see if that makes a difference. If not I'll try the image from Jan.

**Comment by nachoparker** [comment]
hello,

There was a bad image uploaded by mistake, only like 3 megabytes big. There is a new one that I just uploaded and that one should be fine.

Please, let us know if it's not
