### ISSUE TITLE
Automatic Update of NoIP DDNS

### ISSUE THREAD

**Issue by cottoa00** [nextcloud/nextcloudpi#83]
### QUESTIONS (not an issue... not sure how to tag as such)

Have my NextcloudPi up and running... just received notice from NoIP (my free DDNS service) that I need to reregister (to maintain free service) or upgrade to paid service.
Somewhere in my review of all the forums and docs that you have a script that automatically reregisters my system. Can you please confirm... if not I want to be able to keep my DDNS alive ;-)

Cheers,
Tony Cotton

**Comment by cottoa00** [comment]
Did some more digging in docs... think the cron job was updating noIP whith any IP change not sending "renewal requests" for domain name maintenace every 30 days.
Went ahead and confirmed my free domain for another month and should just upgrade to paid to avoid the monthly renewal ;-)

**Comment by nachoparker** [comment]
There is a service (or daemon) called `noip2` that updates the IP address associated with your domain.

The registration of the domain itself, has to be renewed every month unless you upgrade. It's just clicking a link once a month.
