### ISSUE TITLE
Installation on Rock64 failed

### ISSUE THREAD

**Issue by suxlex** [nextcloud/nextcloudpi#830]
I'm trying to get NCP to work on a Rock64 (4GB). First I installed Armbian Stretch legacy kernel 4.4.y (Armbian_5.75_Rock64_Debian_stretch_default_4.4.174.img) on an SD card.
Then
curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash 
started.  The installation program downloaded and installed many files.

Unfortunately there are error messages at the end:
....
Setting up fail2ban (0.9.6-2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/fail2ban.service → /lib/systemd/system/fail2ban.service.
Job for fail2ban.service failed because the control process exited with error code.
See "systemctl status fail2ban.service" and "journalctl -xe" for details.
invoke-rc.d: initscript fail2ban, action "start" failed.
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-03-09 17:24:54 UTC; 42ms ago
     Docs: man:fail2ban(1)
  Process: 22254 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=255)

Mar 09 17:24:54 rock64 systemd[1]: fail2ban.service: Unit entered failed state.
Mar 09 17:24:54 rock64 systemd[1]: fail2ban.service: Failed with result 'ex…de'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package fail2ban (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up whois (5.2.17~deb9u1) ...
Processing triggers for systemd (232-25+deb9u8) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 fail2ban
E: Sub-process /usr/bin/dpkg returned an error code (1)
Running nc-init
Setting up a clean Nextcloud instance... wait until message 'NC init done'
Setting up database...
Setting up Nextcloud...
Set an admin username.
Set an admin password.

The installtion is invald, https://192.168.1.64/ asks for to create administrator account, data directory /var/www/nextcloud/data , database, database directory, password and so on.

**Comment by nachoparker** [comment]
easier to download one of the premade images
