### ISSUE TITLE
NTFS (Innocent newbie question)

### ISSUE THREAD

**Issue by Ypot** [nextcloud/nextcloudpi#831]
I am using libreelec, installed nextcloud using docker and I fell in love with it.

I know it's already said that there is no support for NTFS external disks due to permission issues, low performance, etc.

But can't stop thinking that Kodi plays movies from an external NTFS disk, transmission (add-on) works with torrents great, even syncthing (add-on) doesn't seem to have any problem with this file format.
Why not nextcloud?
Would those mentioned programs work much better in ext3 for example?
Do they work fine just because they are addons and are very tweaked?

Thanks for your work

**Comment by ovpc** [comment]
Please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm) for questions
