### ISSUE TITLE
Fix/find a workaround for btrfs snapshots on docker

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/nextcloudpi#832]
When using btrfs-snapshots in docker, a variety of ncp-apps fail (due to not being able to delete or create the data directory (due to it being a btrfs volume), for example).
It should be evaluated

1) which apps have these kind of problems
2) whether it's feasible to implement workarounds
3) whether functioning btrfs-snapshots can be achieved by elevating container privileges (which then should be added to the wiki)

**Comment by theCalcaholic** [comment]
@nachoparker I don't seem to be able to assign this to myself, so feel free to do that. :)

**Comment by nachoparker** [comment]
thanks for the help, that would be awesome. Also `nc-update-nextcloud` is one of them

**Comment by Zakspeed** [comment]
In docker - NexcloudPi   "x.x.x.x:4443"
Update current instance to a new Nextcloud version
```
[nc-update-nexcloud]
BTRFS not supported

```

**Comment by ovpc** [comment]
![CommentOutBtrfsCheckScreenshot2019-07-15_12-02-13](https://user-images.githubusercontent.com/8775469/61208841-94334900-a6f8-11e9-9d30-cb299da128b7.png)
Need to do that from commandline, comment out the btrfs check with
> sudo nano /usr/local/bin/ncp-update-nc

**Comment by Zakspeed** [comment]
Thanks
I made that change in ncp-update-nc (comment that line)
And the update of docker-NexcloudPi, and update !!!
:)

**Comment by Zakspeed** [comment]
But, I do not know what I do wrong, that if I do tests, and stop the service or restart the machine (the raspidocker :)))
do not lift the container with the NCP

**Comment by nachoparker** [comment]
BTRFS is now supported
