### ISSUE TITLE
Bind port 443 already used

### ISSUE THREAD

**Issue by Victornade** [nextcloud/nextcloudpi#833]
Hi everyone !
Thank you for your amazing work here !

I face some issue here deploying nextcloudpi :

I already have apache2 installed (redirecting my subdomain chat.X.com to localhost:3000 aka rocketchat)
Now I want apache to redirect cloud.X.com to nextcloud 

BUT I can't launch nextcloudpi docker since port 80 and 443 are already used by apache2...
Even if I bind port 444 and 81 to docker using :

`docker run -d -p 4443:4443 -p 444:443 -p 81:80 -v /media/pi/usb/ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi-armhf 192.168.0.17
`

I can't figure out how to make a good redirection within apache. any idea here ?

Something like :

```

 <IfModule mod_ssl.c>
     <VirtualHost *:80>
         ServerName              cloud.X.com
         Redirect                / https://cloud.X.com
     </VirtualHost>
     <VirtualHost *:443>
         ServerName             cloud.X.com
         ServerAdmin             X@X.com
         SSLCertificateFile      /etc/letsencrypt/live/cloud.X.com/cert.pem
         SSLCertificateKeyFile   /etc/letsencrypt/live/cloud.X.com/privkey.pem
         SSLCertificateChainFile /etc/letsencrypt/live/cloud.X.com/chain.pem
         ProxyPreserveHost On
     ProxyPass / https://localhost:444/
     ProxyPassReverse / https://localhost:444/
 
     </VirtualHost>
</IfModule>

```

The other workaround would be to disable https over nextcloud and let my apache do the job, but I didn't found how to disable https (even with nc-httpsonly disabled)

Please help me, I shouldn't be the only one hving this issue :) 

And again, thank you for your work.

EDIT : going to cloud.X.com give me :
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by nachoparker** [comment]
Hi, 

this is not a bug, so the proper place to discuss your issue is in the forums

https://help.nextcloud.com/c/support/appliances-docker-snappy-vm

cheers!
