### ISSUE TITLE
1.10.0 update failed - ncc command not found

### ISSUE THREAD

**Issue by TimTaler007** [nextcloud/nextcloudpi#845]
Try to update from an older version 1.5.1 to the new one and it fails every time with the line:
`./update.sh: line 202: ncc: command not found`
I found an older issue which describe the reason. NCC is an alias for `sudo -u www-data php /var/www/nextcloud/occ` and it could set manually. I tried it but it will not works.
I also made the alias permant and wrote it to /etc/bash.bashrc but this will not work with the sudo command and you have to run the ncp-update with sudo.
Is is possible to build in a check-routine in the update script to handle this case or is it possible to fix it manually?

Thanks for your attention and your help!

**Comment by nachoparker** [comment]
I suggest you backup and restore in a new image. We don't know what other updates you have skipped.
