### ISSUE TITLE
Mobbing Data to new Drive

### ISSUE THREAD

**Issue by Sporty01** [nextcloud/nextcloudpi#847]
Hi,

I‘m Running nextcloudpi since one year. Now I bought a new 1Tb Drive and want to move the Data from the old  Drive to the new one. 
What have I tried:
I have done a Backup on an other Drive. 
I have Format the new Drive in nextcloudpi to media/USBdata. 
I tried to restore the Backup at the new Drive. 
At the end of the restore process there was the Feedback: „ERROR 2002 (HY000): Can‘t connect to local MySQL Server through socket ‚var/run/mysqld/mysql.sock‘ (2 „No such file of Directory“)“. 
Can you please help me to fix this Problem?

**Comment by nachoparker** [comment]
please use the forums for support
