### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by EtienneHenger** [nextcloud/nextcloudpi#851]
**Description**

It would be awesome to have an Android App to perform quick on-the-go server maintenance tasks.

**Comment by nachoparker** [comment]
note that you can access ncp-web from your phone browser

**Comment by EtienneHenger** [comment]
Yeah, I know. It would just be nicer/easier to manage in an App. 
This is a nonessential luxury incase you ever have nothing to do... 😉

**Comment by theCalcaholic** [comment]
We're not gonna implement this as it is a lot of work that we need for other things. If anyone wants to work on this, feel free to contact me
