### ISSUE TITLE
Time in Nextcloud settings is wrong

### ISSUE THREAD

**Issue by amilopowers** [nextcloud/nextcloudpi#854]
Hello
First I want to thank you for your amazing software!

I installed NCP and set up everything. The time zone in the underlying Linux is correct.

![grafik](https://user-images.githubusercontent.com/9914682/54848148-6acd5800-4cd8-11e9-95b3-6638e431c6f0.png)

However the time in NC settings says:
![grafik](https://user-images.githubusercontent.com/9914682/54848175-86d0f980-4cd8-11e9-894b-576f0b549f57.png)

So it is one hour behind. The actual time here is 20:27 (7:52PM).

Is this a bug or just a wrong configuration?

**Comment by nachoparker** [comment]
Hi,

If the Linux time is correct, then this must be a Nextcloud bug. Please report tere.

Thanks!
