### ISSUE TITLE
Letsencrypt dependencies missing

### ISSUE THREAD

**Issue by lb1974** [nextcloud/nextcloudpi#863]
My certificate was not renewed. So I tried running letsencrypt again and was met by the following

[ letsencrypt ]
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://packages.sury.org/php stretch InRelease
Reading package lists...

Reading package lists...
Building dependency tree...

Reading state information...
ca-certificates is already the newest version (20161130+nmu1+deb9u1).
python is already the newest version (2.7.13-2).
openssl is already the newest version (1.1.1b-1+0~20190228092419.10+stretch~1.gbp729d89).
openssl set to manually installed.
gcc is already the newest version (4:8.1.0-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
python-dev : Depends: libpython-dev (= 2.7.13-2) but it is not going to be installed
Depends: python2.7-dev (>= 2.7.13-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by nachoparker** [comment]
https://help.nextcloud.com/t/the-following-packages-have-unmet-dependencies/46386/23
