### ISSUE TITLE
ncp-update errors

### ISSUE THREAD

**Issue by 05nelsonm** [nextcloud/nextcloudpi#866]
Had unattended upgrades on and I kept getting notifications that Apache3 was installed about every hour.

logged in via ssh to see what was up.

Tried disabling unattended upgrades and got an error message that said my swap file was full, so I increased its size and kept it mounted at /var/swap

rebooted machine

tried ncp-update and I'm getting this error

> pi@nextcloudpi:~ $ sudo ncp-update
> Downloading updates
> Performing updates
> jq: error: Invalid escape at line 1, column 4 (while parsing '"\'"') at <top-level>, line 1:
> .params[2].value = "\''/matthew_nelson/MyCloudEX2Ultra/Matthew/'\"                    
> jq: error: syntax error, unexpected $end, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Unix shell quoting issues?) at <top-level>, line 1:
> .params[2].value = "\''/matthew_nelson/MyCloudEX2Ultra/Matthew/'\"                                                                
> jq: 2 compile errors

`matthew_nelson/MyCloudEX2Ultra/Matthew/` is a folder location where I have an NFS mount established through fstab setup. Wondering what's going on.

also from nc-info, my PHP service is down and I'm getting a 503 error.

Thanks.

**Comment by ovpc** [comment]
@ [forum](https://help.nextcloud.com/t/ncp-update-errors/50574)
We can re-open here if it turns out to be a bug ;-)
