### ISSUE TITLE
App installation not enough space

### ISSUE THREAD

**Issue by mcbigmoses** [nextcloud/nextcloudpi#87]
Hi,

didn’t know if its a bug or a feature:
I’ve used a 8 GB SD Card on my RPi and installed nextcloud apps but after a view apps I got the information that there is not enough space. I change the installation to a 64 GB card and got the same problem.

Is there any restriction in the installed apps?

**Comment by nachoparker** [comment]
have you expanded the filesystem in `sudo raspi-config`?

**Comment by mcbigmoses** [comment]
Yes, i did, no change, it is also a greater Sd Card

**Comment by nachoparker** [comment]
mmm output of `df -h`?
