### ISSUE TITLE
NextCloud Version 15.0.6 doesnt exist.

### ISSUE THREAD

**Issue by lotze1234** [nextcloud/nextcloudpi#877]
Hi all,

I try to install mynextcloudpi with : https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh .....

Everything worksfine till the script will download the nextcloud release. 

It tryed to download the version 15.0.6 but it doesnt exist. 

"unning nc-nextcloud
Downloading Nextcloud 15.0.6...
couldn't download https://download.nextcloud.com/server/releases/nextcloud-15.0.6.tar.bz2
root@raspberry:~# 
"

How i can fix that?

Regards

**Comment by ovpc** [comment]
Probably a time out of the NC server, just wait a cpl min or hr and try again.
Please use the [forum](https://help.nextcloud.com/tags/ncp) to get help.

**Comment by lotze1234** [comment]
Hi thank you for your answer, but please visit the nextcloud homepage - they took the release 15.0.6 off. Latest working version is now again 15.0.5.

**Comment by ovpc** [comment]
Weird! But nothing to do with NCP tho
Please report it on the Nextcloud forum or hub.
If NCP is installed, you can run nc-nextcloud and at least install 15.0.5 
and just wait for NC devs to get it fixed.
