### ISSUE TITLE
Rename configuration variables into self-documenting ones

### ISSUE THREAD

**Issue by Hofer-Julian** [nextcloud/nextcloudpi#886]
Especially when it comes to number-based configuration variables, I often had to look into the source code to be 100% sure what they meant. That is why I suggest to rename some of them to make their purpose more clear to other users. 

- Backups
  - nc-backups-auto
    - Backup days -> Backup periodicity (in days)
    - Backup limit -> Number of backups to keep
  - nc-backup
    - Backup limit -> Number of backups to keep
  - nc-rsync-auto
    - Sync days -> Sync periodicity (in days)
  - nc-snapshot-sync
    - Sync days -> Sync periodicity (in days)
- Config
  - nc-previews-auto
    - Run time -> Runtime (in minutes)
  - nc-scan-auto
    - Scan interval -> Scan periodicity (in minutes)
- Networking
  - freeDNS
    - Update Interval -> Update periodicity (in minutes)
  - no-ip
    - Time -> ?

I used the word periodicity a lot of times, maybe there is a better one, but it would be great if it would be the same for all entries which occur periodically :)

**Comment by nachoparker** [comment]
good point. Please send a PR with your proposed changes, it's only a bunch of JSON files so it's an easy edit

**Comment by nachoparker** [comment]
PR merged, thanks!
