### ISSUE TITLE
Issue with web-ui and no-ip on Rock64

### ISSUE THREAD

**Issue by tmvtarqan** [nextcloud/nextcloudpi#887]
Hi, I hope this is appropriate to post here. If not, please direct me to the appropriate medium.

I just set up NextCloudPi on a Rock64 last night, and have been struggling with two simple but extremely irritating issues since. I want to use no-ip for the DDNS provider, but when I select the option I'm unable to enter setup. The initial prompt, which reads: "For this step to succeed, you need to register a noip account first. Internet access is required for this configuration to complete.", appears and I select "I understand", after which the screen simply reads "Done. Press any key..." as it does for every option after successful setup. The duckDNS and freeDNS options allow me to enter setup parameters with no issue.

If I try to set up no-ip manually it reproduces this issue: https://github.com/nextcloud/nextcloudpi/issues/62

So, I thought, fine. I'll try the web-UI. Maybe there's a bug in the TUI, which would be nice to know, but I just want to get this working for now. I enabled the nc-webui option, restart apache2, ok. From the same device I'm able to SSH into the Rock64 with and use the TUI with no issue, I try to access the web-UI. An "Authentication Required" prompt appears, which reads "https://nextcloudpi is requesting your username and password. The site says: "ncp-web login"". It isn't the themed screen showed in the NextCloudPi docs. So, no matter what combination of username and password I try here (root with the password I've set, non-root user with password I set up, or "ncp" with password "ownyourbits" as I've found mentioned a few places) it immediately fails and gives me an Internal Server Error page, and any attempt to reach the same address without clearing cookies, cache, etc. produces that page.

Does anyone have any insight into this? I've tried rewriting the image to the SD card and tinkered with just about every other configuration option, but to no avail.

**Comment by ovpc** [comment]
This is not the place to get help, use the forum for that please.
All passwords are generated at initial run.
For ncp-web:4443 you can view/set password for user ncp in terminal with ncp-config>Config>nc-passwd.
