### ISSUE TITLE
Update to 1.12.0 fails due to unmet dependency

### ISSUE THREAD

**Issue by XDA-Bam** [nextcloud/nextcloudpi#896]
I am currently running NCP 1.11.5 on Armbian 5.73 on a Rock64. The update to 1.12.0 fails with the following log:

> [ nc-update ]
> 
> Downloading updates
> Performing updates
> Config value squareSizes for app previewgenerator set to 32
> Config value widthSizes for app previewgenerator set to 128 256 512
> Config value heightSizes for app previewgenerator set to 128 256
> System config value jpeg_quality set to string 60
> [ unattended-upgrades ]
> Running unattended-upgrades
> Unattended upgrades active: yes (autoreboot true)
> Unattended upgrades active: yes (autoreboot true)
> 
> --2019-05-02 15:55:59-- https://packages.sury.org/php/apt.gpg
> Resolving packages.sury.org (packages.sury.org)... 104.31.94.169, 104.31.95.169, 2606:4700:30::681f:5fa9, ...
> Connecting to packages.sury.org (packages.sury.org)|104.31.94.169|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1769 (1.7K) [application/octet-stream]
> Saving to: '/etc/apt/trusted.gpg.d/php.gpg'
> 
> 0K . 100% 5.73M=0s
> 
> 2019-05-02 15:55:59 (5.73 MB/s) - '/etc/apt/trusted.gpg.d/php.gpg' saved [1769/1769]
> 
> [ nc-backup-auto ]
> Running nc-backup-auto
> automatic backups enabled
> 
> automatic backups enabled
> Installing nc-backup
> Hit:1 http://security.debian.org stretch/updates InRelease
> Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
> Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
> Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease
> Hit:6 http://cdn-fastly.deb.debian.org/debian stretch Release
> Hit:7 https://packages.sury.org/php stretch InRelease
> Hit:2 https://apt.armbian.com stretch InRelease
> Reading package lists...
> 
> Reading package lists...
> Building dependency tree...
> 
> Reading state information...
> pigz is already the newest version (2.3.4-1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Installing nc-restore
> Hit:1 http://security.debian.org stretch/updates InRelease
> Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
> Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
> Hit:5 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease
> Hit:6 http://cdn-fastly.deb.debian.org/debian stretch Release
> Hit:7 https://packages.sury.org/php stretch InRelease
> Hit:2 https://apt.armbian.com stretch InRelease
> Reading package lists...
> 
> Reading package lists...
> Building dependency tree...
> 
> Reading state information...
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> file : Depends: libmagic1 (= 1:5.30-1+deb9u2) but 1:5.34-2 is to be installed

If I understand this correctly, some package depends on an outdated version of libmagic1, which I don't have installed. Is this a problem with NCP, or rather with Armbian?

**Comment by bearsh** [comment]
the same happens for me on armbian (odroid hc2)...

**Comment by nachoparker** [comment]
mmm I don't see that on my Armbian devices... can you try the usual stuff to see what fixes it? 

(`apt install -f`, use `aptitude`...)

**Comment by bearsh** [comment]
`sudo apt-get install libmagic1=1:5.30-1+deb9u2 libmagic-mgc=1:5.30-1+deb9u2`
solved the problem for me

**Comment by XDA-Bam** [comment]
> 
> 
> `sudo apt-get install libmagic1=1:5.30-1+deb9u2 libmagic-mgc=1:5.30-1+deb9u2`
> solved the problem for me

Worked for me too. Thanks!

**Comment by markedphillips** [comment]
Worked for me too. Thanks.
