### ISSUE TITLE
Possibility of using NCP WEB; BTRFS management commands - tools

### ISSUE THREAD

**Issue by Zakspeed** [nextcloud/nextcloudpi#899]
**Description**  
Possibility of using NCP WEB; BTRFS management commands - tools

**Example**  
- choice of devices (SDA SDB ...) to format
- To be able to activate RAID1
- Degrade a disk for its replacement (repair RAID)
- Transparent compression (-o compress = lzo)
- info window (`btrfs filesystem df / mnt / btrfs1 /`)

**Comment by md9931852945** [comment]
Description
Possibility of using NCP WEB; BTRFS management commands - tools,
To be able to activate RAID1

**Comment by nachoparker** [comment]
not on the radar, I don't think this will be implemented unless somebody weighs in to do it
