### ISSUE TITLE
Odroid XU4 USB-Drive problem

### ISSUE THREAD

**Issue by amilopowers** [nextcloud/nextcloudpi#901]
I run an Odroid XU4 with the latest NCP.
![grafik](https://user-images.githubusercontent.com/9914682/57643589-94ed1900-75a9-11e9-83e5-79fa61d32df3.png)

As soon as I connect a second USB-Drive even just a stick it doesn't recognize the USB-Drive with the data on. The main data-drive is powered with an external power supply though.

**Comment by ovpc** [comment]
One should generally use LABEL's when formatting drives.
So automount will mount your drives as
**/media/YOURLABEL/** and create a symbolic link to it named **/media/USBdrive#**
You can edit your config file to point to /media/YOURLABEL/ncdata

It seems, adding a second or third drive when automount is enable, can move **/media/USBdrive** to **/media/USBdrive1**

I'd check content of /media/ with
> ls -lh /media/

**Comment by nachoparker** [comment]
Thanks Oliver. Yes this is explained in docs.nextcloudpi.com
