### ISSUE TITLE
OnlyOffice Integration

### ISSUE THREAD

**Issue by b-m-f** [nextcloud/nextcloudpi#909]
**Description**  
Adding an option to install and integrate a local OnlyOffice instance.

**Problems**  
Might be too heavy for some ARM boards? That's why it should only be optional.

**Comment by nachoparker** [comment]
Hi,

There is no OnlyOffice for ARM AFAIK, so unless somebody wants to port it and maintain it, it doesn't look like something that will be added any time soon.

Cheers

**Comment by kosssi** [comment]
You can find more information here https://github.com/ONLYOFFICE/DocumentServer/issues/152
