### ISSUE TITLE
How to speed up the process of building custom image?

### ISSUE THREAD

**Issue by pbajno** [nextcloud/nextcloudpi#915]
Hi,

**./build-SD-armbian.sh rock64**

I am using this command to build armbian image for my rock64. Is there any possibility to speed up this process? When I check this out it takes about 20% of my total CPU, and I would like it to possibly use all of it.

Is there any way to do it?

**Comment by nachoparker** [comment]
CPU is normally not the bottleneck unless you are compiling. Most of the build involves `apt` which is single threaded I/O limited stuff so I don't see an easy way of speeding that up.
