### ISSUE TITLE
ncp-update saves updates within data folder and re-backups them

### ISSUE THREAD

**Issue by heebj** [nextcloud/nextcloudpi#920]
When performing an update of nextcloud with ncp-update-nc a backup is created within /var/www/nextcloud/data/ncp-update-backups

This has the effect that everytime when a new update is performed the previous backups are backuped within the new backup. Thus the backups are getting bigger and bigger everytime a new update or backup is performed.

**Comment by ovpc** [comment]
Could you provide (link to) ncp-report?

**Comment by nachoparker** [comment]
I was able to reproduce. Already fixed in `v1.13.2`

Thanks for reporting!

**Comment by heebj** [comment]
Cool, thanks!
