### ISSUE TITLE
NextCloudPi not yet initialized, trying again in a few seconds ... 

### ISSUE THREAD

**Issue by Staubgeborener** [nextcloud/nextcloudpi#921]
I try to run the docker image of nextcloupi on my raspberry 3. The command is:
`docker run -d -p 4443:4443 -p 443:443 -p 99:80 -v ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi-armhf myip`
(port 99:80, because i already use port 80 for pihole). Well, this works in the first place, i can rech the web-gui of nextcloudpi with https://myip:443.

If i click activate, i'll get 
> NextCloudPi not yet initialized, trying again in a few seconds ...

I already read the whole day about those problems, but didnt find a solution (and no, there is no problem with the power supply /sd card, already tried different ones).

After that, i'll tried ` docker logs -f nextcloudpi` with the output

> pi@raspberrypi:~ $ docker logs -f nextcloudpi
> Starting PHP-fpm
> Starting Apache
> Starting mariaDB
> 2019-06-11 20:08:17 1995541296 [Note] mysqld (mysqld 10.1.37-MariaDB-0+deb9u1) starting as process 81 ...
> Starting Redis
> Starting Cron
> Starting Postfix
> Nextcloud is not installed - only a limited number of commands are available
> 
> 
>   There are no commands defined in the "config:system" namespace.
> 
> 
> Init done

I used [this tutorial](https://ownyourbits.com/2017/06/08/nextcloudpi-docker-for-raspberry-pi/)together with [this one](https://ownyourbits.com/2017/11/15/nextcloudpi-dockers-for-x86-and-arm/). You can see, i use the docker image nextcloudpi-armhf, which should be the correct one.

Like i said, i read all the stuff around here and in the forum. Nothing which actually helps. Already tried the docker image nextcloudpi.

More information:

> Running nc-info
> Gathering information...
> NextCloudPi version  v1.10.0
> NextCloudPi image    NextCloudPi_docker_03-14-19
> distribution         Debian GNU/Linux 9 \n \l
> automount            no
> USB devices          sda
> datadir              /data/nextcloud/data
> data in SD           yes
> data filesystem      ext2/ext3
> data disk usage      7.2G/30G
> rootfs usage         7.2G/30G
> swapfile             /var/swap
> dbdir                /data/database
> Nextcloud check      ok
> Nextcloud version    15.0.5.3
> HTTPD service        up
> PHP service          up
> MariaDB service      up
> Redis service        up
> Postfix service      up
> internet check       ok
> port check 80        open
> port check 443       closed
> IP                   172.17.0.2
> gateway              172.17.0.1
> interface            eth0
> certificates         none
> NAT loopback         no
> uptime               1:25

**Comment by ovpc** [comment]
Interesting, but this is really not the place to try and get help, please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm)

I'd investigate if Pihole could be responsible for?
> port check 443 closed
Or if in some other way Pihole interferes with NCP!? 
I'd try using port 99 or other alternate port for pihole.
And start a new container using regular ports for NCP.

Docker_03-14-19 arm (and x86) images have been reported to work, very recently, on the forum.
Feel free to comment here or re-open if this turns out to be a NCP issue. For which it would have to be reproduce-able on a clean installation.
