### ISSUE TITLE
Adding second usb external

### ISSUE THREAD

**Issue by cryptopher17** [nextcloud/nextcloudpi#924]
Hi Guys. 
I've been trying for days trying to get a second USB external setup on my NCPI. I formatted the additional drive in NC-format to create a new label. As soon as I plug my original drive back in I cannot access NC. I try and move the DB and NCDATA folder in the config but gives me issues. 
Is there some documentation on a procedure how to do so? Any assistance would be greatly appreciated! Would love to get a second drive setup.

**Comment by ovpc** [comment]
Use [forum](https://help.nextcloud.com/tags/ncp) please. This is not for support. Thank you

You probably have nc-[automount](https://docs.nextcloudpi.com/en/configuration-reference/#nc-automount) enabled. Which is just for first time users with no knowledge on how to mount a drive in Linux. If you use LABEL to name your drives they will be mounted for you at /media/LABEL when you have nc-automount enabled. It will also create symbolic links to them and uses that in NC's config.php
So if you look at media folder with
> ls -lh /media/

It will tell you what got mounted and were the links are pointing to. Edit config.php "datadirectory" accordingly and you should be fine ;-)
