### ISSUE TITLE
Encrypt backups to external drives

### ISSUE THREAD

**Issue by TheGreatestJannet** [nextcloud/nextcloudpi#930]
**Description**  
Would it be possible to encrypt backups to external drives?

**Comment by burgerkingGH** [comment]
It looks like [http://duplicity.nongnu.org/features.html](duplicity) would be the perfect tool for this. Found this from [https://www.nixtutor.com/linux/off-site-encrypted-backups-using-rsync-and-aes/](here)

**Comment by theCalcaholic** [comment]
This is already possible, just enable automount and use the external disk as target path for ncp-backup
