### ISSUE TITLE
Enable HSTS when HTTPS is enabled

### ISSUE THREAD

**Issue by alistair23** [nextcloud/nextcloudpi#942]
Enable HTTP Strict Transport Security (HSTS) when HTTPS is configured.

Similar to what is described here: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html#enable-http-strict-transport-security

**Comment by nachoparker** [comment]
Hi

HSTS is enabled by default (and HTTP redirected to HTTP)

**Comment by alistair23** [comment]
I couldn't see the flag set when I queried my server, I must have just missed it though. Thanks
