### ISSUE TITLE
ufwban filter

### ISSUE THREAD

**Issue by Haraade** [nextcloud/nextcloudpi#943]
Filter for ufwban should be:
failregex = UFW BLOCK.* SRC=< HOST >

HOST and <> must be complex. It will not appear on this website!

If not, you get this error message:

ERROR No 'host' group in 'UFW BLOCK.* SRC='
WARNING Command ['set', 'ufwban', 'addfailregex', 'UFW BLOCK.* SRC='] has failed. Received RegexException("No 'host' group in 'UFW BLOCK.* SRC='",)

**Comment by nachoparker** [comment]
should be fixed as part of https://github.com/nextcloud/nextcloudpi/pull/937
