### ISSUE TITLE
ncp-backup directories excluded in dataless backup

### ISSUE THREAD

**Issue by supercoincoin** [nextcloud/nextcloudpi#944]
Hello, 
In NextCloudPi v1.14.3 (also probably in some older version) ncp-backup exclude `nextcloud/data/appdata_*/previews/*` in dataless backup. But directory is "preview" and not "previews"

May i also suggest to exclude `nextcloud/data/*/uploads`, `nextcloud/data/*/cache`, `nextcloud/data/*/files_trashbin` and `nextcloud/data/*/files_versions` ? 

Added a patch for backup script. Hope it's in the right way. 

[ncp-backup.diff.txt](https://github.com/nextcloud/nextcloudpi/files/3372529/ncp-backup.diff.txt)

**Comment by nachoparker** [comment]
Good catch, thanks. Can you send a pull request please?

**Comment by nachoparker** [comment]
I implemented it. Thanks!
