### ISSUE TITLE
Add support for Debian Buster

### ISSUE THREAD

**Issue by pmeckoni** [nextcloud/nextcloudpi#947]
With the [recent release of Debian Buster](https://www.debian.org/News/2019/20190706) please consider adding Debian 10 Buster to the list of supported systems.

**Comment by feutl** [comment]
I also would like to know how to safely upgrade my debian stretch running NCP to debian buster.

Thanks

**Comment by ovpc** [comment]
@pmeckoni Buster is being tested, there already is an image for RPI at https://ownyourbits.com/downloads/testing/

@feutl This is not the place to get assistance, please use the [forum](https://help.nextcloud.com/c/support/appliances-docker-snappy-vm).

If you want to help testing, join us at https://t.me/NextCloudPi

**Comment by ovpc** [comment]
I tested upgrade using v 1.15.0 devel and ncp-dist-upgrade on a rpi3B 
It seems to break my install, get 403 Forbidden 
Output at https://pastebin.com/UNBtZbtJ

**Comment by feutl** [comment]
@ovpc I know how to upgrade a debian system, but I already learned something new - the command ncp-dist-upgrade ;)
I am waiting until someone officially says that an upgrade is safe, but thanks

**Comment by nachoparker** [comment]
@feutl I tested it on three devices. More testers are welcome. OPVC's pi died with HW problems so his upgrade didn't go through. 

If it fails for whatever reason (like some package needs dependencies), `ncp-dist-upgrade` can be ran again after the conflict is fixed manually

**Comment by feutl** [comment]
@nachoparker well thanks, I gonna test tomorrow evening :)

**Comment by nachoparker** [comment]
Instructions:

```
ncp-update devel
ncp-dist-upgrade
```

**Comment by nachoparker** [comment]
I would love a couple testers giving me the thumbs up so I can merge to master soon and make it available to everyone.

**Comment by ovpc** [comment]
On rpi3b ncp-distr-upgrade ended with 👍 Maintenance mode disabled
Upgrade to buster successful 
 
Just imagick missing warning in NC admin
![NC16 0 3BusterImagickWarningScreenshot2019-07-17_13-36-15](https://user-images.githubusercontent.com/8775469/61372768-49e8ce00-a898-11e9-94ad-1bd78b336de1.png)

NCPweb shows Raspbian 10
![NCPv1 15 0develScreenshot2019-07-17_13-35-18](https://user-images.githubusercontent.com/8775469/61373054-0f336580-a899-11e9-91bf-cc58cc1be9a1.png)

Thank you!
Let me know if want big uploads tested here?

**Comment by ovpc** [comment]
When trying to enable ufw:
> ERROR: Couldn't determine iptables version

**Comment by nachoparker** [comment]
iptables should be fine after a reboot. 

I disabled imagick because of some security concerns 

https://github.com/nextcloud/server/issues/13099

Probably nothing serious but just to be safe, let's wait for feedback from the NC security team.

**Comment by nachoparker** [comment]
many thanks!

**Comment by ovpc** [comment]
Yep, ufw fine after reboot.

**Comment by nachoparker** [comment]
merging Buster

**Comment by pmeckoni** [comment]
So now we should have Debian Buster listed in the "Supported Systems" along with Debian Stretch on the webpage https://ownyourbits.com/nextcloudpi/ ?

**Comment by feutl** [comment]
Sorry for taking me so long
I did an upgrade on my x86 machine running debian installed via ncp script. It ran through without errors but errors I have

* imagick (which is stated above)
and

```
sudo ncp-config
cat: /var/run/.ncp-latest-version: No such file or directory
Running nc-update
Downloading updates
Performing updates
Update to buster available. Type 'sudo ncp-dist-upgrade' to upgrade
Unknown user
```

**Comment by feutl** [comment]
I reran the ncp-dist-upgrade and did get the following, have no idea how to fix this.

```
$ sudo ncp-dist-upgrade 
Already on the lastest recommended distribution. Abort.
$ sudo ncp-config 
Running nc-update
Downloading updates
Performing updates
Update to buster available. Type 'sudo ncp-dist-upgrade' to upgrade
Unknown user
Done. Press any key...
```

I also figured out that `smbclient` was removed and not installed again. This made my mounted smb shares unusable inside nextcloud. `apt install smbclient` fixed it.

**Comment by nachoparker** [comment]
@pmeckoni good point, thanks, I just did some updates to that page

@feutl you can ignore the Imagick warning. I removed it on purpose for security reasons but it's only used by the theming app. You can re-add it if you want it. Also fixed the false recommendation to dist upgrade again.

Thanks for the help

**Comment by devincowan** [comment]
ncp-dist-upgrade
on a Rock64
received the following:
> Processing triggers for dbus (1.12.16-1) ...
> Errors were encountered while processing:
>  locales
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> Something went wrong. Fix it and try again

Did
sudo dpkg --configure -a
then ncp-dist-upgrade worked fine.

Thanks!

**Comment by cervorange** [comment]
Hello, 

I pass to ncp-dist-upgrade on rpi3b, i reboot two times and follow the command i need to do. The serveur works, i have acces with the android app and pc app. I have just after a problem with the internet interface (on firefox and chrome) but it seems to work 2 hours after (not tested NCP access).  

Thank you!!!
