### ISSUE TITLE
Hard Coded IP address in Nextcloud Config files?

### ISSUE THREAD

**Issue by jsfrederick** [nextcloud/nextcloudpi#95]
Nacho,

Question for you.  Do you know if any of the Nextcloud config files use hardcoded IP addresses?

I need to change the subnet that I have my home network setup for to another subnet (ie. from 192.168.0.xx to 192.168.5.xx)

If I change the IP address of my RPi, will NextcloudPi, and Nextcloud pick that up without an issue?

**Comment by nachoparker** [comment]
Nextcloud will pick it up automatically. Only for `dnsmasq` and `nc-forward-ports` you will have to update it.

**Comment by jsfrederick** [comment]
Thanks Nacho. Not using dnamasq or nc-forward-ports on NCPi, so I should be fine.
