### ISSUE TITLE
Fail2Ban doesn't work after Update to Buster

### ISSUE THREAD

**Issue by fischerit** [nextcloud/nextcloudpi#951]
After upgrading Nextcloud Pi from Strech to Buster I get this error in my fail2ban.log:

NOTICE  [nextcloud] Flush ticket(s) with iptables-multiport

Since the upgrade fail2ban is not working anymore.

**Comment by ovpc** [comment]
Tried rebooting?

**Comment by fischerit** [comment]
Yes I have rebooted it several times. After the upgrade UFW wasn't working but after the first reboot UFW was OK but not Fail2Ban.

**Comment by ovpc** [comment]
Please post ncp-report to pastebin or similar, for devs to look at, could be useful, thanks.

**Comment by fischerit** [comment]
Here is the report:
https://pastebin.com/qAUKXF2d

**Comment by nachoparker** [comment]
outdated
