### ISSUE TITLE
nc-snapshot in buster: ncdata is not a BTRFS mountpoint.

### ISSUE THREAD

**Issue by Haraade** [nextcloud/nextcloudpi#953]
nc-snapshot-auto stopped working after upgrade to Buster. When run nc-snapshot I get this message: ncdata is not a BTRFS mountpoint.

![Screenshot_20190721-201410__01](https://user-images.githubusercontent.com/23292068/61595422-5aca7400-abf7-11e9-9bd3-cf68fc5c94d8.jpg)
![Screenshot_20190721-201529__01](https://user-images.githubusercontent.com/23292068/61595423-5aca7400-abf7-11e9-853d-1e72d3b31653.jpg)

**Comment by zedocrob** [comment]
Same issue for me

**Comment by nachoparker** [comment]
I was able to replicate on my Odroid HC2. Thanks for reporting

**Comment by nachoparker** [comment]
fixed. Thanks

**Comment by malbreitenbach** [comment]
Hey @nachoparker,
thanks for the fix and the great work, in the latest version the problem is solved on Raspi 4.
