### ISSUE TITLE
NCP + Buster => imagick notification

### ISSUE THREAD

**Issue by Zakspeed** [nextcloud/nextcloudpi#957]
after installing Booster in my NCP

"Overview"
```
Security & setup warnings
It's important for the security and performance of your instance that everything is correctly configured. To help you with that we are doing some automatic checks. Please see the linked documentation for more information.

There are some warnings regarding your setup.
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
**imagick**
```

Anyone else has happened?

**Comment by ovpc** [comment]
Yes, everyone has, imagick has been removed for security reasons.

**Comment by Zakspeed** [comment]
> Yes, everyone has, imagick has been removed for security reasons.

Does this imply any performance problem in improving Nacho with the image gallery?

**Comment by Co0p3r21** [comment]
It´s already discussed nextcloud/server#13099 and nextcloud/nextcloudpi#947

**Comment by nachoparker** [comment]
> Does this imply any performance problem in improving Nacho with the image gallery?

They paid zero attention to my proposal
