### ISSUE TITLE
Wrong file size of folders and files

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/nextcloudpi#96]
There is a  issue with file sizes of all files shown I  web and clients (Android and Windows at least) 

I've found a solution in git hub that is very simple. It is just a matter of removing a small portion of text in configuration.php

**Comment by Ricardosgeral** [comment]
In fileinfo.php. Remove "(1)" 
See https://github.com/nextcloud/server/issues/5031

However I am afraid that this my have side effects. 

I've done it in the  past and solved it but later I hade the status.Php file missing, and I don't know if they are related. 

What should I do to fix the wrong file sizes
Thanks

**Comment by Ricardosgeral** [comment]
Sorry the patch is to remove (int) from Getsize function and not (1)

Anyone reported side effects?

**Comment by nachoparker** [comment]
Thanks for the info. 

Regarding to NCP, we will wait until it is [rolled out in NC12.0.2](https://github.com/nextcloud/server/issues/5031#issuecomment-320890965)
