### ISSUE TITLE
[Suggestion] special configs for Raspberry Pi 4 (more ram, etc.)

### ISSUE THREAD

**Issue by Larsene** [nextcloud/nextcloudpi#963]
**Description**  
Perhaps could be added special settings on NextCloudPi installation to use the 4Gb memory available (higher memory for PHP, auto activate log to ram, etc).

Thanks for NextCloudPi :-)

**Comment by nachoparker** [comment]
the system already adapts automatically to available resources. You can fine tune with `nc-limits` also
