### ISSUE TITLE
Backups page in NCP web displays incorrect backup file sizes

### ISSUE THREAD

**Issue by nero120** [nextcloud/nextcloudpi#967]
![image](https://user-images.githubusercontent.com/4236238/62662494-2df2bc80-b96c-11e9-8a84-d5967701a594.png)
![image](https://user-images.githubusercontent.com/4236238/62662697-cee17780-b96c-11e9-986a-fce7a2dc2892.png)

Running the latest docker image, looks like backups larger than 2GB display the wrong file size. I'm guessing this is due to the [32bit integer issue](https://www.php.net/manual/en/function.filesize.php).

There's some suggestions on that page for displaying the correct size, will give it a try if I get some time and submit a PR.

**Comment by nachoparker** [comment]
fixed in v1.35.2 in `devel`

thanks!
