### ISSUE TITLE
External DB and Cache

### ISSUE THREAD

**Issue by dm3ll3n** [nextcloud/nextcloudpi#973]
**Description**  

Given the resource constraints of a RPi, it would be great to have the ability to configure NCP to use external DB and cache instances (possibly hosted on another RPi).

**Example**  

From the admin panel, an option to provide a MySQL/Maria server and another option to specify a Redis server which would also provide the option to migrate/terminate the local instances.

**Comment by nachoparker** [comment]
That can be done manually if the user is technical enough.
