### ISSUE TITLE
NextCloudPI VM won't boot on Virtualbox

### ISSUE THREAD

**Issue by fancsali** [nextcloud/nextcloudpi#984]
Following the guide here: https://ownyourbits.com/2018/10/25/introducing-the-nextcloudpi-vm/; downloaded the image from the downloads area: https://ownyourbits.com/downloads/NextCloudPi_VM_07-20-19/NextCloudPi_VM_07-20-19.tar.bz2.

Unfortunately, when following the documentation, and converting the raw image and importing it into Virtualbox, the VM won't boot. It only emits an error message:

    FATAL: No bootable medium found! System halted.

**Comment by nachoparker** [comment]
You will have to export the image from qcow2 formate. Please use the forums for further assistance

**Comment by fancsali** [comment]
Well, do understand, this is not a support forum, and even not the right piece of code to file a bug against.

On the other hand, please rest assured, I did search the forums, and didn't succeed, but I still think, following the guide should not get me an error. So, I guess, what I was trying to say is, perhaps the documentation is out of date...
