### ISSUE TITLE
Linux 9 / Debian 9 / Distro not suported ==== Installation issues

### ISSUE THREAD

**Issue by jsanfe** [nextcloud/nextcloudpi#985]
**Description**  
Hi NachoParker!
I started to reinstall nextcloudPi into a fresh Debian 9 net installer. Ok, when use Curl installer, i have the next issue:

 curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

Installing NextCloudPi...
ERROR: distro not supported:
Debian GNU/Linux 9 \n \l

And thats all, curl installer does not work with debian 9.

Thanks for your support

**Example**

**Comment by ovpc** [comment]
Curl installer works on Debian 10 (Buster) presently, all the latest images on Buster now.

**Comment by jsanfe** [comment]
Thanks, so I will update my Debian version.
